### ISSUE TITLE
In iteration_structure.cpp (and others?), change order of loops and if statements

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#10]
In iteration_structure, there are currently several places that say things along the lines of 

for (iZone = 0; iZone < nZone; iZone++) {  
    if (config_container[ZONE_0]->GetWind_Gust())
SetWind_GustField(config_container[iZone],geometry_container[iZone],solver_container[iZone]);
    }
}

The iteration loop is on the outside with the if statement inside rather than the opposite. This is less legible (you have to read the loop rather than seeing you aren't using a wind gust) and slower (you have to evaluate the if statement every time). These occurrences should be changed

**Comment by hlkline** [comment]
Closing this issue, since as far as I can tell this was fixed at some point in the last 3.5 years. Please re-open if that's not the case.
