### ISSUE TITLE
Choose a reference element length for limiters based on a metric that scales with grid units/a characteristic length

### ISSUE THREAD

**Issue by economon** [su2code/SU2#100]
For example, take an average of the surface element size for the markers being monitored.

**Comment by hlkline** [comment]
Is this covered by REF_ELEM_LENGTH?

**Comment by economon** [comment]
That's the option in question here, but we would like to use an automatic method of selecting this parameter so that we only have 1 parameter to select for the limiter (LIMITER_COEFF).

**Comment by economon** [comment]
Addressed in #451
