### ISSUE TITLE
Structural Modal Analysis (Eigenfreqencies) & Adjoint Shape Optimization

### ISSUE THREAD

**Issue by ng0177** [su2code/SU2#1003]
Judging from the Tutorials, I am not sure whether SU2 is able to perform **Structural Modal Analysis** (Eigenfreqencies) and possibly **Adjoint Shape Optimization** for it. If not, I would like to request an implementation since it is a common problem e.g. to avoid high cycle fatigue in industry. Is a Structural Modal Solver already implemented to use standalone?

**Comment by cvencro** [comment]
Hello @ng0177! The mass and stiffness matrices are calculated in the structural solver which could be extracted and used offline for modal analysis. At the moment this isn't integrated as an overall modal solver but I agree it would be a useful feature.

**Comment by cvencro** [comment]
There are a couple of talks in the upcoming SU2 conference (https://su2foundation.org/su2conference2020/) which sound related to this, perhaps tune in to those.

**Comment by Arindamn** [comment]
try matlab or python scripting in conjuction with ABAQUS or ANSYS for introducing genetic algorithms or other simulation optimization methods.
