### ISSUE TITLE
Possible bug in CSolver::SetRotatingFrame_GCL

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1005]
As mentioned in #975 
This routine was averaging the solution at nodes i and j but it was updating the residuals at those nodes with the un-averaged solution.
https://github.com/su2code/SU2/blob/626be8fd3fcc63c4f2c5aaeb1d93fdcbd0734f56/SU2_CFD/src/solvers/CSolver.cpp#L2732
Upon fixing it one of the turbomachinery cases started diverging, so I kept the suspicious implementation.

**Comment by economon** [comment]
Actually, on closer look, this seems ok. I am only averaging the grid velocities on either side of the face, not the solution. That routine might be more efficient as an edge loop, but should be correct. If you're really bored, see pg. 83 for details about the Geometric Conservation Law as implemented there: https://economon.github.io/docs/economon_dissertation.pdf

**Comment by pcarruscag** [comment]
I wasn't bored, but I'm always curious.

**Comment by pcarruscag** [comment]
Conclusion, it is not a bug, but there was a bit of code (the averaging) that was not needed.
