### ISSUE TITLE
Wrong output from meson

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#1011]
**Describe the bug**
When I run the meson script for building it gives the wrong build command. This is both for the master and develop version.

**To Reproduce**
Simply type
./meson.py build

One of the last output lines is
Use './ninja -C false install' to compile and install SU2

while it should be
Use './ninja -C build install' to compile and install SU2

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - C++ compiler and version: GCC 8.4.0
 - MPI implementation and version: Sequential
 - SU2 Version: 7.0.5

**Comment by pcarruscag** [comment]
My fault, I'll fix it.

**Comment by vdweide** [comment]
Looks like this one is solved, right?

**Comment by pcarruscag** [comment]
Yup, I thought the PR would close it automatically.
