### ISSUE TITLE
Conditionals formatting style 

### ISSUE THREAD

**Issue by leminhman0312** [su2code/SU2#1013]
**Is your feature request related to a problem? Please describe.**
* Following the SU2 style guide, I understand that we should try to keep things as consistent as possible.  One thing that I note is the style for single `if` and `for` statement.  Sometimes, there are no braces and other time, there are braces.  An example would be in line 223 of `CDriver.cpp` vs line 382 of the same file.  An example for the `for` statement can be seen in line 420 of the same file as well. Sometimes, this is hard to read. 

**Describe the solution you'd like**
* Could you please let me know the prefer style? I understand that this is a very minor thing but should I go ahead and make sure every single if/for fits this "prefer style"?

**Comment by pcarruscag** [comment]
The official style is Google's but folks have their own preferences (I certainly have mine and they're not Google's), there is a .clang-format file in the repository now, and we will put it in place at some point and auto format the whole code.
