### ISSUE TITLE
Develop does not compile with GCC 5.4

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1021]
Just as FYI, the fix is in #1020.

**Comment by TobiKattmann** [comment]
On gcc 4.8.5 as well. If anyone has the same issue (sth like `error: array must be initialized with a brace-enclosed initializer`) -> to work on rn I cherry picked from the mentiond PR
`git cherry-pick 1f4232a06a3086821c88c2ba601c99b1387f78e3`

Thanks posting this info here pedro :+1:
