### ISSUE TITLE
SCALE_GRID does not always work

### ISSUE THREAD

**Issue by geronimo750** [su2code/SU2#1023]
**SCALE_GRID does not "always" work**

Hello Everybody,
I have been using the SCALE_GRID function in SU2 quite often with previous versions of SU2, without any problem. However, after passing to v7.0.5 and working with a completely new mesh the SCALE_GRID option does not seem to work anymore (at least for me!)

I am trying to scale down my mesh of a factor 0.001. In the config file, I set up the following parameters :
- DV_KIND= SCALE_GRID
- % Marker of the surface in which we are going apply the shape deformation
DV_MARKER= (Inlet_wall )  %this has also been commented but the result is the same
- DV_PARAM= ( 1.0 )
- % Value of the shape deformation
DV_VALUE=0.001

However, when I run SU2_DEF I obtained the following 

*--------------------- Volumetric grid scaling (ZONE 0) ------------------
Scaling the mesh by a constant factor of 1.*

**To Reproduce**
*The config file is attached. The mesh file is quite big but it can be provided on request.*
[inlet.cfg.txt](https://github.com/su2code/SU2/files/4761675/inlet.cfg.txt)

**Desktop (please complete the following information):**
 - OS: [centos7.5 and centos8]
 - C++ compiler and version: [g++ (GCC) 4.8.5]
 - MPI implementation and version: [OpenMPI 4.0.0]
 - SU2 Version: [v7.0.5]

**Comment by stephansmit** [comment]
What you can do for the time being is use the SU2_PER in the Meshtools to generate a scaled down grid. [MeshTools- SU2_PER]( https://github.com/su2code/MeshTools/tree/master/SU2_PER)
You need to remove all the periodic stuff that it generates at the end of your mesh though, as this is not needed anymore.

**Comment by geronimo750** [comment]
> What you can do for the time being is use the SU2_PER in the Meshtools to generate a scaled down grid. [MeshTools- SU2_PER](https://github.com/su2code/MeshTools/tree/master/SU2_PER)
> You need to remove all the periodic stuff that it generates at the end of your mesh though, as this is not needed anymore. Edit: Also don't forget to lower the number of boundaries (NMARK) by the number of periodic boundaries in your mesh (SU2_PER adds two because of the periodicity).

Thanks for the temporary suggestion, much appreciated

**Comment by pcarruscag** [comment]
This is how the scale factor is computed `su2double Scale = config->GetDV_Value(0)*config->GetOpt_RelaxFactor();`
OPT_RELAX_FACTOR is 1000 in your config, and so it cancels the scale you want to apply. Please try this again and reopen the issue if the problem persists.

**Comment by geronimo750** [comment]
> 
> 
> This is how the scale factor is computed `su2double Scale = config->GetDV_Value(0)*config->GetOpt_RelaxFactor();`
> OPT_RELAX_FACTOR is 1000 in your config, and so it cancels the scale you want to apply. Please try this again and reopen the issue if the problem persists.

Thanks a lot, your hekp has been much appreciated
