### ISSUE TITLE
Jacobian of stress tensor

### ISSUE THREAD

**Issue by qwebean** [su2code/SU2#1028]
It seems that the differential process is applied during each edge connecting node i and its neighboring points. If that's right,
the question gets answered.

**Comment by pcarruscag** [comment]
I think the person that most recently looked into those Jacobians was @bmunguia 
All I know is that an 100% accurate Jacobian is not necessary for correctness (only the flux matters) but it may make convergence better (sometimes it also makes it worse).

**Comment by clarkpede** [comment]
I also worked on refactoring (and checking) the stress tensors.  So if there's any questions, feel free to ping me.

**Comment by qwebean** [comment]
> I think the person that most recently looked into those Jacobians was @bmunguia
> All I know is that an 100% accurate Jacobian is not necessary for correctness (only the flux matters) but it may make convergence better (sometimes it also makes it worse).



> I also worked on refactoring (and checking) the stress tensors. So if there's any questions, feel free to ping me.

Thank you for your reply, in fact there still exists some question.
Because in the code for calculating viscous Jacobians, I did not find any partial derivative of primitive variables.
In the stress tensor, partial derivatives such as ∂u/∂x_i, ∂ρ/∂x_i (GradPrimVar[iVar][iDim]) are part of the expression of tau[iDim][jDim], which affects the value of Proj_Flux_Tensor[iVar].
In the approximate process of the Jacobian matrix, it seems that the originally expected terms such as ∂(u/ρ)/∂x are replaced by values like val_Mean_PrimVar[jDim+1]/(Density*val_dist_ij), and then used as part of Jacobian_i and Jacobian_j's expression.
I thought there should be some differential terms, but I didn't find it.
So my question is to know more details about the approximation in calculating viscous Jacobians.
I mention this problem because I want to add some equations (such as concentration equations, moment distribution equations) based on SU2's NS solver, develop an implicit solver, and solve adjoint problems. So augmented Jacobian matrices are needed. I have gone through the SU2 code of TNE2Solver in version 4.0.1. But the solver seems to be imperfect, and have some differences from NSSolver in dealing with the viscous Jacobian matrix. Moreover, the TNE2Solver can be applied to only a few cases. It seems that its code requires further modification.

**Comment by qwebean** [comment]
It seems that the jacobian of each block is equal to the sum of val_Proj_Jac_Tensor_i and val_Proj_Jac_Tensor_j, doesn't it? And the question seems to be answered.

**Comment by economon** [comment]
> I have gone through the SU2 code of TNE2Solver in version 4.0.1. But the solver seems to be imperfect, and have some differences from NSSolver in dealing with the viscous Jacobian matrix. Moreover, the TNE2Solver can be applied to only a few cases. It seems that its code requires further modification.

You may want to check out #1014, which is an updated version of the old TNE2 solver. Just fyi

**Comment by clarkpede** [comment]
@qwebean The derivative terms you describe would appear in an analytical Jacobian.  But SU2 needs the Jacobian of the discrete system. In other words, we don't need to know how the residual depends on the analytical gradient.  We need to know how the values at some points "i" and "j" affects the residual.   You want the Jacobian of the residual with respect to individual values at individual nodes, not interpolated functions.

You can approximate the derivative (`da/dx`) of some quantity `a` as "(a_j - a_i)/d_{ij}`, where `d_{ij}` is the distance between the point "i" and "j".  So the Jacobian of (`da/dx`) with respect to `a_i` is  (approximately) `-1/d_{ij}`.  Does that answer your question? Do you have further questions?
