### ISSUE TITLE
Wrong communication of gradients for periodic cases

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1029]
FYI
Introduced in #1009
Found by @TobiKattmann 
Fixed in #1020

**Comment by TobiKattmann** [comment]
Thanks for incorporating that fix into your PR. I actually wanted to propose to put that commit into another PR… but you were faster to do so 🏃‍♂️ 💨 
The relief after knowing the root caused me to deviate from the necessary follow-up.

**Comment by pcarruscag** [comment]
No prob, we can cherry pick all these fixes into a new PR if my one does not go through for the next release.
