### ISSUE TITLE
You've got two options:

### ISSUE THREAD

**Issue by Karthik-ksd** [su2code/SU2#1034]
You've got two options:

1. Use the cfg option `WRT_BINARY_RESTART= NO` to dump the restart file(s) in human-readable ASCII.
2. Use the cfg option `OUTPUT_FORMAT= TECPLOT` or `OUTPUT_FORMAT=PARAVIEW` with SU2_SOL to export the solution to an ASCII-formatted tecplot or paraview file. If you're not familiar with SU2_SOL, then check out [the documentation](https://su2code.github.io/docs/Post-processing/).

You can find those cfg options in `config_template.cfg` in the root SU2 source code directory.

In the end, using the tecplot or paraview option may be your best bet.  Trying to manually parse the text files smells like an [XY Problem](https://en.wikipedia.org/wiki/XY_problem).  Tecplot and Paraview both have scripting capabilities that make post-processing very efficient.

Does that answer your question? Do you have any follow-up concerns?

_Originally posted by @clarkpede in https://github.com/su2code/SU2/issues/787#issuecomment-528435629_

**Comment by Karthik-ksd** [comment]
> You've got two options:
> 
> 1. Use the cfg option `WRT_BINARY_RESTART= NO` to dump the restart file(s) in human-readable ASCII.
> 2. Use the cfg option `OUTPUT_FORMAT= TECPLOT` or `OUTPUT_FORMAT=PARAVIEW` with SU2_SOL to export the solution to an ASCII-formatted tecplot or paraview file. If you're not familiar with SU2_SOL, then check out [the documentation](https://su2code.github.io/docs/Post-processing/).
> 
> You can find those cfg options in `config_template.cfg` in the root SU2 source code directory.
> 
> In the end, using the tecplot or paraview option may be your best bet. Trying to manually parse the text files smells like an [XY Problem](https://en.wikipedia.org/wiki/XY_problem). Tecplot and Paraview both have scripting capabilities that make post-processing very efficient.
> 
> Does that answer your question? Do you have any follow-up concerns?
> 
> _Originally posted by @clarkpede in [#787 (comment)](https://github.com/su2code/SU2/issues/787#issuecomment-528435629)_

**Comment by economon** [comment]
Looks like this was an accidental duplicate post. Closing for now, but please feel free to open with more information if you have a question / issue.
