### ISSUE TITLE
Compilation issues with spack and meson and a configure-make workaround

### ISSUE THREAD

**Issue by gmfricke** [su2code/SU2#1037]
Hello, 

We are attempting to provide compilation instructions for one of our users who wishes to use SU2 on our HPC clusters.

We use spack to provide library access, including to openmpi. When we use meson and ninja, we run into a linker error: /opt/spack/opt/spack/linux-centos7-nehalem/intel-19.0.3/zlib-1.2.11-zjmi5fwzodf5iizukl7aptz2eexrcblo/lib: file not recognized: Is a directory

The path is provided by pkg-config and the spack provided .pc file. We don't see any errors in the zlib .pc and that package is used frequently in other compilations.

As a workaround, we used the version 6 installation procedure on the version 7 source. This produced runnable binaries. Could you let me know if this will fail to produce binaries that meson and ninja would have?

qsub -I -q debug -l nodes=1:ppn=8
on the compute node:
cd into the SU2 git repo then,
module load python-3.7.2-intel-19.0.1-zj5ljxy 
module load openmpi-3.1.5-gcc-9.3.0-cc2bj5i # for gcc mpi compilers.
./configure --prefix=<install destination> --enable-mpi --with-cc=$(which mpicc) --with-cxx=$(which mpicxx)
make -j 8 # compile the code using all 8 cores
make install # copy the binaries to the installation destination
Then, assuming the input file is in the same directory as the SU2_CFD executable I ran it on 8 cores with mpirun:
mpirun -np 8 $PWD/SU2_CFD lam_cylinder.cfg 

I got what looked like reasonable output but is are there unit tests I can run to test the installation.

Thanks very much for any guidance you can offer. 

Matthew

**Comment by pcarruscag** [comment]
Sorry for taking so long to reply to this.
The old automake build system is loosely maintained, so far as I know it is currently working fine.

None that you need to specify the optimization flags manually, on gcc these work well:
export CXXFLAGS="-O2 -funroll-loops -DNDEBUG -march=native"

**Comment by amaji** [comment]
Hi,

I have similar issues building SU2-7.0.6 with spack-compiled libraries and mason/ninja on CentOS7.

I am using gcc-6.3.0, openmpi-3.1.4 and python-3.7.0. The configure/build commands I use are:
```
./meson.py build -Denable-pywrapper=true --prefix=$PREFIX 
./ninja -j16 -C build install
```

At the linking stage, I get the error:
```
mpiCC  -o SU2_MSH/src/SU2_MSH SU2_MSH/src/SU2_MSH.p/SU2_MSH.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group externals/cgns/libcgns.a externals/metis/libmetis.a externals/parmetis/libparmetis.a externals/tecio/teciompisrc/libteciompi.a Common/src/libSU2Common.a -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags /apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib/libmpi.so -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags /apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib/libmpi_cxx.so -Wl,--end-group -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags '-Wl,-rpath,$ORIGIN/../../externals/cgns:$ORIGIN/../../externals/metis:$ORIGIN/../../externals/parmetis:$ORIGIN/../../externals/tecio/teciompisrc:$ORIGIN/../../Common/src' -Wl,-rpath-link,/scratch/brown/SU2/SU2-7.0.6/build/externals/cgns -Wl,-rpath-link,/scratch/brown/SU2/SU2-7.0.6/build/externals/metis -Wl,-rpath-link,/scratch/brown/SU2/SU2-7.0.6/build/externals/parmetis -Wl,-rpath-link,/scratch/brown/SU2/SU2-7.0.6/build/externals/tecio/teciompisrc -Wl,-rpath-link,/scratch/brown/SU2/SU2-7.0.6/build/Common/src
/usr/lib64: file not recognized: Is a directory
collect2: error: ld returned 1 exit status
```

After manually playing with the mpiCC command, I found that the error is coming from 
```
-Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,/usr/lib64 ... ...
```
If I replace the additional `-Wl,/path/to/lib` with `-Wl,-rpath -Wl,/path/to/lib` things work fine. For example this links fine:
```
-Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/apps/spack/brown/apps/openmpi/3.1.4-gcc-7.3.0-ik4qowj/lib -Wl,-rpath -Wl,--enable-new-dtags -Wl,-rpath -Wl,/apps/spack/brown/apps/hwloc/1.11.11-gcc-7.3.0-xoecbyv/lib -Wl,-rpath -Wl,/usr/lib64 ... ...
```
Is there something wrong in the mason.build script which is expanding wrong `-rpath` arguments, or is this a version incompatibility?

Please let me know how I can fix this.
