### ISSUE TITLE
Bug in the Markers and Boundary Conditions website

### ISSUE THREAD

**Issue by suargi** [su2code/SU2#1045]
**Describe the bug**
When explaining the Symmetry Wall in https://su2code.github.io/docs_v7/Markers-and-BC/, there is a copy paste from the explanation for Euler (slip) Wall:

"For all Finite Volume (FVM) solvers, i.e. not the FEM_* solvers, its implementation is identical to MARKER_SYM solvers and both options can be used interchangeably."

which makes no sense.

**Comment by pcarruscag** [comment]
Thanks for bringing this to our attention.
In the meantime, they both make the flow tangent to the surface.
