### ISSUE TITLE
Multipoint Optimization not running under Windows 10

### ISSUE THREAD

**Issue by usbrem** [su2code/SU2#1046]
Hi all,

for multipoint optimization only Linux User were the target group ;-) :

In bin\SU2\eval\functions.py and two times in bin\SU2\eval\gradients.py replace:

                string = "ln -s " + src + " " + dst
                stringlist = string.split()
                subprocess.Popen(stringlist)

with something like:

if os.name == 'nt':
                # make windows link
                string = "mklink /d \"" + dst + "\" \"" + src + "\""
                stringlist = string.split()
                try:
                    subprocess.Popen(stringlist, stdout = subprocess.PIPE, stderr = subprocess.STDOUT, shell = True)
                except:
                    print("Enable in Windows settings -> Update and Security -> Developer Options, otherwise symbolic links cannot be created")
                    
            else:
                # make unix link
                string = "ln -s " + src + " " + dst
                stringlist = string.split()
                subprocess.Popen(stringlist)

Cheers,

US

**Comment by economon** [comment]
Hi @usbrem : thanks for making us aware of the issue. If you have some time, would you consider submitting a pull request with these changes, since you can test locally very easily? Thanks!
