### ISSUE TITLE
TECPLOT surface file writer

### ISSUE THREAD

**Issue by suargi** [su2code/SU2#1051]
**Describe the bug**
When setting OUTPUT_FILES= (SURFACE_TECPLOT) the output file is <name>.szplt. According to the code nomenclature, this file extension should be for the binary file: SU2_CFD/src/output/CTecplotBinaryFileWriter.cpp
When using the OUTPUT_FILES= (SURFACE_TECPLOT_BINARY) I get the following error:
OUTPUT_FILES: invalid option value SURFACE_TECPLOT_BINARY. Check current SU2 options in config_template.cfg

I think the nomenclature has changed w.r.t. previous versions but the template config file did not.

SURFACE_TECPLOT which should output a ".dat" file (see SU2_CFD/src/output/CTecplotFileWriter.cpp) is now (v7.0.6) SURFACE_TECPLOT_ASCII
SURFACE_TECPLOT_BINARY which should output a ".szplt" file (see SU2_CFD/src/output/CTecplotBinaryFileWriter.cpp) is now (v7.0.6) SURFACE_TECPLOT

**Correction**
Update the config file.

 - SU2 Version: v7.0.5 (also applicable to v7.0.6)

**Comment by pcarruscag** [comment]
Looks like you tracked the origin of the issues, can you open a pull request with the fixes?

**Comment by suargi** [comment]
I will do that
