### ISSUE TITLE
Question about classical RK4 time coefficients

### ISSUE THREAD

**Issue by ayuxjh** [su2code/SU2#1053]
Hi. I have some questions about  SU2 implementation of classical Runge-Kutta method .

According to the wikipedia (https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta_methods),  the formula is as follows
<img width="430" alt="wiki_Runge-kutta" src="https://user-images.githubusercontent.com/31647163/88119795-07b54380-cbf4-11ea-8e21-1baeafbc5c6f.png">

 and the implementation in SU2  is:

``` 
 /*--- Hard-coded classical RK4 coefficients. Will be added to config. ---*/
  const su2double RK_FuncCoeff[] = {1.0/6.0, 1.0/3.0, 1.0/3.0, 1.0/6.0};
  const su2double RK_TimeCoeff[] = {0.5, 0.5, 1.0, 1.0};
```

Here, I have no question about RK_FuncCoeff `{1.0/6.0, 1.0/3.0, 1.0/3.0, 1.0/6.0}`,  however, the RK_TimeCoeff is ` {0.5, 0.5, 1.0, 1.0}`,  Shouldn't It be `{1.0, 0.5, 0.5, 1.0} `from the formula?? Did I think something wrong?

Thanks in advance.

**Comment by pcarruscag** [comment]
See #961, the summary is that the implementation is such that the first 1 is implicit, i.e. we only use the first 3 coefficients in RK_TimeCoeff.

**Comment by ayuxjh** [comment]
> See #961, the summary is that the implementation is such that the first 1 is implicit, i.e. we only use the first 3 coefficients in RK_TimeCoeff.

ok, I understand.  thanks~
