### ISSUE TITLE
Non-ideal gas models

### ISSUE THREAD

**Issue by FlorianDm** [su2code/SU2#1065]
I am wondering what it would take to adapt SU2 to model the flow of (thermally/calorically) non-ideal gases where cp, gamma, etc. vary with the state and for which the relations R = Cp - Cv, H = Cp * T, etc. are not valid. 

Do all the computations of flux jacobians etc. formulated in terms of gamma already rely on the ideal gas (or polytropic) assumption? 

Is this sort of thing considered unimportant since SU2 is mainly intended for aerodynamics or would it be too demanding for the solver to converge reliably?

To give a "simple" example where this would be useful: A converging-diverging nozzle expanding the refrigerant r134a from around 24 bar to 3 bar. Only if gamma is set to the throat value the choked flow rate will be fairly correctly predicted but the outlet temperature will then be very far below the isentropic 1D result with a real EoS. This seems to have consequences not only for the temperature field but also for the performance certainly of more complex devices.

**Comment by pcarruscag** [comment]
Hello, I am no expert on this but I guess it might not take any work.  See https://www.cfd-online.com/Forums/su2/229392-high-temperature-flow.html and links therein, and TestCases/nicf/

**Comment by economon** [comment]
Just adding a couple more things that may be of interest w.r.t. what is available for non-ideal fluids: 

article: https://su2code.github.io/documents/2017_J._Phys.3A_Conf._Ser._821_012013.pdf

tutorial: https://su2code.github.io/tutorials/NICFD_nozzle/

**Comment by FlorianDm** [comment]
I should have said I was already using that "polytropic Peng-Robinson" eos and I have read the publications related to it. It just takes gamma as an argument from the config.

Also for many boundary conditions Cp is calculated as gamma/(gamma-1)*R which is only true for ideal gases. And I am curious about how gamma is used in CNumerics. Nevermind, thank you. For my cases I will try to update Gamma whenever the Temperature is calculated with the eos.
