### ISSUE TITLE
Version Listed during build process is incorrect.

### ISSUE THREAD

**Issue by snowbird294** [su2code/SU2#1072]
The SU2 version that is listed during the config process is incorrect.

Output of ./configure --enable-mpi --prefix=/apps/intel-2020.2/impi-2020.2/su2-7.0.6/ CC=mpiicc CXX=mpiicpc CXXFLAGS="-I/apps/intel-2020.2/intel-2020.2/compilers_and_libraries_2020.2.254/linux/mkl/include -g -O2 -std=c++11"

```
-------------------------------------------------------------------------
|    ___ _   _ ___                                                      |
|   / __| | | |_  )   Release 6.2.0 'Falcon'                            |
|   \__ \ |_| |/ /                                                      |
|   |___/\___//___|   Suite                                             |
|                                                                       |
-------------------------------------------------------------------------

Build Configuration Summary:

    Source code location: /tmp/jhrogers/SU2-7.0.6
    Install location: 	  /apps/intel-2020.2/impi-2020.2/su2-7.0.6
    Version:              6.2.0
    C++ Compiler:         mpiicpc
    C Compiler:           mpiicc

```

OS: CentOS 7.8
Compiler/MPI: Intel 2020/impi 2020
Version: "7.0.6" according to the tar ball

**Comment by pcarruscag** [comment]
That's because that is the legacy build system on its way to deprecation.
Please use meson and ninja https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/
If you need to use the legacy build system, you should add -DNDEBUG to the CXXFLAGS.
