### ISSUE TITLE
SURFACE_STATIC_PRESSURE not recognized as objective function

### ISSUE THREAD

**Issue by MiGaff** [su2code/SU2#1075]
The objective functions SURFACE_STATIC_PRESSURE and SURFACE_TOTAL_PRESSURE do not work with the shape_optimization.py script. 

This has been verified by running the python optimization using the test case "multiobjective_wedge" in the optimization_euler test case folder, using the provided script ("inv_wedge_ROE_multiobj.cfg")

I get the following error: 

>Traceback (most recent call last):
  File "/usr/local/bin/shape_optimization.py", line 183, in <module>
    main()
  File "/usr/local/bin/shape_optimization.py", line 98, in main
    options.nzones      )
  File "/usr/local/bin/shape_optimization.py", line 155, in shape_optimization
    project = SU2.opt.Project(config,state)
  File "/usr/local/bin/SU2/opt/project.py", line 129, in __init__
    group = historyOutFields[this_obj]['GROUP']
KeyError: 'SURFACE_TOTAL_PRESSURE'

The same happens if setting these keywords for the constraints.

My environment:

OpenSuse Leap 15.1
Python 3.6.10
gcc 7.5.0
OpenMPI 1.10.7
SU2 v7.0.6

**Comment by pcarruscag** [comment]
I might have fixed the issue in #1167

**Comment by pcarruscag** [comment]
Give this a try if/when you get a chance and let us know.

**Comment by MiGaff** [comment]
Dear Pedro,

sorry for getting back to you so late. Yes, it works now with 7.1.0.
Thank you for the fix!

**Comment by pcarruscag** [comment]
No worries, glad to hear it works (I admit I did not test).
