### ISSUE TITLE
Tag the major optimization iterations among the full set of shape design output

### ISSUE THREAD

**Issue by economon** [su2code/SU2#108]
Currently, we output all CFD evaluations during shape design, which will include calculations as part of line searches. We should tag the subset of candidate designs that represent the major optimization iterations.

**Comment by hlkline** [comment]
The optimization output includes a list of the major optimization iterations and the associated minor iteration number, which allows you to identify which of the CFD evaluations are associated with the major optimization iteration. Is that sufficiently addressing this issue?

**Comment by economon** [comment]
Indeed, this helps, but it could be more general, since you only get to see this in the console output. I was thinking that a simple tag in the optimization history file for the evaluations that are 'major' would make this much simpler (and easier to post-process).
