### ISSUE TITLE
Latest version of develop does not build in debug mode

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#1081]
**Describe the bug**
The latest version of develop gives undefined references when building in debug mode, e.g.
undefined reference to `CRoeBase<CRoeScheme<CCompressibleViscousFlux<2ul> >, CCompressibleViscousFlux<2ul> >::nVar'

**To Reproduce**
Build the debug version with meson using --buildtype=debug

**Desktop (please complete the following information):**
 - OS: Ubuntu 18:04
 - C++ compiler and version: g++ 8.4.0
 - MPI implementation and version: OpenMPI version 2.1
 - SU2 Version: [e.g., v7.0.6]

**Comment by pcarruscag** [comment]
funny... '--buildtype=debugoptimized', while I fix it.
