### ISSUE TITLE
SU2 HEATFLUX not working

### ISSUE THREAD

**Issue by Mich803** [su2code/SU2#1084]
Hi everyone. 

I'm using SU2 to calculate the drag reduction in a fuselage by heating the boundary layer. 

For doing that I'm applying a heat-flux with "MARKER_HEATFLUX" at some part of my fuselage. After calculating the simulation and seeing the post-processing I obtain a heated surface but a very very small transfer to the boundary layer and to the air free stream, maybe cero transfer. 

I'm attaching some pictures showing a cut of the fuselage with different contours, like pressure, Mach, and TEMPERATURE. 
I'm also attaching the .cfg file for you to know if I'm doing it wrong. 

Thanks very much for your time!!

![4](https://user-images.githubusercontent.com/72448710/95202887-3bab0880-07e2-11eb-9768-c3957172fe2f.png)
![1](https://user-images.githubusercontent.com/72448710/95202890-3c439f00-07e2-11eb-9496-939564ae2445.png)
![2](https://user-images.githubusercontent.com/72448710/95202893-3cdc3580-07e2-11eb-880e-c52d14c518f9.png)
![3](https://user-images.githubusercontent.com/72448710/95202896-3cdc3580-07e2-11eb-8e4c-a1f744dc65bb.png)

[Heatflux.txt](https://github.com/su2code/SU2/files/5333800/Heatflux.txt)

**Comment by oleburghardt** [comment]
Hi,
so just from looking at the temperature plots, they shouldn't give an (almost) zero heatflux? It rather looks like temperature increases a lot when approaching the mantas.. ?

Best, Ole
