### ISSUE TITLE
Error centrifugal_blade test case

### ISSUE THREAD

**Issue by flybob91** [su2code/SU2#1086]
**Describe the bug**
I met an error while running the test case  [centrifugal blade](https://github.com/su2code/SU2/tree/master/TestCases/turbomachinery/centrifugal_blade) which gives

```
Error in "void CConfig::SetConfig_Parsing(std::istream&)": 
-------------------------------------------------------------------------
Line 139 MARKER_NRBC: invalid option name. Check current SU2 options in config_template.cfg.
Line 141 MIXING_PROCESS_TYPE: invalid option name. Check current SU2 options in config_template.cfg.
Line 155 MARKER_TURBO_PERFORMANCE: invalid option name. Check current SU2 options in config_template.cfg.
GRID_MOVEMENT: invalid option value YES. Check current SU2 options in config_template.cfg.
Line 172 GRID_MOVEMENT_KIND: invalid option name. Check current SU2 options in config_template.cfg.
Line 178 ROTATION_RATE_X: invalid option name. Check current SU2 options in config_template.cfg.
Line 178 ROTATION_RATE_Y: invalid option name. Check current SU2 options in config_template.cfg.
Line 178 ROTATION_RATE_Z: invalid option name. Check current SU2 options in config_template.cfg.
```

**To Reproduce**
Another case that gives me the same problem is the [centrifugal stage](https://github.com/su2code/SU2/tree/master/TestCases/turbomachinery/centrifugal_stage) test case

**Desktop (please complete the following information):**
 - OS: [Linux (Ubuntut 16.04 LTS)]
 - C++ compiler and version: [g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0]
 - SU2 Version: [v7]

**Comment by pcarruscag** [comment]
Those two cases are not part of the regression suite, and so they were probably not updated as some of the options were renamed.
You can have a look at the other turbomachinery examples (at least two of them are part of the regressions) it should be simple to adapt those options.

**Comment by flybob91** [comment]
Thank you Pedro. I'm happy I can exlude compliation error.

**Comment by afshawnlotfi** [comment]
> Thank you Pedro. I'm happy I can exlude compliation error.

Wait so what did you do to get this working, I'm having the same issue
