### ISSUE TITLE
A lot of warnings from the Intel compiler when building the AD version

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#1087]
**Is your feature request related to a problem? Please describe.**
When building the AD version of SU2 with the Intel compiler a lot of warnings are given. Most of these warnings are of the type

warning #2196: routine is both "inline" and "noinline"

The files where the warnings come from are
externals/codi/include/codi/tapes/modules/tapeBaseModule.hpp
externals/codi/include/codi/tapes/chunkVector.hpp
externals/codi/include/codi/tools/data/jacobian.hpp

The total number of warnings is roughly 3000, so any other information is very difficult to pick up.

**Describe the solution you'd like**
Remove either the inline or noline, if possible.

**Describe alternatives you've considered**
We can ignore the warning, if you think it is not a relevant one. However, I cannot judge that.

**Additional context**
I can provide more information, e.g. the entire log file of the build process.

**Comment by MaxSagebaum** [comment]
We have submitted a bug report to Intel about this three years ago. I recently talked with a higher support guy from Intel and he told me that this ticket is on very low priority. 

If you (or anybody else) has the possibility to submit a bug report to intel, we would appreciate it. Bug report number 02697346.

The problem is, that we defined this method inside of the template class, which makes it automatically inlined. For specific methods I do not want them to be inlined, since it provides a small performance boost and also improves debugging and performance sampling.

An example is:
```
#include <iostream>

template<typename T>
struct S1 {
  void func() { std::cout<< "Creates no warning, is inlined" << std::endl;}
};

template<typename T>
struct S2 {
  __attribute__((noinline)) void func() { std::cout<< "Creates warning, is not inlined" << std::endl;}
};

template<typename T>
struct S3 {
  __attribute__((noinline)) void func();
};

template<typename T>
void S3<T>::func() { std::cout<< "Creates no warning, is not inlined" << std::endl;}

int main(int nargs, char** args) {
  S1<int> s1; 
  s1.func();

  S2<int> s2; 
  s2.func();

  S3<int> s3; 
  s3.func();
}
```

I do not want to change CoDiPack to the implementation of S3 since this is a code copy of the declaration. But there are other options. You can disable the 'no inlining' with the option -DCODI_UseAvoidedInlines=0. Another option is, that we add the pgrama `#pragma warning disable 2196` for intel compilers in CoDiPack. But this is also not a good option as general case. So I would add it as a new parameter e.g. `-DCODI_DisableIntelNoInlineWarning`

What do you think?

**Comment by pcarruscag** [comment]
Intel has some very idiosyncratic ideas about the `noinline` and `alwaysinline` attributes (we get warnings for the second on the SU2 side).

I think we can implement the #pragma alternative on SU2's side.

@vdweide the warnings I mentioned with GCC10 are of this type:
```
../SU2_CFD/src/solvers/CFEM_DG_NSSolver.cpp:6575:60: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘using su2double = codi::RealReverse’ {aka ‘class codi::ActiveReal<codi::JacobiTape<codi::JacobiTapeTypes<codi::ReverseTapeTypes<double, double, codi::LinearIndexHandler<int> >, codi::ChunkVector> > >’} with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
 6575 |         memcpy(resElem+nVar*i, fluxes+NPad*i+llNVar, nBytes);
```
They also occur for memset operations. This needs --warnlevel=2 to show up.

**Comment by vdweide** [comment]
I don't have a specific preference for either #pragma warning disable 2196 or -DCODI_DisableIntelNoInlineWarning. However, if we do get this type of warning also for SU2, then it is logical to use the same solution for both. @MaxSagebaum, if you do not like the pragma solution, maybe we could have a general flag like -DDisableIntelNoInlineWarning?

**Comment by MaxSagebaum** [comment]
Yes we can have the same flag `-DDisableIntelNoInlineWarning` is fine for me. 

I will implement it using the pragma solution, but a header library should not disable warnings of the compiler for the program. I checked the documentation. It will probably be something like:

```
#pragma warning push
#pragma warning disable 2196
// code
#pragma warning pop

**Comment by MaxSagebaum** [comment]
As always, there is some other bug lurking in the background. The pop lets the warning reappear again. I posted this issue now in the Intel forums:

https://community.intel.com/t5/Intel-C-Compiler/Inline-and-no-inline-warning/m-p/1216764#M37672

and 

https://community.intel.com/t5/Intel-C-Compiler/Where-is-the-online-documentation-for-suppressing-warnings/m-p/1111955/highlight/false#M32905

**Comment by pcarruscag** [comment]
I will implement the pragma option on our side, in the same place we define FORCEINLINE and NEVERINLINE, which I think is before we include CoDi, as there is one more of these silly warnings I need to disable.

I would take GCC over Intel every day of the week and twice on Sundays and bank holidays.

**Comment by vdweide** [comment]
That may be, but for some of my applications Intel is significantly faster than GCC. 

Anyway,  can we close this issue?

**Comment by MaxSagebaum** [comment]
Yes it can be closed. I added the above option to the CoDiPack master branch:

https://github.com/SciCompKL/CoDiPack/commit/1b8d3f5f03de560fb63a2a76ad91ab7bb3fa67d8

**Comment by vdweide** [comment]
So let's close it then. Thanks @MaxSagebaum  and @pcarruscag for responding so quickly.
