### ISSUE TITLE
../src/toolboxes/CSymmetricMatrix.cpp(220): error: identifier "MKL_DC_POTRF_CONVERT" is undefined

### ISSUE THREAD

**Issue by rohezal** [su2code/SU2#1088]
Hi guys,

we used bootstrap to get the new autoconf tools and build the configure file.

For compilation we use 

  1) intel-studio-2019.5         2) mpi/intelmpi/2019.5.281  

There was a problem with an openmp flag which was not set (-qopenmp for intel).

After fixing this we are getting this errors:

```
"../src/toolboxes/CSymmetricMatrix.cpp(220): error: identifier "d" is undefined
    dpotrf_(&uplo, &sz, mat.data(), &sz, &info);
    ^

../src/toolboxes/CSymmetricMatrix.cpp(220): error: identifier "MKL_DC_POTRF_CONVERT" is undefined
    dpotrf_(&uplo, &sz, mat.data(), &sz, &info);
    ^
```

compilation aborted for ../src/toolboxes/CSymmetricMatrix.cpp (code 2)
make[1]: *** [../src/toolboxes/libSU2_a-CSymmetricMatrix.o] Error 2"

This part is an 

#ifdef part of the codefile. After changing to HAS_LAPACK to HAS_LAPACK_WILL_NEVER_BE_FOUND_1234

the code continus compiling. 

Maybe this is an intel specific problem, but it may be a problem for a some users. We don't know if the software work properly without the line 220 of CSymmetricMatrix.cpp. 

Kind regards

**Comment by pcarruscag** [comment]
Please use meson and ninja to build the code as documented here: https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/

This is what I do:
```
export BUILD=build
export CXXFLAGS="-funroll-loops -march=native -mtune=native"

./meson.py $BUILD -Dcustom-mpi=true -Dwith-omp=true -Denable-mixedprec=true -Denable-autodiff=true -Denable-tecio=false -Denable-mkl=true -Dmkl_root=$MKLROOT --prefix=$PWD/$BUILD --optimization=2 --warnlevel=2
./ninja -C $BUILD install
```
Depending on how your compilers are setup you may find convenient to modify this:
```
if get_option('custom-mpi')
  mpi_dep = []
```
To:
```
if get_option('custom-mpi')
  mpi_dep = [declare_dependency(link_args: ['-lmpi'])]
```
In the meson.py script, I'm sure there is a way to do it with environment variables but I never bothered trying.

Regards,
Pedro

**Comment by pcarruscag** [comment]
Let us know if you are still having compilation issues, I'll close this for now.
Regards,
Pedro
