### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by GiacomoFly** [su2code/SU2#1093]
Dear all,

I have tried to install/compile the source code on Windows 10 by following literally the instructions on the documentation page but I got the following error also reported in the attached document:

OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'C:\\MINGW_W64\\mingw_w64\\posix\\mingw64\\bin\\..\\lib\\gcc\\x86_64-w64-mingw32\\8.1.0\\libC:\\MICROSOFT_SDKs\\MPI\\Lib\\x64\\msmpi.a'

[error.txt](https://github.com/su2code/SU2/files/5379915/error.txt)
 
Can you help me to fix it?
Thanks,

**Comment by pcarruscag** [comment]
It looks like that path ('C:\MINGW_W64\mingw_w64\posix\mingw64\bin\..\lib\gcc\x86_64-w64-mingw32\8.1.0\libC:\MICROSOFT_SDKs\MPI\Lib\x64\msmpi.a') should actually be 2
C:\MINGW_W64\mingw_w64\posix\mingw64\bin\..\lib\gcc\x86_64-w64-mingw32\8.1.0\lib
C:\MICROSOFT_SDKs\MPI\Lib\x64\msmpi.a

Maybe some environment variable is not setup correctly? I'm not at all familiar with building SU2 on Windows unfortunately.

**Comment by vdweide** [comment]
Can you check if you can compile and run the mpi version of hello world?

See e.g https://abhilashreddy.com/writing/3/mpi_instructions.html for more information to set up Microsoft MPI with mingw.

**Comment by pcarruscag** [comment]
It has been about a month so I'll close this issue, if you still need help let us know.

**Comment by GiacomoFly** [comment]
Dear Pedro,

thank you for your support!!
Thabks to your suggestion I have fixe d the issue! Thank you again!!

Giacomo

Il Ven 20 Nov 2020, 18:58 Pedro Gomes <notifications@github.com> ha scritto:

**Comment by ndkazu** [comment]
Hello, 
I have the exact same problem by following instructions for windows.
I generated a "msmpi.a" file by following the instrusction given in the link: https://abhilashreddy.com/writing/3/mpi_instructions.html
added the file to my path, and even manually added it in the msmpisdk folder, nothing is changed.
As you can see in the attached textfile, mpiexec seems to work fine. 
[mpi_lib_problem.txt](https://github.com/su2code/SU2/files/6782110/mpi_lib_problem.txt)

thanks in advance for your help.
Kazunobu
