### ISSUE TITLE
How to check the optimization objective is  minimize OPT_OBJECTIVE

### ISSUE THREAD

**Issue by tuzitt** [su2code/SU2#1103]
Hello guys,
I run the shape_optimization.py to optimize a wing. I want to minimize the drag function. But the drag function increased. And I have not found any setting in the configuration that  clearly define the  optimization goal is minimize or muximize the  objective function. I only found  two setting, 'OPT_OBJECTIVE= DRAG * SCALE' and 'OPT_CONSTRAINT= (STATION1_THICKNESS > 0.077) *SCALE' , ralating to optimization objective. Does it  default to minimize drag and muxmize lift? 
Can anybody know that?
the second question is about the scale of OPT_OBJECTIVE and OPT_CONSTRAINT. Does the SLSQP change  the constrainted question into unconstrainted with the two scale when solve the optimization question. If so, can anyone tell me the transformed function.
Thanks.

 - SU2 Version: [ v6.2.0]

**Comment by economon** [comment]
For the first question, yes, the framework assumes that drag should be minimized and lift maximized. You should be able to flip it by using a negative scale factor, or you can directly modify the python framework to change this (just a one-line change). See get_objectiveSign() in SU2/SU2_PY/SU2/io/tools.py.

For the second questions, it is difficult to known what SLSQP is doing under the hood. However, we use the scale factors to try to better control the optimization process (step sizes in particular). See more discussion about this in #733
