### ISSUE TITLE
Compilation fails with gcc5.3.0 due to isnan() ambiguity 

### ISSUE THREAD

**Issue by TobiKattmann** [su2code/SU2#1112]
**Describe the bug**
In PR #1105  an `isnan(SU2_TYPE::GetValue(monitor))` check was introduced. I get a compiler error (serial build, no AD DD involved) `call of overload isnan(souble&) is ambiguos` so the complier is probably confused about the return type of `SU2_TYPE::GetValue(monitor)` which is `passivedouble` which itself is hardcoded to be `double` in `datatype_structure.hpp`. Or sth else is happening idk

![image](https://user-images.githubusercontent.com/31306376/99810957-c5b9f100-2b44-11eb-80e6-b58ce4277bd2.png)

I only have the problem with gcc5.3.0. On the same system I have an unsupported gcc7.4.0 that works. My private machine with gcc10.2.0 works fine as well. So I guess it is a specific compiler problem.

In my I hit the :keyboard: a few times without actually knowing what I am doing:
- use `isnan(monitor)` ... same error
- use `isnan(static_cast<double>(monitor))` ... same error
- use `isnan(static_cast<double>(SU2_TYPE::GetValue(monitor)))` ... same error
- changed the return type of `GetValue` to `double` ...same error

I guess this problem is really specific to my setup. gcc5.3.0 is old but not grandpa kinda old with the release dec 2015 ... well ok maybe it is :older_man: 
I would be happy with some suggestions what to try out maybe, also if I misinterpret the error a pointer in the right direction would help. If @pcarruscag could have a quick look that would be great. 

Thanks and warm regards, Tobi

**To Reproduce**
You probably cant without an old enough compiler

**Desktop (please complete the following information):**
 - OS: RHES 7.6
 - C++ compiler and version: g++ (GCC) 5.3.0
 - SU2 Version: latest develop

**Comment by pcarruscag** [comment]
Can you try sticking the good old std:: behind `isnan`
(I don't have 5.3.0 and 5.4.0 does not complain).

**Comment by TobiKattmann** [comment]
Dang... that fixes it :octopus: . I close issue then as you already resolve this in PR #1107 
Thanks pedro
