### ISSUE TITLE
How does SU2 select the axis about which the simulation is treated to be axisymmetric?

### ISSUE THREAD

**Issue by sandeeprmurthy** [su2code/SU2#1121]
If I have a 2D square mesh with every boundary as a symmetry BC and if I select AXISYMMETRIC=YES which directions does SU2 assume as the radial and axial directions ?

**Comment by bigfooted** [comment]
The symmetry axis is always the X-axis, so the first coordinate. The r-axis is the Y-axis, so the second coordinate. the axisymmetry has to be at r=y=0

**Comment by sandeeprmurthy** [comment]
Thank you for the clarification.

**Comment by sandeeprmurthy** [comment]
Section C 4 in the following paper https://su2code.github.io/documents/AIAA-2018-3111.pdf says that the axisymmetric source terms are yet to be added. Is this no longer necessary or do we need to modify the code for the compressible viscous cases to work?

**Comment by WallyMaier** [comment]
There is a current pull request for the compressible viscous source terms at the moment.  Those should be pulled into develop soon, but feel free to take a look :)

**Comment by WallyMaier** [comment]
This was completed in #1106 .
