### ISSUE TITLE
Segfault with Multizone SU2_CFD_AD in CNearestNeighbor::SetTransferCoeff

### ISSUE THREAD

**Issue by TobiKattmann** [su2code/SU2#1123]
**Describe the bug**
Hi, 
1. compile SU2 with debug flags and autodiff
2. run /Testcases/coupled_cht/incomp_2d with SU2_CFD_AD
3. segfault coming from `partial_sort` in CNearestNeighbor.cpp ll. 142-147. The actual segfault is down in the stl std::__adjust_heap 🤷 

The problem occurs with another CHT problem of mine but I suspect it is a related to multizone in general. The segfault does not occur when using `KIND_INTERPOLATION= RADIAL_BASIS_FUNCTION`

As I used only gcc I am not sure whether it might be an stl bug (or feature because the code is wrong) so trying with clang or intel might be worth a shot.

I know I had this issue already quite some time ago but forgot about it. 

If you know sth about it plz let me know 📣 👂 

**To Reproduce**
described above

**Desktop (please complete the following information):**
 - OS: Manjaro and RHLES
 - C++ compiler and version: gcc 5.3.0 and 10.2.0
 - MPI implementation and version: 3.1.6 and 4.0.4
 - SU2 Version: latest develop

**Comment by pcarruscag** [comment]
The fact that the primal works, and the comment I left in that function
`/*--- Find k closest points (need to define the comparator inline or debug build give wrong results). ---*/`
should be pretty indicative of the level of crazy happening there.

I think convectional sort works and min_element too, at least they did not have the "inline problem" above in direct mode.
I was never able to find confirmation if this is a glibc bug... and it does not seem very easy to install a different glibc version...

ISOPARAMETRIC interpolation is equivalent to NEAREST_NEIGHBOR for matching grids.
I can also try to re-write the algorithm...

**Comment by TobiKattmann** [comment]
u no dumdum
