### ISSUE TITLE
Info on current status of LM transition model in SU2

### ISSUE THREAD

**Issue by lorenzob95** [su2code/SU2#1130]
Hi all!

I'm using SU2 v.7.0.3 to compute the flow field over a wing of particular shape and I'd need LM transition model to match experimental results. I already tried Spalart Allmaras with Bas-Cakmakcioglu without success.

In the SU2 source code I found that classes for LM model are already defined, but when I try to activate it with the option:
KIND_TRANS_MODEL= LM
a bad termination error occurs during the Numerics Preprocessing phase.

I posted this thread on the online CFD forum (https://www.cfd-online.com/Forums/su2/232347-info-current-status-lm-transition-model-su2.html) and it seems that the "creation logic" is broken and the code has to be fixed. I have been redirected here, since someone could possibly have already solved the problem.

Thanks in advance for any kind of help!

**Comment by vdweide** [comment]
I worked on this quite some time ago. It is in the branch feature_LM_model. However, it is significantly out of sync with the current development version and probably needs to be implemented pretty much again. @economon, back then we had the discussion that it was better to wait until a general framework for additional transport equations was in place, but we have not really followed up on this. Any suggestion how to tackle this now?

**Comment by economon** [comment]
@vdweide : I think our goal was to look again after the general changes for scalar transport equations from #777 were added. That PR was eventually closed, as there are other efforts that will supersede it when they are submitted. In particular, the work on combustion modeling (flamelets) should include all of those changes and more. Maybe @bigfooted has more info about the latest status and if we can expect a PR soon (prob after the holidays either way, I am guessing)? 

I think that if it essentially needs to be reimplemented, then it makes sense to wait for the structural changes. For now, we should just throw an error if someone tries to run with LM, since it is not working.

**Comment by rkagarwal1000** [comment]
You should use two-equation Wray-Agarwal (WA) Gamma Transition model. It has one equation WA RANS model described on NASA TMR and one intermittency transport equation gamma (AIAA Paper  2018-3384). It will work like a charm. It is not difficult to code. We can provide you source code for OpenFOAM.

**Comment by pcarruscag** [comment]
@lorenzob95 we talked about this issue in our weekly developers meeting.
The current implementation of LM in the code is not stable enough and it has known bugs, so we will not re enable it for now.
A revised implementation by @vdweide exist in branch https://github.com/su2code/SU2/tree/feature_LM_model, but this is based on SU2 v6.2, it has been used on simple problems, convergence is not ideal on more complicated ones.
The decision is to wait for some developments that will make it easier to bring this revised implementation into version 7 (which is different in many ways from 6).
You can follow this issue to know when this gets implemented, it will probably take a few months.

**Comment by rkagarwal1000** [comment]
I suggest that you incorporate Wray-Agarwal (WA) one equation RANS model listed on NASA TMR in SU2. NASA is planning to list two equation WA-gamma transition model on NASA TMR next month. WA model is available on Github and WA model will also be posted on Github as source code. If you need any additional information or help, let me know.
Ramesh Agarwal
________________________________

**Comment by lorenzob95** [comment]
@economon , @vdweide , @pcarruscag , @rkagarwal1000 thank you very much for your interest and help, it's really appreciated. Probably I will try the proposed implementation.
Hopefully, the project on which I'm working will end in few months, so I think I will not be able to use the newly implemented model. In any case, a transitional model will surely be useful for future analysis using SU2. 
Regarding the suggestion by prof. Agarwal, I read the paper and found that an experimental correlation for Re_theta is used (which, if I'm not wrong, is correct for Blasius boundary layer and it's still acceptable for moderate pressure gradients). In my application, adverse pressure gradients are an important aspect and this model, just like Bas-Cakmacioglu's, despite being faster than other models, will probably produce incorrect results.  Please, correct me if I'm wrong.
Thanks again

**Comment by pcarruscag** [comment]
Thank you for the recommendation @rkagarwal1000, traditionally the way that features are added to SU2 is through the contributions of volunteers that are interested in using those features, rather than via a centrally organized effort.
These new developments we are waiting for to re-implement LM should also facilitate the implementation of other models, if you would like to leave a link to the Github repository you mentioned, it might make it easier for someone interested in adding new transition models to SU2.

**Comment by rkagarwal1000** [comment]
All our calculations with WA-gamma model have shown that it is as good as LM model and even better than LM in some cases including adverse pressure gradient mildly separated flows. However, no model is perfect, but WA-gamma model has worked as good as LM or better in many cases. Not all cases are reported in the original first paper by Nagapetyan and Agarwal. If you can provide me information about your case, I can have my student try it using OpenFOAM or at least I can give you my hunch whether WA-gamma model will work or not. We also have WA-T model following SA-BC approach. It is unpublished but will be published in Aviation 2021 conference. After that it may be put on NASA TMR. NASA has our submitted paper.
Ramesh Agarwal
________________________________

**Comment by rkagarwal1000** [comment]
The WA RANS models (WA2017m and WA2018) source code for OpenFOAM and UDF for ANSYS Fluent are available on:
 https://github.com/xuhanwustl/WrayAgarwalModels

We have not put the WA-gamma transition model on github right now. We can do it quickly within a week.

Ramesh Agarwal



________________________________

**Comment by lorenzob95** [comment]
@rkagarwal1000  I'm studying a case like this https://aip.scitation.org/doi/full/10.1063/1.4896748. I don't want to change the subject of the discussion too much nor to use your time or your student's, so if you are interested I can provide the mesh file, but even just your hunch would be really appreciated.

**Comment by rkagarwal1000** [comment]
I am working from home. I cannot download the paper. Could you send me the pdf? Thanks.
Ramesh Agarwal
________________________________
