### ISSUE TITLE
Mesh Adaptation and missing SU2_MSH in v7.0.8

### ISSUE THREAD

**Issue by timjim333** [su2code/SU2#1143]
I noticed that there is a 'Grid Adaptation Strategy' section in the v7 .cfg files but I'm not entirely sure how to get it working (running a supersonic Euler).

I changed `KIND_ADAPT= GRAD_FLOW` and tried running `SU2_CFD` but no mesh adaptation seemed to take place. After digging around the github comments, I tried running `SU2_src/SU2_PY/mesh_adaptation.py` with python but it gave me an error:

```
------------------------- Exit Success (SU2_CFD) ------------------------

Traceback (most recent call last):
  File "/home/user/programs/su2/SU2_src/SU2_PY/mesh_adaptation.py", line 106, in <module>
    main()
  File "/home/user/programs/su2/SU2_src/SU2_PY/mesh_adaptation.py", line 62, in main
    options.save_all    )
  File "/home/user/programs/su2/SU2_src/SU2_PY/mesh_adaptation.py", line 93, in mesh_adaptation
    SU2.run.MSH(config)
  File "/home/user/programs/su2/SU2_src/SU2_PY/SU2/run/interface.py", line 134, in MSH
    run_command( the_Command )
  File "/home/user/programs/su2/SU2_src/SU2_PY/SU2/run/interface.py", line 292, in run_command
    raise exception(message)
RuntimeError: Path = /home/user/projects/mesh_adapt_testing/,
Command = /home/user/programs/su2/SU2-7.0.8/bin/SU2_MSH config_MSH.cfg
SU2 process returned error '127'
/bin/sh: /home/user/programs/su2/SU2-7.0.8/bin/SU2_MSH: No such file or directory
```

And indeed, when I checked the compiled SU2 bin, `SU2_MSH` seemed to be missing. Has this functionality been removed and is that why the python script is not in the compiled SU2 bin?

I found that some people have had success using the `feature_adap` branch instead but that is running on v7.0.3. I also tried compiling this version but there appears to be a `mesh_adaptation.py` and `mesh_adaptation_amg.py`. If one wants to use mesh adaptation, is this the recommended branch?

Wishing all a Merry Christmas, good health and a happy New Year.
Thanks and regards,
Tim

**Desktop (please complete the following information):**
 - OS: Linux CentOS 8
 - C++ compiler and version: GCC 8.22
 - MPI implementation and version: Intel (Open MPI) 3.0.0
 - SU2 Version: v7.0.8

**Comment by pcarruscag** [comment]
The native mesh adaption was deprecated. The amg interface is in development, you can re-open some of the issues where it is mentioned to ask new questions (that way all "documentation" stays in one place).
