### ISSUE TITLE
Variable length arrays in Common/src/grid_movement/CVolumetricMovement.cpp

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#1146]
**Describe the bug**
It is not really a bug, but the coding in not conform ISO C++. In the file Common/src/grid_movement/CVolumetricMovement.cpp there are quite a few arrays defined with length nDim, which is a runtime value. @pcarruscag, you have defined the MAXNDIM parameter somewhere, right? It is better to use that one.

**To Reproduce**
Compile with -Wpedantic in combination with g++.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - C++ compiler: GCC 8.4.0
 - MPI implementation and version: Any
 - SU2 Version: current develop

**Comment by pcarruscag** [comment]
Damn...
