### ISSUE TITLE
Py Wrapper hangs on Set_MPI_ActDisk in CEulerSolver

### ISSUE THREAD

**Issue by EduardoMolina** [su2code/SU2#1150]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*

Python wrapper hangs on Set_MPI_ActDisk in CEulerSolver.cpp line 1091 "SU2_MPI::Barrier(MPI_COMM_WORLD);"
If the SU2_CFD is called without python wrapper, it runs ok.

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*

Go to the test case solver, choose the propeller one and run the following script.

mpirun -np 2 python launch_su2.py --parallel -f propeller.cfg
[launch_su2.py.txt](https://github.com/su2code/SU2/files/5762218/launch_su2.py.txt)

There is no issue when SU2_CFD is called directly:
mpirun -np 2 SU2_CFD propeller.cfg

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04.6 LTS]
 - C++ compiler and version: [g++ (GCC) 9.3.0]
 - MPI implementation and version: [OpenMPI 4.0.5]
 - SU2 Version: [develop]
 - Python Version: 3.6.12
 - MPI4Py Version: 3.0.3

In order to fully reproduce the error one can try running the following commands under Anaconda Python Manager, although the same error appears using the default ubuntu python3 and openmpi compilers :
->conda create -n su2code python=3.6
->conda activate su2code
->conda install -c conda-forge c-compiler compilers cxx-compiler openmpi swig mpi4py numpy scipy

Install SU2 with the following script:

#!/bin/bash
export CC=/path/anaconda3/envs/su2code/bin/mpicc
export CXX=/path/anaconda3/envs/su2code/bin/mpicxx
export CXXFLAGS=${CXXFLAGS}:"-lmpi"
rm -rf SU2/build
rm -rf SU2_exec_dev/bin
cd SU2
./meson.py build -Denable-pywrapper=true  -Dcustom-mpi=true --prefix=/path/SU2_exec_dev
./ninja -C build install

**Comment by pcarruscag** [comment]
Seeing as that is one of the few places in SU2 where buffered sends are used... and that SU2_MPI::Buffer_attach is only called in SU2_CFD.cpp... My spider senses suggests Buffer_attach needs to be called on the python side.
Alternatively I would try replacing Bsend by Send and deleting the barriers.
(that ActDisk function looks way too complicated for its own good)
