### ISSUE TITLE
ninja build fails with `-Dcustom-mpi=true -Dextra-deps=mpich` flags

### ISSUE THREAD

**Issue by aditya12398** [su2code/SU2#1151]
I had raised the issue #1000 and followed the development when #1102 was proposed. I tried to install SU2 on my new PC with the proposed changes but the ninja built failed with [this long error](https://www.dropbox.com/s/mh3x98kcv8pifv7/ninjarun.log?dl=0)

**To Reproduce:**
Run the meson script similar to the following command: `./meson.py build -Denable-openblas=true -Denable-autodiff=true -Denable-directdiff=true -Dwith-mpi=enabled -Dcustom-mpi=true -Denable-pywrapper=true -Dextra-deps=lapack,mpich -Denable-pastix=false --prefix=/home/slimshady/UserPackages/su2-test/SU2_INSTALL`

**Desktop:**
 - OS: Arch Linux: Kernel 5.10.4
 - C++ compiler and version: gcc (GCC) 10.2.0
 - MPI implementation and version: mpich 3.3.2
 - SU2 Version: 7.0.8

I was able to install it by changing the meson.build file like so:
```
# mpi_dep = [dependency('mpi', language: 'c', required : get_option('with-mpi')),
# dependency('mpi', language: 'cpp', required : get_option('with-mpi'))]
mpi_dep = [dependency('mpich', required : get_option('with-mpi')),                            #new-change
dependency('mpich', required : get_option('with-mpi'))]                                       #new-change
```
and then configuring without the custom-mpi flag.

What could be the issue? Am I using the flags wrong?

**Comment by pcarruscag** [comment]
I built the code with your command and it worked.
In the error message you have undefined references to e.g. ompi_mpi_long_long_int
I "grepped" my SU2 directories for that kind of symbol, it only appears on binaries built with OpenMPI, not on those built with MPICH.
The change you made to the meson file is equivalent to what -Dextra-deps does.
So, I do not think this is an issue of the build system.

**Comment by aditya12398** [comment]
In that case it sounds like the system still builds with openmpi if it is installed, can that be the issue?
Because it seems like it builds with the openmpi libraries even after providing said flags.

I will try it on another system. Do you suggest trying something? Could it be because of a faulty mpich installation or something of that sort?
