### ISSUE TITLE
Modified-Steger-Warming segfaults

### ISSUE THREAD

**Issue by WallyMaier** [su2code/SU2#1161]
I am making a note here that the MSW scheme in develop segfaults. I will try to find to fix the issue, unless someone already has.

**Comment by pcarruscag** [comment]
I started having a "quick" look, since I was doing stuff with valgrind, that scheme is totally *********

**Comment by WallyMaier** [comment]
I agree....though its how most hypersonics codes get any time of convergence.

**Comment by pcarruscag** [comment]
I meant its implementation :) I got no problem with the method.
