### ISSUE TITLE
Bugs in CVolumetricMovement::ComputenNonconvexElements

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1171]
**Describe the bug**
A compiler warning brought me to this routine.
The logic to check for convexity of 3D elements seems flawed, I left two comments in the code in #1167 (it will be in develop soon enough) of what seems odd about it.
I think this routine was introduced in #1076, and it seems the intention is to check the volume of the tet associated with each corner of an element, a similar method is used in CPhysicalGeometry::Check_IntElem_Orientation.

I am not planning to fix this myself :)

**Comment by bigfooted** [comment]
I see the problem. With meson I use --warnlevel=3 but do not see a warning for this function, what do I need to do to see it?

**Comment by pcarruscag** [comment]
It is compiler dependent, I got the warning with clang with warnlevel 2, now it will probably not show the warning because I put an "if false" around that part of the code.

**Comment by bigfooted** [comment]
sorry, stale bot, I'm still planning on fixing it, I just didn't have much time lately to work on it.
