### ISSUE TITLE
CDriver instances deadlock when initialised with subset of MPI_COMM_WORLD

### ISSUE THREAD

**Issue by aa-g** [su2code/SU2#1179]
**Describe the bug**
When creating a CDriver instance, for example through the Python wrapper, with an MPI communicator which is defined only on a subset of the processes on which the MPI library was initialised, SU2 will deadlock. This seems to be because most of the MPI communication and synchronisation operations in SU2 explicitly refer to the global `MPI_COMM_WORLD`.

The issue arose when attempting to control several Euler/RANS SU2 `CSinglezoneDriver` and `CDiscAdjSinglezoneDriver` instances in parallel (i.e. simultaneously) within a larger optimisation code, which provides each analysis with a subset of the ranks in its own MPI communicator.

Naively replacing _all_ references to `MPI_COMM_WORLD` with `SU2_MPI::GetComm()` throughout the code (except where it is defined, and where it is used to initialise the MPI wrapper in the SU2_XXX.cpp files) prevents the deadlock and results in the desired behaviour. However, I imagine that this "fix" may well cause all sorts of issues outside of my own, limited use case.

**To Reproduce**
The issue can be reproduced with any SU2_CFD configuration file and mesh, run in parallel using the Python wrapper as follows: 
```
from mpi4py import MPI
import pysu2  # or pysu2ad


filename = 'example.cfg'
zones = 1

rank = MPI.COMM_WORLD.Get_rank()
size = MPI.COMM_WORLD.Get_size()

group = MPI.COMM_WORLD.group.Excl([0])  # exclude the first rank
comm = MPI.COMM_WORLD.Create_group(group)

if comm:  # is False only on the excluded rank
    print("Running SU2 on global rank {} of {} ... ".format(rank, size))

    # create SU2 instance -- will hang during Geometry preprocessing
    instance = pysu2.CSinglezoneDriver(filename, zones, comm)

else:
    print("Doing nothing on global rank {} of {} ... ".format(rank, size))

```

**Desktop (please complete the following information):**
 - OS: Redhat 7.7
 - C++ compiler and version: g++ (GCC) 4.8.5
 - MPI implementation and version: MPICH 3.2.1
 - SU2 Version: 7.0.2 "Blackbird" (looks to be reproducible on 7.1.0 also)

**Comment by pcarruscag** [comment]
All external libraries seem to take a communicator as argument. And it would be important for this to work for example for fault tolerant communication.
It would be very important to undefine the dummy MPI_COMM_WORLD used for serial compilation to ensure that it does not get silently re-introduced in the code.

Can you create a PR for this?

**Comment by TobiKattmann** [comment]
I guess this can be closed, now that your PR is merged @aa-g (feel free to reopen but as far as I understand this issue is fixed with the PR). Thanks  a lot for the contribution 💐
