### ISSUE TITLE
bad Mutationpp address in meson init.py

### ISSUE THREAD

**Issue by BTemp1282020** [su2code/SU2#1184]
A clean build fails nearly immediately upon running ./meson.py as the download of Mutationpp gets a 404 error.

to fix:
Remove ".git" from github_repo_mpp (line 56 of init.py)

**Comment by CatarinaGarbacz** [comment]
thanks for reporting this together with the solution! fixed in the feature_NEMO branch and will be pushed to develop as soon as possible
