### ISSUE TITLE
Error with wetted area calculation

### ISSUE THREAD

**Issue by aidanjungo** [su2code/SU2#1190]
By running exactly the same mesh and config flle on Linux Centos 8 with two version of SU2, it leads to two different values for the wetted area which is calculated during the initialization.

with SU2 v7.0.3:

> Finding max control volume width.
> Semi-span length = 13.5934 m.
> **Wetted area = 466.385 m^2.**
> Area projection in the x-plane = 19.4802 m^2, y-plane = 109.691 m^2, z-plane = 165.851 m^2.
> Max. coordinate in the x-direction = 34.8253 m, y-direction = 13.5934 m, z-direction = 5.44607 m.
> Min. coordinate in the x-direction = -0.00557099 m, y-direction = -13.5934 m, z-direction = -1.75235 m.

with SU2 v7.1.0:

> Finding max control volume width.
> Semi-span length = 13.5934 m.
> **Wetted area = 1.85378e-06 m^2.**
> Area projection in the x-plane = 19.4802 m^2, y-plane = 109.691 m^2, z-plane = 165.851 m^2.
> Max. coordinate in the x-direction = 34.8253 m, y-direction = 13.5934 m, z-direction = 5.44607 m.
> Min. coordinate in the x-direction = -0.00557099 m, y-direction = -13.5934 m, z-direction = -1.75235 m

Regarding my geometry and the other values given, the second one (v7.1.0) seems to be the wrong one.

**Comment by pcarruscag** [comment]
It seems that a += became just an =.
Thanks for reporting we'll fix it (that value is only a convenience output, it does not affect any calculation).
