### ISSUE TITLE
BC intermittency is always zero in output file

### ISSUE THREAD

**Issue by Rois19952** [su2code/SU2#1196]
Hi everybody,

First of all thank you so much for all the work you have done with this amazing software.

I think there is a bug with the BC transition model in function CSourcePieceWise_TurbSA::ComputeResidual in path SU2_CFD/src/numerics/turbulent/.

The initialization value of chi_2 is 50.0 instead of 5.0 as suggested in the original paper at https://journals.sagepub.com/doi/pdf/10.1177/0954406217743537

Moreover, the computation of the variable term2 seems dubious, also when referring to the original paper. 

There is another bug related to the fact that gamma_bc is redefined within the above mentioned function. Thus when trying to output it by adding the option INTERMITTENCY to Volume_Output in .cfg file it results in a 0 value everywhere.

Thank you so much in advance and keep up with the great work!

Best,
Andrea

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - C++ compiler and version: gcc 9.3.0
 - MPI implementation and version: 4.0.3
 - SU2 Version: 7.1.0

**Comment by sametcaka** [comment]
Hello Andrea,
Please refer to these regarding the implementation of the model:

1- Cakmakcioglu, S. C., Bas, O., Mura, R., and Kaynak, U., "A Revised One-Equation Transitional Model for External Aerodynamics," AIAA Paper 2020-2706, June 2020, https://doi.org/10.2514/6.2020-2706

2- https://turbmodels.larc.nasa.gov/sa-bc_1eqn.html

Best,
Samet

**Comment by Rois19952** [comment]
Hi Samet,

Thank you so much, I totally missed this paper! The bug for gamma_bc still remains but it is a minor one.

Thank you again and have a nice evening.

Best,
Andrea

**Comment by pcarruscag** [comment]
Thank you for reporting Andrea, the output bug is probably on me, will be fixed in the next release.
Regards,
Pedro
