### ISSUE TITLE
ninja build with -Denable-autodiff=true failed

### ISSUE THREAD

**Issue by bakakouhai** [su2code/SU2#1209]
**Describe the bug**
Ninja build with -Denable-autodiff=true or -Denable-directdiff=true failed.
Build success with both option = false

**To Reproduce**
set either -Denable-autodiff=true or -Denable-directdiff=true and rebuild

**Desktop (please complete the following information):**
 - OS: Macosx BigSur
 - C++ compiler and version: clang-1200.0.32.29
 - MPI implementation and version: OpenMPI 4.0.5 [via homebrew]
 - SU2 Version: 7.1.0 [via git]

Attached are the logs for ninja build and meson.py --reconfigure
Cheers
bakakouhai

[ninja.log](https://github.com/su2code/SU2/files/6038336/ninja.log)
[meson.log](https://github.com/su2code/SU2/files/6038339/meson.log)

**Comment by pcarruscag** [comment]
@jblueh @MaxSagebaum is there a mpi4 compliant version of Medi?

@bakakouhai if the answer to the above is "no" you will need to downgrade to mpi 3.

**Comment by bakakouhai** [comment]
@pcarruscag Thank you for the fast response. In case I need to downgrade to OpenMpi 3, do you know where could I find the brew package [tap for su2 perhaps]? I checked the Homebrew formulae and there is no openmpi@3 on the core repo.

Otherwise I need to install from source, which I am not familiar with yet.

**Comment by MaxSagebaum** [comment]
@bakakouhai I tested this on my machine and in my OpenMPI version (4.0.4) they still exist. Therefore I can currently can not reproduce this myself and I would like to use you as a  guinea pig.

I made the fixes to MeDiPack in the branch bugfix/mpi4_0. Could you please checkout this branch and try if it works now? 
```
cd <SU2 dir>/externals/medi
git fetch
git checkout bugfix/mpi4_0
```

Thanks.

**Comment by bakakouhai** [comment]
@MaxSagebaum Building with -Denable-autodiff=true now. So far no error.

**Comment by bakakouhai** [comment]
@MaxSagebaum Finished building with both option = true without error.

Thank you for the fix. I can now try to connect SU2 with paraBlade.
Do I have to run git commands again to be back on default branch?

Attached are the new meson and ninja log.
They are from the last cycle:
    python meson.py --reconfigure build -Denable-directdiff=true | tee meson.log
    ./ninja -C build install | tee ninja.log
I forgot to rename them so the -Denable-autodiff parts were overwritten.

Thank you.
[ninja.log](https://github.com/su2code/SU2/files/6041732/ninja.log)
[meson.log](https://github.com/su2code/SU2/files/6041731/meson.log)

**Comment by MaxSagebaum** [comment]
@bakakouhai Thank you for testing this, I will merge the branch into the master now.

> Do I have to run git commands again to be back on default branch?
You just changed the branch of MeDiPack. SU2 is still on the default.

**Comment by MaxSagebaum** [comment]
I created a merge request for this https://github.com/su2code/SU2/pull/1210

**Comment by bakakouhai** [comment]
Thank you all.
I will test the installation with the test suite now.
Feel free to close the thread.

Cheers
