### ISSUE TITLE
Unsteady simulation: single restart file on cauchy convergence

### ISSUE THREAD

**Issue by ChristianBauerEng** [su2code/SU2#1211]
**Describe the bug**
When an unsteady simulation converges due to the CAUCHY criterion, only the restart file for the latest time-iteration is written, even if 2nd-order dual timestepping is selected for time-marching. However, when the simulation is stopped due to reaching the maximum number of time_iterations, two restart files are written.

**To Reproduce**
Run unsteady simulation with 2nd order euler implicit time-marching and define a cauchy criterion for transient convergence. Set output write frequency to high value so that no restart file is written before reaching time-convergence.

**Desktop (please complete the following information):**
 - OS: SLES15
 - C++ compiler and version: g++, 8.4.0
 - MPI implementation and version: IntelMPI
 - SU2 Version: 7.1.0

**Comment by pcarruscag** [comment]
@ScSteffen I think you worked on these criteria, can you lend a hand?

**Comment by ScSteffen** [comment]
Hi,
I'll have a look next week. :)

Cheers

**Comment by ScSteffen** [comment]
Hi @ChristianBauerEng, 
SU2 writes Files with the specified `OUTPUT_WRT_FREQ`. If 2nd order time stepping is chosen, SU2 will check if the _next_ iteration hits the write frequency, if yes, it will write the current to file. Similarly, if the next iteration is the final iteration, it writes the current one to file (and then the final iteration). 
However, one cannot know if the Cauchy criterion is fullfilled in the _next_ iteration. Thus you need to set  `OUTPUT_WRT_FREQ =1`, if you need the last and the second last restart file. 

@pcarruscag, we would need to implement something like a buffer to achieve this feature - or we write every iteration to file and delete the file of the last iteration if the Cauchy criterion is not fulfilled in the current. The only motivation to do this is a situation, where one runs out of disc space, if every iteration is written to file. 
What do you think?

**Comment by ChristianBauerAMDC** [comment]
Thank you for the clarification @ScSteffen.

Here's my suggestion: If the Cauchy criterion is satisfied, save the restart file and do one extra iteration, after which the second restart file is written. The one extra iteration will probably hurt a lot less than the excessive I/O required for saving all intermediate timesteps with` OUTPUT_WRT_FREQ=1`

Regards,
Christian

**Comment by pcarruscag** [comment]
I think what Christian thinks, just make the solver go for another spin, making sure that:
- This was not the last iteration already.
- The solver will stop afterwards even if the criteria stops being fulfilled.

The logic will be a little bit gnarly... The developer in me would just SU2_MPI::Error if the output frequency is not one :)
But that would not be very nice for the users.

**Comment by pcarruscag** [comment]
The cleanest implementation I can think off is using a counter that starts at 1 or 2 and goes to zero.
At zero the solver stops, if it decrements files are written out, if it is less than the initial value it must be decremented again.

**Comment by ScSteffen** [comment]
Hi, 
the corresponding PR is #1237. 
I implemented it,  as Christian suggested. 

Cheers
