### ISSUE TITLE
SU2 Ignores AVG_MASSFLOW and AVG_MACH output fields

### ISSUE THREAD

**Issue by GomerOfDoom** [su2code/SU2#1231]
**Describe the bug**
Title says it all. SU2 v. 7.1.1 gives me the following: "Info: Ignoring the following screen output fields: AVG_MASSFLOW, AVG_MACH"

**To Reproduce**
Use "MARKER_ANALYZE" and "SCREEN_OUTPUT = ( ... , AVG_MASSFLOW, AVG_MACH, ... ) in your configure file.

**Desktop (please complete the following information):**
 - OS: WSL Debian
 - C++ compiler and version: gcc 8.3
 - MPI implementation and version: OpenMPI 3.1.3
 - SU2 Version: 7.1.1

**Comment by pcarruscag** [comment]
Hi Paul,
The names of those and other options were changed in #1167 to (hopefully) make them compatible with the shape_optimization script. SURFACE_MASSFLOW and SURFACE_MACH now.
Do you still see the old names when in "dry run" mode?

**Comment by GomerOfDoom** [comment]
Hi @pcarruscag thanks for responding. I had not run dry run, since I didn't realize anything had changed.

Which brings up a topic that has probably been thrown around a lot... I think we need to work on our documentation of those output terms (relying on dry run is clumsy) and/or release notes and/or how the code is documented overall.

I'll close this particular issue.

**Comment by pcarruscag** [comment]
I agree... We do what we can https://github.com/su2code/SU2/releases/tag/v7.1.0 :shrug:
