### ISSUE TITLE
[Question] Script to output airfoil/wing shapes 

### ISSUE THREAD

**Issue by r-ashwin** [su2code/SU2#1234]
(new user here and apologies if this has been raised/addressed before).

I want to perturb the Hicks and Henne bump function design variables and write out the airfoil shape, __without running the primal or adjoint solvers__. So I want to implement `Y = f(X)` where `X` is the vector of Hicks and Henne bump function weights and `Y` is a vector of the actual `y` coordinate of the airfoil at each `x` corresponding to an element of `X`.

Is there a script that already exists to this effect? If so can you share that with me? If not do you have suggestions as to how to implement this? Thank you!

**Comment by pcarruscag** [comment]
Run SU2_DEF
