### ISSUE TITLE
Memory usage increases with higher output frequency in parallel

### ISSUE THREAD

**Issue by mschwalbs** [su2code/SU2#1261]
# Describe the bug

**Issue**
The memory usage of SU2_CFD continuously grows over time and is most noticeable when writing out files at high frequency. This caught my attention when cluster jobs with higher output frequency were consistently exceeding memory limits after a certain amount of time, leading to the job being killed. The same configuration with a lower output frequency can run significantly more iterations without exceeding limits.

I may be missing something, but it seems like there is a potential memory leak dependent on the output frequency, which I've documented in this report.

**Expected**
Memory usage remains steady over time and does not significantly change with output frequency.

**Local tests**
I was able to reproduce the issue locally on a workstation using the [Unsteady NACA0012 Tutorial case](https://github.com/su2code/Tutorials/tree/master/compressible_flow/Unsteady_NACA0012), whereby all 2200 time iterations are performed by setting `WINDOW_CAUCHY_CRIT = NO`. As you can see in the plot below, the memory usage increases over time and is more pronounced with a lower `OUTPUT_WRT_FREQ`:

![unsteady_naca0012_mem_usage_by_freq_20210413](https://user-images.githubusercontent.com/82448366/114564646-c9275380-9c70-11eb-8352-c5f1e4492c35.png)

Further editing the config file to run as a steady state simulation with `INNER_ITER= 20000` iterations produces similar results:

![steady_naca0012_memory_usage_by_output_freq_v711_20210413](https://user-images.githubusercontent.com/82448366/114564622-c4fb3600-9c70-11eb-873d-f9e0696c6484.png)

**Serial case**
This issue was not reproducible in serial and exhibits expected behavior:

![serial_steady_state_naca0012_memory_usage_20210413](https://user-images.githubusercontent.com/82448366/114564602-bf9deb80-9c70-11eb-89dd-88d1e240ce79.png)

# To Reproduce

Using [Unsteady NACA0012 Tutorial case](https://github.com/su2code/Tutorials/tree/master/compressible_flow/Unsteady_NACA0012) mesh, config, and restart files.

## Parallel Unsteady Freq=1
* Following changes to tutorial config file:
  * `WINDOW_CAUCHY_CRIT = NO`
* `parallel_computation.py -n 4 -f unsteady_naca0012.cfg`
* Take note of PIDs for memory measurement (see below).

## Parallel Unsteady Freq=100
* Following changes to tutorial config file:
  * `WINDOW_CAUCHY_CRIT = NO`
  * `OUTPUT_WRT_FREQ= 100`
* `parallel_computation.py -n 4 -f unsteady_naca0012.cfg`
* Take note of PIDs for memory measurement (see below).

## Parallel Steady Freq=1
* Following changes to tutorial config file:
  * `WINDOW_CAUCHY_CRIT = NO`
  * `TIME_DOMAIN = NO` and comment out `TIME_MARCHING`, `TIME_STEP`, `TIME_ITER`
  * `INNER_ITER= 20000`
  * `OUTPUT_WRT_FREQ= 1`
* `mv restart_flow_00499.dat restart_flow.dat`
* `parallel_computation.py -n 4 -f unsteady_naca0012.cfg`
* Take note of PIDs for memory measurement (see below).

## Parallel Steady Freq=100
* Following changes to tutorial config file:
  * `WINDOW_CAUCHY_CRIT = NO`
  * `TIME_DOMAIN = NO` and comment out `TIME_MARCHING`, `TIME_STEP`, `TIME_ITER`
  * `INNER_ITER= 20000`
  * `OUTPUT_WRT_FREQ= 100`
* `mv restart_flow_00499.dat restart_flow.dat`
* `parallel_computation.py -n 4 -f unsteady_naca0012.cfg`
* Take note of PIDs for memory measurement (see below).
 
## Serial Steady Freq=1
* Following changes to tutorial config file:
  * `WINDOW_CAUCHY_CRIT = NO`
  * `TIME_DOMAIN = NO` and comment out `TIME_MARCHING`, `TIME_STEP`, `TIME_ITER`
  * `INNER_ITER= 20000`
  * `OUTPUT_WRT_FREQ= 1`
* `mv restart_flow_00499.dat restart_flow.dat`
* `SU2_CFD unsteady_naca0012.cfg`
* Take note of PIDs for memory measurement (see below).

## Memory measurement
I measured the memory usage with a minutely cronjob of the following snippet:

```
#!/bin/bash

dir=/path/to/testdir

#list of PIDs:
pid_list='XXXX XXXX'

cd $dir
for PID in $pid_list
do
	now=$(date +"%Y%m%d%H%M")
	current_kb=$(pmap $PID| tail -n 1 | awk '{print $3}') # current memory
	echo $now,$current_kb >> memory_history_$PID.csv
done
```

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.2
 - C++ compiler and version: gcc 7.5.0
 - MPI implementation and version: OpenMPI 4.1.0
 - SU2 Version: v7.1.1

**Comment by pcarruscag** [comment]
Valgrind does not detect any leaks.
What is probably happening is heap fragmentation, some large temporary arrays are used during parallel output, they are free'd correctly but the OS is not obligated to re-use that space the next time something is allocated.

If you want to experiment with modifying some code (to make those arrays persistent) we can show you what to do.
(developers meetings every Wednesday at 4pm CET https://meet.jit.si/SU2_DevMeeting)

Cheers

**Comment by mschwalbs** [comment]
Hi Pedro,

Thanks for the hint!

If I understood it correctly, it's possible that after the large temporary array for parallel output is freed, some smaller blocks are eventually allocated in that free space, which means a new block of memory needs to be allocated when the large temporary array is created again. And if this keeps happening over a long enough period of time, the memory usage increases?

**Comment by pcarruscag** [comment]
That is how I understand it, but memory allocation is a complex beast.
For example I expect the policy for small and large sizes to be different, maybe the interaction between similar sizes (e.g. from different MPI processes) is more important, because memory is a global resource and the different processes do not request it in a predictable order.
