### ISSUE TITLE
OpenMP version of the adjoint solver does not compile with the Intel compiler

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#1273]
**Describe the bug**
When I try to create the OpenMP version of the adjoint solver with the Intel compiler, I get compiler error in opdi. Here are a couple of examples, which are all of the same error type

../SU2/externals/opdi/include/opdi/backend/macro/dataTools.hpp(39): error: threadprivate variable should not be incomplete or reference type
        #pragma omp threadprivate(parallelData)

../SU2/externals/opdi/include/opdi/backend/macro/implicitBarrierTools.hpp(41): error: threadprivate variable should not be incomplete or reference type
        #pragma omp threadprivate(implicitBarrierStack)

../SU2/externals/opdi/include/opdi/logic/omp/adjointAccessControl.hpp(47): error: threadprivate variable should not be incomplete or reference type
        #pragma omp threadprivate(currentAdjointAccess)

**To Reproduce**
Use the following build options (I don't think the mkl option is needed, but that is what I used)

export CXX=mpiicpc
export CC=mpiicc
export CXXFLAGS="-O2"
export CFLAGS="-O2"

./meson.py ../Build_MKL --prefix=/home/whatever -Denable-mkl=true -Dcustom-mpi=true -Dwith-omp=true -Denable-autodiff=true -Denable-directdiff=true
./ninja -C ../Build_MKL install

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - C++ compiler and version: Intel 19.1.0.166 20191121
 - MPI implementation and version: Intel MPI
 - SU2 Version: Latest develop version

**Comment by jblueh** [comment]
Thank you for reporting this. This seems to be an OpDiLib issue, I'll look into it.

**Comment by jblueh** [comment]
I can confirm this with Intel 19.1.3.304 independently of SU2. OpDiLib does not support the Intel compiler at the moment.

**Comment by vdweide** [comment]
Thanks @jblueh. So should we close this issue for now then? BTW, do you plan to support the Intel compiler in the future?

**Comment by vdweide** [comment]
Alright let's close this one. We can test it again when OpDiLib supports the Intel compiler.

**Comment by pcarruscag** [comment]
We talked about this yesterday, and we'll put some kind of check in meson.
I'll reopen this to remind me.
