### ISSUE TITLE
Unsteady FSI with SU2 Compressible Solver and SU2 FEM Solver Diverges when Restarted (v7.1.1)

### ISSUE THREAD

**Issue by sangeetsourav** [su2code/SU2#1287]
1. Initially I was trying to restart the unsteady FSI from the steady flow solution over the initially undeformed structure. I noticed that the case diverged when I tried to use 2nd order dual time-stepping and the case worked when I used 1st order dual time-stepping.
2. Then I encountered a new problem when I tried to restart the case from the FSI solutions after 1900 time steps and it diverged. I tried the restart files of time iteration 1890 and it still diverged without iterations. 
3. Surprisingly, when I tried to restart using the restart file from time iteration 10, iterations started without an immediate divergence.

Please advise on what could be going wrong.
Thank You
Sangeet

I have attached the case folder with all required restart files.
[testing.zip](https://github.com/su2code/SU2/files/6464073/testing.zip)

**Comment by sangeetsourav** [comment]
I was not able to restart at 1500 or 1000 time iteration. I was able to restart from time iteration 500. Is the problem that SU2 can't be restarted when the mesh is deformed beyond a certain limit?

**Comment by pcarruscag** [comment]
I'm looking into this. It looks like it might be a bug, but 1st order dual-time-stepping appears to restart correctly.
Please give it a try while we look into this.

**Comment by sangeetsourav** [comment]
Hello
Oh! Is the restart working for you from the 1900 time step restart files?

**Comment by pcarruscag** [comment]
I'm not using your case. You are doing FSI at Mach 3, I do not like punishment that much.

**Comment by sangeetsourav** [comment]
Do you have any tips for what could get the restart working?

And I wanted to ask if it's possible to use subcycling for the fluid?

**Comment by pcarruscag** [comment]
Does 1st order work or not?
What is subcycling?

**Comment by sangeetsourav** [comment]
Yes as I mentioned in my initial post, first order works fine while restarting from the steady flow solution but when I want to restart FSI from a later time iteration, SU2 diverges.

By subcycling, I meant that I would like to use different time step sizes for structure and fluid. For example, if I specify an FSI timestep of 1e-02s then I would like to use smaller timesteps on the fluid side (like 1e-05s) and maybe keep the structure time step to 1e-03s, and when both fluid and solid reach the same time, the deformation and load convergence be monitored and if they have not converged another outer iteration would begin.

Does that make sense?

**Comment by pcarruscag** [comment]
Ah got it, I have no explanation for that. But the fact that you need CFL of 1 for the fluid tells me the flow conditions are challenging.
Also Poisson ratio of 0.37 on the structural side makes it harder to converge, you can try compiling SU2 with PaStiX which guarantees you can solve the structural problem (instructions are in TestCases/pastix_support/).

It is not possible to do that in SU2, however, to some extent, dual-time methods are already a form of subcycling, in each inner iteration you are advancing in pseudo-time.

**Comment by sangeetsourav** [comment]
Thank you for the clarification on subcycling. I will try compiling SU2 with PasTiX and will post if I see any improvement in my case.

**Comment by pcarruscag** [comment]
If you add GRID_VELOCITY to VOLUME_OUTPUT the 2nd order restart will work properly in 7.1.1, this will not be needed in future versions.
Restarting the solver does not recover precisely the same values as letting it continue the simulation, I do not have an explanation for this (or time to look for it unfortunately) but it may be why you have crashes with some iterations but not others (combined with the case being sensitive).

**Comment by sangeetsourav** [comment]
Do you mean I need to add this in the flow config file? I tried that, it didn't work.

**Comment by pcarruscag** [comment]
Yes you need to have it in the fluid config file that produces the files you will use to restart. The files you have without grid velocities will not work... but the new ones will.

**Comment by sangeetsourav** [comment]
I added it to the volume output by
```
VOLUME_OUTPUT= (GRID_VELOCITY, COORDINATES, SOLUTION, PRIMITIVE,VORTEX_IDENTIFICATION)
```
I get the following output
```
  Info: Ignoring the following volume output fields/groups:
  GRID_VELOCITY
Volume output fields: COORDINATES, SOLUTION, PRIMITIVE, VORTEX_IDENTIFICATION
```
I ignored this and copied the restart files to my FSI case and the case still diverged.

**Comment by pcarruscag** [comment]
A steady rigid case does not have grid velocities.
I guess you could use those results for a 1st order simulation, which could output grid velocities, and then use that to initialize 2nd order.

**Comment by sangeetsourav** [comment]
I tried your suggestion. I ran the FSI case in 1st order for one time-step and then made two copies of the restart file. I then tried 2nd order restart from this and the case still diverged. The FSI flow config file had the following VOLUME_OUTPUT
```
VOLUME_OUTPUT= (GRID_VELOCITY, COORDINATES, SOLUTION, PRIMITIVE,VORTEX_IDENTIFICATION)
```
I also tried to manually the add columns "Grid_Velocity_x" and "Grid_Velocity_y" to the ASCII restart file of the rigid case. The case still diverged.

**Comment by sangeetsourav** [comment]
Is there something I am missing?

**Comment by pcarruscag** [comment]
You can try this branch "hybrid_parallel_ad3"
It should start from steady state without extra steps, I also got the restart to be smoother, i.e. the first restarted iteration converges to pretty much the same values that would be obtained by not stopping the simulation (even with large displacements).
However it is still not perfect, during the first outer iteration the residuals go up a bit, which at Mach 3 may cause issues... I don't think I can get it better though, so try to setup the case in the most robust way possible.

**Comment by sangeetsourav** [comment]
I tested the branch and second-order dual time stepping restart works without any problems. I will post if the restarts after a few thousand time steps also work.

**Comment by sangeetsourav** [comment]
Restarting after 1000 time steps also works. With this, both of the bugs have been fixed.

Thank you

**Comment by pcarruscag** [comment]
Good to know, thank you for testing it.
I'll close this issue once the PR is merged.
