### ISSUE TITLE
Python scripts (parallel_computation.py, etc.) fail if there are multiple FFD control points defined

### ISSUE THREAD

**Issue by Daamanbarara** [su2code/SU2#1289]
Hello,

I'm posting this issue based on the discussion on CFD Online [here](https://www.cfd-online.com/Forums/su2/235889-error-executing-deformation-multiple-ffd-control-point.html#post803932). The original query goes like this- 

I'm trying to perform the mesh deformation of Onera M6 mesh with SU2_DEF using multiple FFD control points. The same mesh has been used in the current case as used in the SU2's tutorial of [Onera M6](https://su2code.github.io/tutorials/Inviscid_3D_Constrained_ONERAM6/). The configuration file used in the simulation is attached below- 
[Adjoint_ONERAM6.txt](https://github.com/su2code/SU2/files/6489000/Adjoint_ONERAM6.txt)

On executing SU2_DEF, .su2 format of mesh is generated which is used as an input for the simulation. But on executing discrete_adjoint.py, I get the following error-

Error in "void CConfig::SetConfig_Parsing(std::istream&)":
-------------------------------------------------------------------------
DV_VALUE: DV_VALUE does not contain enough entries to match DV_KIND or DV_PARAM.

------------------------------ Error Exit -------------------------------

From the looks of the error and my configuration file, I do have an equal number of arguments in the DV_VALUE as well as DV_KIND or DV_PARAM. Thanks!  

Desktop:
 - OS: Linux (CentOS)
 - C++ compiler and version: -
 - MPI implementation and version: OpenMPI 1.8.8
 - SU2 Version: v7.1.1

**Comment by pcarruscag** [comment]
Just to save others the trouble, the python scripts work by automatically creating temporary configs for the different steps, e.g. running SU2_CFD, SU2_CFD_AD, etc. It seems that if there are multiple control points (DV_PARAM) in the user config, the scripts break because they only write one DV_VALUE (and DV_KIND I think).
