### ISSUE TITLE
compilation with GCC v11.1 fails

### ISSUE THREAD

**Issue by maxaehle** [su2code/SU2#1293]
**Describe the bug**
When compiling the master branch or v7.1.1 of SU2, as described in the [Quick compilation guide](https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/#quick-compilation-guide) with gcc version 11.1.0, the ninja command fails, saying that `'numeric_limits' is not a member of 'std'`.

**Likely reason**
There were [header dependency changes in GCC 11](https://www.gnu.org/software/gcc/gcc-11/porting_to.html#header-dep-changes). Probably because of this, the header `<limits>` is not (recursively) `#include`d from the file

    Common/include/geometry/primal_grid/CPrimalGrid.hpp

any more. Thus `std::numeric_limits` has not been declared when it is used in line 243.

**Solution**
`#include <limits>` in `CPrimalGrid.hpp`

**Comment by pcarruscag** [comment]
Can you add this to your current PR?

**Comment by maxaehle** [comment]
ok, fixed in #1286 (commit aaf5b8ab)
