### ISSUE TITLE
Simulating Gusts in 3D

### ISSUE THREAD

**Issue by mandralis** [su2code/SU2#1319]
Hi all, 

I recently discovered the Gust simulation capabilities of SU2 for two-dimensional Euler flows. 

I am trying to implement the additional terms necessary for extending the method to 3D Navier-Stokes flows.

I am running into trouble when trying to implement the changes necessary to achieve this.

For now, I have began working on the two functions responsible for the gust simulations:

1. SU2/SU2_CFD/src/iteration_structure.cpp::CFluidIteration::SetWind_GustField
2. SU2/SU2_CFD/src/numerics/flow/flow_sources.cpp::CSourceWindGust::ComputeResidual

From what I understand the extension to 3D should simply consist in modifying the function  `SetWind_GustField` to impose a 3D grid-velocity instead of a 2D grid velocity, and adding the appropriate source terms in the function `CSourceWindGust` (these can even be set to zero, just to debug the code). 

However, when I try to implement these changes, I get a segmentation fault that I cannot identify. 

Does someone have an idea on how to implement this feature successfully ?  

PS: I have attached the modifications I made to the two functions mentioned above here:
[SetWind_GustField.txt](https://github.com/su2code/SU2/files/6740388/SetWind_GustField.txt)
[ComputeResidual.txt](https://github.com/su2code/SU2/files/6740389/ComputeResidual.txt)

**Comment by pcarruscag** [comment]
Hello,
I think @bigfooted tried to implement the 3D version, this is in the develop branch now.
We have developer meetings every Wednesday at 3pm UK https://meet.jit.si/SU2_DevMeeting to discuss this type of issue.
Join if you can.

**Comment by mandralis** [comment]
Hi, 
Thanks for your response ! I will join the developer meeting in one hour. See you then.
Best,
Ioannis

**Comment by bigfooted** [comment]
Maybe you can create a feature branch with this added feature so we can reproduce the crash and (help you) debug it.

**Comment by pcarruscag** [comment]
Were you able to implement the 3D gusts @mandralis? I recall some issue you mentioned with a segfault.
