### ISSUE TITLE
Make SU2 gcc11 ready

### ISSUE THREAD

**Issue by DavidAnderegg** [su2code/SU2#1321]
**Describe the bug**
When building with gcc11, some header files do not import "limits". Due to a change in gcc, this is now needed:
https://gcc.gnu.org/gcc-11/porting_to.html

**To Reproduce**
Build su2 with gcc11

**Comment by pcarruscag** [comment]
Can you try with the develop branch please? I think we fixed this already.

**Comment by DavidAnderegg** [comment]
You are right. This seams to work.
