### ISSUE TITLE
No success in building SU2 for windows 10

### ISSUE THREAD

**Issue by ndkazu** [su2code/SU2#1322]
Hello, 
I need to build SU2 on windows for the adjoint capabilities.
I have the exact same problem as the one described in this issue: https://github.com/su2code/SU2/issues/1093
I followed build instructions for windows, used python 3.7 instead of 3.9 to be sure,
I generated a "msmpi.a" file by following the instruction given in the link: https://abhilashreddy.com/writing/3/mpi_instructions.html
added the file to my path, and even manually added it in the \Microsoft SDKs\\MPI\\Lib\\x64\\ folder, nothing is changed.
As you can see in the attached textfile, mpiexec seems to work fine. 
[mpi_lib_problem.txt](https://github.com/su2code/SU2/files/6782110/mpi_lib_problem.txt)

Thanks in advance for your help.
Kazunobu

_Originally posted by @ndkazu in https://github.com/su2code/SU2/issues/1093#issuecomment-876174111_

**Comment by pcarruscag** [comment]
Try giving -Dcustom-mpi=true to meson.py
