### ISSUE TITLE
"Per surface" outputs do not work

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1336]
The "per surface" problem starts in `COutput::CheckHistoryOutput` where the table header is not given the right number of columns. The function does not add the "per surface names" because we are using the same identifier for normal outputs and "per surface" outputs.
Moreover, the "per surface" implementation is only considering the first marker name and value for printing.
However, there is one value added per "marker analyse".
Let's fix this in a different PR.

_Originally posted by @pcarruscag in https://github.com/su2code/SU2/issues/1226#issuecomment-889067006_

**Comment by TobiKattmann** [comment]
I just noticed that this also means that e.g. SURFACE_STATIC PRESSURE in screen outputs cannot be used for regression tests as the python script needs a delimiter in between values which is not the case with that doubled output.
