### ISSUE TITLE
a possible bug for loading grid points for a zone

### ISSUE THREAD

**Issue by dingxiwang** [su2code/SU2#1345]
**Describe the bug**
When loading grid points for the ith zone, it seems that grid points for all zones after the ith zone will be loaded as well.
This grid point loading is implemented in the function of void CSU2ASCIIMeshReaderFVM::ReadPointCoordinates() 

The code snippet below is doing the function. I think there should be a break for the while loop once the grid points for the required zone are loaded.

  /*--- Open the mesh file and jump to our zone. ---*/

  mesh_file.open(meshFilename, ios::in);
  FastForwardToMyZone();

  /*--- Read the point coordinates into our data structure. ---*/

  string text_line;
  string::size_type position;
  while (getline (mesh_file, text_line)) {

    position = text_line.find ("NPOIN=",0);
    if (position != string::npos) {

 - SU2 Version:7.1.1

It should be noted that this bug is not expected to cause wrong solutions, but lead to unnecessary extra time cost and memory consumption probably.

**Comment by pcarruscag** [comment]
I think you are right.
You joined the dev meeting today as we were ending right? Maybe the European summertime misled you.
Can you open a pull request for this? There are other parts of that function that are not very efficient.

**Comment by dingxiwang** [comment]
Aha, yes, Nitish from Delft University of Technology sent me the link and I opened it at that time.
I started looking into SU2 very recently and may join the development meeting next time.
