### ISSUE TITLE
SA and SST turbulence model consistent implementation with literature, and handling more options

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#1364]
_Originally posted by @suargi in https://github.com/su2code/SU2/issues/1066#issuecomment-906376697_

Currently each variation/correction model has its unique name identification in SU2. In order to simultaneously combine multiple correction models to a given turbulence model I suggest the following:
- The config file option KIND_TURB_MODEL should specify only which turbulence model to use, i.e. SA or SST.
- Introduce an additional config file field TURB_MODEL_CORRECTIONS to indicate all variations/corrections to be considered. 

Here an example,
% Specify turbulent model (NONE, SA, SST)
KIND_TURB_MODEL= SA
% Turbulence model corrections (NONE, SA-EDW, SA-NOFT2, SA-COMP, SA-NEG, SA-QCR2000, SST-SUST)
TURB_MODEL_CORRECTIONS= SA-EDW, SA-NEG

What do you think?

**Comment by suargi** [comment]
As discussed I will follow your suggestions and implement the new procedure of specifying the turbulence models guaranteeing backwards compatibility of the config file.              
                                                                                                                                                                                    
Besides, the baseline or standalone Spalart-Allmaras turbulence model currently implemented in SU2 is actually its ft2=0 variation, a.k.a noft2. To keep compatibility with previous SU2 versions results it is preferable to keep the current nomenclature, i.e., SA will refer to the SA-noft2 variant. In that sense, to introduce the actual baseline version an additional variant should be implemented, yesft2 :), corresponding to the standard model found in the literature. I will make sure to properly document this matter in the SU2 website.

**Comment by erangit** [comment]
The ft2 term was a "not a very successful" attempt to allow computation of transitional flow or relaminarization, where a region exists without turbulent diffusion. During the time that passed since the nineties, it was commonly considered ineffective. I think Philipe also agrees with that. That way, though historically it is not correct, I think the basic SA model should be with ft2=0
I appreciate your effort. I put some order and logic in a combination that creates a lot of misunderstanding by many
Best,
Eran

**Comment by HexFluid** [comment]
@pcarruscag

Hi Pedro, 
While I am trying to figure out the implementation of SA model in SU2, I found in Ver 7.2.1 /SU2/SU2_CFD/src/numerics/turbulent/turb_sources.cpp, line 103:

  if (rotating_frame) { Omega += 2.0*min(0.0, StrainMag_i-Omega); }

This is effectively the Bradshaw's correction (i.e., SA-R from NASA TMR). Does that mean the default flavor of SA is actually SA-R-noft2?

**Comment by sun5k** [comment]
Thank you for the escort 👍  


It looks like the SU2 code considers both practical and academic points. The first options give considerable confusion as, who needs just RANS models(SA or SST). Additionally, for expert users who need a specific model, either option is not an issue.
So, in my opinion, the latter option is suitable for many users.
