### ISSUE TITLE
Error while cloning SU2 repository on Windows

### ISSUE THREAD

**Issue by dbrezgin** [su2code/SU2#1368]
Hello to everyone. 

I found out the error while cloning the SU2 repository on Windows. The problem is related to **OpDiLib** module, in which the 'aux' directory exists. The '_aux_' is a reserved name in Windows and cannot be used in file or catalog names. 
I realize that **OpDiLib** is an external module and removing/renaming '_aux_' directory (which actually prevents successful cloning on Windows) is not an option but there are probably other ways to fix it.

Best wishes

 - OS: [Windows Server 2016]
 - C++ compiler and version: [Mingw-w64 8.1.0]
 - MPI implementation and version: [Microsoft MPI]
 - SU2 Version: [7.2.0]

**Comment by jblueh** [comment]
Thanks for noting. #1369 should fix it.

**Comment by dbrezgin** [comment]
Thanks a lot. It's working like a charm now!!!
