### ISSUE TITLE
Bug in config.py prevents asserts from providing correct error message

### ISSUE THREAD

**Issue by spendres** [su2code/SU2#141]
in the file /SU2_PY/SU2/io/config.py ...
The block that reads:

# read config if it exists
        if filename:
            try:
                self.read(filename)
            except:
                raise IOError , 'Could not find config file: %s' % filename

mask all assertion errors used to check the integrity of the config options as an 'IOError, Could not find the config file: known_and_present_config_file.cfg'

the block should read:

# read config if it exists
        if filename:
            try:
                self.read(filename)
            except IOError:
                 print 'IOError , 'Could not find config file: %s' % filename
            except:
                 print "Unexpected error:", sys.exc_info()[0]
                 raise

or just trap the IOError and let exceptions triggered by failed assertions propagate up the call stack

**Comment by aerialhedgehog** [comment]
great catch! could you submit a pull request for this?

**Comment by spendres** [comment]
just did...

**Comment by juanjosealonso** [comment]
Thanks Steve!

Juan
