### ISSUE TITLE
Segmentation Fault when mesh is too fine near wall (TURBOMACHINERY)

### ISSUE THREAD

**Issue by AmauryBilocq** [su2code/SU2#1429]
**Describe the bug**
Hello everyone, 

I'm trying to study the secondary flows around a compressor stator blade. To do so, I need to simulate the 3d blade, the hub and the shroud (as shown in the picture below).
![blade](https://user-images.githubusercontent.com/24920252/140755903-23c7ad28-3b91-4476-9eae-8907b20a8bf7.png)

To simplify a bit the problem, the geometry is assumed to be constant along the span. Therefore, a hybrid mesh is used on a 2d surface and is extruded along the span. The following pictures represented a global view of the test case, the hybrid mesh and the mesh distribution for the extrusion:

![global](https://user-images.githubusercontent.com/24920252/140758176-d1e5da98-5e54-457e-9a80-92878a1e88ba.png)
![2dmesh](https://user-images.githubusercontent.com/24920252/140756176-4560688b-1c6c-42e7-b404-95589764acad.png)

![extrusion](https://user-images.githubusercontent.com/24920252/140756190-d5a423b7-c172-4fff-9fe3-53ed0364756e.png)

As we can see, the mesh is refined near the two walls (the hub/shroud) to get a y+ of 1 and here starts my issue. 

While I can retrieve a correct y+ near the blade, I have trouble to get a y+ lower than 65 near the walls. At y+ = 65, SU2 runs and converges to some results. For y+ < 65, SU2 raises a segmentation fault at this location: 
![segfault](https://user-images.githubusercontent.com/24920252/140756620-db3ed08f-05cd-4811-b037-642a221ea501.png)
 Here are the results of the gdb analysis. It seems that the seg faut comes from the Giles BC part of the initialisation of the turbo data containers. Especially those lines (CEulerSolver.cpp line 435-436)

`CkInflow[iMarker].resize(nSpanWiseSections,2*geometry->GetnFreqSpanMax(INFLOW)+1) = complex<su2double>(0.0,0.0);`

`CkOutflow1[iMarker].resize(nSpanWiseSections,2*geometry->GetnFreqSpanMax(OUTFLOW)+1) = complex<su2double>(0.0,0.0);`

 but I don't understand why.

![issue](https://user-images.githubusercontent.com/24920252/140783485-0d856d2a-7353-468f-aeab-c78b742d8582.png)

The first thing I checked was to reduce the number of elements in my domain but the problem remains the same (so no memory issue).
Then I checked if it was not an issue from 

- : a too small size of my first element. I scaled my domain by a factor of 1000 and the issue is the same (can't go below y+ = 65);
- : trouble with the expansion ratio of the boundary layer;
- :the number of procs (tried with 2 - 6 -15 and the issue is the same).

I don't have idea anymore and that is why I'm coming to you. 

*Please provide a config file and mesh for a minimal example that recreates the problem.*

Here is a link to the .geo file (line 28 is to get a y+ of 1. You can uncomment line 29 for y+=65), the .cfg and two .su2 meshes to directly launch the case. 

https://mseduculiegebe-my.sharepoint.com/:u:/g/personal/amaury_bilocq_uliege_be/EaUIIj1J_-BBktcLu8F9kosBsRjtOduWrrtENbW_bnx1ow?e=F47adW

Thank you already for your help!

Amaury

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu 21.04
 - C++ compiler and version: g++ (GCC) 10.3.0
 - MPI implementation and version: Intel(R) MPI Library for Linux* OS, Version 2021.4 Build 20210831
 - SU2 Version:7.2.1

**Comment by pcarruscag** [comment]
@matteopini @NAnand-TUD @EvertBunschoten any chance something similar has been fixed in one of the turbomachinery branches?

**Comment by pcarruscag** [comment]
Thank you @AmauryBilocq for having thoroughly documented the issue, trying to diagnose it, and providing the info needed to reproduce it.
I am truly sorry that we don't have enough active (or active-enough) turbomachinery developers to look into this...

**Comment by NAnand-TUD** [comment]
@AmauryBilocq Thanks for your post. Can you please check that you are actually not running out of memory, as that can also raise such errors? Second, if Giles BC is the issue I think you will still be able to run the case with Riemann which is a bit simpler than Giles. Can you also test that?

**Comment by NAnand-TUD** [comment]
@AmauryBilocq Initial tests do show that Giles BC is giving errors however, the Riemann is working just fine. Unfortunately, I do not have access to my workstation these days and cannot deep-dive into the problem. Possibly, next week I will be able to give you a more detailed view of the problem. @pcarruscag If you are able to find some leads in the meantime do let me know.

Thanks !
