### ISSUE TITLE
Onera M6 RANS Test case diverges when NUM_METHOD_GRAD=WEIGHTED_LEAST_SQUARES

### ISSUE THREAD

**Issue by SumanVajjala** [su2code/SU2#143]
SU2 v 3.2.4

**Comment by economon** [comment]
Hi, 

This question is more related to numerical method selection, meshes, and usage of the code. Can you please post this question in the CFD online forum and we'll tackle it there? http://www.cfd-online.com/Forums/su2/

Thanks,
Tom
