### ISSUE TITLE
Convergence issue with Euler_Explicit time stepping for inviscid flow over cylinder case.!

### ISSUE THREAD

**Issue by svkindia** [su2code/SU2#145]
I tried inviscid flow over cylinder case and it is not converging with Euler_Explicit time stepping. I tried with low CFL no also. Still the problem exists.

**Comment by hlkline** [comment]
implicit and explicit methods have very different stability characteristics (implicit is more stable). 
Please post any follow-up questions to the forum at http://www.cfd-online.com/Forums/su2/ .
