### ISSUE TITLE
SU2 cannot create restart file on Windows

### ISSUE THREAD

**Issue by HarshulJolly** [su2code/SU2#1537]
Hello!

I am new to SU2 and I'm having trouble running the incompressible turbulent RANS NACA0012 test case on SU2 in Windows.
I have downloaded the binary excecutables SU2 v7.3.0 and my simulation seems to stop after 250 iterations with the error:

_Error in"bool CFileWriter::OpenMPIFile(std::__cxx11::string)":
Unable to open file restart_flow.dat_

At first I thought that perhaps my MPI I/O was causing this error to occur, however this error also appears when I run the case in serial.
I have had a look at the SU2 documentation and on this forum and so far I haven't been able to find a similar error happening for anyone else.

I am not sure how to go about fixing this issue so any help is appreciated.

I have attatched the configuration file and screenshots from Windows Powershell to this post and the mesh I am using is  n0012_897-257.su2.
Let me know if I need to clarify any further details.

Thank you!

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043
 - C++ compiler and version: g++ MinGW-W64 8.1.0
 - MPI implementation and version: Microsoft MPI v10.1.2 
 - SU2 Version: v 7.3.0 'Blackbird'
[turb_NACA0012_sa.txt](https://github.com/su2code/SU2/files/8005251/turb_NACA0012_sa.txt)
![SU2_error_1](https://user-images.githubusercontent.com/99037921/152580001-7c7670fd-b5ca-4667-a4f5-16350cb67378.png)
![SU2_error_2](https://user-images.githubusercontent.com/99037921/152580035-fe0d1954-2044-4767-a4f8-47effb1d1082.png)
![SU2_error_3](https://user-images.githubusercontent.com/99037921/152580030-60da648d-4d96-451c-8449-e17b4a04e01d.png)
![SU2_error_4](https://user-images.githubusercontent.com/99037921/152580021-abb070b1-9d94-4649-a265-c9ad35a678d3.png)

**Comment by pcarruscag** [comment]
What are the contents of the directory where you are running? Is there something called "restart_flow.dat" or "restart_flow.dat.lock" in there?

Try:
OUTPUT_FILES= PARAVIEW
OUTPUT_FILES= RESTART_ASCII, PARAVIEW_ASCII

**Comment by HarshulJolly** [comment]
Hello!
Thanks for your help.

Writing the line:
OUTPUT_FILES= RESTART_ASCII

enabled the simulation to run past 250 iterations and after 4500 or so iterations, I was able to yield the correct values for Cl and Cd.
However, an issue still persists. The file restart_flow.csv doesn't seem to appear in the directory. I have amended the config file to have the lines:

OUTPUT_WRT_FREQ = 10
OUTPUT_FILES=(RESTART_ASCII)

at the very end. However, after 10 iterations, a csv file isn't created.
I am not sure how to go about fixing this issue so any help is appreciated.
I have attatched the amended configuration file and a screenshot from Windows Powershell.
[turb_NACA0012_sa.txt](https://github.com/su2code/SU2/files/8008885/turb_NACA0012_sa.txt)

Thank you
![SU2_](https://user-images.githubusercontent.com/99037921/152658358-bdf3c06c-d3a6-4343-aa14-d5d7c7374cb9.png)
!

**Comment by pcarruscag** [comment]
You are running inside Program Files, it is very likely that Windows is not giving SU2 permissions to create files there.
Try running somewhere in your documents.

**Comment by pcarruscag** [comment]
Or desktop, etc.

**Comment by HarshulJolly** [comment]
Hello!
Apologies for my late response.

I ran the program in my documents and that fixed the issue- 'restart_flow.csv' and 'flow.dat' for Tecplot were able to be created by SU2.
Thank you very much for your help!
