### ISSUE TITLE
Alternative time-averaging for rectangular window to avoid performance degradation

### ISSUE THREAD

**Issue by ChristianBauerEng** [su2code/SU2#1545]
**Is your feature request related to a problem? Please describe.**
In my transient cases I would like to average the flow-field over many time-iterations, in order to filter out highly dynamic effects. For me the volumentric time-averages and rms values have significant value. However, I have observed, that once averaging is enabled, the solver performance gradually decreases up to a point, where time-iterations are orders of magnitudes slower than without averaging. This does not seem to be a bug but rather inherent to the way averaging is implemented.

I suspect, that the averaging occurs over all timesteps and thus a complete history of all the values is required. This may gradually increase memory consumption and effort for calculating averages. I suspect this to happen around here, but I may be wrong.

https://github.com/su2code/SU2/blob/72b2fa977b64b9683a388920f05298a40d39e5c5/SU2_CFD/src/output/tools/CWindowingTools.cpp#L69-L76

I assume, that this may be a necessity for the higher-order windows, but seems to be overkill for a rectangular window, where the new time-average can be computed from the previous time-average, the number of iterations and the new values. Nevertheless, also the rectangular window seems to save the full value history:

https://github.com/su2code/SU2/blob/72b2fa977b64b9683a388920f05298a40d39e5c5/SU2_CFD/src/output/tools/CWindowingTools.cpp#L94-L100

**Describe the solution you'd like**
Being able to calculate (at least) non-windowed time-averages without a gradual drop in performance would be a real asset for me. This may be possible by choosing a different averaging method. If this cannot be done due to the data structure used, a dry-run message warning the user about this may be helpful. 

**Describe alternatives you've considered**
The same effect can be achieved by running simulations without time-averaging but with regular volumetric outputs and calculating time-averages as a post-processing step. However, the associated data overhead is considerable.

**Additional context**
I performed my tests so far with the RANS solver, employing SST turbulence and SLAU2 scheme. Time-averaging started at around time-iteration 160k and cintinous for another 200k iterations.

**Comment by ChristianBauerEng** [comment]
Unfortunately, I'm still a bit unsure of the math behind the averaging.

I assumed, that the average of a new iteration calculates as follows:

avg(it) = (cumulativeWeight(it-1, it+1) * avg(it-1) + Weight(it, it+1)*Value(it)) / (cumulativeWeight(it-1,it+1)+Weight(it,it+1))

Translated into words:
At iteration `it` we define a window of width `it+1`.
The previous average is weighted with the integral of the window from 0 to it-1. The new value arriving at iteration it is weighted with the actual window weight. The weighted sum is then divided by the sum of the weights.

For a rectangular window this seems to converge towards the right value, but for the hanning window it does not.
Probably the math behind it is simply wrong.

Any idea what the proper weighting should look like?

**Comment by pcarruscag** [comment]
When the window size changes the weights for each sample change, you do need the history for nontrivial windows and to recompute the weights.
But it is possible to cache the sum over n-1 samples until the number of samples changes again.

**Comment by pcarruscag** [comment]
It makes sense to cache because addValue does not always add a new value, only when the time iteration changes, after the first inner iteration addValue only modifies the last entry of the history.
The changes you mention sound ok, keep the switches, virtual would make everything slower and more complicated.

**Comment by ChristianBauerEng** [comment]
Added in #1548
