### ISSUE TITLE
Allow specification of temperature profiles (x,y,z) at isothermal walls

### ISSUE THREAD

**Issue by ChristianBauerEng** [su2code/SU2#1553]
**Is your feature request related to a problem? Please describe.**
Under high aerothermal loads heat fluxes over walls are an important design aspect of many components. In my specific case a wall temperature distribution is known from experiments. I would like to apply this spacial temperature distribution as boundary condition to one or more isothermal walls. In my case the heat flux is then used for validation purposes.

**Describe the solution you'd like**
I would like to specify the temperature of an isothermal wall with respect to the x/y/z coordinate. I believe something similar is already possible with the structural load boundaries:
`MARKER_DISPLACEMENT = (surface, multiplier, magnitude [m], x component, y component, z component)`

For temperature this could possibly look like this:
`MARKER_ISOTHERMAL_PROFILE = (surface, temperature[0...N], x[0...N], y[0...N],z[0...N])`

In order to keep the config file cleaner a better solution may be to specify an external file, from which the locations and temperatures are read. This seems to be already possible for inlet boundaries:
https://github.com/su2code/SU2/blob/72b2fa977b64b9683a388920f05298a40d39e5c5/config_template.cfg#L812-L816
However, I could not find any example actually using this functionality. If this is implemented, extending the functionality to also work with isothermal walls is probably the least intrusive modification.

**Describe alternatives you've considered**
A possible, but cumbersome solution could be to split the respective walls into many markers and specify piecewise-constant wall temperatures for each marker.

**Comment by pcarruscag** [comment]
This is already possible with the python wrapper, see testcases/py_wrapper/flatPlate_unsteady_CHT_FlatPlate.py
I am against adding any more "profile files" to SU2.

**Comment by ChristianBauerEng** [comment]
I see. The python wrappers are far more powerful than I thought. But I'm still a bit lost with respect to the API of the driver(s). Where's a good place to start reading into that?

**Comment by pcarruscag** [comment]
Sadly no, it is one of the main development areas we have identified in #1487, the interface is not very large, you can scroll over `python_wrapper_structure.cpp` to see the methods that allow modifying things at inputs, and the methods for control flow are in that example I pointed to.
If you join one of our dev meetings we can try to get a working example with what we need.
Wednesdays at 3pm UK - https://meet.jit.si/SU2_DevMeeting

**Comment by ChristianBauerEng** [comment]
If you don't mind I'll leave this question open for now.
I'm planning to provide a simplified example setup later on, once I've had time to properly dive into the wrapper API.

**Comment by mutlu-celik** [comment]
I am trying to do the same thing for a loosely coupled cht problem. I have the wall temperature data but cannot implement it to SU2. I have checked the python wrapper code but I think it needs to be updated to be able to work as isothermal wall boundary condition with varying T through x coordinate(or any). Is there any progress about this issue?
