### ISSUE TITLE
Visualization issue on intersection of slip (Euler) and no-slip walls

### ISSUE THREAD

**Issue by jf-thomas** [su2code/SU2#1558]
**Describe the bug**
We noticed that the symmetry boundary condition is showing a different behavior between sequential and parallel run. With the parallel run, the skin friction lines become parallel to the symmetry wall. We reproduced the issue on a naca0012 profile extruded between two slip walls. 

![cfx_comp1](https://user-images.githubusercontent.com/91184648/157279610-e77efb04-25bd-4b8c-a0cf-fd7bf16b2b1c.png)
![cfx_comp2](https://user-images.githubusercontent.com/91184648/157279687-843f22fe-ebe9-46b6-8338-485592922b31.png)
![cfx_comp3](https://user-images.githubusercontent.com/91184648/157279704-55fed159-ed8f-4252-a15d-28331ad6096c.png)

The convergence of the residuals is not good and is similar between sequential and parallel run. The drag coefficient is also taking a long time to stabilize. During convergence, the skin friction lines are much more deviated at the cell touching the slip wall but it improves with iterations (for both sequential and parallel runs).
![Residuals convergence](https://user-images.githubusercontent.com/91184648/157280437-d688be87-8833-405f-bed6-a2dc6c5ef338.png)
![Drag coefficient convergence](https://user-images.githubusercontent.com/91184648/157281353-99dc49b0-bbfa-49dc-8386-0fcc97dd8e85.png)

**To Reproduce**
The extruded NACA0012 profile testcase is provided in this archive.
[naca0012.zip](https://github.com/su2code/SU2/files/8207844/naca0012.zip)

**Desktop (please complete the following information):**
- OS: Linux Red Hat ELS 6.5
- C++ compiler and version: intel/2018.0.1
- MPI implementation and version: intelmpi/2018.0.1
- SU2 Version: v7.3.0

Thank you for looking at this issue and for any help.

**Comment by pcarruscag** [comment]
On how many cores were you running?

**Comment by jf-thomas** [comment]
It was run on 10 cores.

**Comment by pcarruscag** [comment]
Ok I reproduced the problem, it seems to be a problem in the output file, not in the solver, some of the nodes on the intersection between symmetry and wall are getting the Cf value from the symmetry (0) instead of from the wall.
If I restart the solver in serial from the parallel results the residuals are the same and the visualization problem goes away.

You might find these settings [naca0012.cfg.txt](https://github.com/su2code/SU2/files/8218394/naca0012.cfg.txt) better to converge the solver (in steady state at least):

**Comment by pcarruscag** [comment]
@jf-thomas I found the issue, if you replace MARKER_EULER by MARKER_SYM there are no visualization issues. We'll work on a fix for when MARKER_EULER intersects a viscous boundary. Thank you for reporting the problem.

**Comment by jf-thomas** [comment]
Thank you for solving this issue so rapidly. Actually I found this issue while trying to reproduce the problem I have on a flap from a high lift wing section. The skin friction lines are not parallel. I could not reproduce it on the naca0012. I guess that I will have to check if it comes from my mesh. Here is a view of my problem.
![cfx](https://user-images.githubusercontent.com/91184648/158140447-9e22fb8c-ade2-4b15-b445-f73f4ab7ad7a.png)
