### ISSUE TITLE
Symmetry plane deformation 

### ISSUE THREAD

**Issue by hlkline** [su2code/SU2#156]
Symmetry planes are currently set to accept in-plane deformation; this is great - however they also deform out-of-plane. It is currently up to the user to make sure that there are no deformations normal to a symmetry plane. This should be modified to either prevent out-of-plane deformation entirely or deform uniformly (aka, translate while keeping the symmetry plane in the same orientation).

**Comment by fpalacios** [comment]
I have also found some problems in 2D runs when we use the symmetry BC in an axisymmetric problem. I don't think it is well defined in 2D.

**Comment by hlkline** [comment]
actually I included a small change that I think addressed this in a recent pull request. I'm not sure whether this will help with axisymmetric conditions. 
See: 
https://github.com/su2code/SU2/commit/1f1fb9a5f1c3570b60b2059a5deda67ee664cb9f

**Comment by economon** [comment]
Fixed in #624
