### ISSUE TITLE
2D-ROTATIONAL PERIODIC BOUNDARY CONDITION BUG 

### ISSUE THREAD

**Issue by LorenzoFabris** [su2code/SU2#1562]
**Describe the bug**
During the last weeks of 2021, two different periodic flow scenarios have been investigated ( #1523 ).
While setting the periodic boundary conditions, the 2D-divergent wedge case solution seemed to be negatively affected even after the precious suggestions and corrections received in the quoted discussion. 

Consequently, different test cases have been simulated again to avoid any possible mistake.
Scenarios investigated are better explained here below:
- **Rectangular Duct** 

_2D case_ 
![2022-03-13 (3)](https://user-images.githubusercontent.com/96534491/158036413-52921fc0-3ae9-464c-b9f9-1ef6b4075ecf.png)

_3D case_ 
![2022-03-13 (5)](https://user-images.githubusercontent.com/96534491/158036422-9fba20d1-9757-40a2-93f6-e4b05aeac2de.png)

- **Divergent Wedge**

_2D case_ 
![2022-03-13 (2)](https://user-images.githubusercontent.com/96534491/158036446-959ee5d1-f394-48c5-8ce6-383a1dc8d3a6.png)

_3D case_ 
![2022-03-13 (12)](https://user-images.githubusercontent.com/96534491/158036910-39f879f2-3c74-4735-b416-212f17181933.png)

Meshes have been realized with ICEM CFD, then correctly converted into .cgns (adf) format.

The results obtained are the following:

- 2D Rectangular Duct (Translational Periodicity) --> **Converged**
- 3D Rectangular Duct (Translational Periodicity) --> **Converged**
- 2D Divergent Wedge (Rotational Periodicity) --> _**Diverged**_
- 3D Divergent Wedge (Rotational Periodicity) --> **Converged**

It is suggested that this solution behavior might be traced to a bug.
It has also been observed that the converged simulations are providing consistent results only for the following convective scheme and time discretization settings: 

CONV_NUM_METHOD_FLOW = ROE
MUSCL_FLOW = NO
TIME_DISCRE_FLOW = EULER_IMPLICIT

**To Reproduce the simulations**

_2D Rectangular Duct_
[channel2D.txt](https://github.com/su2code/SU2/files/8238476/channel2D.txt)

_3D Rectangular Duct_
[channel3D.txt](https://github.com/su2code/SU2/files/8238474/channel3D.txt)

_2D Divergent Wedge_
[wedge2D.txt](https://github.com/su2code/SU2/files/8238478/wedge2D.txt)

_3D Divergent Wedge_
[wedge3D.txt](https://github.com/su2code/SU2/files/8238481/wedge3D.txt)

 .cgns files cannot be attached to this report (format not supported from GitHub) but can be provided separately.
Thank you in advance for your support, always precious and more than welcome.

**Desktop:**
OS: Microsoft Windows 10 64bit
C++ compiler and version: g++ (GCC) 11.1.0
MPI implementation and version: OpenMPI 10.1.12498.18
SU2 Version: v7.2.0 Blackbird

**Comment by pcarruscag** [comment]
There were in fact a couple of bugs, should be fixed in #1563 and a regression case has been added.

**Comment by LorenzoFabris** [comment]
> There were in fact a couple of bugs, should be fixed in #1563 and a regression case has been added.

Thank you Pedro. 
I'll be re-compile the source code today and I'll let you know if the bug is actually fixed.

**Comment by pcarruscag** [comment]
Note that you need to checkout this branch `fix_2d_periodic_rotation` (it is not in `develop` yet).

**Comment by TobiKattmann** [comment]
> C++ compiler and version: g++ (GCC) 1.42.0 

Just as an unrelated sidenote: I hope you are not using gcc 1.42 ... and I also doubt you would get SU2 to run with that.
After [this website](https://gcc.gnu.org/releases.html) gcc 1.42 was released `September 20, 1992` ... just a couple days after I was born (and I am already starting to get old :wink:  ).

**Comment by LorenzoFabris** [comment]
> > C++ compiler and version: g++ (GCC) 1.42.0
> 
> Just as an unrelated sidenote: I hope you are not using gcc 1.42 ... and I also doubt you would get SU2 to run with that. After [this website](https://gcc.gnu.org/releases.html) gcc 1.42 was released `September 20, 1992` ... just a couple days after I was born (and I am already starting to get old 😉 ).

Thank you, Tobi. It’s a typo, I corrected my post.  
However, thank you for your note; it is always good to correct even the smallest detail.

**Comment by LorenzoFabris** [comment]
> Note that you need to checkout this branch `fix_2d_periodic_rotation` (it is not in `develop` yet).

Hi Pedro,
I checked the files you sent but building SU2 from source provided some errors:

- _MinGW64_ files provided from SU2 official website are corrupted and the installation crashes; however, it is possible to install the software but the .exe file mentioned in the installation guide won't be present. 
- After building _meson.py_ , the ninja installation command was line typed and the following alert message appeared " **ninja: fatal: chdir to 'build' - No such file or directory** "

On a different laptop (with different user, to avoid the same mistakes), with different user, the following ERROR came up after the mason.py command line:
" **'meson.py' is not recognized as an internal or external command, operable program or batch file** ".

I don't know if any other users might have experienced the same errors. 
Anyway, are the bugfix files you published already available in the pre-compiled version? 
In the meanwhile, I'll try to figure out this inconvenient.

Thank you in advance.

**Comment by pcarruscag** [comment]
I'll merge the PR and that way the github actions will build the Windows binaries

**Comment by pcarruscag** [comment]
The binaries will be available once this: https://github.com/su2code/SU2/actions/runs/1994296209 finishes.
Let me know if you don't see them, in which case I'll attach them here.

**Comment by LorenzoFabris** [comment]
> The binaries will be available once this: https://github.com/su2code/SU2/actions/runs/1994296209 finishes. Let me know if you don't see them, in which case I'll attach them here.

Hi Pedro, 
I just ran the simulations and the bug is fixed. 
Here below Mach and Pressure contours post-processed using Paraview.


**SIMULATION RESULTS**

_2D Divergent Wedge - **Before Bugfix**_



![Screenshot (4)](https://user-images.githubusercontent.com/96534491/159000363-82936c7f-79bd-43c9-b148-1c743e6aa04f.png)

![Screenshot (5)](https://user-images.githubusercontent.com/96534491/159000368-b9aea0aa-d3fb-4c57-b3af-37760c6272bb.png)



_2D Divergent Wedge - **After Bugfix**_


![Screenshot (9)](https://user-images.githubusercontent.com/96534491/159000577-fdb4f2cd-3a1d-484f-9908-5d11bce6c6ff.png)

![Screenshot (8)](https://user-images.githubusercontent.com/96534491/159000579-d5b7d8d6-bd09-4f71-b934-980bd950f91e.png)

**Comment by TobiKattmann** [comment]
great to hear that #1563 of pedro fixes your issue. Therefore i close it then :)
