### ISSUE TITLE
CGNS import fails in multizone simulations

### ISSUE THREAD

**Issue by ChristianBauerEng** [su2code/SU2#1564]
**Describe the bug**
I'm attempting to run coupled CHT simulations with a single fluid and a single solid zone. Both zones are read as seperate CGNS files.
In Dry-run mode everything works fine. However, when starting an actual run no matter in which order the zones are specified in the configuration list, the 2nd zone is always considered invalid:

> ------------------- Geometry Preprocessing ( Zone 1 ) -------------------
> Reading the CGNS file: MeshSolid.cgns.
> WARNING: The CGNS file version (3.31)  is old and may cause high memory usage issues, consider updating the file with the cgnsupdate tool.
> CGNS file contains 1 database(s).
> Database 1, BASE#1:  cell dimension of 2, physical dimension of 3.
> 1 total zone(s).
> Zone number 2 invalid

It seems this error is thrown during the CGNS import.
https://github.com/su2code/SU2/blob/72b2fa977b64b9683a388920f05298a40d39e5c5/externals/cgns/cgns_internals.c#L10186-L10198

Both zones run fine individually (when adding the missing, coupled BC of course).
When the second zone is converted to SU2 format and read in the native format, the case runs normally.

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*
[CoupledSim.zip](https://github.com/su2code/SU2/files/8303540/CoupledSim.zip)

**Desktop (please complete the following information):**
 - OS: SUSE Linux Enterprise Server 15 SP1
 - C++ compiler and version: intel 19.0.5.281
 - MPI implementation and version: intel MPI 2019
 - SU2 Version: v7.3.0 (develop)

**Comment by pcarruscag** [comment]
Literally a one-liner bug, I'll open a PR soon.
Thank you for making it easy to reproduce 👍
