### ISSUE TITLE
Failed to compile su2 in win10

### ISSUE THREAD

**Issue by zhang-qiang-github** [su2code/SU2#1570]
**Bug**
```
PS C:\Users\qiang_zhang\Desktop\TestCases\SU2> ./ninja.exe -C C:\Users\qiang_zhang\Desktop\TestCases\SU2\build install
ninja: Entering directory `C:\Users\qiang_zhang\Desktop\TestCases\SU2\build'
[1/767] Linking target externals/cgns/hdf5/H5detect.exe
FAILED: externals/cgns/hdf5/H5detect.exe
"gcc"  -o externals/cgns/hdf5/H5detect.exe externals/cgns/hdf5/H5detect.exe.p/H5detect.c.obj "-Wl,--allow-shlib-undefined" "-Wl,-O1" "D:/Anaconda/Library/lib/z.lib" "-Wl,--start-group" "-lC:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\msmpi" "-Wl,--subsystem,console" "-lkernel32" "-luser32" "-lgdi32" "-lwinspool" "-lshell32" "-lole32" "-loleaut32" "-luuid" "-lcomdlg32" "-ladvapi32" "-Wl,--end-group"
D:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lC:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\msmpi
collect2.exe: error: ld returned 1 exit status
[10/767] Compiling C object externals/cgns/hdf5/libsu2hdf5.a.p/H5Pint.c.obj
ninja: build stopped: subcommand failed.
```

**To Reproduce**

I can sucess configure su2:
![image](https://user-images.githubusercontent.com/29271051/159446256-dc866db4-9199-42d0-86b4-c38839753dd3.png)
![image](https://user-images.githubusercontent.com/29271051/159446307-354518f6-3382-401b-80c9-ac9e72f3d224.png)

Then, I want to compile it by:
```
./ninja.exe -C C:\Users\qiang_zhang\Desktop\TestCases\SU2\build install
```
And the bug is reported:

```
cannot find -lC:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\msmpi
```
However, I have install the `msmpisdk.msi` and `msmpisetup.exe`. 

![image](https://user-images.githubusercontent.com/29271051/159446649-f606a381-0896-461c-bd09-9e0b9243ce2e.png)

**Desktop (please complete the following information):**
 - OS: win10
 - C++ compiler and version: as the recommanded `gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)`
 - MPI implementation and version: as the recommanded v10.1.2
 - SU2 Version: Project version: 7.3.0 "Blackbird"

Any  suggestion is appreciated~~~

**Comment by pcarruscag** [comment]
Duplicated from #1468
