### ISSUE TITLE
SU2 python wrapper build failed in win10

### ISSUE THREAD

**Issue by zhang-qiang-github** [su2code/SU2#1575]
**Describe the bug**

I have suceeded build SU2 when `-Denable-pywrapper=false`. Then, I want to install SU2 by python wrapper build. But the bug is reported:

```
FAILED: SU2_PY/pySU2/_pysu2.dll.p/pySU2.cxx
"D:\Program Files\swigwin-4.0.2\swig.EXE" "-DHAVE_CGNS" "-DNDEBUG" "-DHAVE_MPI" "-DHAVE_METIS" "-DHAVE_PARMETIS" "-DHAVE_TECIO" "-DTECIOMPI" "-c++" "-python" "-I" "-outdir" "C:/Users/ZHQ/Desktop/SU2/build/SU2_PY/pySU2" "-o" "./SU2_PY/pySU2/_pysu2.dll.p/pySU2.cxx" "../SU2_PY/pySU2/pySU2.i"
..\SU2_PY\pySU2\pySU2.i(58) : Error: Unable to find 'mpi4py\mpi4py.i'
[2/10] Linking static target externals/cgns/hdf5/libsu2hdf5.a
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Firstly, I install the `mpi4py` in a conda environment. And I am sure I have install `mpi4py`:

```
(SU2) C:\Users\ZHQ>python
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpi4py import MPI
>>> MPI
<module 'mpi4py.MPI' from 'D:\\Anaconda\\envs\\SU2\\lib\\site-packages\\mpi4py\\MPI.cp37-win_amd64.pyd'>
>>>
```
But the `python ./meson.py build` find another python environment:
```
Program python3 found: YES (C:\Users\ZHQ\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe)
```
I have find a similar issure (https://github.com/su2code/SU2/issues/722). This issue suggestion that we need to modify the `Makefile`. However, since I build SU2 in Win10, I have no `Makefile`. Then, I find the `build/build.ninja` specified the location of `python.exe`. So I modify the `python.exe` location in `build.ninja` by:
1. modify all `C:\Users\ZHQ\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe` to `D:\Anaconda\envs\SU2\python.exe`. 
2. modify all `C$:/Users/ZHQ/AppData/Local/Microsoft/WindowsApps/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/python.exe` to `D$:/Anaconda/envs/SU2/python.exe`.

Then, `.\ninja.exe -C build install` again, but the bug is still reported. 

I even add the `mpi4py` to the computer environment variable:

But the bug is still reported.

**Desktop (please complete the following information):**
 - OS: Win 10
 - C++ compiler and version: as the recommanded gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
 - MPI implementation and version: as the recommanded v10.1.2
 - SU2 Version: 7.3.0 "Blackbird"

Any suggestion is appreciated~~~

**Comment by clarkpede** [comment]
The primary solution in the linked issue is to use a virtualenv.  I quote:

> The easiest workaround: Switch to a [virtualenv](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/). This will ensure that all of your python packages are stored in single location.

**Comment by pcarruscag** [comment]
Looks a problem with how the environment is setup then.

**Comment by zhang-qiang-github** [comment]
@pcarruscag, @clarkpede , actually, I have used a anaconda environment. But `python ./meson.py build` do not find my anaconda environment. 

Can I provide the location of python.exe?

Or how can I setup a anaconda environment to build su2?
