### ISSUE TITLE
Patching of Mesh

### ISSUE THREAD

**Issue by Ajinkyamaske** [su2code/SU2#158]
Does SU2 allows patching of quadrilateral mesh. If yes, then are there any issues concerned with the same?

**Comment by hlkline** [comment]
This sounds like a question that would be great for the forum at cfd-online.com/Forums/su2/
I'm not 100% sure what you mean by "patching of quadrilateral mesh" in this context; however someone reading the forum may be able to help, and posting to the forum will allow more people to benefit from the answers.
