### ISSUE TITLE
pysu2: NaNs in GetFlowLoad() in combination with dynamic / moving mesh

### ISSUE THREAD

**Issue by ArneVoss** [su2code/SU2#1588]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*

This issue is a follow-up of a discussion here: https://www.cfd-online.com/Forums/su2/241889-rotating_frame-grid-velocity-correct-flow-physics-wrong.html

Summary: To calculate an aircraft during pitch-up as a steady Euler simulation, I use the dynamic / moving mesh module with GRID_MOVEMENT= STEADY_TRANSLATION and/or ROTATING_FRAME and set the farfield mach number = 0.0. The results look fine, but when reading the nodal forces f_xyz on the surface via pysu2 and GetFlowLoad(), I now receive NaNs... My first idea was that maybe the forces are calculated from the pressure coefficients, which show "strange" values in Tecplot, probably due to the division by V_inf=0.0.

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*
I derived a test case from the Naca0012 example and added a short python script that should reproduce the NaNs in line 66.
[testcase_dynamic_mesh.zip](https://github.com/su2code/SU2/files/8396025/testcase_dynamic_mesh.zip)

**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Workstation 7.9
 - C++ compiler and version: mpicc (gcc 4.8.5 "gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)")
 - MPI implementation and version: MPICH 3.4.2
 - SU2 Version:  7.3.0 "Blackbird"

**Comment by pcarruscag** [comment]
Some coefficients were still using the farfield velocity and density as reference, I hope to have a fix soon-ish.
