### ISSUE TITLE
paraview cannot open surface_grid.dat in version 3.2.8

### ISSUE THREAD

**Issue by hlkline** [su2code/SU2#161]
Issue brought up by cfd-online user JanH
For a previous version surface_grid.stl output from grid deformation could be opened in paraview. 
In version 3.2.8 the output is surface_grid.dat and cannot be opened in paraview. 
I took a look, seems like the paraview writing was taken out after version 3.2.3 
Was that intentional? Should we add it back in?

**Comment by economon** [comment]
This has been fixed. SU2_DEF output should work in ParaView for SU2 v5+ (tested successfully with ParaView v5.4.1).
