### ISSUE TITLE
Fail to Generating 'SU2_PY/pySU2/_pysu2.so.p/pySU2.cxx'

### ISSUE THREAD

**Issue by Brimp** [su2code/SU2#1617]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*
I try to build SU2 from source on cluster. but it failed in Generating 'SU2_PY/pySU2/_pysu2.so.p/pySU2.cxx'.  The log of meson build info is like the figure shows
![image](https://user-images.githubusercontent.com/54931653/165111891-b9f26f7f-efe4-4e08-a7af-0945f916748a.png)
![image](https://user-images.githubusercontent.com/54931653/165111974-25211d0c-72e0-401e-8619-ab8c30163fd5.png)
![image](https://user-images.githubusercontent.com/54931653/165112038-98e00c96-c2fb-4662-b98d-6b7a9be4581a.png)
![image](https://user-images.githubusercontent.com/54931653/165112129-cd00f7ef-1195-4a39-86a5-608fb0b036eb.png)
![image](https://user-images.githubusercontent.com/54931653/165112177-4dbef8c9-cb54-48ec-9787-6ef7213ce934.png)

when using ninja, it shows the error like the figure show
![image](https://user-images.githubusercontent.com/54931653/165111571-a795012b-e0f4-4fb7-9f87-f78c67242a2f.png)

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*
The meson command for build is
 ./meson.py build -Dcustom-mpi=true -Denable-pywrapper=true --prefix=$HOME/SU2_prefix 

**Desktop (please complete the following information):**
 - OS: [Red Hat 8.5.0-4]()))
 - C++ compiler and version: [gcc 8.5.0]
 - MPI implementation and version: [intel MPI]
 - SU2 Version: [ v7.3.1]

**Comment by pcarruscag** [comment]
Should work with swig 3.0.11 onward according to this https://www.swig.org/
(I have 3.0.12 and it's fine)
Please confirm if upgrading swig works for you and I will try to put this requirement meson.

**Comment by Brimp** [comment]
Thanks for your reply. 3.0.12 works well in my own machine. But the newest version in HPC is 3.0.10. I have required ICT to install it. Hopefully, it will be done tomorrow. Thanks

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Pedro Gomes ***@***.***>
发送时间: Monday, April 25, 2022 8:49:52 PM
收件人: su2code/SU2 ***@***.***>
抄送: Jia, Guangnan ***@***.***>; Author ***@***.***>
主题: Re: [su2code/SU2] Fail to Generating 'SU2_PY/pySU2/_pysu2.so.p/pySU2.cxx' (Issue #1617)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Should work with swig 3.0.11 onward according to this https://www.swig.org/
(I have 3.0.12 and it's fine)
Please confirm if upgrading swig works for you and I will try to put this requirement meson.

―
