### ISSUE TITLE
NEMO symmetry boundary condition problem

### ISSUE THREAD

**Issue by otumuklu** [su2code/SU2#1625]
**Describe the bug**
*This is not a bug, rather it is a defect in the implementation of the symmetry boundary conditions. The pressure field show imperfections in the vicinity of the symmetry plane whereas the temperature field seems to be fine, as can be seen in the attached figure. Of note, although the attached result and corresponding config and mesh file belong to SU2-NEMO (i.e. non-equilibrium), this problem exists for the SU2 branch, based on private communication with @WallyMaier and @jtneedels. This case is  Argon flow over a cylinder at Mach 7.68 with a freestream pressure of 50Pa.*

**To Reproduce**
*Please find the attached config and mesh file.*

[configmesh.zip](https://github.com/su2code/SU
![SymmetryPlaneDefect](https://user-images.githubusercontent.com/104862595/166668880-2c0ba583-b276-4759-9ded-0b977e0658dc.png)
2/files/8619649/configmesh.zip)

**Comment by otumuklu** [comment]
Thank you @TobiKattmann, the previous symmetry issues were very helpful for us to narrow down the problem. It is obvious that NAVIER_STOKES (SU2 EQUILIBRIUM) solver with the STANDARD_AIR model doesn't have the issue any longer, as opposed to NEMO_NAVIER_STOKES. I ran the same case with the standard air, see the attached.  We (@WallyMaier and @jtneedels) will take care of the SU2-NEMO part.


![SymmetryPlane_NS_SU2](https://user-images.githubusercontent.com/104862595/167034076-d1c627c4-2d4d-494a-9524-72ea7074b49a.png)

**Comment by jtneedels** [comment]
Adding on here: we also observe a similar issue with inviscid simulation in NEMO. I've run the same case with NEMO_EULER_SOLVER and still observe a defect at the stagnation point. I implemented a mirrored state for the evaluation of the convective fluxes, following the procedure of the symmetry BC implemented in CFVMFlowSolverBase.inl, and I still observe the issue. I've zoomed in on the stagnation point here.
![image](https://user-images.githubusercontent.com/44848904/167720992-44aecdd7-2cd6-4896-a2a1-e1bd7c8e6294.png)

**Comment by jtneedels** [comment]
I'll add that when I run the same case with standard air (EULER_SOLVER) with MUSCL turned off, I get the same behavior, though it goes away when MUSCL is turned on. 
![image](https://user-images.githubusercontent.com/44848904/167723450-913f963d-b848-4484-90c7-68f400bcce71.png)

**Comment by jtneedels** [comment]
An update here. I did some digging and saw there was a previous PR #1168, where Fabio looked at this issue and implemented a fix for NEMO about 1.5 years ago. It looks like the results were great, but the PR never got merged in. If I pull the most recent commit and run this test case on it, it looks like it solves the issue. 

It sounds like we might be able to address this by merging this branch into current Develop and opening a new PR. Thoughts on this approach?
![image](https://user-images.githubusercontent.com/44848904/167740530-c2e23dc5-a264-4d80-8cf1-66b4396cccc7.png)

**Comment by pcarruscag** [comment]
It needs cleanup @jtneedels, but it had potential to also solve #1125 so I'm in favor.

**Comment by jtneedels** [comment]
Okay, sounds good. I just wanted to check before I deep-dived into merging. As I understand it, the way Fabio implemented this it is specific to NEMO. To address #1125 it sounds like we would want to generalize to the full code?

**Comment by pcarruscag** [comment]
Yep, having the implementation in CFVMFlowSolverBase should be enough.
And I think there were some geometry modifications that need to be moved to one of the geometry classes, to make sure everything works when we have deforming meshes.

**Comment by fmpmorgado** [comment]
@jtneedels  Let me know if you need help!

**Comment by pcarruscag** [comment]
Symmetry has been improved, if you could re test it would be great. Re-open if you still see the same issues.
