### ISSUE TITLE
Parser problem with interpreting : in names of boundary conditions 

### ISSUE THREAD

**Issue by libm3l** [su2code/SU2#163]
Hello

I have a mesh which has a boundary condition with name containing : symbol. SU2 considered just the part of the name in before : When : was used in definition of the optimization problem, the parser returned an error message

**Comment by btracey** [comment]
I don't think there is any good way to fix this (without completely changing how the config file is defined). Many of the options allow one or multiple entries, and colons are among the tokens used to split up the entries. If we don't use a token to split it, then we won't know how many BCs there are (for example).

**Comment by WallyMaier** [comment]
There isn't a good way to address this.
