### ISSUE TITLE
Supersonic inlet node shared with viscous wall leads to nonphysical behavior

### ISSUE THREAD

**Issue by bigfooted** [su2code/SU2#1639]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*

related to #1631 

A similar fix is necessary for supersonic inlets.

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*

**Comment by bigfooted** [comment]
It's probably a small fix, but better if @WallyMaier  or @jtneedels look into this and fix it, since they are more capable of setting up the compressible test case for verification/validation.

**Comment by pcarruscag** [comment]
The fix is not as simple, using the strategy from #1631 makes it worse.
Intersection with symmetry/euler look ok, so the best is to extend the domain...
