### ISSUE TITLE
Specify inlet profile for supersonic inlet

### ISSUE THREAD

**Issue by eskimmel** [su2code/SU2#1650]
**Is your feature request related to a problem? Please describe.**
There is the option to specify an inlet profile for subsonic flows, but not supersonic flows. This feature would help reduce domain sizes and prevent divergence for no-slip walls at the inlet.

**Describe the solution you'd like**
A supersonic inlet profile specification method as similar as possible to the incompressible inlet profile method would be preferable, as that method is very straightforward.

Thank you!

**Comment by bigfooted** [comment]
Would be great if you can take the lead and 
1. create a new feature branch feature_supersonicinlet here on github from the develop branch and 
2. start a draft pull request from this feature branch as soon as possible so we can help you from here.

First thing to look at is in CEulerSolver.cpp at CEulerSolver::BC_Supersonic_Inlet and compare it with CEulerSolver::BC_Inlet. The inlet profile data is stored in Inlet_***[val_marker][iVertex]

You will have to replace the GetInlet_Velocity(Marker_Tag) etc. with the profile data stored in Inlet_Velocity[][] etc...

**Comment by eskimmel** [comment]
Hi, thanks for the first steps. I forked the project, created the new branch (I called it feature_supersonicinletprofile) under the develop branch, and will be sending the draft pull request soon shortly.

**Comment by bigfooted** [comment]
OK great! I recommend working in vscode so if you haven't installed it yet, please have a look at it. It's also easy to discuss problems that you have with the implementation when your code can be viewed, so even if it is not working (especially if it's not working yet), it's good to have the code in a PR already.

**Comment by eskimmel** [comment]
Thanks! I sent the draft pull request through. The only changes I have made so far are to CEulerSolver.cpp with the changes you suggested.
