### ISSUE TITLE
Angular velocity in RIGID_PITCHING movement does not contain the Phase parameter

### ISSUE THREAD

**Issue by HL-ZHI** [su2code/SU2#1654]
**Describe the bug**
When I employed the pitching movement, I found the angular velocity has something wrong. So I checked the code of grid movement (can be seen in SU2/COMMON/src/grid_movement/CVolumetricMovement.cpp, line 2069). It seems the expression of angular velocity does not contain the initial phase.

At line 2063-2065, we can see that the expression of pitching angle considers the initial phase, like, "angle=Ampl * sin(Omega * Time + Phase)". Therefore, shouldn't the angular velocity is "AlphaDot = Omega * Ampl * cos(Omega *Time + Phase)" ? However, there is no Phase parameter in the expressions at line 2069-2071. I think it is a small bug.

**Desktop (please complete the following information):**
 - SU2 Version: [v7.3.1]

**Comment by pcarruscag** [comment]
I think you are right, thank you for looking into it. Can you open a pull request with the fix?

**Comment by HL-ZHI** [comment]
> I think you are right, thank you for looking into it. Can you open a pull request with the fix?

Thank you for your reply. I have submitted my pull request at #1656. It is my first time to use github, hope I didn't make a mistake :-)
