### ISSUE TITLE
Allow to define markers of a same type in separate lines.

### ISSUE THREAD

**Issue by taalf** [su2code/SU2#166]
On industrial cases, there can be tens of independent boundaries of a same type (eg. inlets / outlets).

It would be very good to be able to define them in separate lines in the config file.

Some graphical text editor can't even handle such "infinite" lines.

(This is also true for optimization variables like DEFINITION_DV.)

**Comment by btracey** [comment]
Obviously it is possible to implement this, but it would significantly complicate the config parsing code. Right now the parser is very simple: Go through each line, and get the name and the tokens. As far as I can see there aren't good ways to allow this aside from either having a whitelist of options that can go on multiple lines (thus, only some options are allowed to do so), or to switch up the config file entirely and go to a more standard format like JSON.
