### ISSUE TITLE
arrrow206

### ISSUE THREAD

**Issue by arrow206** [su2code/SU2#167]
I am using SU2 version 3.2.8. I have tried all the steady-state Euler and Navier-Stokes test cases and they worked fine. However, none of the demos for Rotating (NACA and CAradonna) are working. Both are diverging. I have decreased the Courant number from 4 to 2 and increased the number of implicit iterations. There is still divergence. In the cfg file, I removed all the variables related to the dynamic mesh motion nad put a freestream of 0.8. SU2 did not diverge. Is there a specific setting to put in the cfg file in order to get convergence for the Rotating test cases

**Comment by economon** [comment]
Thanks for the note! Indeed, we are aware of this issue, and we are already testing a patch that fixes it. We should be pushing the fix any day to the master, and I’ll note it here/close the thread when that happens.

**Comment by arrow206** [comment]
Thanks for your fast answers.

We are definitely going to use SU2 here and I wanted to be sure that it is working correctly.

We will look to use its inverse design capability too (provide Cp target) . I have tried the test case on the NACA 0012 but it did not work.
From your CFD forum, it seems it could be related to the scipy library used.

I will look more to be sure if I am doing things correctly before making any note.

Francois

**Comment by padronas** [comment]
Fix pushed to master and develop branches.

**Comment by jehanz** [comment]
Hi,
I am doing an analysis using a rotating propeller and I did a first attempt with Euler with no issues. As soon as I used Navier-Stokes with SA turb model, I get the same error: SU2 has diverged... 
I have already the most up to date version plus made sure the fixes as reported in the source file. What might be causing it. Thanks for the help.
Jehan
