### ISSUE TITLE
A screen output issue

### ISSUE THREAD

**Issue by otumuklu** [su2code/SU2#1681]
Hi all: 

I'm running a time-dependent problem and need to screen output the current time and time step. I use 
"SCREEN_OUTPUT =  CUR_TIME, TIME_STEP" .. command in the config file for the time discretization of "TIME_DISCRE_FLOW= EULER_EXPLICIT" for "NAVIER_STOKES" and "NEMO" solvers, and it prints out just **ZERO** for both solvers:
....
|        6907|  0.0000e+00|  0.0000e+00|
|        6908|  0.0000e+00|  0.0000e+00|
|        6909|  0.0000e+00|  0.0000e+00|
|        6910|  0.0000e+00|  0.0000e+00|
|        6911|  0.0000e+00|  0.0000e+00|
|        6912|  0.0000e+00|  0.0000e+00|
|        6913|  0.0000e+00|  0.0000e+00|
....
 Any suggestion and help is greatly appreciated.

**Comment by pcarruscag** [comment]
Hi,
Can you provide a minimal example that replicates the issue?

**Comment by pcarruscag** [comment]
I could not replicate your issue, please see one of the unsteady examples and check that you are really running in unsteady mode
