### ISSUE TITLE
develop does not compile anymore

### ISSUE THREAD

**Issue by bigfooted** [su2code/SU2#1701]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*

some recent changes causes SU2/develop to fail to compile on older compilers. Specifically:
I cannot compile SU2 with gnu compilers older than 7.4.0. My next most recent compiler gnu/10.2.1 works.
I cannot compile SU2 with intel compilers < 17.0, which is the most recent compiler installed on our system
I cannot compile SU2 with openmpi support, even for the gnu compiler gnu/10.2.1 that works. 
EDIT: The HPC guys added openmpi/4.0.4 which, together with gnu/10.2.1, compiles
I have mpich on my local machine, together with gnu 10.3.0, which still works.
What I understood from @Cristopher-Morales is that even the most recent openmpi/4.1.3 does not work (@Cristopher-Morales  what was the gnu compiler version you used?). 

So this issue affects the RB HPC as well as the TU/e HPC.

**Comment by bigfooted** [comment]
the error for older compilers:
```
cc1: error: -Werror=stringop-truncation: no option -Wstringop-truncation
cc1: error: -Werror=cast-function-type: no option -Wcast-function-type
cc1: warning: unrecognized command line option ‘-Wno-stringop-truncation’

```

**Comment by pcarruscag** [comment]
We have been trying to support gcc 4.8.5

**Comment by pcarruscag** [comment]
Yes, extra warnings had to be disabled once we updated the compiler used for regressions. As a workaround you remove the offending options from meson.build. While we sort it out.

**Comment by martin-g** [comment]
The build fails with old compilers due to the upgrade of the Ubuntu version
in the Docker images used by CI.
Ubuntu 20.04 comes with GCC 9.4, I believe.
Should it install older GCC?

**Comment by pcarruscag** [comment]
What's failing @martin-g ? did I miss something?
