### ISSUE TITLE
Time-Spectral test case gives "segmentation fault"

### ISSUE THREAD

**Issue by simaomrq** [su2code/SU2#171]
Tried to run the time-spectral test case (v3.2.9) using the NACA64A010 aerofoil and got a segmentation fault. The fault occurs in the "MeanFlowIteration" routine due to the change in the "nZone" variable value when using the time-spectral method. I tried a quick fix by updating  "nZone" in main.

**Comment by economon** [comment]
Thanks for the note! This issue has just been fixed in the master and develop branches. Please update your repo when you have a chance and try it out.
