### ISSUE TITLE
CMake build system for static linking

### ISSUE THREAD

**Issue by stephenberry** [su2code/SU2#1711]
SU2 is a fantastic library, but the build process is really painful to get static linking within another C++ program. CMake is a standard for building C++ projects and would be extremely helpful. Ideally Python wouldn't be necessary to build SU2 or link it with another project. In our use case we need to link the library so that we can efficiently multithread workflows, keep data in memory, and make analysis as efficient as possible. I realize this is a significant request, but a build process with CMake could be so much simpler and would make your codebase much more accessible to the C++ community. Thanks so much for all your excellent work!

**Comment by stephenberry** [comment]
This issue is still relevant.

**Comment by pcarruscag** [comment]
See #814

**Comment by PENGYAN777** [comment]
You can find how mutation++ and coolprop are build with cmake submodule in SU2/meson.build file.

**Comment by eli-schwartz** [comment]
> SU2 is a fantastic library, but the build process is really painful to get static linking within another C++ program. CMake is a standard for building C++ projects and would be extremely helpful. Ideally Python wouldn't be necessary to build SU2 or link it with another project.

I'm not sure I understand this... the fact that the build system uses python means that it is really painful to configure the build system to emit a static library? (This should absolutely not be the case! Meson has a core option `-Ddefault_library={static|shared|both}` to select what kind of library you want to build, for any library whose build description claims it can support either one. It's a bit like cmake's `-DBUILD_SHARED_LIBS` except much more powerful.)

However, as far as I can tell, su2 doesn't mark any of its libraries as public at all (i.e., installable) so maybe that's a moot point.

As far as making python be necessary to build the project, I think this mainly boils down to "I myself use cmake, I have cmake installed, I don't want to install another program when I could use the program I already have". Is it really that big of a deal, though? The software *does* use it, and it's not that difficult to install TBH (Linux operating systems in particular almost certainly have it installed already).

**Comment by pcarruscag** [comment]
Sounds like you could just change line 195 of SU2_CFD/src/meson.build to `install : true`
