### ISSUE TITLE
Transitional Flat Plate test case 

### ISSUE THREAD

**Issue by linatessier** [su2code/SU2#1719]
To Whom it May Concern, 

I am writing in connection with the Transitional Flat Plate Test Case and wanted to report that the tutorial available on SU2 website was not working with the current version of the code: 7.3. That is to say that after I followed the tutorial step by step without changing anything, I had the following terminal error : "FGMRES orthogonalization failed, linear solver diverged". I checked the source code and found a little contradiction between the configuration file of the tutorial and the implementation of the transitional model.

As you can see in the configuration file, the turbulence intensity Tu is already specified in % so the factor 100 added to Tu in the code does not seem necessary.  

![configuration_file](https://user-images.githubusercontent.com/109698292/180274079-ece0c6f6-4d64-4897-8e2d-abff41d30056.png)
![code](https://user-images.githubusercontent.com/109698292/180274082-b2dbee2d-a0ea-4967-b33e-a698f61d7471.png)

When I erased that factor 100 in the source code (SU2_CFD/include/numerics/turbulent/turb_sources.hpp) I was able to get the same results as displayed in the tutorial for the skin friction coefficient. 

Thank you

**Comment by pcarruscag** [comment]
Thanks, but the code is correct as is, we fixed that recently.  If the error is at the start, try running the case with first order for a few iterations and then restart.

**Comment by bigfooted** [comment]
Hi,
The standard definition of the turbulence intensity is u'/U, and we follow this definition: https://www.cfd-online.com/Wiki/Turbulence_intensity
The papers describing the transition model work with percentages, so we add a factor of 100 internally.

The actual freestream value mentioned in the paper of Schubauer and Klebanoff is 0.03%, which would correspond to u'/U=0.0003 (which is also the value in Schubauer & Skramstad)
So it looks to me that the value in the config file is too high.

**Comment by linatessier** [comment]
Yes, I agree that if this factor 100 should remain in the code, than it is the configuration file of the tutorial that should be modified with a lower turbulence intensity Tu to get the proper results. Thank you!

**Comment by pcarruscag** [comment]
If the case runs with the lower value can someone open a pull request to update the tutorials? thanks
