### ISSUE TITLE
Discrete adjoint solve for multizone problem of turbomachinery

### ISSUE THREAD

**Issue by wkangholy** [su2code/SU2#1720]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

I would like to know if SU2 can run the discrete adjoint case for multizone problem of turbomachinery.

I found
" if (nZone != 1)
      SU2_MPI::Error("The required solver doesn't support multizone simulations", CURRENT_FUNCTION);" in the code.

I am currently working on the optimization of axial turbine stage. I have revised the code for ENTROPY_GENERATION and Total toal efficiency output in the history output file and run the tutorial case "transonic_stator_2D" using "shape_optimization.py" successfully. But I failed to run "discrete_adjoint.py -f xxx.cfg" for turbiens stage optimization, whist the flow simulation using "SU2_CFD xxx.cfg" runs successfully. Seem the currect develop version is not applicable to the problem.

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*

May I ask for the implementation of multizone discrete adjoint solve for turbomachinery? Or if there is any solution for it.
I found the work from Vitale's paper in 2020 includes such capability in SU2 at https://github.com/su2code/SU2/tree/ feature_turbomachinery, yet I fail to run the multizone case.

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

I would like to try FADO for alternatives and may concern about the solver of the discrete adjoint for multizone problems in turbomachinery will still be needed.  

**Additional context**
*Add any other context or screenshots about the feature request here.*

Here is the function I have added for turbo coeffcient output in CFlowOutput.cpp:

void CFlowOutput::AddTurbomachineryCoefficients(const CConfig* config) {
  
  if (!config->GetBoolTurbomachinery()) return;
  /// BEGIN_GROUP: AERO_COEFF, DESCRIPTION: Sum of the aerodynamic coefficients and forces on all surfaces (markers) set with MARKER_MONITORING.
  /// DESCRIPTION: Drag coefficient
  AddHistoryOutput("ENTROPY_GENERATION",       "ENTROPY_GENERATION",   ScreenOutputFormat::SCIENTIFIC, "TURBO_COEFF", "Entropy generation coefficient of the whole turbomachinery", HistoryFieldType::COEFFICIENT);
  /// DESCRIPTION: Lift coefficient
  AddHistoryOutput("TT_EFFICIENCY",       "TT_EFFICIENCY",   ScreenOutputFormat::SCIENTIFIC, "TURBO_COEFF", "Total efficiency coefficient ", HistoryFieldType::COEFFICIENT);
  /// DESCRIPTION: Sideforce coefficient
  AddHistoryOutput("PRESSURE_LOSS",  "PRESSURE_LOSS",  ScreenOutputFormat::SCIENTIFIC, "TURBO_COEFF", "Pressure ratio between outlet and inlet", HistoryFieldType::COEFFICIENT);
  /// DESCRIPTION: Moment around the x-axis
  AddHistoryOutput("MASS_FLOW_RATIO",   "MASS_FLOW_RATIO",  ScreenOutputFormat::SCIENTIFIC, "TURBO_COEFF", "Mass flux ratio on the outlet", HistoryFieldType::COEFFICIENT);

  AddHistoryOutput("FLOW_ANGLE_OUT",   "FLOW_ANGLE_OUT",  ScreenOutputFormat::SCIENTIFIC, "TURBO_COEFF", "FLOW ANGLE OUT at outlet", HistoryFieldType::COEFFICIENT);

  /// END_GROUP

}

void CFlowOutput::SetTurbomachineryCoefficients(const CConfig* config,  COutputLegacy* output_legacy){
  if (!config->GetBoolTurbomachinery()) return;
  if (config->GetnZone() < 2) {
          SetHistoryOutputValue("ENTROPY_GENERATION", output_legacy->GetTurboEntropyGen(0,config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("TT_EFFICIENCY", output_legacy->GetTurboTTEff( 0,config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("PRESSURE_LOSS", output_legacy->GetTurboPressLoss(0,config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("MASS_FLOW_RATIO", output_legacy->GetTurboMassFlow(0,config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("FLOW_ANGLE_OUT", output_legacy->GetFlowAngleOut(0,config->GetnSpanMaxAllZones()));
  }
  else {
	  SetHistoryOutputValue("ENTROPY_GENERATION", output_legacy->GetTurboEntropyGen(config->GetnMarker_Turbomachinery()+
	  SU2_TYPE::Int(config->GetnMarker_Turbomachinery()/2),config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("TT_EFFICIENCY", output_legacy->GetTurboTTEff(  config->GetnMarker_Turbomachinery()+
	  SU2_TYPE::Int(config->GetnMarker_Turbomachinery()/2),config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("PRESSURE_LOSS", output_legacy->GetTurboPressLoss(config->GetnMarker_Turbomachinery()+
	  SU2_TYPE::Int(config->GetnMarker_Turbomachinery()/2),config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("MASS_FLOW_RATIO", output_legacy->GetTurboMassFlow(config->GetnMarker_Turbomachinery()+
	  SU2_TYPE::Int(config->GetnMarker_Turbomachinery()/2),config->GetnSpanMaxAllZones()));
	  SetHistoryOutputValue("FLOW_ANGLE_OUT", output_legacy->GetFlowAngleOut(config->GetnMarker_Turbomachinery()+
	  SU2_TYPE::Int(config->GetnMarker_Turbomachinery()/2),config->GetnSpanMaxAllZones()));
  }

}

**Comment by pcarruscag** [comment]
Please see #1680
