### ISSUE TITLE
Distributed Wall Temperature

### ISSUE THREAD

**Issue by mutlu-celik** [su2code/SU2#1722]
For a loosely coupled CHT analysis I need to apply the distributed wall temperature as isothermal wall temperature. Is there any possible way to do it? 

I can divide the wall to some dicrete parts and apply average temperature of those nodes but I would prefer to identify each node with a certain temperature. I found a python wrapper which is shared before but do not really understand how to work with it. It could be really nice if you can help me. Thanks in advance.

**Comment by pcarruscag** [comment]
#1553
