### ISSUE TITLE
Symmetry boundary condition is not equivalent to full model

### ISSUE THREAD

**Issue by rois1995** [su2code/SU2#1723]
**Describe the bug**
Symmetry boundary condition does not work properly. In particular, the values on the symmetry plane are wrong with respect to a computation performed on the complete mesh. In the images you can see the pressure coefficient and the skin friction coefficient magnitude for both the simulations. For each image, the upper half is the solution on the complete mesh whereas the lower portion is the solution on the halved mesh with the symmetry plane. I am performing an incompressible RANS simulation with SST turbulence model. I am attaching the files needed to perform both the simulations. The branch I used is the develop one. I also tried with the main branch but the error persists.

![PressureCoefficient](https://user-images.githubusercontent.com/43813346/180821411-9978c962-b3c0-42d0-b631-35a5b0c71b29.png)
![SFC_Error](https://user-images.githubusercontent.com/43813346/180821429-f476bb80-1ac1-4fad-b55b-f5ea05f3a604.png)

**To Reproduce**
Please find the config and mesh file at the following link.

https://we.tl/t-nmjBv7HJv0

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.6.1810 (Core)
 - C++ compiler and version: gcc 11.2.0
 - MPI implementation and version: OpenMPI 4.0.1
 - SU2 Version: v7.3.1

**Comment by pcarruscag** [comment]
How many of orders of magnitude are the residuals dropping? And have you tried SA instead of SST?

**Comment by rois1995** [comment]
> How many of orders of magnitude are the residuals dropping? And have you tried SA instead of SST?

Residuals drop down by roughly 5 orders of magnitude across the board. I have just tried with SA and the results are the same. I am running a second order starting from a restart of a first order. I can send you a link with all of the results if needed.

**Comment by pcarruscag** [comment]
In a vertex centered code it is not trivial to make a symmetry plane perfectly equivalent to the full model. We are computing fluxes for an edge that does not exist in the full model.
Can you try reducing the grid spacing in the normal direction, close to the plane? Or just compare results on globally-refined meshes?
The implementation could certainly be better, for numerous reasons #1125 #1373, but I don't think this particular issue is a bug.
Nevertheless, if you have time to obtain the results above it would help with characterizing the limitations a bit better.

**Comment by rois1995** [comment]
I tried reducing the grid spacing both in normal and in tangential direction to the symmetry plane. It seems that acting only on the tangential direction only worsen the results. The first image reflects this behavior. The upper half is the refined one, whereas the lower one is the reference half mesh solution.

![TangRef](https://user-images.githubusercontent.com/43813346/182622324-21ea0d54-1ca1-49e1-8b3f-9a3f1bc96788.png)

Reducing normal spacing, instead, greatly improves the results, but still, the contours of pressure coefficient are not the same wrt the mesh without symmetry plane.  This can be seen from the second image, where on the bottom there is the solution on the refined mesh, whereas on the top there is the solution on the whole mesh.

![NormRef](https://user-images.githubusercontent.com/43813346/182622377-3aedd185-d54a-47ce-b1aa-ddc63bc8e634.png)


I might try further refining along the normal direction to check whether I can reach or not the reference solution.
