### ISSUE TITLE
SU2 do not produce plot files such as vtk etc.

### ISSUE THREAD

**Issue by jehanz** [su2code/SU2#173]
I have downloaded most up to date version of SU2 and compiled for parallel. Analysis produced history etc. files successfully but no vtk plot files. I tested it on Quick folder with given example and there also it does not produce any plot files. I wonder if there is something I need to do to fix the issue.

**Comment by jehanz** [comment]
Interestingly I recompiled the code with no parallel feature i.e. just ./configure instead of ./configure --enable-mpi and then re-ran the Quick folder case. It did produce the plots. Then I ran the rotating airfoil case and it also produced the plots. Finally I ran my particular case and it also dumped the plot files. However, it is sad as it is taking way too longer to process on a single core as compared to what I can do with multi-cores. I wish some one can attend to this unique problem ASAP. Thanks :)

**Comment by talbring** [comment]
If you run the code with enabled mpi support SU2_CFD will only write the restart files. You need to use SU2_SOL to convert them to .vtk. Therefore simply copy the restart_flow.dat to solution_flow.dat and run SU2_SOL. Or you could just use the parallel_computation.py script that does this automatically.

**Comment by jehanz** [comment]
Thank you so much


Jehan



Sent from Yahoo Mail on Android
