### ISSUE TITLE
TNE2 + O2 gas model error

### ISSUE THREAD

**Issue by hlkline** [su2code/SU2#175]
Tne2 using O2 gas model has a memory bug. N2 model as given in the TestCases folder works, but O2 model give bad_alloc or segfault before starting solver. 

Thanks to:
http://www.cfd-online.com/Forums/su2/147743-changing-gas-model-tne-tutorial-results-error.html#post546080

**Comment by hlkline** [comment]
Related/ maybe the same issue:
http://www.cfd-online.com/Forums/su2/157026-changing-gas-model-tne-results-error.html#post555971

**Comment by Lattanzio** [comment]
The problem is in the solver_direct_tne2 because when in the line 207 the Jacobian is initialize this causes bug. This bug it is caused by allocation an array in the matrix_structure.cpp in the line 227 because there is not free memory for allocating the matrix array

**Comment by paulhzhang** [comment]
which version are you using? Could have been updated by now.

**Comment by economon** [comment]
TNE2 solver deprecated and no longer in the source. Closing.
