### ISSUE TITLE
Addition of the eN transition model

### ISSUE THREAD

**Issue by RichRoos** [su2code/SU2#1763]
**Is your feature request related to a problem? Please describe.**
To continue the current work being done on different transition models, I am looking at the addition of the eN model for low-turbulence external aerodynamics as proposed by James G. Goder and Mark D. Maughmer ([10.2514/1.J052905](https://arc.aiaa.org/doi/10.2514/1.J052905)). This model incorporates a new transport equation to describe the growth of the maximum Tollmien-Schlichting instability amplitude in the presence of a boundary layer.  

I will open a new Pull Request to start working on this topic. If there are other groups working on this or planning on doing so, please let me know!

**Describe the solution you'd like**
This work will be set-up in the same way as the LM model is in [PR1751](https://github.com/su2code/SU2/pull/1751) (which was also generally speaking how I had set up my own LM transition implementation) to make sure merging in a later stage will be easier.

**Comment by pcarruscag** [comment]
#1765
