### ISSUE TITLE
Can we define FFD box with predefined control points in the mesh file?

### ISSUE THREAD

**Issue by CourageFruit** [su2code/SU2#177]
Is SU2 allow user to define the FFD box by predefined control points? For example define the FFD_CORNER_POINTS,FFD_CONTROL_POINTS in the .su2 file and let SU2_DEF to calculate the FFD_SURFACE_POINTS.

**Comment by demanosalvas** [comment]
Hey CourageFruit , 

Would you mind posting this question on the Forum?
http://www.cfd-online.com/Forums/su2/

David

**Comment by CourageFruit** [comment]
Hi David,

I've posted it on the Forum, and looking forward to get your replay.
