### ISSUE TITLE
Allow massflow outlet

### ISSUE THREAD

**Issue by taalf** [su2code/SU2#180]
Hello,
In STAR-CCM+, it's enough to put an outward flow direction on a "mass flow inlet" condition to have a mass flow _outlet_.
I tried this with SU2 but the result was not expected (the mass flow was simply not the desired one).

**Comment by fpalacios** [comment]
This is an interesting capability that we ( or you :-) ) can easily add to SU2 (feel free to work on this. As you know, mass flow outlet is not typically the same as the inlet (bleeding, primary and secondary flow paths, fuel, etc). That is the reason why, based on my experience, in practical applications we prefer to provide total pressure and temperature from the engine deck. If you are interested, the new Actuator Disk boundary condition preserves the mass flow (you just need to specify the thrust).
