### ISSUE TITLE
mass flow + temperature

### ISSUE THREAD

**Issue by taalf** [su2code/SU2#181]
Hello,

I wanted to put a given mass flow and given temperature at an inlet.
Here is the thread: http://www.cfd-online.com/Forums/su2/151385-mass-flow-inlet-given-temperature.html

My workaround was 1) to estimate the pressure (eg. p = p_inf), then 2) to use the perfect gas equation to get the density:
p = rho . Rs . T     =>     rho = p / Rs / T
, thanks to which I could 3) get the velocity:
v = mass_flow / rho / S

Thanks to this, and because my case was quite simple, I could have somehow the desired temperature at my inlets.

I think, though, that it would be nice to estimate the local pressure at each iteration, for example by averaging it on the boundary, so as to update the inlet density & velocity.

**Comment by hlkline** [comment]
The boundary conditions are implemented in SU2_CFD/src/solver_direct_mean.cpp
aka, CEulerSolver::BC_Inlet 
If you (or anyone else viewing this issue) would like to implement a new inlet condition, that's a good place to start.
