### ISSUE TITLE
SU2 is missing documentation for slope limiters 

### ISSUE THREAD

**Issue by kamo6346** [su2code/SU2#1823]
**Is your feature request related to a problem? Please describe.**
Under the User's Guide, there are no direct explanations of the different slope limiters available to the user, or what solvers they apply to. I think that information on this topic in the documentation would be extremely helpful to a new user in understanding the differences between the available limiters and their respective strengths/weaknesses. There exists an [open pull request](https://github.com/su2code/su2code.github.io/pull/83/commits/4dcff98256e61d9d478e5af677859cbcfc6c80f1) within the documentation repo that starts this idea. However, it is incomplete and contains very little new information. 

**Describe the solution you'd like**
We would like to contribute more to this idea. Specifically, we would like to add

- A description of why slope limiters are used in a FVM formulation. This can explain the concept of Total Variation Diminishing methods, monotonic schemes, and 2nd order accuracy requirements. 
- Mathematically describe the limiters available to the user in SU2. This will include a brief discussion of their properties (e.g., diffusivity, tunable parameters) and potential Sweby plots. 
- An empirical comparison of the available limiters on a test problem(s). One problem that was considered was the laminar cylinder, or the viscous wedge cases. The flowfield colored by the limiter value can be shown to the user. 

**Describe alternatives you've considered**
N/A

**Additional context**
This issue ticket is part of an open-source community contribution assignment in our graduate studies "Numerical Solutions to Partial Differential Equations". Our team is comprised of four graduate students: Thomas Calascione (@tomtom252525) Grant Norman (@gnorman7), Kal Monroe (@kamo6346), Mitch Wall (@mitchwall85). Our academic research is highly coupled with CFD and numerical methods. For this reason, we chose SU2 as a community we wished to contribute to. 

A secondary goal of this project is to familiarize ourselves with the workings of an open-source community. These include issue submission, pull-requests, and code reviews. Please let us know of any suggestions/comments on this, as we plan to begin work on this immediately and would like this contribution to be useful to the SU2 community.

**Comment by pcarruscag** [comment]
Hi, welcome to SU2, we certainly need help with documentation.
Feel free to pick up the pull request you mentioned (I know from the author that he doesn't have time right now to finish it), I believe I left some comments there, or your team can also start your own PR.
I suggest you start with the basics of just describing what options are available and providing some references for them, before diving into comparisons which can be a lot more work.

We have developer meetings next Tuesday at 10am PT and then Wednesday (2 weeks from now) at 4pm CET, and so on, alternating every week. Feel free to join https://meet.jit.si/SU2_DevMeeting
