### ISSUE TITLE
How can I debug SU2

### ISSUE THREAD

**Issue by zhang-qiang-github** [su2code/SU2#1832]
**Is your feature request related to a problem? Please describe.**

I want to look into `SU2` source code when running an experiment. But, I am frustrated that I can not find a solution. The provide demo is running the code by commond line. But, for commond line, how can I debug it?

**Describe the solution you'd like**

1. I hope `SU2` could provide a solution to build source code by `CMakeLists.txt` and `visual studio`, because `visual studio` is widely used. 

2. Could `SU2` provide an explanation about how to call `SU2` from compiler rather than command line? `VS code`  or `Visual studio` is OK.

Any suggestion is appreciated~~~

**Comment by pcarruscag** [comment]
This is not a feature SU2 developers can implement.
