### ISSUE TITLE
How to generate the su mesh file?

### ISSUE THREAD

**Issue by zhang-qiang-github** [su2code/SU2#1833]
**Is your feature request related to a problem? Please describe.**

Currently, I can segment a aorta vessel mask. How can I convert it to the mesh file?

**Describe the solution you'd like**

I can generate the surface `(vtkPolyData)` by `vtk`. Is there any tool can convert `vtkPolyData` to `su` file?

Or is there any tool can convert a 3D mask to `su` file?

**Comment by bigfooted** [comment]
There are no publicly available tools to directly convert vtkpolydata to an su2 file, you'll have to write the connectivity and point information to a file yourself, this is easy when you are e.g. in paraview or in python. You also need to write the boundary surfaces and connectivity information as separate entities. You can also look into the capabilities of meshio, which is a very good python library with support for many mesh types. 

You could also try to export your data as cgns data and read a cgns file directly in su2.
