### ISSUE TITLE
Warnings SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#1916]
*If this is a general question or difficulty building/using the code, please open a "Discussion" instead.*

**Describe the bug**
Not really a bug, but compiler warnings that can be avoided easily. In the file SU2_CFD/include/numerics/NEMO/NEMO_diffusion.hpp, class  CAvgGradCorrected_NEMO, the variables iDim and iVar are defined, which are used as counters as far as I can tell. First of all I don't think such variables should not be defined as member variables of a class, but if you do then don't define variables with the same name in the implementation of the member functions. In this case in SU2_CFD/src/numerics/NEMO/NEMO_diffusion.cpp. It is causing a lot of compiler warnings in combination with the Intel compiler, which makes it more difficult to see the warnings that actually matter.

If you want I can fix this, but maybe it is better if somebody with a NEMO background does it.

**Bug report checklist**
*Please make sure that you have followed the checklist below, many common problems can be solved by:*

- [X] Consulting the build instructions (https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/).
- [X] Looking for similar problems on GitHub or CFD-Online (https://www.cfd-online.com/Forums/su2/).
- [X] Updating to the newest version of SU2 (either develop, master, or the pre-built executables https://su2code.github.io/download.html).

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - C++ compiler and version: Intel compilers version 19.1.0.166
 - MPI implementation and version: Intel MPI
 - SU2 Version: develop branch

**Comment by WallyMaier** [comment]
Hi @vdweide,
Thanks for catching this,  I've almost exclusively used GCC compiler so this slipped through the cracks.  Ill go ahead and fix this.
