### ISSUE TITLE
Paraview multiblock filename differs from other volume output filenames.

### ISSUE THREAD

**Issue by danielmayer** [su2code/SU2#1928]
The filename of the Paraview multiblock is set to the case name / config filename:

https://github.com/su2code/SU2/blob/b1e7e7bb7229152f26e5035c0eae70804fee5ca2/SU2_CFD/src/output/COutput.cpp#L562

For all other volume outputs, the filename is specified with 'VOLUME_FILENAME' in the config file. See e.g. the Paraview XML filename:

https://github.com/su2code/SU2/blob/b1e7e7bb7229152f26e5035c0eae70804fee5ca2/SU2_CFD/src/output/COutput.cpp#L508

This is counter-intuitive and the user is not able to change the multiblock filename in the config file. Is there a reason behind this or can we align that by using the volume filename for multiblock as well?

**Comment by pcarruscag** [comment]
We can change it :+1:

**Comment by danielmayer** [comment]
Awesome! I will file a pull request.
