### ISSUE TITLE
class CNeurNet has no member named totalNumParameters: Missing 'int totalNumParameters'

### ISSUE THREAD

**Issue by pdpdhp** [su2code/SU2#197]
It seems `int totalNumParameters;` has been deleted from the line #205 in _numerics_machine_learning_ header which brings up the error: `‘class CNeurNet’ has no member named ‘totalNumParameters’` in version _4.0.1_ while configuring the suit with Jsoncpp options. I just add it back.

**Comment by economon** [comment]
CNeurNet deprecated. Closing.
