### ISSUE TITLE
I get negative drag coefficient when I set the REF_DIMENSIONALIZATION

### ISSUE THREAD

**Issue by HL-ZHI** [su2code/SU2#1975]
*If this is a general question or difficulty building/using the code, please open a "Discussion" instead.*

**Describe the bug**
To be honest, I haven't care about the dimensionalization since today I got a negative CD for a very very simple case. The case setup is:
1. NACA0012 airfoil, structured grid
2. Freestream condition: Re=1E6, AoA=5, Mach=0.1
3. Solver: RANS with S-A model, Roe upwind scheme.

Every other thing can be default. The drag coefficients I got are:
REF_DIMENSIONALIZATION=DIMENSIOAL:                                   0.005
REF_DIMENSIONALIZATION=FREESTREAM_VEL_EQ_MACH:         -0.025

It is interesting. I am gonna check the code in CEulerSolver::SetNondimensionalization.

**Desktop (please complete the following information):**
 - OS: WINDOWS & Ubuntu
 - C++ compiler and version: [e.g., g++ (GCC) 4.8.5]
 - MPI implementation and version: [e.g., OpenMPI 4.1.3]
 - SU2 Version: 7.3.1 & 7.5.1

**Comment by bigfooted** [comment]
You have a negative mach number, that doesn't sound right.

**Comment by HL-ZHI** [comment]
> You have a negative mach number, that doesn't sound right.

I'm sorry. My mach number is 0.1. When I set REF_DIMENSIONALIZATION=FREESTREAM_VEL_EQ_MACH, I got CD=-0.025.

**Comment by HL-ZHI** [comment]
I found ENTROPY_FIX_COEFF is of great influence on the CD, I got the negative CD when it is small.
