### ISSUE TITLE
Parallel Execution Changed?

### ISSUE THREAD

**Issue by RcktMan77** [su2code/SU2#2]
I just (08/23/2013 @ ~12:30p.m. PDT) pulled over the latest changes via git.  After re-compiling, and launching a parallel job (OM6 Turbulent Wing Test Case) with the parallel_computation.py script, SU2 seems to launch 4 serial, duplicate jobs rather than 1 parallel job on 4 cores.

**Comment by hlkline** [comment]
This indicates that the code has not been successfully compiled for parallel. 
I recommend checking the configuration and recompiling. 
For a faster response and information on how others have troubleshot configuration problems, please see our forum at http://www.cfd-online.com/Forums/su2/
