### ISSUE TITLE
Incompressible solver not producing mean volume output

### ISSUE THREAD

**Issue by a3adam** [su2code/SU2#2044]
The incompressible solver does not accept the TIME_AVERAGE output field:

`  Info: Ignoring the following volume output fields/groups:`  
`    TIME_AVERAGE`  
`  Volume output fields: COORDINATES, SOLUTION, PRIMITIVE, RESIDUAL, VORTEX_IDENTIFICATION, MPI, MESH_QUALITY`  

whereas the compressible solver accepts the field and prints mean volume variables:

`Volume output fields: COORDINATES, SOLUTION, PRIMITIVE, RESIDUAL, VORTEX_IDENTIFICATION, MPI, MESH_QUALITY, TIME_AVERAGE`

**Desktop:**
 - OS: Linux (CentOS 7.9)
 - C++ compiler and version: g++ (GCC) 12.1
 - MPI implementation and version: OpenMPI 4.1.4
 - SU2 Version: v7.5.0

**Comment by pcarruscag** [comment]
It will be fixed in develop branch by #2047
