### ISSUE TITLE
ninja build gives hdf5 error

### ISSUE THREAD

**Issue by albenstein** [su2code/SU2#2058]
**Describe the bug**
I tried to install SU2 from source on HPC system, but on ninja install step it gives error about hdf5 like on attached file.
`(base) [root@headnode SU2_v7.5.1]# ./meson.py build -Denable-autodiff=true -Denable-directdiff=true -Dwith-mpi=enabled -Dwith-omp=true --prefix=/shared/apps/SU2/7.5.1/`
`(base) [root@headnode SU2_v7.5.1]# ./ninja -C build install`

**Bug report checklist**
*Please make sure that you have followed the checklist below, many common problems can be solved by:*

- [x] Consulting the build instructions (https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/).
- [x] Looking for similar problems on GitHub or CFD-Online (https://www.cfd-online.com/Forums/su2/).
- [x] Updating to the newest version of SU2 (either develop, master, or the pre-built executables https://su2code.github.io/download.html).

**Desktop (please complete the following information):**
 - OS: [e.g., Linux (Redhat 7.9)]
 - C++ compiler and version: [e.g., g++ (GCC) 8.5.0]
 - MPI implementation and version: [e.g., OpenMPI 4.0.3]
 - SU2 Version: [e.g., v7.5.1]

[ninja.txt](https://github.com/su2code/SU2/files/11848633/ninja.txt)

**Comment by pcarruscag** [comment]
Try going to `externals/cgns/hdf5/meson.build` and in line 19 replace 'cpp' with 'c'

**Comment by albenstein** [comment]
I forgot to call miniconda eval bash.hook. I re called ninja and got this error:
[ninja.txt](https://github.com/su2code/SU2/files/11849593/ninja.txt)

**Comment by pcarruscag** [comment]
ok please try the same change in `externals/cgns/meson.build`

**Comment by albenstein** [comment]
@pcarruscag It fixed installation issue.
Thank you.

**Comment by pcarruscag** [comment]
Thanks for testing, we'll put the fix in the new version
