### ISSUE TITLE
"FFD_TWSIST_2D" method doesn't work

### ISSUE THREAD

**Issue by Zcaic** [su2code/SU2#2080]
I use ”FFD_TWSIST_2D“ method to deform 2D_airfoil, but the defomed ffd_box (ffd_boxes_def_0.vtk) is name as the original FFD_BOX, then I find the source code about "SetFFDTwist_2D" in **"SU2/Common/src/grid_movement/CSurfaceMovement.cpp"**.
![微信截图_20230715023935](https://github.com/su2code/SU2/assets/70070459/5ea25d96-0f64-4168-af99-ea9a2baa3181)
It doesn't seem to be defined yet

**Desktop (please complete the following information):**
 - OS: [e.g., Arch (WSL )]
 - C++ compiler and version: [e.g., g++ (GCC) 13]
 - MPI implementation and version: [e.g., OpenMPI 4.1.5]
 - SU2 Version: [e.g., v7.5.1]

**Comment by pcarruscag** [comment]
Thank you I will remove the option, I don't know what twist is supposed to mean in 2D

**Comment by Zcaic** [comment]
Maybe twist in 2D means the whole 2D FFD_BOX rotates **DV_VALUE** around (x_Orig, y_Orig).

**Comment by pcarruscag** [comment]
FFD_ROTATION should work for that
