### ISSUE TITLE
Running Optimization with FFD and Periodic Boundaries

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#210]
I noticed that it is not possible to run an optimization of a case where you have FFD design variables and periodic boundaries defined. It seems like that SU2_DEF is not correctly writing out the periodic information to the new mesh file. I think the problem is that there are different routines responsible for writing the FDD information and the periodic information.

**Comment by salvovitale** [comment]
@economon if I am not wrong, you used FFD with periodic boundary conditions for the adjoint optimization of the unducted fan. It might be that with the subsequent developments on that part of the code some generality has been lost there. Any comment on that?

**Comment by talbring** [comment]
I should add that I was running a 2D case. SU2_CFD fails in the second optimizer iteration in the setup of the periodic boundaries due to wrong information in the new mesh file.

**Comment by talbring** [comment]
Problems solved in #242 .
