### ISSUE TITLE
Add more content to history.csv file

### ISSUE THREAD

**Issue by lcheng9** [su2code/SU2#2138]
**Is your feature request related to a problem? Please describe.**
*No time and min/max value are available in the history file, which makes the post-processing module difficult to handle the unsteady results.*

**Describe the solution you'd like**
*Add a "Time" column in the history.csv file, this column shows the simulation time for the current "Time_Iter". Add minimum and maximum values for all available result quantities, such as pressure, velocity, density, etc.*

**Describe alternatives you've considered**
*An alternative way to get the min/max values is by reading each flow_.vtu result file and it is expensive for a many-step unsteady analysis. There seems no way to have the "Time" quantity for now.*

**Additional context**
*An example of the columns in history.csv is:*
`"Time_Iter", "Time", "Outer_Iter", "Inner_Iter",   "Rho_min", "Rho_max", "RhoU_min", "RhoU_max", ......, "rms[Rho]", "rms[RhoU]",  "rms[RhoV]", "rms[RhoE]", "rms[nu]" `

**Comment by bigfooted** [comment]
You can show all available options for screen/history output by running `SU2_CFD -d config.cfg`

**Comment by pcarruscag** [comment]
See the docs https://su2code.github.io/docs_v7/Custom-Output/

**Comment by KillingVector** [comment]
Hello! I seem to remember that it used to be possible to get angle of attack in the history file? Is this still possible? I would like to be able to just pull the angle of attack out of the history file, along with the aero coeffs.
Context:
I have looked through the custom output document and the reference config file, and (perhaps I am secretly blind), but there does not seem to be a simple output group for it.
Reason I need it: performing analysis for fixed Cl, so angle of attack is useful information.

At the moment I am getting probed data:
```
CUSTOM_OUTPUTS='m_vel_x : Macro{VELOCITY_X};\
                m_vel_y : Macro{VELOCITY_Y};\
                vel_x1: Probe{$m_vel_x}[-15, -15];\
                vel_y1: Probe{$m_vel_y}[-15, -15]'
```
And just getting the tan(y/x) of the probed values for angle. This works well enough.
The other option I have is stripping the angle of attack out of the forced breakdown file, would prefer to not do, but can.

Please and thank you (:
