### ISSUE TITLE
platform.processor() in TestCase.py

### ISSUE THREAD

**Issue by TripleRider** [su2code/SU2#2159]
SU2/TestCases/TestCase.py uses `platform.processor()` which returns `i386` on an Intel Core i7 MacBookPro running mac OS 11.7. This just differentiates between Power PC vs Intel processors and not necessarily between 32-bit and 64-bit architectures. This causes all the tests in the test suite to be skipped even though the machine is 64-bit. 

`platform.machine()` returns `x86_64` allowing the tests to run from the TestCase.py script. 

Python documentation (3.12.0) also notes that many platforms do not provide the information for `platform.processor()` or simply return the same value as for `platform.machine()`.

Suggestion is to replace `platform.processor()` with `platform.machine()`.

**Comment by pcarruscag** [comment]
Thank you, do you know what that returns for ARM? That's the distinction we are trying to make.

**Comment by TripleRider** [comment]
I haven't been able to try this myself but from what I have read in a few resources online, it should return `arm64' on macOS and `aarch64' otherwise for ARM.

**Comment by TripleRider** [comment]
Verified on an Apple M2 hardware that `platform.processor()` returns `arm` and `platform.machine()` returns `arm64`. 
I think possibly even outside of the `platform.processor()` vs. `platform.machine()` discussion, the TestCase.py script currently might not be able to handle all the different values returned by MacOS or Windows systems.

**Comment by pcarruscag** [comment]
Thanks for checking that, do you think you can open a PR? Then we can check if it works in our ARM regression tests.

**Comment by TripleRider** [comment]
Yes, I will open a PR.
