### ISSUE TITLE
bug about the config_gui.py

### ISSUE THREAD

**Issue by chengdi123000** [su2code/SU2#216]
When I run config_gui.by, it goes wrong

Traceback (most recent call last):
  File "./SU2_PY/config_gui.py", line 314, in <module>
    option_data = prepare_data()  
  File "./SU2_PY/config_gui.py", line 300, in prepare_data
    option_list = parse_config(config_cpp, config_hpp)
  File "/home/ubuntu/SU2/SU2_PY/parse_config.py", line 84, in parse_config
    thisval = s2.split('"')[1]
IndexError: list index out of range

When it reads an empty line, split() returns a list with one element. So the index [1] goes beyond the range.

---

My OS:
Linux ip-172-31-10-55 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

SU2 version:
4.0.2

---

p.s. Another problem is I have to install wxpython to run config_gui.py. But I think it would be better to use Tkinter which is distributed with python. So it would be helpful to run in cluster environment.

**Comment by erangit** [comment]
A simple workaround would be to add an if line before the split:
Line 84 of parse_config.py
if np.size(s2) > 1:
          thisval = s2.split('"')[1]
Yes, it requires also 
import numpy as np
at the beginning of the script.
Now it runs with no error message but no output produced.
Also config_gui.py is running, but it opens an empty window,
so apparently this is not good enough

best,
Eran
