### ISSUE TITLE
Fix use of `'U'` mode in Python `open()` function

### ISSUE THREAD

**Issue by TripleRider** [su2code/SU2#2170]
`serial_regression.py` errors out while running `TestCases/cont_adj_euler/naca0012` test due to the use of `'U'` mode in `fromlines = open(fromfile, 'U').readlines()` in `TestCase.py`.

`'U'` mode has been deprecated for a while and removed from latest Python versions.

**Comment by pcarruscag** [comment]
Thanks, open a PR please :)

**Comment by bigfooted** [comment]
fixed in #2171
