### ISSUE TITLE
Compiling SU2 without HDF5

### ISSUE THREAD

**Issue by Cadair** [su2code/SU2#219]
Hello,

I am trying to compile SU2 on the central HPC facility at Sheffield University. I am running into problems with SU2 trying to link against HDF5 or ZLIB when I would rather it did not.

When I try and not build against HDF5 I use the following script:
https://gist.github.com/385ee9c8589fd9146ade

and get this output:
https://gist.github.com/8fb4ab586ea12d9c28b2

which can basically be summed up as it is configured to not build with HDF5 (it says this in the configure output), but then errors because it can not link against the HDF5 lib.

If I try and build SU2 against the version of HDF5 we have compiled on the cluster it will then error because that library was not built with ZLIB support. Am I doing something wrong to disable linking against HDF5 or will I have to recompile HDF5 with ZLIB?

Thanks

rcgsheffield/iceberg_software#159

**Comment by hlkline** [comment]
Compilation tips, and a larger base of people with experience using SU2 with cgns/hdf5, can be found at:
http://www.cfd-online.com/Forums/su2/

Your script includes '--with-CGNS...', and CGNS requires the HDF5 library.  You will either need to disable the CGNS options or recompile the HDF5 library. Either that or you need a 'make clean' somewhere in your script to make sure that you are not using compiled files from a previous build, but it looks like that would be taken care of by the file structure created by that script.
In any case, if after fixing that you still have problems, please check the forum linked above where someone else may have already encountered and solved a similar compilation issue.

**Comment by Cadair** [comment]
@hlkline Thanks for the tip about CGNS and HDF5, I couldn't see anywhere that the CGNS library needed HDF5 with ZLIB support. Perhaps that is something the configure script should catch?
