### ISSUE TITLE
Bug in HLLC Jacobian calculation

### ISSUE THREAD

**Issue by ashwaniassam** [su2code/SU2#2198]
https://github.com/su2code/SU2/blob/60270690cd749bd190e16b4c34cf724c42edbeb1/SU2_CFD/src/numerics/flow/convection/hllc.cpp#L543C3-L543C3

As per the https://www.sciencedirect.com/science/article/pii/S0021999197957934 (original paper), multiplying the Jacobian with \kappa = 0.5 is not right. It is leading to non-convergence. 

Further,  dpStar_dU[iVar] calculations need to be relooked. As per the original paper, density should be at "j" when it is being used at "i". Though I have not seen a major difference, but currently testing the same more for strong shock cases.

**Comment by pcarruscag** [comment]
You are right we fixed that for the Roe scheme at some point, if you have time open a PR please.

**Comment by ashwaniassam** [comment]
Sure, will try. Mostly will ask a student, as I am not quite familiar to
GitHub working.
