### ISSUE TITLE
Using surface deformation to produce pitching on a surface with two or more markers results on inaccurate displacements on shared nodes between markers

### ISSUE THREAD

**Issue by Cnevesg** [su2code/SU2#2215]
I've been simulating a NACA0012 airfoil with a rough upper surface and a smooth lower surface while pitching. To induce the forced motion in this case, I'm using the SURFACE_MOVEMENT=DEFORMING with MARKER_MOVING= (UPPER, LOWER, TE) where UPPER and LOWER have different roughness. These are three different markers along the airfoil surface, naturally connected, but it seems that once the deformation to mimic forced pitching starts, the shared nodes between these markers seem to be displaced twice. It seems that this could be a result of separate displacements of each marker so that the node that's shared is being applied the deformation twice.

An example can be observed in the attached files. These correspond to the shared leading edge, and the blunt trailing edge.

![LE](https://github.com/su2code/SU2/assets/160247579/9e515d0f-cd37-440d-8280-738b97670ff0)
![Screenshot 2024-02-16 145351](https://github.com/su2code/SU2/assets/160247579/a9df8a33-5bd0-4944-a8e2-c5cb49817685)
![TE dt 8 lower](https://github.com/su2code/SU2/assets/160247579/28d9933f-8bd3-4b9d-9be3-b53fa4a2974f)
![TE dt 8](https://github.com/su2code/SU2/assets/160247579/752c7826-0751-452e-aa92-79bcca628327)

Desktop:
-OS Windows 11 - Ubuntu WSL
-SU2 version 8.0

**Comment by pcarruscag** [comment]
Can you attach the entire case so we can replicate, makes it easier to fix the bug that way.

**Comment by Cnevesg** [comment]
Sure, you'll find attached the .cfg file, the mesh, and the two solution_file required for the dual-time-stepping solver to start.

[Uploading Pitching_Airfoil_Bug.zip…]()

**Comment by Cnevesg** [comment]
[Pitching_Airfoil_Bug.zip](https://github.com/su2code/SU2/files/14313854/Pitching_Airfoil_Bug.zip)

**Comment by pcarruscag** [comment]
Thanks, I should fix it this weekend.

**Comment by pcarruscag** [comment]
I opened a PR with the fix, you also have a problem in your config, the motion of the trailing edge is not consistent with the other surfaces (the amplitude has too many zeros)
