### ISSUE TITLE
Restart file interpolation sporadically hangs with mpi

### ISSUE THREAD

**Issue by bigfooted** [su2code/SU2#2225]
When restarting a case with a different mesh (for instance restarting with a finer mesh, using the restart file of a coarser mesh), the restart file is interpolated onto the new mesh.
When this is done in parallel, sometimes the procedure hangs. Problem is that it not always occurs. 

Some issues were already fixed in #1999 

I will investigate further.

**Comment by pcarruscag** [comment]
Do you have examples?

**Comment by pcarruscag** [comment]
If there are no examples I think we can close this.
