### ISSUE TITLE
Question regarding Description of available screen/history output fields

### ISSUE THREAD

**Issue by lei866** [su2code/SU2#2236]
Hi!
I am currently testing the case inside [TestCases/disc_adj_turbomachinery/transonic_stator_2D](https://github.com/su2code/SU2/tree/master/TestCases/disc_adj_turbomachinery/transonic_stator_2D)
When I use the command 
```shell
SU2_CFD -d transonic_stator.cfg
``` 
The output contains Description information that seems inconsistent with the previous names. Could there be an error here? 
![image](https://github.com/su2code/SU2/assets/70613699/714d56eb-cdd3-463d-a48e-538792c753c1)

Examining the source code, I found that the issue arises at line 4054 in the [CFlowOutput.cpp](https://github.com/su2code/SU2/blob/master/SU2_CFD/src/output/CFlowOutput.cpp) file.

This is my first time asking a question here, and I really appreciate receiving your response.

**Comment by joshkellyjak** [comment]
Resolved in #2209
