### ISSUE TITLE
SU2 V8 missing functions in PythonWrapper

### ISSUE THREAD

**Issue by Igarizza** [su2code/SU2#2263]
Dear SU2 community,
in the v7.5 there were several useful functions in the pysu2 which I can't find anymore in V8:

- Get_DragCoeff
- Get_LiftCoeff
- Set/GetTemperature - now it is only  SetMarkerCustomTemperature
Is there any reason why these functions are removed or there is another way to get Lift and Drag coeff  / Get Temperatures in python? 

Thank you for your support!

**Comment by pcarruscag** [comment]
You can now access any output, please look at the examples in TestCases/pywrapper
