### ISSUE TITLE
Muscl reconstruction for flow variables applied twice when scalar_upwind  scheme is used

### ISSUE THREAD

**Issue by Cristopher-Morales** [su2code/SU2#2297]
Hi all,

It seems that in the CScalarSolver.inl, in the upwind residual line 209, we are reconstructing the flow variable again when the SCALAR_UPWIND scheme is used. 

![image](https://github.com/su2code/SU2/assets/98025159/fb52c574-0dc2-49e1-9d29-e18b31a91bf7)

if we use MUSCL_FLOW=YES and the CONV_NUM_METHOD_SPECIES= SCALAR_UPWIND (also for turbulence models), the flow variables are reconstructed twice. 

Please let me know if I am not understanding correctly this piece of code.

Thank you so much in advance.

**Bug report checklist**
*Please make sure that you have followed the checklist below, many common problems can be solved by:*

- [ ] Consulting the build instructions (https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/).
- [ ] Looking for similar problems on GitHub or CFD-Online (https://www.cfd-online.com/Forums/su2/).
- [ X] Updating to the newest version of SU2 (either develop, master, or the pre-built executables https://su2code.github.io/download.html).

**Comment by pcarruscag** [comment]
That's correct. The reconstruction is never stored.

**Comment by Cristopher-Morales** [comment]
Thanks!!
