### ISSUE TITLE
Option for Joule Heating not in configuration file

### ISSUE THREAD

**Issue by deshpan2** [su2code/SU2#230]
I am trying to include Joule heating as a source term.
Although the source term for Joule heating is defined in numerics_structure.hpp, unlike other source terms (like Wind Gust), it is not allocated in definition_structure.cpp. Also its option is not present in either the config_structure.cpp file or the config_template.cfg file.
Is any modification of code required?

Thanks.

**Comment by hlkline** [comment]
Thanks for identifying this
It sounds like modifying the code will be required to make that option work. Since you have already identified the places in the code which need to be modified, are you interested in making those modifications yourself?
If so, you will find information on how to get started in the wiki at: https://github.com/su2code/SU2/wiki/Developer-Docs

**Comment by deshpan2** [comment]
I am a new developer so I might need some help. I have added some expressions based upon the discussion on cfdonline: http://www.cfd-online.com/Forums/su2/129165-add-source-terms-user-defined-boundary-condition-set-up-transient-simulation.html.
Based upon that discussion, I have allocated the already defined class in definition_structure.cpp:
numerics_container[iMGlevel][FLOW_SOL][SOURCE_FIRST_TERM] = new CSource_JouleHeating(nDim, nVar_Flow, config);

Also, I have referred to the implementation of source term of Wind Gust. To get started, I am trying to implement a Yes/No option to include Joule Heating in the configuration file. I have added the following statements:
config_structure.inl: inline bool CConfig::GetJoule_Heating(void) {return Joule_Heating}
config_structure.hpp: a flag: Joule_Heating and bool GetJoule_Heating(void)
config_structure.cpp: addBoolOption("JOULE_HEATING", Joule_Heating, false)

On compiling, I get an error stating that "JOULE_HEATING" is an invalid option name. Please let me know where I am going wrong.
Thanks!

**Comment by talbring** [comment]
Sorry to ask this, but where do you find the CSource_JouleHeating class defined in numerics_structure.hpp ?

**Comment by deshpan2** [comment]
Its starts from line 4618 in that file. I explored the code using its doxygen documentation.

**Comment by talbring** [comment]
Unfortunately, this doxygen documentation is quite old (based on version 3.0). In the meantime this Joule heating source implementation was removed.

**Comment by hlkline** [comment]
To see doxygen documentation for any version, download the Documentation repository, go to the Doxygen folder, and compile there. 
The doxygen input file looks for the code in ../../SU2, so the folder structure should be something like:
home/SU2/
home/Documentation/Doxygen

**Comment by deshpan2** [comment]
Thanks a lot for letting me know! I will look into it

**Comment by hlkline** [comment]
It appears to me that this issue can be closed now; please feel free to reopen if you disagree.
