### ISSUE TITLE
New in version 8 in docs 

### ISSUE THREAD

**Issue by stefano2734** [su2code/SU2#2361]
**Is your feature request related to a problem? Please describe.**
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

Now Is Version 8.x

See https://su2code.github.io/docs_v7/Guide-to-v7/

**Describe the solution you'd like**
*A clear and concise description of what you want to happen.*

guide to v8 

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by pcarruscag** [comment]
The page is still valid when migrating from pre v7 to post v7 versions

**Comment by stefano2734** [comment]
Guide new in 8 should be added like new in 7 before.

**Comment by pcarruscag** [comment]
We have not found that to be necessary because the interface is mostly unchanged, but if you are aware of anything please open a pull request to the website repository with updates, we welcome all contributors.
