### ISSUE TITLE
SU2 not getting all external dependencies

### ISSUE THREAD

**Issue by nikishe** [su2code/SU2#2363]
*If this is a general question or difficulty building/using the code, please open a "Discussion" instead.*

**Describe the bug**
This might be linked to issue #2086
I am  building SU2 with both Terminal and using  a build system called EasyBuild.
On terminal everything went seamlessly. The issue is on EasyBuild. The meson configs are not pulling in the external files. I had to clone it recursively.

None of the following options were activated in my tests, so the external files should have been added 

```
--no-codi         do not download own copy of CoDiPack
  --no-medi         do not download own copy of MeDiPack
  --no-opdi         do not download own copy of OpDiLib
  --no-mpp          do not download own copy of Mutationpp
  --no-coolprop     do not download own copy of CoolProp
  --no-mel          do not download own copy of MEL
  --no-mlpcpp       do not download copy of MLpCpp
```

**HPC
 - OS:Centos7
 - C++ compiler and version: [e.g., g++ (GCC) 12.2]
 - MPI implementation and version: [e.g., OpenMPI 4.1.4]
 - SU2 Version: 7.0.6

**Comment by pcarruscag** [comment]
If you want to use the packages provided by that build system use the --no-* options and point to the packaged provided by the build system.
