### ISSUE TITLE
Incorrect Descriptions for enable-mlpcpp and enable-gprof in Meson Options

### ISSUE THREAD

**Issue by kjrstory** [su2code/SU2#2366]
The descriptions for the options enable-mlpcpp and enable-gprof in the meson_options.txt file seem to be swapped.

```text
option('enable-mlpcpp', type : 'boolean', value : false, description: 'enable profiling through gprof')
option('enable-gprof', type : 'boolean', value : false, description: 'enable MLPCpp support')
```

**Comment by pcarruscag** [comment]
Thanks, can you open a pull request to set it right?

**Comment by EvertBunschoten** [comment]
I set the descriptions to the right option in #2369

**Comment by EvertBunschoten** [comment]
The descriptions are now set in the correct position after closing PR #2369
