### ISSUE TITLE
Potential memory leak in PyWrapper

### ISSUE THREAD

**Issue by HahsFilip** [su2code/SU2#2386]
*If a pysu2.CSinglezoneDriver is created repeateadly within a loop, in a member function, memory appears to leak out.*
**Describe the bug**
If the following simple code is run, with one of the example configuration files, memory leaks out. Adding python gc methods does not help.
```
from mpi4py import MPI
import numpy as np
import pysu2

class LeakTester:
    def __init__(self):
        self.comm = MPI.COMM_WORLD
        self.rank = self.comm.Get_rank()
    def leak_test(self):
        for i in range(1000):
        
            self.su2driver = pysu2.CSinglezoneDriver(f'spinning_cylinder.cfg', 1, self.comm)
            self.su2driver.Preprocess(0)
            self.su2driver.Run()
            self.su2driver.Output(0)
            self.su2driver.Postprocess()
            del self.su2driver
if __name__ == "__main__":
    test = LeakTester()
    test.leak_test()

```

**Bug report checklist**
*Please make sure that you have followed the checklist below, many common problems can be solved by:*

- [x] Consulting the build instructions (https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/).
- [x] Looking for similar problems on GitHub or CFD-Online (https://www.cfd-online.com/Forums/su2/).
- [ ] Updating to the newest version of SU2 (either develop, master, or the pre-built executables https://su2code.github.io/download.html).

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - C++ compiler and version: [e.g., g++ (GCC) 4.8.5]
 - MPI implementation and version: mpirun (Open MPI) 4.1.2
 - SU2 Version: Branch feature_fsi_python

**Comment by pcarruscag** [comment]
You have to call .Finalize(), see the other examples.
