### ISSUE TITLE
High metadata and file operations impacting HPC system stability due to SU2 simulation 

### ISSUE THREAD

**Issue by himakarganti** [su2code/SU2#2389]
While running SU2 on a HPC cluster, I ran into an issue where it is generating excessive loads on the file-system as identified by the HPC admins. They identified the following problem during runtime, which causes SU2 runs to overload the file system on the HPC as shown below: 

`openat(AT_FDCWD, "TargetCp_07752.dat", O_RDONLY) = -1 ENOENT (No such file or directory)`

The admins have suggested that somewhere in the program there's an open call in a try/catch that lacks a stat()=based guard to test if the file exists.

`/SU2/Install/directory/SU2_CFD/src/output/**CFlowOutput.cpp**
 
1811 /*--- Prepare to read the surface pressure files (CSV) ---*/
1812
1813 const auto surfCp_filename =
config->GetUnsteady_FileName("TargetCp", curTimeIter, ".dat");
1814
1815 /*--- Read the surface pressure file, on the first inner
iteration. ---*/
1816
1817 ifstream Surface_file;
1818 Surface_file.open(surfCp_filename);
1819
1820 if (!Surface_file.good()) {
1821 solver->SetTotal_CpDiff(0.0);
1822 SetHistoryOutputValue("INVERSE_DESIGN_PRESSURE", 0.0);
1823 return;
1824 }`

Instead of testing if the file exists, SU2 calls open and then the good() method to determine if it was successful or not. This is leading to the filesystem getting overloaded with potential HPC system instability as the file is not existing and is being accessed thousands of times each second.

Can someone please let me know how I can fix this issue to not have so many file operations for SU2 that cause filesystem problems and system instability?

**Comment by pcarruscag** [comment]
It seems like there is not a huge difference between using `open` and `stat` (and both seem super fast enough)
https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exists-using-standard-c-c11-14-17-c
Can you try commenting out the open command (and changing `if (!Surface_file.good()) {` to `if (true) {`) and recompiling the code before we invest more time optimizing this call?

**Comment by pcarruscag** [comment]
Closing since there was no follow-up for two weeks.
