### ISSUE TITLE
After restart segmentation fault in SU2_SOL

### ISSUE THREAD

**Issue by Bullnados** [su2code/SU2#240]
Hey,

i have here a little bigger testcase (3D pipe with 1.5 Mio cells). The solution_flow.dat filesize is ~265M.
First the flow.vtk was written perfectly allright.
After i restart the case, the flow.vtk wasn't written automaticly.
Also i tried to do manual with SU2_SOL but here i get all the time _Segmenation fault (core dump)_
after or while
"Merging solution in the Master node"

I tried it "local" on our  visualisation cluster and also on our HPC-Cluster with same error.
I'm using branch **feature_internalflow**

**Comment by talbring** [comment]
I guess you running it in parallel ? You can try to pull the newest changes (last commit was 10th of Feb.), there were some changes.

**Comment by Bullnados** [comment]
"Local" is 1 Thread, HPC i tried 1 thread and 2 threads wih same result.

Wanna check the changes next week, when im back in Lohr ;)
Best regards
Alex

**Comment by Bullnados** [comment]
Ok, now i have tried with new version. But same segmenation fault error

**Comment by Bullnados** [comment]
As u wish, i switched to Tecplot, but same error. After complete new calculation, the error was gone perhaps it was to small. If i can reproduce it, I reopen the issue here
