### ISSUE TITLE
Installation documentation inconsistant

### ISSUE THREAD

**Issue by DevonSimpson** [su2code/SU2#245]
A section of the Build From Source tab of the WIKI mentions the following: 

"For example, to configure SU2 for parallel calculations (i.e., with ParMETIS and MPI) along with CGNS and TecIO support and a high level of compiler optimization, the configure command might look like this (replace with specific paths on your system):

"$ ./configure --prefix=/path/to/install/SU2 --enable-mpi --with-cc=/path/to/mpicc 
--with-cxx=/path/to/mpicxx CXXFLAGS="-O3" --with-CGNS-lib=/path/to/CGNS/lib 
--with-CGNS-include=/path/to/CGNS/header"

Note that the actual configure call does not actually use TECIO as discribed in the paragraph leading up to the call.

**Comment by economon** [comment]
Ah, nice catch, Devon. You're right, we don't actually need to include the --enable-tecio flag, since the configure process will try to include it by default.

In your builds, did it find, compile, and link TECIO automatically for you?

**Comment by hlkline** [comment]
It looks to me like this was resolved; if not feel free to re-open.
