### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by gbaty** [su2code/SU2#246]
Is a python 3.x support planned or existing for SU2 ?
It is not so hard to make a code compatible with both version python 2 and 3 but only with recent version of each (2.7 and 3.5 for example). 
So my question is about python 2.x : what minimal version do you want to support ?

You can see a quick fix, only for config class for the moment, here: [gbaty/SU2/py2_and_py3_support](https://github.com/gbaty/SU2/tree/py2_and_py3_support)

**Comment by economon** [comment]
At the moment, we do not have any developers working to expand to Python 3.x. Like many other scientific packages, we have settled around Python 2.7. It can often be a challenge to get the correct versions of Python (including packages) onto clusters.

Are there particular features of Python 3+ that you would like to have or think would benefit SU2?

**Comment by gbaty** [comment]
I don't think there are particular feature of Python 3 that are necessary except to be able to use SU2 in python 3 environment (What I would like). 
I'd like to work on porting SU2 to python 3 but as I currently use only basic features of SU2 (getting start tutorial on desktop computer), it is hard to me to check that changes on python code works for all python2.7 version test cases. 
Sure #228 could be very useful for that.

**Comment by petebachant** [comment]
As @gbaty said, it's usually easy to support both. Many times it can be done with a simple

```python
from __future__ import division, print_function
```

at the top of each file, and tweaking the `print` and `import` statements. In my experience, the Anaconda (or miniconda) Python distribution makes it very easy to setup just about any version of Python you like on a cluster, since it's installed in the user's home directory by default. 

Most scientific packages (NumPy, SciPy, Matplotlib, Pandas) already support both 2.7 and 3.x within a single codebase. Python 3 is the future!

**Comment by fpalacios** [comment]
This could be a very interesting contribution! Please, feel free to work on this and create a push request to the developer release. SU2 is looking forward for contributions from the open-source community.

Thanks!
Francisco

**Comment by gbaty** [comment]
I can do it. I will create a p/r when ready, I hope soon.

**Comment by hlkline** [comment]
Great!
As an FYI, we are planning on adding regression scripts which cover more of the python code features, so there may be a delay while we get those implemented and running prior to merging your pull request. 
For the existing regression tests, you can run those on your own machine using the scripts within the TestCases/ folder. (There is also more information on the wiki)

It will also be helpful to refer to our developer docs in the wiki: https://github.com/su2code/SU2/wiki/Developer-Docs

**Comment by economon** [comment]
Agreed, this sounds great. Thanks for working on this! Just let us know if we can be of any help while you're making progress.

We'll try to get those Python regression tests into Travis CI asap...

**Comment by gbaty** [comment]
# Import issues

In Python 3, relative import behaviour changes.
In Python 2, "import module" loads first local module, then system module. In Python 3, it is the opposite.

## Import patterns in SU2 code

If we consider, to simplify, these generic packages:
``package1/p1m1.py``
``package1/p1m2.py``
``package1/__init__.py``

``package2/p2m1.py``
``package2/__init__.py``

In SU2 code we find these patterns:

**Pattern 1**
``package1/__init__.py``
 contains

```python
import p1m1
import p1m2
```
These instructions are useless as it is the common behaviour of package.
If a `__init__.py` is defined, I can do from package1 import p1m1 or import package1.p1m1.

Do you know why this happens ? Is there an historical reason or other ?
For example, in [``SU2_PY/SU2/__init__.py``](https://github.com/su2code/SU2/blob/master/SU2_PY/SU2/__init__.py) or [``SU2_PY/SU2/mesh/__init__.py``](https://github.com/su2code/SU2/blob/master/SU2_PY/SU2/mesh/__init__.py)

**Pattern 2**
``package1/__init__.py``
 contains

```python
from p1m1 import f
```

**Pattern 3**
``package1/p1m1.py``
 contains

```python
from ..p1m2 import f
```

**Pattern 4**
```python
import cPickle as pickle
```


## Solution
I suggest these solutions:

**Pattern 1**
 delete  imports

**Pattern 2**
replace ``from p1m1 import f`` with ``from .p1m1 import f`` 

See also next solution

**Pattern 3**

This is OK. Another approach is to always use absolute imports, for example
```python
from ..p1m2 import f
```
becomes
```python
from package1.p1m2 import f
```
Result is the same except that it is recommended in [PEP8](https://www.python.org/dev/peps/pep-0008/#id20) but first approach is ok too.
I can do it if you want.


**Pattern 4**
Py3 pickle now manage both accelerated cPickle and pure python pickle
See https://docs.python.org/3/whatsnew/3.0.html#library-changes, 4th item.
So replace it with

```python
if sys.version_info.major > 2:
    # Py3 pickle now manage both accelerated cPickle and pure python pickle
    # See https://docs.python.org/3/whatsnew/3.0.html#library-changes, 4th item.
    import pickle
else:
    import cPickle as pickle
```

Do you agree with these solutions ?
Do I apply absolute import for pattern 3 ?

**Comment by economon** [comment]
More to come on your questions above, but a quick note to say that we're nearly finished with adding new regression tests for the Python scripts in a separate branch. We will merge those in soon, so that you can more effectively test your modifications.

**Comment by aerialhedgehog** [comment]
@gbaty, a few comments basedon experience solely in py2.7 --

pattern 1
this is in place to save the need for additional import lines in user scripts.  namely package1.p1m1.* would not be accessible without import package1.p1m1

since in the grand scheme of things the SU2 python package is a small package, i think it's important for the whole python package to be accessible with one import SU2.  So would hesitate to delete all imports without understanding how the sub (and subsub) modules would be accessed.

pattern 2
this is aliasing a submodule that is commonly used to a higher module tier.  this can be removed if it's too messy.  the .p1m1 syntax is fine since this isn't exposed to the user.

pattern 3
same aliasing idea as pattern 2, except aliasing a commonly used object to another module branch.  absolute imports are great, i'm cool with this

pattern 4
sounds fine, i think this only shows up in one or two places right?  if it's in multiple places i'd be concerned about a lot of repeated code and would try to make an import helper function.

**Comment by gbaty** [comment]
Thank you for all your answers.

@economon very good news! I am looking forward this improvement. I will rebase my branch on it.

@aerialhedgehog: For first pattern, I didn't thought about this case. Thanks for feedback.
So ok to not change code matching pattern 1.

In my own experience, in such cases, I prefer to create a new user friendly module that do all imports. In one hand, users have a very simple module and developers keep all real packages as clean as possible. But in other hand, it is true that there is a bit of duplication and can be confusing for whom exploring code.

For pattern 4, yes, if I remember well, It happens only two times. So no need to write an helper function I think.

**Comment by aerialhedgehog** [comment]
re pattern 1 -- the helper module is certainly a valid approach too.  but as you noted we aired on the side of the module mirroring the package structure so new users could explore.  

granted, the inter-package import is kinda confusing so that could be reworked if changes were vetted by the community.

**Comment by economon** [comment]
FYI: the new Travis CI regression tests for the Python scripts are now live in the develop branch. Hope this helps with your testing.

**Comment by gbaty** [comment]
@economon : thanks.

**Comment by gbaty** [comment]
Some new questions:

**iteritems** 
iteritems is sometime used to iter on dict. 
In py2, it uses less memory than items due to use of iterators instead of returning list of couple (key, value). In py3, items corresponds more or less to iteritems.
There are 3 solutions to fix it:
1. use only items (right way in py3, more memory consuming)
2. use viewitems (compatible py2.7, not compatible 2.6, not well known attribute)
3. write a check if py2 ... iteritems, if py3 items
In #260 I used the 1st.

**lower case class name conflicting with module name**
In code there is is some __init__ codes like
```python
from ..util.ordered_bunch import OrderedBunch as ordered_bunch
```
It seems that such imports are not compatible with new py3 import approach. Even I am not absolutly sure that bug come from that point. In all cases, I would suggest to use OrderedBunch instead of alias ordered_bunch every where. Is there a reason explaining this choice ?
I tried in my branch to remove this alias ... hopping nothing is broken. let's wait travis answer

**travis for py3**
Do you plan to add it ?

**how to contribute**
I decided to create a pull request with flag "DO NOT MERGE", I did it for these reasons:
  - benefit from travis ci
  - make it visible
  - ease code review and comment directly on code
But with flag "do not merge" because it still remains some questions and bugs to be discussed.

Is it the right way or do you prefer just a branch on my fork and ask for pull-request only when branch is very clean and tested ?

thanks

**Comment by Kenneth-T-Moore** [comment]
for `iteritems`, a 4th way is to use iteritems from the `six` library. See Dean Serenevy's reply here.

http://stackoverflow.com/questions/13998492/iteritems-in-python

**Comment by gbaty** [comment]
For the moment I tried to not use six to avoid to add a new library dependency but it could be another solution!

**Comment by hlkline** [comment]
In terms of the how to contribute question, we will not accept the pull request unless it is clean and tested, but you can post not-quite-finished pull requests.

However, if all you want is the regression tests, you can do that on your own system using the provided *_regression.py scripts. There are also directions on how to use the travis CI tools within your own fork: https://github.com/su2code/SU2/wiki/Running-Regression-Tests

**Comment by gbaty** [comment]
Thanks for your answers. 
Sure I agree not to accept until perfectly clean ;)
Unfortunately, I cannot use _regression on all test cases (not enough memory for some test cases) and travis test do not run on my fork because only branch develop is enabled in travis file. 
How do you work on your side to benefit from travis ci without pushing changes to develop branch ?
I can modify travis file locally in a test branch, do you suggest other approaches ?
Thanks a lot

**Comment by talbring** [comment]
If you do some tests in your own fork of SU2 using travis, remember to change the recipients of the notifications in the .travis.yml :)

**Comment by gbaty** [comment]
Done, sorry for flooding

**Comment by gbaty** [comment]
I can create an issue to exchange good practices on how to benefit from travis continuous integration while avoiding common issues like "build do not start" or "how to not flood mailing list" ;)

Here a first **suggestion** 
I am not an official su2 developer so it is just suggestions hoping it could be useful for su2 community.


If you want to run travis continuous integration on your fork, you need ...

  - create a new branch based on your development branch, for example: ``test_feature_xyz``, based on ``feature_xyz``.
  - edit ``.travis.yml`` and remove following lines

``` yaml
notifications:
    email:
        recipients:
            - su2code-dev@lists.stanford.edu
```
Replace

``` yaml
branches:
    only:
        - develop
```

with

``` yaml
branches:
    only:
        - test_feature_xyz
```

  - push branch ``test_feature_xyz`` to your fork
  - if all tests are ok, you can 
    - create on pull-request on ``feature_xyz`` (**not on ``test_feature_xyz``** to be sure not to push your modified travis.yaml)
    -  delete test branch ``test_feature_xyz``

**Comment by hlkline** [comment]
I previously linked directions to the wiki with directions on how to do this, in which step #1 includes bold text stating that you should update the email address in the yaml file, in addition to the other .yaml file edits that are needed.

**Comment by gbaty** [comment]
**All tests pass for both python 2.7 and python 3.2**
See [travis tests](https://travis-ci.org/gbaty/SU2/builds/123336107) that include both py2 and py3.

Sorry again for my mistakes and thanks again for your work on docs and your answers. 
I don't know how i missed regression test link only two comments above :(

**Comment by economon** [comment]
No problem at all about the notifications. It was a nice reminder for the community, :).

As you said, it looks like the tests are passing. Are there other things you would like to add to the implementation, or is the existing pull request ready for review?

**Comment by gbaty** [comment]
It is ready for review !

**Comment by economon** [comment]
Support added in #424. Thanks again for all of the effort @gbaty and @petebachant!
