### ISSUE TITLE
Wrong output file when using discrete_adjoint.py

### ISSUE THREAD

**Issue by Bullnados** [su2code/SU2#257]
I started a calculation with discrete:adjoint.py -f MyConfigFile.cfg
The console output seems to be wrong
Wrong:
----Exit Success (SU2_CFD)---
...
----Exit Success (SU2_SOL)---
...
----Exit Success (SU2_CFD)---
...
----Exit Success (SU2_SOL)---
...
----Exit Success (SU2_DOT)---
...

Expected:
----Exit Success (SU2_CFD)---
...
----Exit Success (SU2_SOL)---
...
----Exit Success (SU2_CFD**_AD**)---
...
----Exit Success (SU2_SOL)---
...
----Exit Success (SU2_DOT**_AD**)---
...

**Comment by talbring** [comment]
Hey Alex,

we'll consider changing it in the future. Thanks bringing this up.

**Comment by Bullnados** [comment]
Also nice would be a clear separation between the blocks. Atm at ending u get Exit .....
Somethin like that:
![unbenannt](https://cloud.githubusercontent.com/assets/11041576/15497673/13a67f62-219c-11e6-9c89-7dcc1236a706.PNG)

**Comment by Bullnados** [comment]
That still would be a sweet nice2have also im not involved in SU2 anymore
