### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [su2code/SU2#26]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) like the following.
- [CPrimalGrid](https://github.com/su2code/SU2/blob/6f1bbb437ac6dd36a70affb244adfca79991ac51/Common/src/primal_grid_structure.cpp#L37)
- [CSysMatrix](https://github.com/su2code/SU2/blob/b98ee0d7074767ebf9645f772d1cfc0826f9dd27/Common/src/matrix_structure.cpp#L56)
- [CVariable](https://github.com/su2code/SU2/blob/6f1bbb437ac6dd36a70affb244adfca79991ac51/SU2_CFD/src/variable_structure.cpp#L125)

**Comment by hlkline** [comment]
I apologize that it has taken a long time for us to respond to this. 
Would you mind creating a pull request with your suggested changes so that we can take a closer look at this?
When creating a pull request, make sure to base your changes on the current develop branch.

**Comment by economon** [comment]
Thanks for pointing these out. Closing since we have had major memory improvements over the past year, mainly in #294 and #265.

**Comment by elfring** [comment]
Were there [a few update candidates left over](https://github.com/su2code/SU2/blob/6d6727d350a918e78592c7e33316edcad06ffb66/SU2_CFD/src/variable_direct_elasticity.cpp#L160 "Update candidate: Destructor for CFEM_ElasVariable")?

**Comment by economon** [comment]
We've fixed nearly all of the leaks in the code, but may be overly checking for NULLs. Do you have a tool for identifying these that you can share?

**Comment by elfring** [comment]
How do you think about to search for questionable null pointer checks a bit more also by the GitHub interface?
