### ISSUE TITLE
boundary conditions

### ISSUE THREAD

**Issue by woodjude** [su2code/SU2#262]
Hi,

It seems to me that the boundary conditions of

BC_ActDisk_Boundary
BC_Interface_Boundary
BC_NearField_Boundary

in CIntegration::Space_Integration are called always. There is no if function to switch off these boundary conditions.

Is this necessary please?

What are these boundary conditions please?

It seems to me that they do not need to be called for every case.

Best wishes
Jack

**Comment by talbring** [comment]
Hi Jack,

when you take a look at these routines you can see that there is a loop over all markers. Only if the marker is actually of that specific kind, there is something done. These boundaries are special two-sided boundaries. They are different from the other boundaries in that for imposing the correct values they need information from both sides of the boundary. This is why they are not in the loop with the other markers (they only require specified boundary values and information from inside the domain).

If this does not answer your questions, consider reopening this issue. I'll close it for now.

Tim

**Comment by woodjude** [comment]
Hi Tim,

I see. Thanks for your answer.

Best wishes
Jack
