### ISSUE TITLE
Cannot write volume solution flow.dat when using parallel computation

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#268]
Version 4.1.0 "Cardinal", installed both on my own MacBook Pro and the super computer at my school.  Neither can output flow solution when using more than one cores, but the restart file is written with no problem. Not quite sure why...

Have to trick the code and restart it to get the solution. 

Thanks,
Paul

**Comment by aeroamit** [comment]
Hi, Paul,


You can use SU2_SOL command to generate the output


________________________________

**Comment by paulhzhang** [comment]
Got that. Thought there is a bug in the code or I did not compile it right.

Thanks,
Paul

**Comment by Bullnados** [comment]
Here too. Sometimes flow.vtk is not created automaticly. But no idea why. Same case one time with auto flow.vtk other time no flow.vtk.

**Comment by aeroamit** [comment]
If you run on single core by using SU2_CFD file.cfg, it will create flow.vtk if you have choosen output option as ParaView in file.cfg or flow.dat if it is Tecplot.

For running in parallel If you are running using python script, it will automate the process and generate .vtk or .dat output files.

If you are running in parallel without using python script i.e. by using mpirun than it will not generate output file and you have to use
SU2_SOL file.cfg command for generating the .vtk or .dat output files but before usong this command you have to copy restart_flow.dat to solution_flow.dat file and than use SU2_SOL file.cfg command. May be you missed the copying step for restart_flow.dat file.

Regards
Amit
________________________________

**Comment by Bullnados** [comment]
Mmh firstly I thought this too . But I always run parallel with mpi. And as I said sometimes flow.vtk is generated and sometimes not. Perhaps it is a problem with our HPC?

**Comment by hlkline** [comment]
Is this happening when the flow solution has diverged? The flow file will only be generated if SU2 successfully exits - either by reaching a convergence criteria or a maximum number of iterations. If the flow diverges or the code encounters some other error it will exit without writing the flow visualization.

**Comment by Bullnados** [comment]
Ok thanks for the info. I will check this the next days.
But normally the flow.vtk is created after WRT_SOL_FREQ, isn't it? :

**Comment by talbring** [comment]
So I am a little confused here, is the problem that the flow.vtk is not generated when running the python scripts or when running it manually ?

**Comment by abdulhaq-e** [comment]
> But normally the flow.vtk is created after WRT_SOL_FREQ, isn't it? :

Only when running on a single process, i.e. when using `SU2_CFD`. In this situation, the history file and the restart file _and_ the solution files (flow.vtk and surface_flow.vtk) are written. 

However, when running in parallel using the python script. The solution files will not be written until the end (a successful completion), only the history and restart files are written every `WRT_SOL_FREQ`.

**Comment by economon** [comment]
We have a bit of documentation about this on the wiki here: https://github.com/su2code/SU2/wiki/Post-processing.

Does this clear things up? Please let us know if this isn't adequate, and we can add more detail.

**Comment by Bullnados** [comment]
Okay.
We have a little script here which sets some standard parameters like standard runtime, standard memory use mpi Version fpr the HPC.
As I can see(with my little knowledge about that script) it is doing the same like mpirun -n2 SU2_CFG config.cfg. And mostly I using parallel with mpi I get .vtks automaticly.

It seems, that bigger files (~140mb mesh, 650mb flow.vtk) tends to not generating the automatic .vtk?
