### ISSUE TITLE
SU2_SOL and automatic flow.vtk creat different output variablenames

### ISSUE THREAD

**Issue by Bullnados** [su2code/SU2#269]
Perhaps i found a little bug. 
Can someone confirm, that the output name of variables is different which flow.vtk "maker" you use?

SU2_SOL creates "Conservative_1" with "" and the automatic flow.vtk has Conservative_1 without "".
This is little irritating when using Paraview and especially Paraview states.

If u have a state file created without "" variables and want import a flow.vtk created with SU2_SOLfirst u get an error, second u have to add "" in every calc to get results again

**Comment by talbring** [comment]
Hi Alex,

I could reproduce this issue. We'll have a look into this.

Tim

**Comment by talbring** [comment]
Fixed this issue.
