### ISSUE TITLE
SU2 3.0.0 Eagle fails to compile due to missing automake-1.14 and aclocal-1.14

### ISSUE THREAD

**Issue by cfbaptista** [su2code/SU2#27]
I tried to compile SU2 with:

````
git clone https://github.com/su2code/SU2
cd SU2
./configure
make -j$(nproc)
````

`Configure` ran without any issues, but `make` failed because it was looking for `automake-1.14` and `aclocal-1.14`. On my system I have version `1.11` installed. So I created two symlinks:

````
sudo ln -s /usr/bin/automake /usr/local/bin/automake-1.14
sudo ln -s /usr/bin/aclocal /usr/local/bin/aclocal-1.14
````

Ran make again, et voila, everything worked out fine. No issues.

I would like to suggest to change the source of SU2 to **not** specifically require version 1.14 of `automake` and `aclocal`.

**Comment by hlkline** [comment]
I believe that this has been fixed with the bootstrap script in more recent versions.
