### ISSUE TITLE
SU2 optimization does not work correctly with CGNS format

### ISSUE THREAD

**Issue by AndreiCFD** [su2code/SU2#270]
SU2 optimization does not work correctly with CGNS format

Direct computation with CGNS format work correctly.

First step of optimization is correct (DSN_001).
On second step (DSN_002) the program write the mesh_airfoil_deform.cgns.
The extension is correct, but internal format is SU2 format.
The command CONVERT_TO_SU2= YES does not work also.

May be I do not know something. 

Help me!

MESH_FILENAME= mesh_airfoil.cgns
MESH_FORMAT= CGNS
%CGNS_TO_SU2= YES
MESH_OUT_FILENAME= mesh_out.cgns or MESH_OUT_FILENAME= mesh_out.su2

**Comment by talbring** [comment]
Hi Andrei,

for the optimization you have to convert the mesh to .su2 first. You can do that for example by just running SU2_DEF  with DV_KIND set to FFD_SETTING. This will create a mesh_out.su2 (which is the default if MESH_OUT_FILENAME is not set). Afterwards change MESH_FILENAME and MESH_FORMAT accordingly.

**Comment by AndreiCFD** [comment]
Thanks!
But, does not work.
No output file.

**Comment by talbring** [comment]
Sorry I was wrong, this only works if you have a FFD box defined. Another way is to just scale the mesh by 1.0. Use this settings:
DV_KIND = SCALE
DV_MARKER = ( put here all markers of the mesh separated by comma)
DV_PARAM= (1.0)
DV_VALUE=1.0

Then run SU2_DEF.

**Comment by AndreiCFD** [comment]
Tim Albring, many thanks!
