### ISSUE TITLE
Three GetPMatrix s 

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#271]
Why there are three different P matrix implementations? I know this function is overloaded, but why in different forms? And what does "SU2_CPP2C " mean? Can someone shed some light on the related literature? I am quite confused...

P.S. I am a Gnoffo guy. 

Thanks,
Paul

**Comment by WallyMaier** [comment]
I think this is not slightly outdated.   It looks however, that 1/2 P Matrices is unused.

**Comment by WallyMaier** [comment]
All P Matrices are used.  One is specifically for Generalization of numerics
