### ISSUE TITLE
Bug in multigrid agglomeration 

### ISSUE THREAD

**Issue by talbring** [su2code/SU2#276]
There seems to be a bug in the multigrid agglomeration. I came across this issue while running the **parallel** regression tests on a local machine. Here, everything was fine. On travis, however, the laminar flatplate case failed. So I ran the case several times and I noticed that the agglomeration rate changes randomly between

`MG level: 3 -> CVs: 97. Agglomeration rate 1/3.28. CFL 3.02.`

and

`MG level: 3 -> CVs: 98. Agglomeration rate 1/3.24. CFL 3.03.`

each time you run the case (sometimes you have to try it a lot of times to get the other result though). This of course also gives slightly different solutions. 

For more information just check the most recent travis ci run at pull request #242 (https://travis-ci.org/su2code/SU2/jobs/131067620). Note that this bug also occurs on the develop branch.

I labeled this issue "priority" because it could potentially lead to other problems as well.

**Comment by economon** [comment]
Thanks, Tim.

Did you check if this is related to the compiler or architecture, by any chance? I know that the partitions provided by ParMETIS change depending on the system (although they should be deterministic). In the past, compiler optimizations have led to non-deterministic behavior on some systems. Does it still occur with -O0 optimization?

We'll look into it too.

**Comment by LaSerpe** [comment]
I run into the same issue in the last few days. Iooks to me that this behavior is related to the Parent_CV variable which is not initialized. I solved this issue by setting it to 0 in the  CPoint constructor in dual_grid_structure.cpp. Could someone have a look into this and confirm this?

I opened a new issue earlier today, im closing it right now so we can keep working in this thread

**Comment by talbring** [comment]
Hi Giulio, if you have solved this problem, could you open a pull request ?

**Comment by LaSerpe** [comment]
Hi Tim, I just created a branch feature_agglomeration_bugfix.
I'll make some more tests and submit a pull request later.
