### ISSUE TITLE
Detailing config_template.cfg with all parameters and more detailed descriptions

### ISSUE THREAD

**Issue by Bullnados** [su2code/SU2#277]
First one:
It seems, some parameters are missing in config_template.cfg. Would be realy great if u can add rly all parameter u can set. For example ARTCOMP_FACTOR isnt listed in the actual *.cfg. But this parameter can be very important to convergence a problem.
For SU2 beginners this would simplify the getting in not crawling through

The second one is, that some mor detailed infos for every single parameters would be nice, the default value. Either directly in the *.cfg or in an extra description file.

An example for ARTCOMP_FACTOR
Adds artificially compressibility | default 1.0 | Can help to convergence a problem or can speed up convergence

**Comment by hlkline** [comment]
Thank you for the suggestion, the artificial compressibility should probably be added to config template - although I would also note that this option only operates when running an incompressible problem, which some users may not realize.
The config template is generated for releases, and some options are excluded for development purposes. Artificial compressibility is not in that category, however, and so it should be added to the config template. 

All options, and default values, can be found in the source file: Common/src/config_structure.cpp

One alternate solution for getting more detail on options, which unfortunately is only partially complete, is to leverage doxygen:
https://github.com/su2code/SU2/issues/122

example output:
![image](https://cloud.githubusercontent.com/assets/5167760/15504600/9beafe66-2174-11e6-836d-f20777f4f474.png)

**Comment by Bullnados** [comment]
Thank you for answering.
You mean that Doxy right?
http://su2.stanford.edu/doxygen/
I asked you cause it seems this is an outdateted version? BTW the Doxy is also outdateted.

Mmmh are realy all options and parameter in that *.cpp? For example I can set INLET_TYPE= MASS_FLOW but this option isn't shown in that *.cpp

**Comment by hlkline** [comment]
The doxygen at that link is very out of date, we no longer update it. 
I meant the doxygen at https://github.com/su2code/Documentation/tree/master/Doxygen
The file there will allow you to get the doxygen documentation for whichever version of the code you have on your computer, as it uses comments within the code to generate the documentation. The output where I clipped the above example is in >Modules > Description of the Configuration Options. 

In reading the .cpp you have to do some searching, as the options are stored in a map in another file (option_structure.hpp). But in terms of those maps, yes, they do have all the options.

**Comment by aeroamit** [comment]
Hi Heather,

Can you please tell me how to generate doxygen document for the latest version on my computer (step by step commands).

Thanks and Regards
Amit
________________________________

**Comment by economon** [comment]
If you are looking for another way to view all of the current config options, you can find them all directly in config_structure.cpp under the routine SetConfig_Options(). We also have a script that should be able to parse this portion of code automatically to give you a clean list, but it might need to be fixed up a little. That script is parse_config.py and can be found in SU2/SU2_PY/.

**Comment by hlkline** [comment]
As Tom and I noted, you can find all the options in config_structure.cpp - which I repeat because the doxygen documentation is not our main tactic and so it may not be as complete and informative as the source file itself. 

doxygen: 
1. check out the SU2 and Documentation files in the same folder structure as they appear in the su2code github repository. Navigate to the Documentation/Doxygen folder in a terminal.
2. See step 2 of the doxygen manual: https://www.stack.nl/~dimitri/doxygen/manual/starting.html

**Comment by Bullnados** [comment]
Thank you for explanation. Will give it a try tomorow. :+1: 

But MASS_FLOW for the INLET_TYPE i cant find. INLET_TYPE is in the cpp, is that right or was that the wrong Common/src/config_structure.cpp I took a look?

**Comment by talbring** [comment]
I am currently working on updating the config_gui.py and parse_config.py scripts. Should be ready this week. I think they are quite useful.

**Comment by talbring** [comment]
Doxygen documentation was updated in #373 (http://su2.stanford.edu/doxygen/).
