### ISSUE TITLE
Problem with discrete_adjoint.py script and its sequence creating the config_xx.cfg files

### ISSUE THREAD

**Issue by Bullnados** [su2code/SU2#279]
Hey at all

I have a problem with the discrete_adjoint-Phytonsript. The problem is, that my cases needs a lot of RAM(Over 500GB for CFD_AD and MG). But it is impossible to start the script on our HPC an the machine where I can start the script is low memoried.
With smaller cases it was possible to start discrete_adjoint.py with EXT_ITER=1 to creat all config files, modifying some options and send them separately to the HPC.

But as I said with the big files the CFD_AD part takes to much memory. So the last *cfg-files aren't created because the files are just created directly before the calculation. For me especially the config_DOT_AD script is importend

 I come to mind to two options
1. Changing the creation sequence of the *.cfg files from  "before calculation" to all *.cfg-files at once directly after starting the script

2. Please tell me how I can creat the *.cfg-files "manually". Especially the config_DOT_AD script

Thank you

**Comment by talbring** [comment]
The following python script just creates the config_DOT.cfg: http://pastebin.com/G122hEp0

I hope this is what you were looking for, otherwise just reopen the issue.

**Comment by Bullnados** [comment]
Thank you for your fast response. 
But wehre i have to copy and Start that script? I try Same folder 
Yourscript.py -f SameStartScriptIusewithdiscrete_ad.py.cfg

./Yourscript.py -f SameStartScriptIusewithdiscrete_ad.py.cfg

Copied in same folder where discrete_adjoint.py is and than switch to bash
Yourscript.py -f SameStartScriptIusewithdiscrete_ad.py.cfg

**Comment by talbring** [comment]
it doesn't matter where it is placed. But it must be run inside the folder where the config file is and the environment variable SU2_RUN must be set correctly.

**Comment by Bullnados** [comment]
Problem solved. Script Workshop now. Just a simple DOS/Windows-Unix fileformat error. -.-
