### ISSUE TITLE
Output deformation to CGNS format

### ISSUE THREAD

**Issue by hlkline** [su2code/SU2#287]
Being able to produce a deformed mesh in cgns rather than SU2 format would be useful for:
- transferring geometries resulting from optimization cases to other simulation tools (whether another fluid solver or for multiphysics simulations)
- editting meshes when the files used to generate the mesh have been lost or are unavailable (currently there is no way to load an su2 mesh into pointwise, for example). 
- general compatibility with external tools: 3rd party mesh deformation & generation, CAD, etc. 

Since we can already read CGNS format hopefully that won't be too burdensome.

**Comment by WallyMaier** [comment]
#674 I believe this resolves this issue

**Comment by MicK7** [comment]
Sorry, but this is not implemented yet. (#674 does not solve this issue)
