### ISSUE TITLE
BUG - VALUE_OBJFUNC_FILENAME 

### ISSUE THREAD

**Issue by tpratt1993** [su2code/SU2#289]
in an optimisation process, once the turbulent flow sim is converged, the adjoint gradients will not

 be calculated unless the value of VALUE_OBJFUNC_FILENAME is set to of_func.dat. 
i had it set to of_eval.dat and the optimiser stopped before even creating adjoint-lift and adjoint-drag directories. 
[M6NSopt.txt](https://github.com/su2code/SU2/files/354316/M6NSopt.txt)
[processfile.txt](https://github.com/su2code/SU2/files/354339/processfile.txt)
[errorfile.txt](https://github.com/su2code/SU2/files/354340/errorfile.txt)

**Comment by talbring** [comment]
Should be solved with this commit: https://github.com/su2code/SU2/commit/ee55e4d1eaf4fadc8e45049a4693269a74443302

If not -> reopen.
