### ISSUE TITLE
Bug in unsteady optimization

### ISSUE THREAD

**Issue by ghost** [su2code/SU2#296]
when doing unsteady optimization in parallel, SU2 can not compute the gradients. Ive tested this issue on many cases (pitching, plunging, gist simulation, ....) with both SU2v4.0.0 and SU2-4.2.0 but each time the gradients are NaN. 
both flow and adjoint equations converged well and also the results on single possessor is ok.

**Comment by talbring** [comment]
Sorry for getting back to you this late, but can you give more details ? Which of the methods do you use to compute the gradients (FD, cont. adj, disc. adj) ?

**Comment by ghaffarime91** [comment]
hi. thanks for your answer. I report this issue on cont. adj and disc. adj
as I said the problem is, when I start parallel calculation it can not comupte the gradient

**Comment by talbring** [comment]
Do you have a particular case that you can share ? Because for me it seems to work, at least for provided test cases.

**Comment by ghaffarime91** [comment]
actually I face the issue when dealing with naca64a10 optimization

**Comment by ghaffarime91** [comment]
sorry I accidently press the Close issue....
anyway Im going to install v 4.3 of the software and try again; then I will report the results.

thanks alot for your response

**Comment by ghaffarime91** [comment]
I tried again and the problem still persist. I test the NACA64A010 euler optimization with V4.3.0. 
I attached the Log for adjoint calculation. same thing happened on all of the unsteady cases. there would be some problems with gradient projection code
[log_Adjoint(DRAG).pdf](https://github.com/su2code/SU2/files/517609/log_Adjoint.DRAG.pdf)

**Comment by talbring** [comment]
Solved in #360.
