### ISSUE TITLE
Node size consistency

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#3]
SU2 should be consistent if the node numbers are represented by unsigned long, long, long long, unsigned int or int

**Comment by hlkline** [comment]
Do you mean the index used to get a CPoint from a node array? (iPoint, iNode, etc)
These are still sometimes unsigned long, sometimes unsigned short. 
It seems like we will pretty easily exceed 65535 points in a  node list, so they should be unsigned long.

**Comment by btracey** [comment]
Yes, that is roughly what I mean. When I filed the issue, I was compiling in xcode, and it threw a bunch of warnings about implicit numeric casts. This is what the isssue was about. I'm off of develop and the moment, and don't have xcode setup, so I'm sorry I can't be more specific.

I think they should all be unsigned long long. The memory overhead is trivial (8 bytes per node), and if we want the code to be usable in an exascale environment we don't want to limit ourselves to 4 billion node meshes.

**Comment by hlkline** [comment]
Preconditioner used short, is fixed in 9e55060bb80aab78002a63e3550e5c9f592a2569
I think all node numbers are unsigned long now; 
I think long long is a good idea in the long run.

**Comment by economon** [comment]
Agreed. We removed some remaining long arrays with maps (e.g., local to global mappings) in v5, so we should be consistently using unsigned long in reference to grid node index values. In the future, we will likely have an "su2int" data type too that we can simply typedef. Closing.
