### ISSUE TITLE
Cannot run with the new release v4.3 

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#303]
The same configurations are used to compile
./configure CXXFLAGS="-O3" --enable-mpi --with-cc=/usr/local/mpi3-dynamic/bin/mpicc --with-cxx=/usr/local/mpi3-dynamic/bin/mpicxx 
CGNS flag is no need to enable since the new version has already taken care of it. 

A couple of issues when ran the quicktest,
1. segmentation fault after the Begin Solver. 
2. when using multi-cores, got multi-thread outputs. Must be something wrong with the mpi. 

Does anybody else have a similar issue? Or it is just my problem. 

Thanks,
Paul

**Comment by paulhzhang** [comment]
Sorry if I posted in the wrong place. I tried to delete it and move it to cfdonline. Too late. Paul

**Comment by hlkline** [comment]
closed for movement to cfd-online forum.
multi-threading does indicate an issue with compiling. One thing to check is whether the same mpi implementation is being used for compilation and at runtime. (aka, openmpi vs mpich)
