### ISSUE TITLE
Some bugs when compiling SU2 with metis and cgns-hdf5

### ISSUE THREAD

**Issue by i-zhen** [su2code/SU2#31]
I used SU2-3.0.0 'eagle' 
My metis version is 5.1.0. But when I compile Metis 64bit (set IDXTYPEWIDTH to 64) .There are some compile errors occured below:

......
......
../src/geometry_structure.cpp(5371): error: argument of type "int *" is incompatible with parameter of type "idx_t={int64_t={l    ong}} *"
      METIS_SetDefaultOptions(options);
                             ^
  ../src/geometry_structure.cpp(5373): error: argument of type "int *" is incompatible with parameter of type "idx_t={int64_t={l    ong}} *"
      METIS_PartMeshNodal(&ne, &nn, eptr, elmnts, NULL, NULL, &nparts, NULL, NULL, &edgecut, epart, npart);
......
......

Same to metis, when I compile cgns with hdf5. There are also some errors. The library link may be had some mistake.

But the most important error is that -- when I change --with-mpi=mpicxx to --with-mpi=mpiicpc .

Build Configuration Summary:

    Source code location: /parastor/users/isc01/zy/temp/SU2-master-back
    Install location: 	  
    Version:              3.0.0 "eagle"
    Compiler:             mpiicpc
    Preprocessor flags:   -O3
    Compiler flags:       -O3
    Linker flags:         
    CGNS support:         no
    MPI support:          yes
    Metis support:        yes
    TecIO support:        no
    Mutation++ support:   no
    Jsoncpp support: 	  no

    Build SU2_CFD:        yes
    Build SU2_DDC:        yes
    Build SU2_GPC:        yes
    Build SU2_MAC:        yes
    Build SU2_MDC:        yes
    Build SU2_PBC:        yes
    Build SU2_SOL:        yes
    Build SU2_GDC:        yes
    Build SU2_UMC:        yes

There are some errors below:

Making all in Common/lib
make[1]: Entering directory `/parastor/users/isc01/zy/temp/SU2-master-back/Common/lib'
mpiicpc -DPACKAGE_NAME=\"SU\^2\" -DPACKAGE_TARNAME=\"SU\^2\" -DPACKAGE_VERSION=\"3.0.0\ \"eagle\"\" -DPACKAGE_STRING=\"SU\^2\ 3.0.0\ \"eagle\"\" -DPACKAGE_BUGREPORT=\"susquared-dev@lists.stanford.edu\" -DPACKAGE_URL=\"http://su2.stanford.edu\" -DPACKAGE=\"SU\^2\" -DVERSION=\"3.0.0\ \"eagle\"\" -I.   -O3 -DNO_CGNS -I/parastor/users/isc01/zy/metis-64/include -DMETIS_5 -DNO_TECIO -DNO_MUTATIONPP  -O3 -MT ../src/libSU2_a-config_structure.o -MD -MP -MF ../src/.deps/libSU2_a-config_structure.Tpo -c -o ../src/libSU2_a-config_structure.o `test -f '../src/config_structure.cpp' || echo './'`../src/config_structure.cpp
mv -f ../src/.deps/libSU2_a-config_structure.Tpo ../src/.deps/libSU2_a-config_structure.Po
mpiicpc -DPACKAGE_NAME=\"SU\^2\" -DPACKAGE_TARNAME=\"SU\^2\" -DPACKAGE_VERSION=\"3.0.0\ \"eagle\"\" -DPACKAGE_STRING=\"SU\^2\ 3.0.0\ \"eagle\"\" -DPACKAGE_BUGREPORT=\"susquared-dev@lists.stanford.edu\" -DPACKAGE_URL=\"http://su2.stanford.edu\" -DPACKAGE=\"SU\^2\" -DVERSION=\"3.0.0\ \"eagle\"\" -I.   -O3 -DNO_CGNS -I/parastor/users/isc01/zy/metis-64/include -DMETIS_5 -DNO_TECIO -DNO_MUTATIONPP  -O3 -MT ../src/libSU2_a-dual_grid_structure.o -MD -MP -MF ../src/.deps/libSU2_a-dual_grid_structure.Tpo -c -o ../src/libSU2_a-dual_grid_structure.o `test -f '../src/dual_grid_structure.cpp' || echo './'`../src/dual_grid_structure.cpp
/public/soft/intel/impi/3.2.2.006/include64/mpicxx.h(45): catastrophic error: #error directive: "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"
  **#error "SEEK_SET is #defined but must not be for the C++ binding of MPI. Include mpi.h before stdio.h"**
   ^

compilation aborted for ../src/dual_grid_structure.cpp (code 4)
make[1]: *** [../src/libSU2_a-dual_grid_structure.o] Error 4
make[1]: Leaving directory `/parastor/users/isc01/zy/temp/SU2-master-back/Common/lib'
make: *** [all-recursive] Error 1

**Comment by hlkline** [comment]
Hello
My apologies that this hasn't been answered yet. 
For future installation problems you may get a faster response on the forum at: 
cfd-online.com/Forums/su2/

For this particular problem, I believe that you will have an easier time with the most current version of SU2. Metis is now included in the externals/ folder, so that you can be sure that the Metis version is compatible with SU2.
