### ISSUE TITLE
SU2_MSH writing node index twice

### ISSUE THREAD

**Issue by LaSerpe** [su2code/SU2#317]
When converting meshes from .cgns to .su2 the number of points NPOIN and the index of each node is written twice in the output file.

**Comment by hlkline** [comment]
Sorry that it looks like there was not a response to this; there have been a few changes related to writing meshes in the intervening time - can you please check and see if you are able to reproduce the error with the most recent master branch?

**Comment by LaSerpe** [comment]
yep, I still get double indexing for points of the output mesh file (using the current develop version)

cheers,
Giulio

**Comment by WallyMaier** [comment]
I dont believe SU2_MSH is supported/used anymore.
