### ISSUE TITLE
Non-dimensional time step size? 

### ISSUE THREAD

**Issue by paulhzhang** [su2code/SU2#320]
Got this question when running a shocktube problem. Used Euler explicit time stepping method and a fixed time step. In addition, I non-dimensionalized the variables. By cheking the solution, the solution is marching by the specified physical time. It is supposed to use the non-dimensional time step, right? If so, then a bug report is submmitted. 

  if (time_steping) {
# ifdef HAVE_MPI

```
su2double rbuf_time, sbuf_time;
sbuf_time = Global_Delta_Time;
SU2_MPI::Reduce(&sbuf_time, &rbuf_time, 1, MPI_DOUBLE, MPI_MIN, MASTER_NODE, MPI_COMM_WORLD);
SU2_MPI::Bcast(&rbuf_time, 1, MPI_DOUBLE, MASTER_NODE, MPI_COMM_WORLD);
Global_Delta_Time = rbuf_time;
```
# endif

```
for (iPoint = 0; iPoint < nPointDomain; iPoint++){

                    /*--- Sets the regular CFL equal to the unsteady CFL ---*/
                    config->SetCFL(iMesh,config->GetUnst_CFL());

                    /*--- If the unsteady CFL is set to zero, it uses the defined unsteady time step, otherwise
                     it computes the time step based on the unsteady CFL ---*/
                    if (config->GetCFL(iMesh) == 0.0){
                            node[iPoint]->SetDelta_Time(config->GetDelta_UnstTime()); //Here should we use GetDelta_UnstTimeND?
                    } else {
                            node[iPoint]->SetDelta_Time(Global_Delta_Time);
                    }
            }
```

  }

**Comment by arubino** [comment]
Hi @paulhzhang, if I've understood correctly, please use just the CFL option and remove the non-dimensional time step for your simulation.

**Comment by paulhzhang** [comment]
Hi @arubino. Thank you for answering it. I did not specify any unsteady CFL, so the cases ran with the default unsteady CFL =0. But I think using a fixed time step is more natural for time accurate cases. My previous doubt is that a non-dimensional time step should be used here instead of the physical one for time_stepping flag. Thanks again.
