### ISSUE TITLE
Problems with 3D inverse design

### ISSUE THREAD

**Issue by DominicMasters** [su2code/SU2#321]
I have recently been trying to run a series of 3D inverse design cases but have been struggling to get it to work properly. 

To use the inverse design feature i have set
INV_DESIGN_CP= YES 
in the config file, this adds an output variable CP_diff to the history file.

To test this variables i have been running a test with two wings:
NACA0012 wing (unit chord, span 4, no sweep or taper)
NACA4410 wing (unit chord, span 4, no sweep or taper)

Here there NACA0012 will act as the starting wing and the NACA4410 will be the target.

My current process is:
Mesh NACA0012;
Deform mesh to NACA4410;
Run SU2;
Read in data from solution file and output wing surface to TargetCP.dat in format
"Global_Index", "x_coord", "y_coord", "z_coord", "Pressure", "Pressure_Coefficient", "Mach_Number";
Set mesh back to original NACA0012;
Run SU2; (This produces a solution with Cp_diff=3.4868)
Deform mesh to NACA4410;
Run SU2; (This produces a solution with Cp_diff=0.4733)

This final run should surely give Cp_diff=0?? I have checked the final pressure distributions and they are within 5e-8 of each other at all points.

What equation is used to calculate Cp_diff?

What format should the TargetCp.dat file be in?  I have based the format used here on the test case example, this is only a 2D case though.

Any help would be much appreciated.

I have included my config file and a TargetCp.dat file below

[inv_opt3D.cfg.txt](https://github.com/su2code/SU2/files/533463/inv_opt3D.cfg.txt)
[TargetCp.dat.txt](https://github.com/su2code/SU2/files/533465/TargetCp.dat.txt)

**Comment by DominicMasters** [comment]
To confirm, there seems to be a similar problem in 2D. I did the following test for the test case "steady_inverse_design".

Ran test case with given mesh and config file.
This gave CP_diff=0.178
Copied "surface_flow.dat" -> "TargetCp.dat" (they seem to share the same format)
Re-ran the test case
This gave identical results apart from the Cp_diff=0.009
Again this should definitely equal zero.

I have looked through the source code and found the line that I think equates this value:

PressDiff += Area * (CpTarget - Cp) * (CpTarget - Cp); (from SU2_CFD/src/output_structure.cpp line 7529)

There seems to be some other problem affecting this though as (CpTarget - Cp) should be zero.

**Comment by ZenBel** [comment]
I have experienced the same problem. I think the problem can be connected with the code running in parallel.

Also, if you defined the objective function e.g. on an airfoil but have other boundaries of the same type (e.g. walls) the CpTarget for these boundaries will be set to zero and it will contribute to the final value of the objective function thus possibly giving wrong results.

**Comment by subhanjan21** [comment]
@DominicMasters 
Hey. I have been trying to run a 3d euler case in SU2. My meshed file with boundary as wing, symmetry and farfield is not working, 
I would appreciate if you could share the config file and mesh file for me to view once.
Thank you. 
![capture](https://user-images.githubusercontent.com/31462793/38780237-f802ec6e-4098-11e8-8994-903bf0ea5813.JPG)

**Comment by economon** [comment]
Hi @DominicMasters @ZenBel : have you been able to sort the issues? It might be worth checking these things again with the fixes in #600
