### ISSUE TITLE
AoA keyword in the config file

### ISSUE THREAD

**Issue by fpalacios** [su2code/SU2#323]
I know this is silly... but... Am I the only one who finds the lower case "o" in the AoA keyword (config file) a little bit disturbing?... I think we should use all capital letter for all the keyword and 
AoA should be ANGLE_OF_ATTACK or just AOA... unfortunately, this change will affect a couple of config files :-)

**Comment by btracey** [comment]
I think AOA works.

Line 4586 of https://github.com/su2code/SU2/blob/master/Common/src/config_structure.cpp (on develop) sets the string all to upper case ( StringToUpperCase(option_name);), so AOA should be the same as AoA.

**Comment by fpalacios** [comment]
Thanks! I'll try and, if it works, then will change all config files to AOA
