### ISSUE TITLE
SetRecording call in CDiscAdjMeanFlowIteration::Preprocess

### ISSUE THREAD

**Issue by fpalacios** [su2code/SU2#329]
Hi Tim, 

It is probably correct. But, just in case, have you noticed that SU2 calls 
SetRecording (in CDiscAdjMeanFlowIteration::Preprocess) twice. Once before, and another after the 0 iteration of the discrete adjoint problem? What is the reason for that?

Thanks!
Francisco

**Comment by talbring** [comment]
Hi Francisco,

I dont know if you are referring to that, but we separated essentially the computation of the derivatives with respect to the conservative variables and with respect to the geometry (node coordinates). The latter is only needed when we write the solution files. So every ExtIter%Wrt_Frequency we have to do two recordings.

Tim

**Comment by fpalacios** [comment]
It could be an output issue but, before my last night commit. This was the screen output for a typical run:

"
------------------------------- Begin Solver -----------------------------

-------------------------------------------------------------------------
Direct iteration to store computational graph.
Compute residuals to check the convergence of the direct problem.
-------------------------------------------------------------------------

log10[RMS Density]: -13.0442, Drag: 0.0213497, Lift: 0.326934.

------------------------ Discrete Adjoint Summary -----------------------
Total Geometry Sensitivity (updated every 250 iterations): 2.2985e+02
-------------------------------------------------------------------------

log10[Maximum residual]: -5.3961e+00.
Maximum residual point 211, located at (1.2558e+00, 1.9961e+01).

 Iter    Time(s)   Res[Psi_Rho]     Res[Psi_E]    Sens_Press      Sens_AoA
    0   1.584266      -6.884726     -12.303428   -2.8113e-06    2.3500e-01

-------------------------------------------------------------------------
Direct iteration to store computational graph.
Compute residuals to check the convergence of the direct problem.
-------------------------------------------------------------------------

    1   1.193311      -6.893856     -12.313088   -2.8113e-06    2.3500e-01
    2   0.829305      -6.903124     -12.322907   -2.8113e-06    2.3500e-01

"

As you can see the message

"
-------------------------------------------------------------------------
Direct iteration to store computational graph.
Compute residuals to check the convergence of the direct problem.
-------------------------------------------------------------------------
"

Appears twice, I thought that was a IO bug and I changed

    if (rank == MASTER_NODE) {
      cout << endl << "-------------------------------------------------------------------------" << endl;
      cout << "Direct iteration to store computational graph." << endl;
      cout << "Compute residuals to check the convergence of the direct problem." << endl;
      cout << "-------------------------------------------------------------------------" << endl << endl;
    }

by 

    if (rank == MASTER_NODE && ((ExtIter == 0) || unsteady )) {
      cout << endl << "-------------------------------------------------------------------------" << endl;
      cout << "Direct iteration to store computational graph." << endl;
      cout << "Compute residuals to check the convergence of the direct problem." << endl;
      cout << "-------------------------------------------------------------------------" << endl << endl;
    }

But, I'm not sure if it is only an IO issue.

Thanks!
Francisco

**Comment by talbring** [comment]
It is not really a bug, since there is indeed a new recording at ExtIter=1 because the tape at this point holds the recording with respect to the geometry variables, but for the iteration we need it with respect to the flow variables. 

But I agree that this output is confusing, so yes, I think the change you made is ok (I can remember that some time back it was already like that, but sometimes for debugging purposes I disable that, so maybe at some point it forgot to revert it)

**Comment by fpalacios** [comment]
Great. Thanks!
