### ISSUE TITLE
Optimization of helicopter rotor blade

### ISSUE THREAD

**Issue by Haider-BA** [su2code/SU2#343]
Hi,
I would like to optimize 3D isolated helicopter rotor blade to get optimum twist for uniform blade loading with the available power and overall helicopter weight constraints. the helicopter is 2-bladed, but i will simulate only one with periodic BCs.
Kindly help me how can I do this using SU2 on windows platform?

**Comment by talbring** [comment]
Hi,

please use the forum at http://www.cfd-online.com/Forums/su2/ for these kind of questions or have a look at the tutorials here on github.
