### ISSUE TITLE
SU2_DOT_AD fails writting Tecpot Binary output files

### ISSUE THREAD

**Issue by fpalacios** [su2code/SU2#345]
SU2_DOT_AD works great with the ASCII Tecplot files but it is not able to write the **binary** files. The code stops with the following message

```
Merging solution in the Master node.
Writing Tecplot Binary file (volume grid).

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

Thanks!
Francisco

**Comment by hlkline** [comment]
I'm sure you already checked this, but just to confirm/clarify what the problem might be, is it possible that the system ran out of memory at this step? This looks similar to errors I have seen in that situation.
