### ISSUE TITLE
Problem with regression?

### ISSUE THREAD

**Issue by jschuele** [su2code/SU2#347]
Fetched developed branch and ran serial_regression.py. Got case FAILED with GCC for ls89_sa, centrifugal_blade, centrifugal_stage.
With INTEL compiler on same platform get passed for ls89_sa, centrifugal_blade, centrifugal_stage but failed for statbeam3d. Strange are the differences for naca0012_def and most of the brick-tests with intel. They converge in significant fewer steps and are marked FAILED.
Is it worthwhile to investigate the differences between GCC and Intel for the brick-cases?
I'am asking, because I'm gone look to fasten calculations up with optimizations in the existing code for single core and perhaps MPI. Far goal, but really far, may be using GPUs as well. Currently I have a 15% improvement single core for RANS from the Comp&Fluids_129 paper. But of course the calculations should not only be faster but correct as well.
Regards, Josef

**Comment by economon** [comment]
Hi Josef: glad to see you getting involved!

I am very interested in this. We have seen differing behavior sometimes between the two compiler sets, in particular when high levels of optimization are being used. In fact, you might check if the same issues appear without compiler optimization. Often, it is an initialization problem or some optimization that affects correctness.

If you have the time to explore different settings and perhaps dig into the code a bit, I would very much like to isolate and remove these compiler-dependent problems with your help.

**Comment by jschuele** [comment]
Fine, I will do so and check what the compilers are doing in these cases. 
In between a comment perhaps to the memory leak issue:

In
CUpwCUSP_Flow destructor
memory leak. *Jacobian is not deleted. Just the elements.

**Comment by fpalacios** [comment]
Hi Josef,

This is an important issue that we need to solve, I going to double check
the problem and I'll keep you posted.

Thanks for your interest in SU2,
Best,
Francisco

**Comment by economon** [comment]
Ah, nice catch. Yes, in that particular case we are using periodic BCs, and in serial, the only way nPoint does not equal nPointDomain is when we have periodic grid points.

**Comment by jschuele** [comment]
Ok, the remaining FAILED test I had after the change mentioned above was fea_fsi/StatBeam_3d. I broke down the issue to my changes to Gauss_Elimination in matrix_structure. The major change in terms of a difference is exchanging 
weight = block[..]/block[..]
against
reciproque=1.0f/block[..] 
weight = block[..] * reciproque
which is of course faster as it removes some costly divisions.
I changed algorithms several time and introduced finally quad-precision for my changes (which are now not faster any more, but for sure more accurate than the original one).
The deviations through all my tests are
Res[Displx] +- 0.000049, Res[Disply] +- 0.000133, Res[Displz] 0.000010 and CFEM +- 0.
The threshold for passing is 0.000010 and exceeded for x and y direction.
I am pretty convinced that the threshold should be raised in that test as rounding errors introduce a large difference than the threshold.
Regards, Josef

**Comment by hlkline** [comment]
Thanks for finding a way to speed things up.
With regards to the tolerance, it would be preferable to update the test values rather than the tolerance, since especially for changes in the integrated values rather than the residual values, small changes over the small number of iterations could indicate a problem that will grow over time. A very small number of iterations is used in the tests in order to save time for the tests. 

Are the changes you quote for the original precision, or for the quad-precision? If the latter, and maybe either way, I would recommend running the case for a larger number of iterations to make sure that there aren't larger differences growing over time that would effect the output, maybe due to some other change in the code that hasn't been identified yet. If you are interested in having your changes included in the code, maybe this discussion should move to a pull request, where folks on the su2 dev team could easily view changes in the code.

**Comment by jschuele** [comment]
Hi,
could you please tell me, how to increase the number of iterations in the corresponding configBeam_ed.cfg meaningfull? The LINEAR-SOLVER_ITER is =500, EXT_ITER does not work in this case.

**Comment by rsanfer** [comment]
Hi, 

configBeam_3d.cfg is a linear structural case, so the problem does not iterate. It is solved in one-shot by computing the displacement vector u in the linear system Ku = F.

For tighter convergence, LINEAR_SOLVER_ITER may be taken up to 1000, which is the maximum number of subspaces accepted by the FGMRES linear solver. Also, LINEAR_SOLVER_ERROR may be reduced.

**Comment by jschuele** [comment]
Ok, changed it to 1000. Results changed only slightly. 
Got now
       Iter    Time(s)    Res[Displx]    Res[Disply]    Res[Displz]   CFEM(Total)
Org: 0  34.920000      -8.498275      -8.230640      -8.123825    6.4095e+04
Reci 0  20.430000      -8.498260      -8.230796      -8.123818    6.4095e+04
Quad 0  25.000000      -8.498253      -8.230661      -8.123815    6.4095e+04
(Times are irrelevant - all calcs. do all types redundant).
How to continue? 
My (nasty, debugging) source used is a tiny 320 line C-code called as external "C". There I can select which method to be passed to the callee. I stepped with Totalview through all and found, that in GaussElimination the divisions (no matter how, except for the QUADs) are sometimes only accurate to the 14th decimal which is not unusual for double precision (checked with hand calculator in quad precision).
After all, Res is log10(of something) and "of something" differs in displx by 1,6e-13, that is a relative error of 5e-05

**Comment by rsanfer** [comment]
Hi Josef,
in general, structural problems are quite stiff and it takes quite a lot of effort for the linear solver to find a solution for u. 

I have just run this case in my own computer (GNU compilers), I get:
 Iter    Time(s)    Res[Displx]    Res[Disply]    Res[Displz]   CFEM(Total)
    0   4.018591      -8.498274      -8.230638      -8.123824    6.4095e+04
so even I see a very small discrepancy. If LINEAR_SOLVER_ERROR is reduced to 1E-10,
 Iter    Time(s)    Res[Displx]    Res[Disply]    Res[Displz]   CFEM(Total)
    0   4.223478     -10.390248     -10.043411     -10.058976    6.4095e+04
so it is just a matter of how much are we letting FGMRES converge.

In principle I believe that, if the changes are just in the order of 1,6e-13, it should be fine to put up the tolerance a bit just for this particular case. It's not the same for non-linear structural problems (e.g. configBeam_2d.cfg) where the residuals printed by the code have a different meaning.

In any case, just to be on the safe side: would you mind to share with me the file restart_beam.dat ? That way I can quantify the actual change in the results.

Thanks,

Ruben

**Comment by jschuele** [comment]
Your email?

**Comment by jschuele** [comment]
Hi,
after discussing with Ruben all my cases with SU2_CFD passed. The fea_fsi/StatBeam_3d case needs an increase in the thresholds. It is a stiff problem and therefore not that numerical accurate (By the way: Should for stiff problems a QUAD-Precision version of the Gauss-Elimination be added?)
I introduced some small changes which sum up to 15% savings for the turb_ONERAM6 case (others not tested) sequentially. Interested in merging them? How to proceed?
Josef

**Comment by hlkline** [comment]
Thanks for the inputs - if you are still working on this, can you please create a pull request into the develop branch so that the su2 team can take a closer look?

**Comment by jschuele** [comment]
ok, done.

  Josef

**Comment by talbring** [comment]
Seems to be solved.
