### ISSUE TITLE
Incompressible fluid with free surface

### ISSUE THREAD

**Issue by j8asic** [su2code/SU2#348]
I understand that the level-set and free-surface code is removed at the moment. Can someone please explain why; what is the road-map concerning their implementation?
Thanks,
Josip

**Comment by talbring** [comment]
Hi Josip,

in the current develop/master these features are still included. However, the plan is to remove these. The reason is simply because of maintenance. We have nobody that can spare time to test the current implementation. If you are willing to do this, please let use know.

Tim

**Comment by j8asic** [comment]
Tim,
as I saw your commit 4d89f49ef88c0027f4cf2b8d980c9b63a7a80f92, marked "Removed Free-surface/LevelSet features for now" I thought the features are out at the moment. Surely, here at our university, we're interested in testing the implementations, and if they turn out promising, I'll assemble a group of programmers/engineers to contribute further. I'd like to point out that marine industry is extremely wide, and that SU2 code _base_ is more promising than other solutions, hence it would be pity not to progress in this direction.
Br, Josip

**Comment by hlkline** [comment]
It's fantastic that you're interested in contributing - if you have not already, I encourage you to join the SU2 developer list (see instructions at: http://su2.stanford.edu/develop.html), and also see the wiki section for developers which has some instructions to help with getting started. Please do not hesitate to ask for help, as well.

**Comment by j8asic** [comment]
Ok, I'll be in touch
