### ISSUE TITLE
I/O improvement (no geometry file)

### ISSUE THREAD

**Issue by ghost** [su2code/SU2#353]
If there is no a mesh file... the output in parallel is too dramatic :-)

```
There is no geometry file (GetnZone))!cstr=model.su2
There is no geometry file (GetnZone))!              

cstr=model.su2
There is no geometry file (GetnZone))!
cstr=model.su2                        
There is no geometry file (GetnZone))!
cstr=model.su2                        
There is no geometry file (GetnZone))!
```

It should be only one nice and clear line (even in parallel mode) and "geometry file" is not very accurate... mesh or grid file would be better. The information about the subroutine (GetnZone) ... it is not really very useful for an average user.

**Comment by economon** [comment]
Fixed in #412
