### ISSUE TITLE
SST destruction term jacobian

### ISSUE THREAD

**Issue by shaering** [su2code/SU2#369]
SST Jacobian for the destruction term in the k-equation w.r.t. omega set to zero.  Should be:
val_Jacobian_i[0][1] = -beta_star*TurbVar_i[0]*Volume;

**Comment by talbring** [comment]
Hi shaering,

sounds like a valid bugfix. Can you open a pull request for that issue ? Thanks!

**Comment by demanosalvas** [comment]
Hi shaering, 

I was wondering if you could point us to your reference for this change?

**Comment by shaering** [comment]
Hello David,

The error is in the Jacobian of the destruction term in the k-equation for
SST (Beta^* * rho * k * omega). The off-diagonal d/d(rho*omega) term is
non-zero. It looks like it was just an omission.

On a slightly different note, I am working on implementing a v2-f and/or
zeta-f model in SU2.  If there is interest in the main branch, I would
happily share it when I work the kinks out.

Cheers,
-sigfried

**Comment by economon** [comment]
Sigfried,

Additional turbulence model implementations (v2-f, zeta-f, etc.) are most certainly welcome. Please do keep us in the loop about this, and let us know if we can be of any help in your development.

Tom

**Comment by juanjosealonso** [comment]
Indeed Sigfried, additional turbulence models would only enhance the capabilities of SU2, so they are welcome.  In the late 1990s (and when Paul Durbin was still at Stanford), we tried v2-f in a couple of other codes (structured mesh or multi-block structured).  I think there was even an implementation that was done for Fluent.  In most cases the solution quality was rather good but the stiffness of the solution was significant.  It would be interesting to see how the implementation converges in a fully-unstructured code like SU2.
Juan

**Comment by vdweide** [comment]
That's correct. We had to use all kind of tricks in other to get things reasonably converged for v2-f. Sigfried, I don't know if you already have a working version that can serve as an example, but otherwise we can certainly you provide you with one, albeit a multi-block structured version.

Edwin

**Comment by economon** [comment]
Resolved in #491
