### ISSUE TITLE
NACA 0012 Test Case does not converge with provided config file

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#37]
The NACA 0012 test case (TestCases/rans/naca0012) does not converge with the provided config file if RESTART_SOL=NO, and the number of iterations is increased beyond 25. The test case should be updated to have a config file which converges "out of the box"

**Comment by hlkline** [comment]
Just tested (in develop branch); converged in 256 iterations. 
Please reopen if there is some situation where that's not the case.

**Comment by hlkline** [comment]
naca0012 turbulent, sa model does converge.
