### ISSUE TITLE
SU2 can keep running with ridiculus residuals

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#38]
Sometimes, the code effectively diverges, but does not actually nan. In this case, the code continues to run. There should be some sort of check that halts execution when this occurs.

For example, here the code has a residual increase of 25 orders of magnitude and then continues for a long time afterward. 

  514   0.858170     -3.810382     -0.818090       0.534918       0.011557
  515   0.858110     -3.806673      1.276861       0.535673       0.011433
  516   0.858248     -3.523170      2.017555       0.533807       0.010890
  517   0.858833     -3.146589      2.453353       0.529337       0.009891
  518   0.859031     -2.980286      3.070260       0.523952       0.009211
  519   0.859039     -2.637185      3.740419       0.455339      -0.003290
The solution contains 100 non-physical points.

 Maximum residual: -0.0373748, located at point 4582.

 Iter    Time(s)      Res[Rho]       Res[nu]   CLift(Total)   CDrag(Total)
  520   0.859013     -1.437953      4.373667      -0.099686      -0.094575

The solution contains 127 non-physical points.
  521   0.859003     -1.111074      5.056160      -4.065337      -0.780464
The solution contains 284 non-physical points.
  522   0.858853     -0.693782      5.183287     -15.761187      -2.268335
The solution contains 514 non-physical points.
  523   0.858725     -0.072830      5.147720     -60.615908      -9.156773
The solution contains 691 non-physical points.
  524   0.858711      0.730028      4.462988    -358.683565     -69.148449
The solution contains 1434 non-physical points.
  525   0.858921      1.373102      4.241595    -914.744092    -187.067270
The solution contains 2138 non-physical points.
  526   0.859282      1.713954      3.814762   -1000.000000    -358.772646
The solution contains 1918 non-physical points.
  527   0.859916      2.236290      4.340435   -1000.000000   -1000.000000
The solution contains 3154 non-physical points.
  528   0.860132      2.291044      4.470125   -1000.000000   -1000.000000
The solution contains 2146 non-physical points.
  529   0.860356      2.371124      3.845344   -1000.000000   -1000.000000
The solution contains 1962 non-physical points.
  530   0.860386      2.282541      4.230209   -1000.000000   -1000.000000
The solution contains 2372 non-physical points.
  531   0.860488      2.346939      4.654921   -1000.000000   -1000.000000
The solution contains 2496 non-physical points.
  532   0.860713      2.307424      4.858399   -1000.000000   -1000.000000
The solution contains 2843 non-physical points.
  533   0.860842      2.326434      4.965822   -1000.000000   -1000.000000
The solution contains 1398 non-physical points.
  534   0.861230      2.506742      4.619859   -1000.000000   -1000.000000
The solution contains 1103 non-physical points.
  535   0.861346      3.076538      5.037658   -1000.000000   -1000.000000
The solution contains 1505 non-physical points.
  536   0.861831      3.178817      5.692809    1000.000000   -1000.000000
The solution contains 2716 non-physical points.
  537   0.861933      3.475146      6.055387    1000.000000   -1000.000000
The solution contains 1071 non-physical points.
  538   0.861955      3.352903      5.809910    1000.000000    1000.000000
The solution contains 869 non-physical points.
  539   0.861970     10.502005      5.406599    1000.000000    1000.000000
The solution contains 484 non-physical points.

 Maximum residual: 12.2995, located at point 9122.

 Iter    Time(s)      Res[Rho]       Res[nu]   CLift(Total)   CDrag(Total)
  540   0.862010     10.482742      5.527612    1000.000000    1000.000000
The solution contains 311 non-physical points.
  541   0.862336     10.173994      5.795970    1000.000000    1000.000000
The solution contains 351 non-physical points.
  542   0.862604     10.888136      5.892078    1000.000000    1000.000000
The solution contains 740 non-physical points.
  543   0.862822     11.004870      5.926460    1000.000000    1000.000000
The solution contains 794 non-physical points.
  544   0.863036     10.896925      5.946274    1000.000000    1000.000000
The solution contains 1043 non-physical points.
  545   0.863305     10.780974      6.014822    1000.000000   -1000.000000
The solution contains 52 non-physical points.
  546   0.863434     11.006074      6.193320    1000.000000   -1000.000000
The solution contains 100 non-physical points.
  547   0.863491     16.405862      6.268311   -1000.000000    1000.000000
  548   0.863551     21.156949      6.187249   -1000.000000    1000.000000
  549   0.863572     20.713874      6.055920   -1000.000000   -1000.000000
  550   0.863532     20.780220      6.044304   -1000.000000   -1000.000000
  551   0.863474     20.816135      6.048407   -1000.000000   -1000.000000
The solution contains 21 non-physical points.
  552   0.863471     20.672119      6.034922   -1000.000000   -1000.000000

many iterations later

The solution contains 1914 non-physical points.
  977   0.893147     64.219218     11.800077   -1000.000000    1000.000000
The solution contains 1823 non-physical points.
  978   0.893113     64.232616     11.770575   -1000.000000    1000.000000
The solution contains 2178 non-physical points.
  979   0.893083     64.159323     11.882706   -1000.000000   -1000.000000
The solution contains 1788 non-physical points.

 Maximum residual: 65.7206, located at point 5028.

 Iter    Time(s)      Res[Rho]       Res[nu]   CLift(Total)   CDrag(Total)
  980   0.893109     64.114631     11.897500   -1000.000000   -1000.000000
  981   0.893082     64.243047     12.598995   -1000.000000    1000.000000
  982   0.892990     71.853036     12.042708   -1000.000000    1000.000000
  983   0.892886     71.308281     11.863795   -1000.000000    1000.000000
  984   0.892820     71.180385     11.838073   -1000.000000    1000.000000
  985   0.892757     71.070490     11.785052   -1000.000000    1000.000000

**Comment by WallyMaier** [comment]
PR #697
