### ISSUE TITLE
possible bug in fixed CL model-SU2-5.0.0

### ISSUE THREAD

**Issue by WANGHao1994** [su2code/SU2#383]
When i am evaluating RANS simulation with fixed cl model in su2-5.0, after it reached the convergence criteria (I have tried  EXT_ITER, CAUCHY and RESIDUAL) and executed "Deleted CIntegration container.  Deleted CIntegration container. ", the routine always stopped with this message: *** Error in `/home/wanghao/software/SU2-5.0.0/bin/SU2_CFD': double free or corruption (!prev): 0x00000000045312d0 ***.
But applying fixed AOA won't has this problem. 
My command is :parallel_computation.py -n 8 -f opt_crm.cfg 
Ubuntu 16.04

![screen](https://cloud.githubusercontent.com/assets/23302629/23536602/0932d9a6-0001-11e7-989d-2515b6942dd1.png)

[opt_crm.txt](https://github.com/su2code/SU2/files/815706/opt_crm.txt)

**Comment by WANGHao1994** [comment]
I encountered a similiar "double free" message as above when i am evaluating fixed CL RANS simulation.
I have tested three cases to see when does this error occur.
The first case is a RANS simulation for CRM wing. My configure file is opt_crm.txt in the attachment.
In this case, when I set FIXED_CL_MODE= YES, then in the end of the SU2_CFD execution, it will return messages below:

`Writing comma-separated values (CSV) surface files.
Merging coordinates in the Master node.
Merging solution in the Master node.
Writing SU2 native restart file.
Writing the forces breakdown file.
*** Error in `SU2_CFD': double free or corruption (!prev): 0x0000000007dc2aa0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fbaa7b177e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7fe0a)[0x7fbaa7b1fe0a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fbaa7b2398c]
SU2_CFD[0x8553d5]
SU2_CFD[0x855c59]
SU2_CFD[0x7583c2]
SU2_CFD[0x75ceb5]
SU2_CFD[0x40759c]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fbaa7ac0830]
SU2_CFD[0x735109]
======= Memory map: ========
00400000-00d07000 r-xp 00000000 08:28 1068882                            /home/wanghao/software/SU2-5.0.0_me/bin/SU2_CFD
00f06000-00f2d000 r--p 00906000 08:28 1068882                            /home/wanghao/software/SU2-5.0.0_me/bin/SU2_CFD
......`

But, if i turn off the FIXED_CL_MODE, this error won't occur.
Then i tried an invisid test case, this case is orriginally from the TestCases folder of SU2 (TestCases/euler/naca0012). In this case, SU2 works well for both FIXED_CL_MODE and FIXED_AOA_MODE.
Finally, i tried another tutorial case for NACA0012 (from /TestCases/rans/naca0012), then SU2 has the same problem in FIXED_CL_MODE as in the first case.

Furthermore, I have noticed that this bug is related to the  compilers. 
1. Intel C++ 2013 + Mpich2-3.0.4, fixed Cl model works; System: RHEL 5.3
2. Intel C++ 2017 + Mpich2-3.0.4, fixed Cl model fails; System: Ubuntu 16.04
3. GCC6.1.0 + Mpich2-3.0.4, fixed Cl model fails; System: RHEL 5.3
4. GCC4.9 + Mpich2-3.0.4,fixed Cl model works; System: RHEL 5.3
5. GCC5.4 + Mpich2-3.0.4,fixed Cl modelfails; System: Ubuntu 16.04

**Comment by talbring** [comment]
I am gonna look into this problem ...
