### ISSUE TITLE
Poor quality of mesh after deformation (SU2-5.0.0)

### ISSUE THREAD

**Issue by WANGHao1994** [su2code/SU2#384]
I used SU2_DEF to evaluate CRM wing grid deformation, but the quality of my structured mesh is pretty bad. My question is whether the FFD box settings could affect the grid deformation,for example the distance of  FFD box from the wall. Another question is whether the strctured mesh doesn't fit SU2_DEF? 
Could anyone help with this ? thank you!
Here are my FFD boxes, configuration file and slice of my wing (red color is deformed grid, the black one is original grid)
[screen output.txt](https://github.com/su2code/SU2/files/835550/screen.output.txt)
[configuration.txt](https://github.com/su2code/SU2/files/835551/configuration.txt)
![comparison](https://cloud.githubusercontent.com/assets/23302629/23821092/b4b13030-0663-11e7-91b5-e63849c323ab.png)
![ffdbox1](https://cloud.githubusercontent.com/assets/23302629/23821093/b5400cf6-0663-11e7-9975-e59a144298e6.png)
![ffdbox2](https://cloud.githubusercontent.com/assets/23302629/23821094/b541fd22-0663-11e7-8423-46502ca059d0.png)

**Comment by hlkline** [comment]
Please see the response on the [forum](https://www.cfd-online.com/Forums/su2/184789-poor-quality-mesh-after-deformation-su2-5-0-0-a.html#post640783).
In the future, please note that it is [recommended](https://www.cfd-online.com/Forums/site-help-feedback-discussions/175429-guide-how-ask-question-forums.html#post612025) not to double-post questions.
