### ISSUE TITLE
Peng-Robinson EoS gives non-physical solutions

### ISSUE THREAD

**Issue by khanhija** [su2code/SU2#398]
Hi

While attempting to run compressible N-S simulation using Peng-Robinsion EoS, I ran into a problem with non-physical solutions. Running SU2_CFD gives the following error multiple times and exits:

------------------------------ Begin Solver -----------------------------
not physical solution found, h and s input -1.24974 -3.8387
...
!!! Error: SU2 has diverged. Now exiting... !!! 

The simulation which resulted in the error was run at around 313 K and 400 bar, which is in the critical region of the fluid I used (CO2). Repeating the simulation at lower pressures (less than about 100 bar) seems to work fine. In the critical region the EoS has only one real solution, so perhaps the problem is related to finding a root for the EoS in fluid_model_ppr.cpp.

Has anyone else encountered the problem?

Relevant configuration options were:

FREESTREAM_PRESSURE= 399E+5
FREESTREAM_TEMPERATURE= 313
REF_DIMENSIONALIZATION= FREESTREAM_PRESS_EQ_ONE

MARKER_RIEMANN= (inlet, TOTAL_CONDITIONS_PT, 400E+5, 313.15, 1.0, 0.0, 0.0)
MARKER_NRBC= ( outlet, STATIC_PRESSURE, 395E+5, 0.0, 0.0, 0.0, 0.0)

% ---- IDEAL GAS, POLYTROPIC, VAN DER WAALS AND PENG ROBINSON CONSTANTS -------%
FLUID_MODEL= PR_GAS
GAMMA_VALUE= 1.28
GAS_CONSTANT= 188.9221
CRITICAL_TEMPERATURE= 304.1282
CRITICAL_PRESSURE= 7377300
CRITICAL_DENSITY= 480.9911
ACENTRIC_FACTOR= 0.2239

**Comment by salvovitale** [comment]
Dear @khanhija 
thank you very much for reporting this issue. The h-s call of the Peng-Robinson EoS is iterative. It may be that for these initial conditions the routine is not able to find a root. 
So I have a couple of solutions:

-You may try to use the branch feature_polytropic gas where my colleague @luciaazzini implemented a more robust HS call for PR

-or you may run everything Dimensional (REF_DIMENSIONALIZATION= DIMENSIONAL), converge first the solution with IDEAL_GAS or VW_GAS and then restart it with PR_GAS.

regards

sv

**Comment by khanhija** [comment]
Hi again,

Ok great, thank you for your answer! Based on a quick test, branch feature_polytropicGas seems to work.

**Comment by salvovitale** [comment]
Great to hear that! For any other issue do not hesitate to contact us!

regards

**Comment by talbring** [comment]
Seems to be solved. I am gonna close this one (otherwise reopen this issue).
