### ISSUE TITLE
Bad Termination - Running in parallel with CGNS mesh format < test case/euler/wedge >

### ISSUE THREAD

**Issue by pdpdhp** [su2code/SU2#40]
Hi, 

I have been running a simulation with CGNS mesh format from the provided test cases using the last version, SU2 - 3.2.0. The test case was Euler flow simulation over a wedge using the HLLC scheme. The point is that everything going well with the native mesh format, su2, in both parallel and serial, but with the cgns mesh format only in serial the simulation starts. In parallel, the bad termination error comes up exactly after Solution Postprocessing. I checked out with 2.0.10 and had no problem. The details are provided in the following.

```Python
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 1
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
Traceback (most recent call last):
  File "parallel_computation.py", line 117, in <module>
    main()
  File "parallel_computation.py", line 62, in main
    options.divide_grid  )
  File "parallel_computation.py", line 103, in parallel_computation
    info = SU2.run.merge(config)
  File "/~/SU2/code/320/release/SU2_PY/SU2/run/merge.py", line 70, in merge
    merge_solution(konfig)
  File "/~/SU2/code/320/release/SU2_PY/SU2/run/merge.py", line 96, in merge_solution
    SU2_SOL( config )
  File "~/SU2/code/320/release/SU2_PY/SU2/run/interface.py", line 240, in SOL
    run_command( the_Command )
  File "/~/SU2/code/320/release/SU2_PY/SU2/run/interface.py", line 277, in run_command
    raise Exception , message
Exception: Path = /~/SU2/code/320/release/SU2_PY/,
Command = mpirun -n 4 /usr/local/bin/SU2_SOL config_SOL.cfg
SU2 process returned error '1'
```
Checked out the traceback error in the merge and interface python files, but couldn't figure it out. Is there any problem with the SU2_SOL.cpp? 
I appreciate your help for finding the source.

Bests,
PDP

**Comment by hlkline** [comment]
For future questions on configuration settings you will get a faster response on our forum at http://www.cfd-online.com/Forums/su2/. 
The location of metis can be set with the configuration flags described in the installation instructions at
https://github.com/su2code/SU2/wiki/Build-from-Source
