### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [su2code/SU2#400]
This suggestion is a continuation for the previous report on the topic “[Remove unnecessary null pointer checks](https://github.com/su2code/SU2/issues/26 "Deletion of redundant pointer checks?")”.
Would you like to wrap any pointer data members with the template class “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for std::unique_ptr")”?

Update candidates:
- [CPoint](https://github.com/su2code/SU2/blob/6d6727d350a918e78592c7e33316edcad06ffb66/Common/src/dual_grid_structure.cpp#L323)
- [CSysMatrix](https://github.com/su2code/SU2/blob/6d6727d350a918e78592c7e33316edcad06ffb66/Common/src/matrix_structure.cpp#L70)

**Comment by economon** [comment]
@elfring: thank you very much for the suggestion, but for the time being, our philosophy is to keep the code as simple as possible to keep a low barrier to entry for new users/developers. Therefore, we try to avoid templates when possible (there are a few isolated places where they are necessary). This may change in the future, but we'll close this for now.

**Comment by elfring** [comment]
>Therefore, we try to avoid templates when possible …

I find this view strange.

I would appreciate if current C++ software techniques can be applied. How much can they help to make the source code a bit simpler?

**Comment by economon** [comment]
I understand, but it helps to keep the code more approachable and portable. That being said, there may be some work proposed soon using templates in the linear solver classes, and it would be great to have your feedback then. We really appreciate your interest!

**Comment by elfring** [comment]
>…, but it helps to keep the code more approachable and portable.

How do you think about to improve any corresponding [system configuration checks](https://github.com/su2code/SU2/blob/ec551e427f20373511432e6cd87402304cc46baa/configure.ac#L53 "build specification") then?
