### ISSUE TITLE
axisymmertic problem

### ISSUE THREAD

**Issue by abartulo** [su2code/SU2#404]
Hi, 
I'm new to CFD and SU2. I would like to ask if its possible to perform an axisymmetric flow simulation? I cannot find AXISYMMETRIC tag in the config_template, so I'm wondering if that option still exists. 

Thanks for reply

**Comment by economon** [comment]
Hi, 

Yep! This is still possible for the compressible solver with the following option: AXISYMMETRIC= YES.

Closing this issue for now, please reopen if you have issues,
Tom

**Comment by vdweide** [comment]
Be aware though that the viscous axi-symmetric source terms have not been implemented yet.
