### ISSUE TITLE
Be consistent in file name input files

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#41]
SU2 right now is inconsistent with how it does file names in the config file. For example, the restart file needs to be specified with a ".dat" suffix, but in the case of the surface files, the ".csv" is added automatically. SU2 should be consistent across all filenames. Preferably, this will be fixed by having the user specify all suffixes. This is a tiny amount of additional work for the user, but it makes writing scripts that use the config file much easier. When the suffix is in the config file, it's easy to have python say "open this file". If the config file just has the base name of the file (no extension) then the knowledge of what suffix SU2 uses must be hard-coded into the follow-on script (which can then break later if SU2 changes).

**Comment by WallyMaier** [comment]
This seems to be outdated.
