### ISSUE TITLE
Internode communication (Infiniband)

### ISSUE THREAD

**Issue by sametcaka** [su2code/SU2#411]
Dear all,

Is there a way to compile SU2 such that it uses Infiniband rather than Ethernet for internode communication for parallel runs? If so, would you share how to do that?

Best,
Samet

**Comment by talbring** [comment]
Hi Samet,

to my knowledge that is an option of the underlying MPI library and cannot be be changed by some compiler options for SU2.

Tim

**Comment by sametcaka** [comment]
Thanks Tim! I will check what I can do with the OpenMPI...
