### ISSUE TITLE
Correct commenting of variables within CFluidModel class 

### ISSUE THREAD

**Issue by ChiefSeaBiscuit** [su2code/SU2#414]
Current within the fluid_model.hpp defines the CFluidModel class with varibles however, the variables have incorrect commenting for the briefs with majority of the second half being repeated. From this it's difficult to determine what the variables actually are a part of as the nomenclature of them is a little ambiguous. Could this be sorted?

`class CFluidModel {

protected:
su2double      StaticEnergy,      /*!< \brief Internal Energy. */
       Entropy,          /*!< \brief Entropy. */
       Density,          /*!< \brief Density. */
       Pressure,         /*!< \brief Pressure. */
       SoundSpeed2,       /*!< \brief SpeedSound. */
       Temperature,      /*!< \brief Temperature. */
       dPdrho_e,         /*!< \brief DpDd_e. */
       dPde_rho,         /*!< \brief DpDe_d. */
       dTdrho_e,         /*!< \brief DTDd_e. */
       dTde_rho,         /*!< \brief DTDe_d. */
             Cp,                    /*!< \brief Specific Heat Capacity at constant pressure. */
       Mu,          /*!< \brief Specific Heat Capacity at constant pressure. */
         dmudrho_T,       /*!< \brief Specific Heat Capacity at constant pressure. */
         dmudT_rho,        /*!< \brief Specific Heat Capacity at constant pressure. */
         Kt,          /*!< \brief Specific Heat Capacity at constant pressure. */
         dktdrho_T,       /*!< \brief Specific Heat Capacity at constant pressure. */
         dktdT_rho;        /*!< \brief Specific Heat Capacity at constant pressure. */`

**Comment by salvovitale** [comment]
Dear @ChiefSeaBiscuit ,

thank you very much for bringing up this issue. I will open in the coming days a pull request with the implementation of non-polytropic gas model, in which the specific heat capacity will be a function of the temperature. I will take the opportunity in that pull request to fix all the bad commenting. In the mean time, i can describe what this properties are:

**_dPdrho_e_**, /!< \brief derivative of pressure w.r.t. density at constant energy
**_dPde_rho_**, /!< \brief derivative of pressure w.r.t. energy  at constant density
**_dTdrho_e_**, /!< \brief derivative of temperature w.r.t. density at constant energy
**_dTde_rho_**, /!< \brief derivative of temperature w.r.t. energy  at constant density
**_Cp_**, /!< \brief Specific Heat Capacity at constant pressure. /
**_Mu_**, /!< \brief laminar viscosity
**_dmudrho_T_**, /!< \brief derivative of the laminar viscosity w.r.t. density at constant temperature
**_dmudT_rho_**, /!< \brief derivative of the laminar viscosity w.r.t. temperature at constant density
**_Kt_**, /!< \brief laminar thermal conductivity
**_dktdrho_T_**, /!< \brief derivative of the laminar thermal conductivity w.r.t. density at constant temperature
**_dktdT_rho_**; /!< \brief derivative of the laminar thermal conductivity w.r.t. temperature at constant density


Regards

Salvo
