### ISSUE TITLE
Current status of periodic BCs

### ISSUE THREAD

**Issue by EduardoMolina** [su2code/SU2#416]
Dear developers,

I would like to know about the current status of Periodic BCs in SU2? Anyone working on this topic? For instance, it is working for single periodic BCs, for example, spanwise direction of a 3D channel?

Regards,

Eduardo Molina

**Comment by salvovitale** [comment]
Dear @EduardoMolina,
I am not directly working on the improvement of the periodic BCs, but I am using them a lot for turbomachinery simulations. Their limitations at the moment are:

- Multi-grid  cannot be used with it
- Sometimes SU2_MSH fails in generating the periodic mesh. If that happens, let me know I have a small stand-alone code that does the job properly
- Parametis sometimes crashes in partitioning the domain. If that happens, try to run it with a different number of processors 
  

regards

Salvo

**Comment by EduardoMolina** [comment]
Dear @salvovitale ,

Thanks for your reply.

Unfortunately, all my attempts with periodic BCs failed during the Jacobian initialization independent
of the number of processors....

Apparently, SU2_MSH is converting the mesh correctly, visually at least...

What is the size of your grid? It is 3D? I tried with grids from 1M to 10M without success....

@BeckettZhou and @talbring are also trying to perform unsteady simulations with periodic BCs. Can you share your experiences about this topic?

Any help is really appreciated.

Regards 

Eduardo Molina

**Comment by salvovitale** [comment]
Dear @EduardoMolina  

can you try to generate the periodic mesh with the fortran code attached. After compiling the code you can run it as ./su2perio.exe < config_file.cfg   
The config file is the same you are using for the SU2_MSH.

Let me know if it works. 
[su2_perio.tar.gz](https://github.com/su2code/SU2/files/1177849/su2_perio.tar.gz)

regards

sv

**Comment by salvovitale** [comment]
Dear @fpalacios and @economon,

I would like to add the su2perio fortran program to the MeshTools repository. Could you please give me access to it? I tried to push it, but apparently I do not have the right to push on that repository.

Regards

Salvo

**Comment by economon** [comment]
@salvovitale: just added write access for the developer team. Please try again when you have a moment.

**Comment by salvovitale** [comment]
Thanks @economon, now the SU2_PER is available within the MeshTools repository.

cheers

sv

**Comment by koodlyakshay** [comment]
Hi, @salvovitale, 
Thanks a lot for the script. It works quite well for me. 
Just a very small suggestion - When writing out the marker tags in the mesh output file(subroutine write mesh, line 869) it appears that you have restricted the output to just 10 characters. Might cause some problems if the tags are a bit longer. 
Cheers,
Akshay

**Comment by economon** [comment]
Resolved by #652.
