### ISSUE TITLE
Optimal Shape Design of a Transonic Airfoil tutorial 

### ISSUE THREAD

**Issue by martinsimon88** [su2code/SU2#418]
Hello and thanks for doing great work for this software!

I don't know for sure, but it seems the Optimal Shape Design of a Transonic Airfoil tutorial has a typo?:

2. Execute the shape optimization script by entering `$ python shape_optimization.py -f inv_NACA0012_basic.cfg' at the command line.

where it should be(?):

2. Execute the shape optimization script by entering `$ shape_optimization.py -f inv_NACA0012_basic.cfg' at the command line.

**Comment by talbring** [comment]
Hi Martin,

if you omit the "python" command then the script is passed first to the bash. Here the line "#!/usr/bin/env python " at the beginning of the script determines what is actually used to execute the script. So it essentially doesn't matter whether you put it there or not. Sometimes you want to use a different python version to execute the script though, then it might makes sense to use for example

`$ python2.7 shape_optimization.py -f inv_NACA0012_basic.cfg'

So if everything is set up correctly on your system you should be able to use both. Hope this answers your question.

Tim

**Comment by talbring** [comment]
@martinsimon88 does this answer solve this issue ?

**Comment by martinsimon88** [comment]
Yes! Thank you for explaining! :)
