### ISSUE TITLE
3D Eigenvectors in CNumerics::GetPMatrix

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#423]
Could somebody clarify the 3D eigenvectors in CNumerics::GetPMatrix? E.g. take val_tensor[4][0]. The first term is 0.5*sqvel*val_normal[0], which has dimension velocity squared. The other terms are of type val_density*val_velocity[1]*val_normal[2], i.e. the dimension is density times velocity. That is dimensionally not consistent.

Thanks,
Edwin

**Comment by fpalacios** [comment]
Hi Edwin, I have never thought on the units consistency for the P matrices. Just in case this information is useful for you, the implementation comes from the Hirsh book (picture attached).

Best,
Francisco

![img_2005](https://user-images.githubusercontent.com/29830726/29253855-9754035c-803c-11e7-8455-5a1d4b46dc41.JPG)

**Comment by vdweide** [comment]
The dimensional inconsistency comes from the multiplicity of the normal velocity eigenvalue and the manipulation Hirsch does with the corresponding eigenvectors in order to obtain a formulation that is valid for any normal vector. When you use the P matrix to form the characteristic variables, the dimensional inconsistency disappears again, as it should. Never looked at it this way. Thanks for clearing this up Francisco.
