### ISSUE TITLE
Averaging of flow parameters for URANS

### ISSUE THREAD

**Issue by kmguleren** [su2code/SU2#434]
Hi,

Is there a way to get the average and RMS of flow parameters like velocity, pressure, temperature when we run URANS cases?

Many Thanks,

**Comment by economon** [comment]
@kmguleren: you can find a version of the code that has this capability in the following branch,

https://github.com/su2code/SU2/tree/feature_AvgRMS

which has been worked on in collaboration with @EduardoMolina for DDES mainly. Note the changes in the most recent commits, which are mostly in solver_direct_mean.cpp and output_structure.cpp. Should be straightforward to recreate or copy until we can get this capability merged with develop.

**Comment by economon** [comment]
Hopefully the branch was helpful. Closing this one.. please reopen if necessary. We plan to incorporate this into the develop branch in the future.
