### ISSUE TITLE
Error in AD install for 5.0.0 Raven with libSU2Core.a

### ISSUE THREAD

**Issue by timjim333** [su2code/SU2#447]
Hi, I'm trying to install SU2 5.0.0 Raven on my Ubuntu with AD support. Following the documentation, I ran preconfigure.py with the following options:
`export CXXFLAGS="-O3" && python2.7 ./preconfigure.py --enable-autodiff --prefix=/opt/SU2/SU2v5.0.0 --enable-mpi --with-cc=/opt/openmpi/openmpi-3.0.0/bin/mpicc --with-cxx=/opt/openmpi/openmpi-3.0.0/bin/mpicxx --enable-PY_WRAPPER --with-HDF5-lib=/opt/hdf5/hdf5-1.10.1/lib --with-HDF5-include=/opt/hdf5/hdf5-1.10.1/include --with-ZLIB-lib=/opt/zlib/zlib-1.2.11/lib --with-ZLIB-include=/opt/zlib/zlib-1.2.11/include --with-SZIP-lib=/opt/szip/szip-2.1.1/lib --with-SZIP-include=/opt/szip/szip-2.1.1/include --with-LAPACK-lib=/usr/lib --with-LAPACK-include=/usr/include`

This appears to complete successfully. I then do a `make install` but the install fails when in the /SU2_AD/SU2_PY/pySU2 directory with `make[3]: *** No rule to make target '/opt/SU2/SU2v5.0.0_src/SU2_AD/SU2_CFD/obj/libSU2Core.a', needed by 'SU2_APIPYTHON_wrap.cxx'.  Stop.`

I've attached the whole output in the following text file. Am I missing something in my setup?
[make_install_error.txt](https://github.com/su2code/SU2/files/1339819/make_install_error.txt)

**Comment by talbring** [comment]
Indeed thats a bug when you enable the python wrapper... I am gonna solve this soon. For the time being just compile the normal and AD binaries separately by going to SU2_BASE and SU2_AD and `run make install` in each of them. You should see the same error again in SU2_AD, but you can ignore it, everything should have been compiled fine.

Best,
Tim

**Comment by timjim333** [comment]
Thanks for the update - I'll give it a go and get back to you. Are there any tests I can run to check functionality once complete? 

Kind regards,
Tim

**Comment by timjim333** [comment]
For the SU2 make install, I did not manage to successfully complete the installation, I've attached the output in the text file. Meanwhile, I'll the give AD build a go. Thanks again.
[BASE_make_install_error.txt](https://github.com/su2code/SU2/files/1340083/BASE_make_install_error.txt)

**Comment by timjim333** [comment]
The AD install also seems to have failed - did both actually 'successfully' install? 

[AD_make_install_error.txt](https://github.com/su2code/SU2/files/1340097/AD_make_install_error.txt)

**Comment by talbring** [comment]
If you look at the error in SU2_BASE it says `Error: Unable to find 'mpi4py/mpi4py.i'`. It seems like mpi4py is not properly installed on your machine. The error in SU2_AD can be ignored.

**Comment by tobadavid** [comment]
Indeed, the compilation with AD support is not compatible with the Python wrapper yet. If you are not interested in using the wrapper, just remove the --enable-PY_WRAPPER option and it should be OK.

In general, if you want to compile SU2 with the wrapper in parallel, mpi4py has to be properly installed on your system. As the wiki says, the easiest way to install it is by using python-pip (example for Linux).

**Comment by timjim333** [comment]
Thanks for your thoughts. I've been working on the mpi4py install [here](https://bitbucket.org/mpi4py/mpi4py/issues/78/openmpi-based-mpi4py-runtestspy-error) and I thought I had finally installed mpi4py correctly. I can see the missing file located  in `~/anaconda3/lib/python3.6/site-packages/mpi4py/include/mpi4py/mpi4py.i` - is there a flag I can set in the install script to direct the installer there? Thanks.

**Comment by timjim333** [comment]
I've realised that it might be because my mpi4py installation is within python 3.6.
preconfigure.py seemed to be written python 2.7 but now I think of it, I had not installed mpi4py for my python 2.7 install. Can I use the python2to3 tool and run preconfigure.py using python 3? Or would it be better to set up a separate python 2.7 environment?

Eventually, I want to couple SU2 and I was planning on doing so in a python 3 environment. Thanks for the suggestions!

**Comment by talbring** [comment]
The problem is that the path where the automake looks for mpi4py is hardcoded at the moment. This will also eventually be changed soon. 

A workaround is to add the path manually in `SU2_PY/pySU2/Makefile.am` to the `MPI4PY_INCLUDE` variable. Then run `automake` in the main folder and then the preconfigure script again.

**Comment by tobadavid** [comment]
Concerning the Python wrapper, everything is currently hardcoded for python2.7 which was my Python environment when I originally introduced the wrapper. PR #424 is fixing this. In the meantime, the workaround proposed by @talbring should work.

**Comment by timjim333** [comment]
Hello, thanks for the comments. Can I just clarify that the workaround steps are:
1. Add the path to `SU2_PY/pySU2/Makefile.am`
2. `make install` (not sure which you mean by `automake`)
3. `make distclean`
4. `export CXXFLAGS="-O3" && python2.7 ./preconfigure.py --enable-autodiff ...` with all options
5. Navigate to `SU_BASE` and `SU_AD` and `make install` in each

Is that correct? Many thanks.

**Comment by timjim333** [comment]
I looked up automake, compiled and ran automake-1.12.5 in the place of step 2:
`cd /opt/SU2/SU2v5.0.0_src && /opt/automake/automake-1.12.5/bin/automake-1.12`

It didn't give any confirmation but I assumed it worked as I can see the path was added when attempting to run `make install` in `SU_BASE`. However, it still does not seem to find the file, although I can see the file in that location. I've attached the final part of the output:
[BASE_make_install_error2.txt](https://github.com/su2code/SU2/files/1348152/BASE_make_install_error2.txt)

Although when I run ` ls ~/anaconda3/envs/su2/lib/python2.7/site-packages/mpi4py/include/mpi4py/`, I see: `mpi4py.h  mpi4py.i  mpi4py.MPI_api.h  mpi4py.MPI.h  mpi.pxi`

**Comment by talbring** [comment]
All the steps you mentioned are correct, but you added the path `/anaconda3/envs/su2/lib/python2.7/site-packages/mpi4py/include` to Makefile.am instead of `/home/tjim/anaconda3/envs/su2/lib/python2.7/site-packages/mpi4py/include`

**Comment by timjim333** [comment]
Sorry - in my haste, I missed that...the install now finds mpi4py just fine. Thanks for the help.

On another note, the `make install` fails when searching for what looks a tecplot-related file (output attached [BASE_make_install_error3.txt](https://github.com/su2code/SU2/files/1348289/BASE_make_install_error3.txt) )

This isn't surprising as I don't have Techplot installed but I also did not set the `--enable-tecio` flag. Is there a way I can turn this off? Thanks.

**Comment by talbring** [comment]
The Tecio library is shipped with SU2. Are you sure you have not modified accidentally something else in `SU2_PY/pySU2/Makefile.am` (for example removing line 84) ? That would be the only explanation I have for now ...

**Comment by timjim333** [comment]
Those few lines in my `Makefile.am` look like this:

#External libraries (METIS_LIB and PARMETIS_LIB are already defined)
TECIO_LIB =
if BUILD_TECIO
	TECIO_LIB += ${abs_top_builddir}/externals/tecio/libtecio.a
endif

Maybe it's better for me to attach the file:
[Makefile.am.txt](https://github.com/su2code/SU2/files/1348376/Makefile.am.txt)

**Comment by talbring** [comment]
Your text editor replaced the white spaces at the beginning of a line with tabs. However, automake interprets tabs as build rules which is not what we want ... So check out the original version of the file using `git checkout SU2_PY/pySU2/Makefile.am` and make sure that all the options to correct whitespaces are switched off in your editor before opening and modifying the file.

**Comment by timjim333** [comment]
Thanks for that - I didn't realise that my copy of emacs was doing the replace on saving. I made the edit then reran the above steps. It seems that SU2_BASE now installs fine and SU2_AD only presents the initial error. I assume this means SU2 is up and running? I'll try some test cases to confirm. Thanks for the support!

**Comment by timjim333** [comment]
Sorry, not sure if this is the best place to ask this but after closing this, I am now trying to do the same AD build on my local supercomputer. During the part where I do a `make install` in SU_BASE, I get the following error: [make_error.txt](https://github.com/su2code/SU2/files/1533904/make_error.txt)

Can you give a pointer as to what might be up?

**Comment by tobadavid** [comment]
As the error message says, it cannot find "Python.h". This is again related to the Python wrapper compilation. If you really don't need it, I suggest you to just disable it when configuring your build (remove --enable-PY_WRAPPER). If you need the Python wrapper and if your Python is not located in a standard location on your supercomputer, you will have to manually modify the SU2_PY/pySU2/Makefile.am and put the right paths for the Python include and Python libs (I think similarly to what you did for mpi4py, see above)... Again, everything should be improved after #424 is merged.

**Comment by timjim333** [comment]
Thanks for the heads up - I just noticed you merged today! Does that mean
if I download the fresh-out-of-the oven master, these problems will go
away? Cheers!

**Comment by tobadavid** [comment]
It is now merged indeed. I dit not work in that branch and I did not have the time to test it on several machines...so I suggest you to checkout the develop branch (not the master) and make a clean build. If things are not improved, I'm afraid that you will have to set the paths manually again.

**Comment by timjim333** [comment]
I will try a clean build now. Does the merge mean that Python 3 is now supported? If so, I will build with that instead.
