### ISSUE TITLE
NACA 0012 Mesh has 3 coordinates

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#45]
The NACA 0012 Mesh (mesh_NACA0012_turb_897x257.su2) does not match the input file format. It is listed as a 2-dimensional mesh, but there are three floating point numbers and then a node number.

**Comment by hlkline** [comment]
Took a 30 second look, it's now got 2 floating point numbers and a node number.

**Comment by btracey** [comment]
Sorry, I should have checked this. Thanks @hlkline
