### ISSUE TITLE
Bug in CSourceAxisymmetric_Flow::ComputeResidual

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#454]
I am trying to run an axi-symmetric case with a time stepping scheme (basically SOD's problem), which fails in CSourceAxisymmetric_Flow::ComputeResidual. The reason is that the boolean implicit is determined as follows

bool implicit       = (config->GetKind_TimeIntScheme_Turb() == EULER_IMPLICIT)

However, this must be config->GetKind_TimeIntScheme_Flow, right?

Furthermore, the small y-coordinate case will also fail, because there is no test whether an implicit computation takes place. I can correct this, if somebody can confirm this is indeed a bug.

Edwin

**Comment by economon** [comment]
@vdweide: yep, definitely a bug. Only the mean flow solver uses that routine. Please feel free to clean this up. I would also like to update the version for the incompressible solver (I think it needs a fix or two)... but we'll get to that after your changes.

**Comment by vdweide** [comment]
OK, I'll do that. And as far as I can see it, also the viscous contributions to the axi-symmetric source terms are missing.

**Comment by vdweide** [comment]
I just created the PR for this.
