### ISSUE TITLE
No error checking in read geometry

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#46]
The NACA 0012 Mesh (mesh_NACA0012_turb_897x257.su2) has 3 floating point numbers and then one integer number, but is listed as a 2-dimensional mesh. CPhysicalGeometry::Read_SU2_Format is fine with the mesh file. Worse, it seems to use the z coordinate as the local index under certain conditions (see line 3430). In serial, the node number is ignored, so we are okay, but this is clearly undesirable behavior.

**Comment by WallyMaier** [comment]
Outdated
