### ISSUE TITLE
Write tests to be compatible with pytest

### ISSUE THREAD

**Issue by petebachant** [su2code/SU2#462]
This will provide a lot of power and flexibility. For example, if doing local development, only the tests that failed last could be run with `pytest --lf`. To make the tests compatible, they can be wrapped into functions with a `test_` prefix, then called from the command line with, e.g.,

    pytest TestCases/serial_regression_AD.py

To select and run only one test:

    pytest TestCases/serial_regression_AD.py::test_discadj_multi_py

**Comment by economon** [comment]
This is very interesting, since I often find that I am commenting out most of the python regression script when debugging only a couple of tests locally.

Can you estimate how much work this would be? Is it just a simple wrapping of what we already have? We would also have to make sure that Travis CI can handle it.

**Comment by petebachant** [comment]
It would simply take some reorganizing of the test scripts to make one function per case and maybe renaming the `TestCase` class to `RegressionTestCase` or something. For example, I rewrote one of the tests in `serial_regression.py` here: https://github.com/petebachant/SU2/commit/fe0ee432c67540067046fbebf9889660331a6592

Then I could run this with

    $ cd TestCases
    $ pytest serial_regression.py

the output from which was:

```
$ pytest serial_regression.py
===================== test session starts =======================
platform linux -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /home/pete/SU2/TestCases, inifile:
collected 1 item

serial_regression.py .

===================== warnings summary =======================
serial_regression.py::TestCase
  cannot collect test class 'TestCase' because it has a __init__ constructor

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=============== 1 passed, 1 warnings in 92.18 seconds ==================
```

`pytest` has a bunch of features to control the print output as well.
