### ISSUE TITLE
Monitoring Pressure values on some specified points 

### ISSUE THREAD

**Issue by dassoumen0609** [su2code/SU2#466]
A new feature of monitoring pressure (or any parameter) values on some specified arbitrary points given by users in case of unsteady simulation. This feature is required for our requirement. I'd implemented this feature for a older one and using a 3rd party library called ANN (Approximate Nearest Neighbor). I wanna know whether implementation using such library can be merged with master version? AFAIK it's not practiced. As Harichand, my colleague said a data structure is already available for tree search which can be implemented. Please tell me how this can be implemented so it clears the eligibility of merge. 
Thanks
Soumen

**Comment by economon** [comment]
Hi Soumen: yes, this is something that the developers are actively working on at the moment (in particular, @sravya91 has been taking the lead on this). It is true that most of the ingredients are already available in SU2 (fast searches, interpolation routines, etc.), but the trick is combining them all and making it general.

Do you have any other requirements beyond simple probes? I am guessing we should have something available in the next few months, but it's not set yet.

**Comment by sravya91** [comment]
Hi Soumen,

As Tom said, the routines are all in place and I have been putting them
together for solution interpolation from one mesh to another for unsteady
simulation as post-processing step. So probing at a particular location for
unsteady solution can be also done with this framework. The probe search
implementation is in place for 2D configuration currently. It will be
extended to 3D and probably available in the main branch in the next 2
months.
The implementation so far is in feature_MeshInterpolation branch if you
want to take a look.

Sravya

**Comment by ZenBel** [comment]
Hi all,

it would be nice to implement this feature as an objective function, which works not only for the pressure but also for other quantities.

Best,

Zeno

**Comment by ZenBel** [comment]
Hello,

Is there someone still working on this topic? I saw that feature_MeshInterpolation hasn't been updated in a year and I was wondering whether there are other active branches where something similar is being developed.

**Comment by clarkpede** [comment]
I'm going to jump on this too.  Is anyone working on solution interpolation (from one mesh to another)? @sravya91, are you still working on this? Did PR #672 introduce any capabilities to address interpolation?  This seems to be a common request from SU2 users: [\[1\]](https://www.cfd-online.com/Forums/su2/213321-su2-solution-interpolation.html) [\[2\]](https://www.cfd-online.com/Forums/su2/215920-use-coarse-grid-flow-solution-initial-solution-fine-grid.html)

I've used some pretty rough python scripts to do solution interpolation in the past, and it would be nice to have some SU2 C++ code that could perform the same task.

**Comment by juanjosealonso** [comment]
Folks,

This is indeed a very important capability for many different applications: from interpolation of solutions from coarser grids to finer grids, to querying an unsteady solution, to implementing numerical error estimates…and many others.  It is important that the search / interpolation routines work when interpolating between grids where some points in the target grid may fall outside of the source grid and, therefore some notion of distance to the wall is needed.

Fortunately, Edwin van der Weide had worked on an interpolation library that @sravya91 (who received her PhD yesterday at our graduation ceremony and is now working at NVIDIA) used in her work.  Jayant Mukhopadhaya and Brian Munguia have also been testing/improving the library.

Perhaps everyone can comment on current status and we can create a small task force to see what still needs to be done and who can do what?

Best,

Juan


On Jun 17, 2019, at 10:36 AM, Clark Pederson <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to jump on this too. Is anyone working on solution interpolation (from one mesh to another)? @sravya91<https://github.com/sravya91>, are you still working on this? Did PR #672<https://github.com/su2code/SU2/pull/672> introduce any capabilities to address interpolation? This seems to be a common request from SU2 users: [1]<https://www.cfd-online.com/Forums/su2/213321-su2-solution-interpolation.html> [2]<https://www.cfd-online.com/Forums/su2/215920-use-coarse-grid-flow-solution-initial-solution-fine-grid.html>

I've used some pretty rough python scripts to do solution interpolation in the past, and it would be nice to have some SU2 C++ code that could perform the same task.

**Comment by clarkpede** [comment]
@bmunguia @jayantmukho @sravya91 @vdweide Do you have any comments on the interpolation in SU2?

**Comment by vdweide** [comment]
The interpolation tool I use is a standalone program and not integrated into SU2. However, it is possible that @bmunguia and @jayantmukho have integrated it into SU2. Is that the case?

**Comment by auzbaig** [comment]
Hi all,
I am starting to work on inlet file interpolation capability where it can read an inlet file given in cylindrical coordinates (for a turbomachinery case, say, radius against TotalPressure), convert to cartesian and map onto the inlet vertices (all vertices at a given radius). Is anyone working on something similar? This is different from volume mesh interpolation and involves only surface elements. I have started another issue at #791  where I am looking for a piecewise interpolation function to achieve this. Please pitch in any idea you have.

@vdweide @clarkpede @economon @juanjosealonso @sravya91 @bmunguia @jayantmukho
