### ISSUE TITLE
Incompressible rotating reference frame issues

### ISSUE THREAD

**Issue by koodlyakshay** [su2code/SU2#468]
Hello,
When using the rotating reference frame option with incompressible flow the code blows up immediately. There appears to be two issues - 
1. Omega_ref is not initialized in the SetNondimensionalization subroutine in solver_direct_mean_inc.cpp. In the compressible version, it is defined as Velocity_ref/Length_ref whereas no definition exists in the incompressible one.
2. Since all the definitions of gas constants have been removed from the incompressible routines, using Mach_motion to normalize forces and moments makes them all undefined. 

While both the fixes are easy, it might still lead to issues when free stream velocity is zero as Omega_ref is used to normalize grid velocities in SetRotationalVelocity. 
Is it possible to implement a new config option to compute Omega_ref differently and also use it to normalize forces?

Cheers,
Akshay

**Comment by economon** [comment]
Hi Akshay: 

Both issues are certainly true, plus there are even more problems :). At the moment, the incompressible solver does not have an implementation of the ALE terms needed for grid motion cases, and it is likely that the rotating source term should be double-checked. We are in the midst of a big update to the incompressible solver as we speak though, and this is on the list.

First, can you get by with the compressible code at low (but reasonable) Mach numbers for now, say 0.1? Second, are you interested in developing some of these capabilities (ALE, rotating frame) once we finish the incompressible solver upgrade?

Tom

**Comment by koodlyakshay** [comment]
Hi Tom,
     
I would like to work on the ALE and rotating frame implementations for incompressible solver. Under Edwin's guidance I have been looking at SU2 closely over the past few months and, as you might have heard from him, we are looking to implement a pressure based scheme. 

Also, could you tell me more about what are the changes you are planning for the incompressible solver? 

Thanks a lot.
Regards,
Akshay
