### ISSUE TITLE
2nd Annual SU2 Developers Meeting

### ISSUE THREAD

**Issue by economon** [su2code/SU2#470]
Dear Developers,

Here is a good "issue" for a change :). This post is an announcement for you all to save the date:

**2nd Annual SU2 Developers Meeting
December 18-19, 2017
Stanford University Campus**

The first day will feature public presentations, and the second day will contain discussion about future direction, strategy, etc.

You are all invited to participate, either remotely through a virtual meeting or in-person. If you are interested in presenting your SU2 work on the first day, please let us know. If you have any questions or comments, feel free to share them on this thread. **Suggestions for topics or pressing issues that you as developers would like to see addressed in the meeting are particularly appreciated!**

As always, thank you for being a part of this great open-source community. Please do get involved: the developer community is critical to the success of the SU2 project.

More info as we have it,
Tom

**Comment by EduardoMolina** [comment]
Dear Developers,

If it is possible, I would like to present to the SU2 community my work on Hybrid RANS/LES  implementation focus on Grey Area Mitigation methods. Unfortunately, Stanford is at a long distance from Brazil and I think I will need to participate remotely :).

Thank you very much for this absolutely great and very active open-source community. 

Regards,

Eduardo.

**Comment by economon** [comment]
We now have an official registration form for the meeting. Please fill out the form when you have a moment:

[2nd Annual SU2 Developers Meeting Registration](https://docs.google.com/forms/d/e/1FAIpQLSeUqZmTvRL2PJ4a_nSSECpnlSvrBfm5E5D01qHl6Bd_pbJk4A/viewform?usp=send_form)

Apart from basic participation information, there is a question to specify whether you are interested in presenting your work on the first day. We will send follow-up emails to those that register, including virtual meeting info if necessary.

@EduardoMolina, thanks!

**Comment by koodlyakshay** [comment]
Hi Tom,

I am planning to attend the meeting and I need to apply for a visa. Could you give some details about whom to contact for the official invite letter?

Regards,
Akshay

**Comment by TobiKattmann** [comment]
Hi @economon ,

I would like to take a quick glance on the presented slides in advance. I always find it easier to follow when I already know whats coming my way. I know that slides are often finished the exact second before the presentation but maybe I am lucky.

Also considering that it is quite late here in Germany and the concentration level might drop a little, although you scheduled the Conference quite "Europe-friendly" :) 

Thanks already,
Tobi

**Comment by juanjosealonso** [comment]
Tobi,

We have asked all presenters for slides on Sunday.  We will link them to the agenda in the SU2 main web pages shortly after we receive them and you should be able to see them on Monday morning (your morning) and have a few hours to review them before the actual meeting starts at 8 am Pacific / 5pm in Germany.

Best wishes,

Juan

On Dec 15, 2017, at 1:48 AM, TobiKattmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @economon<https://github.com/economon> ,

I would like to take a quick glance on the presented slides in advance. I always find it easier to follow when I already know whats coming my way. I know that slides are often finished the exact second before the presentation but maybe I am lucky.

Also considering that it is quite late here in Germany and the concentration level might drop a little, although you scheduled the Conference quite "Europe-friendly" :)

Thanks already,
Tobi

**Comment by economon** [comment]
Time to close this one. Thanks all for the participation. The presentations and webinar recording of the developers meeting can be found on the SU2 home page.
