### ISSUE TITLE
"NON" binary file writing error at DDES developing version.

### ISSUE THREAD

**Issue by yukaiweng** [su2code/SU2#474]
Dear Team SU2,

 I've downloaded and compiled the latest developing version of SU2 with DDES feature.
However, since I need to read the solution file in the non-binary format for further process.  I both set NO at WRT_BINARY_RESTART and READ_BINARY_RESTART option.
However, when I open the non-binary restart file, say by excel, some solution values are merged into the wrong column or just missing. And now these mislocated data make the non-binary solution file cannot be used for restart simulation ( a Diverged warning message will pop up ).
Also based on the observation, these kinds of data writing error appeared in every 9 or 10 point id in general, for example, the first error shows in pointID # 9, then # 18...so on.  The example error file is attached.

Could you please advise me if there is any quick fix for this issue. Or is there any converter inside the SU2 that I can run the simulation in binary first then convert them later?

Thank you very much.

Sincerely,
Yu-Kai Weng

[restart_flow_nb_00000.zip](https://github.com/su2code/SU2/files/1493197/restart_flow_nb_00000.zip)

**Comment by talbring** [comment]
It looks like the file you provide was already preprocessed by some text editor. Can you provide the original file to see if there is something wrong ?

**Comment by yukaiweng** [comment]
Hello Talbring,

Thanks for your replying. The original file is attached.

[restartfile.zip](https://github.com/su2code/SU2/files/1497438/restartfile.zip)

**Comment by yukaiweng** [comment]
Hello Talbring,

Thanks for your replying. I put some sample original non-binary file which has mislocated or missing data, and cannot be read as restart file in google drive [here.](https://drive.google.com/drive/folders/1kmAqTV-HyHH6y2o1zxPVLEJ5pU2LRebl?usp=sharing)

Another bad written non-binary file is attached.
[badfile.zip](https://github.com/su2code/SU2/files/1497587/badfile.zip)


Thank you very much.
Yu-Kai Weng
