### ISSUE TITLE
adjoint.dat residuals all equal zero

### ISSUE THREAD

**Issue by ZenBel** [su2code/SU2#475]
Hello, 

all the residuals in the adjoint.dat file written after running a continuous adjoint simulation ( with the option WRT_RESIDUALS= YES) are zero. 

Here are the config file and mesh for the QuickStart example which also has this problem
[files.zip](https://github.com/su2code/SU2/files/1495681/files.zip)

**Comment by economon** [comment]
Hi @ZenBel, 

Thanks for the notice. You can fix this quickly by replacing the line

`LinSysRes.SetBlock_Zero(iPoint);`

with 

`if (!Output) LinSysRes.SetBlock_Zero(iPoint);`

in CAdjEulerSolver::Preprocessing() for Euler or CAdjNSSolver::Preprocessing() for N-S within the file solver_adjoint_mean.cpp.

We will fix this up properly in the source soon. Please reopen the issue if this doesn't fix the issue for you.

Tom
