### ISSUE TITLE
What does the LAPACK compile option actually do?

### ISSUE THREAD

**Issue by clarkpede** [su2code/SU2#478]
When compiling SU2, it appears the LAPACK can be used for some linear solver routines.  There's a optional compile flag `--with-LAPACK-lib` and a `LAPACK support:       no` readout. There's even a comment in the configure.ac file: `LAPACK connection added by Teus van der Stelt, 11/13/2014`

However, I can't find any code at all that uses LAPACK.  At least, there aren't any sections that switch on with `HAVE_LAPACK`.  Am I missing something? Was this removed at some point? Is there a branch that does have this integration?

**Comment by talbring** [comment]
LAPACK is currently not used at all ... we probably need to clean up the configure script at some point.

**Comment by vdweide** [comment]
I use LAPACK as well as BLAS in the DG solver. As we plan to merge the DG solver into the develop version, I suggest we leave it in.

**Comment by rsanfer** [comment]
We recently had a student who had to use LAPACK for new interpolation schemes. His work was great, so from our side it's also worth leaving it in, as we might want to merge that in eventually.

**Comment by talbring** [comment]
Didn't know that :) So the `--with-LAPACK-lib` option actually still works? Then we can definitely leave it in.

**Comment by clarkpede** [comment]
Ok.  Thanks for the clarification.

**Comment by rsanfer** [comment]
In our case, he added the libraries himself and I believe he did some stuff in the configure file in his fork, so I wouldn't be sure whether the `--with-LAPACK-lib` option works as is.

**Comment by vdweide** [comment]
Same for me.
