### ISSUE TITLE
Poor Initial Grid Distribution (ParMETIS Issue)

### ISSUE THREAD

**Issue by gmandrews** [su2code/SU2#479]
I am having issues with grid partitioning for a large case I am trying to run in parallel. I have a 3D grid for a sharp cone with 86 million cells, and I suspect that I am running into a memory issue with ParMETIS. I get a series of errors of the form "PARMETIS ERROR: Poor initial vertex distribution. Processor 384 has no vertices assigned to it!" and then this message at the end of partitioning:

"Finished partitioning using ParMETIS (0 edge cuts).
Communicating partition data and creating halo layers.
0 interior elements including halo cells.
0 vertices including ghost points."

Naturally, when the case tries to run, it then gives me a segfault. I have tried running the case with different numbers of processors (512, 864, 1024) and I have also tried leaving each node with 50% of its cores idle for more available memory in each node (maintaining the same overall number of active processors) but I still seem to get the same problem.

Any suggestions?

**Comment by economon** [comment]
Hi @gmandrews: we have been working hard on issues related to the partitioning / memory, and we have a branch that is under testing and nearly complete. Can you please try your case with the branch here, when you have a moment, to see if the performance is any better?

https://github.com/su2code/SU2/tree/fix_partitioning

**Comment by gmandrews** [comment]
Thanks for the quick response! I tried again and had the same issue.

**Comment by demanosalvas** [comment]
HI @gmandrews I have been running really large cases lately (~100M cells in over 1000 processors) and there are some issues when you go above ~1000 processors due to the mpi calls. @economon has been working of fixing this in the branch that he mentioned, but looking at the info you are providing, I think your problem is with PARMETIS. Can you make a clean build of everything? Up to what size grid/partitions are you able to run without any problems?

**Comment by gmandrews** [comment]
@demanosalvas that's good to know; it seemed like a ParMETIS issue to me, as well. SU2 seems to build all right, and I have successfully run up to 25M cells with 640 processors.

**Comment by demanosalvas** [comment]
@gmandrews did you try a clean installation of SU2 and ParMETIS yet?

**Comment by gmandrews** [comment]
@demanosalvas I tried a clean build of the branch which @economon suggested but experienced the same problem.
