### ISSUE TITLE
Ability to link to alternate LAPACK libraries

### ISSUE THREAD

**Issue by brada4** [su2code/SU2#481]
Could it be possible to alter configure system to allow different lapacke as your user wanted here:
https://github.com/xianyi/OpenBLAS/issues/1383
Also since we talk about linking statically tens of megabytes of blobs into final module - could the (user-specified) LAPACK library (optionally or by default) get imported dynamically?

**Comment by clarkpede** [comment]
What is your goal in including LAPACK?

You might want to see the issue I raised ( #478 ).  I asked what the LAPACK compile option does, and the short answer is that it doesn't do anything for the master and develop branches.  The long answer is that several integrations, such as the higher-order finite element branch, use LAPACK but in different ways.

**Comment by brada4** [comment]
I figured that out too. The linked problem was one of su2 users asking how to make openblas do that nothing in place of reference blas
