### ISSUE TITLE
Aerodynamic Shape Optimization: Solution restarting procedure & Exporting the final shape as 3D CAD model

### ISSUE THREAD

**Issue by jkputtam** [su2code/SU2#489]
Dear SU2 Team Members,

Greetings! We are very happy to inform you that we are exploring the aerodynamic shape optimization script of SU2 R 5.0.0 (Raven) with different configurations. And we would also like to seek your assistance in connection with the following two issues:

1. We are not getting any clue on restarting procedure of the optimization process from previously finished cycles.

2. Is there any way for exporting the intermediate / final optimized geometry as 3D CAD model.

Thanking you in advance.

Regards,
Jyothi Kumar Puttam.

**Comment by jkputtam** [comment]
Dear SU2 Team Members,

Greetings! We are very happy to inform you that we are exploring the aerodynamic shape optimization script of SU2 R 5.0.0 (Raven) with different configurations. And we would also like to seek your assistance in connection with the following two issues:

We are not getting any clue on restarting procedure of the optimization process from previously finished cycles.

Is there any way for exporting the intermediate / final optimized geometry as 3D CAD model.

Thanking you in advance.

Regards,
Jyothi Kumar Puttam.

**Comment by talbring** [comment]
Hi Jyothi,

for questions like that I would kindly refer you to the official forum ([https://www.cfd-online.com/Forums/su2/](https://www.cfd-online.com/Forums/su2/)). 

Tim

**Comment by jkputtam** [comment]
Dear Tim,

Thank you so much. I will post on CFD-ONLINE right now.

Regards,
Jyothi Kumar Puttam.
