### ISSUE TITLE
Xcode SU2_CFD project failed to build in develop branch

### ISSUE THREAD

**Issue by EduardoMolina** [su2code/SU2#499]
Dear SU2 developers,

Xcode is failing to build the SU2_CFD project in develop branch (commit f699102ed6cb6e4ee4a79d8bdbbcf80304cc5f9b). It is related to various issues in CFluidDriver::SetInitialMesh(), CFluidDriver::ResetConvergence(), CFluidDriver::BoundaryConditionsUpdate(), etc....

Thanks,

Eduardo

**Comment by tobadavid** [comment]
I forgot to update the Xcode project when I moved some Python related functionalities into a new cpp file, my bad (see #488 ). Seems like #497 may fix this.

**Comment by EduardoMolina** [comment]
Thank you David.

Good to hear that this issue is already addressed. When this issue is solved, I will close it.

Eduardo
