### ISSUE TITLE
Non-constant experssion in array definition

### ISSUE THREAD

**Issue by ali-ramezani** [su2code/SU2#5]
I saw in 8 places of the code that non-constant expression have been used which are illegal in standard C/C++.
Since by default the Gcc enables new extensions you can not see these errors but actually you don't need those extension and at this moment they weaken potability of your code. 
To see these errors you can add -pedantic-errors switch to gcc or compile it by Microsoft Visual Studio.
I list them in the following (version 2.0.8). I changed them to pointer and the code can be compiled in microsoft visual studio without any change.
1- geometry_structure.cpp -> Line 11597 ->NewSort[nPoint]
2- config_structure.cpp      -> Line 1459  -> periods[N_MOTION_TYPES]
3-solver_structure.cpp       -> Line 1354  -> Solution[nVar]
4-                                     -> Line 1566  -> Solution[nVar]
5-solver_direct_tne2.cpp    -> Line 4469  ->  FluxTensor[nVar][nDim]
6-solver_direct_mean.cpp  -> Line 4124~4132 -> FanFace_MassFlow_local[nMarker ...]
7-solver_direct_mean.cpp  -> Line 4146~4150 -> Exhaust_MassFlow_local[nMarker ...]
8-numerics_direct_transition.cpp ->Line 152,153 -> Density_Grid_i[nDim],...

**Comment by hlkline** [comment]
I apologize that we have taken a long time to respond to this. I am not sure whether this issue has been fixed at some point in between. 
If you don't mind, can you check through the current version of the code, an if this is still an issue submit a pull request with the changes you mentioned above? 
When forking the code and making a pull request, be sure to base your changes on the develop branch.

**Comment by hlkline** [comment]
It looks like these have been fixed at some point in the last three years, I am closing the issue. Please reopen the issue if I have missed something.
