### ISSUE TITLE
LM model in su2

### ISSUE THREAD

**Issue by sysu-tanlang** [su2code/SU2#502]
Just noticed that LM transition model in su2 is does not work. How can I use LM model in current su2? Thank you!

**Comment by vdweide** [comment]
The LM transition model is still under development.

**Comment by vdweide** [comment]
So I am closing this for now. It will be announced when this model becomes available.

**Comment by sysu-tanlang** [comment]
> So I am closing this for now. It will be announced when this model becomes available.

Hello, vdweide. Thank you for your attention and this contribution. Did you ever try some testcases?  I am a beginner SU2 user. Can you maybe give us a configure file about S-K transition flat plate using LM model? Thank you!

**Comment by sametcaka** [comment]
Below you can find a transitional test case using B-C model implemented in SU2:
https://su2code.github.io/tutorials/Transitional_Flat_Plate/

**Comment by sysu-tanlang** [comment]
> Below you can find a transitional test case using B-C model implemented in SU2:
> https://su2code.github.io/tutorials/Transitional_Flat_Plate/

Samet, nice to meet you! Thank you for your suggestion! I have learned this model in current SU2 version. B-C model can provide quite good results in many teatcases.
