### ISSUE TITLE
Discrete adjoint problem with INVERSE_DESIGN_PRESSURE objective function

### ISSUE THREAD

**Issue by ZenBel** [su2code/SU2#515]
When running discrete_adjoint.py (or shape_optimization.py with a discrete adjoint method) for the test case steady_inverse_design, the value of the adjoint variables at the first iterations is already O(1e-10) and after a while the following message is printed on screen:

CSysSolve::FGMRES(): system solved by initial guess.

This problem does not occur when using other objective functions or a continuous adjoint method.

P.S. I am using SU2 v 6.0.0.

**Comment by ZenBel** [comment]
This problem could be solved by inserting the following lines after DirectRun(); in CDiscAdjFluidDriver::SetRecording(unsigned short kind_recording):

  if (config_container[ZONE_0]->GetInvDesign_Cp() == YES){
    output->SetCp_InverseDesign(solver_container[ZONE_0][MESH_0][FLOW_SOL],
	  geometry_container[ZONE_0][MESH_0], config_container[ZONE_0], ExtIter);
  }

Probably, this should also be done for INVERSE_DESIGN_HEATFLUX.

**Comment by economon** [comment]
Thanks for the feedback.. this is resolved in #600
