### ISSUE TITLE
Why does SU2 mesh format have element IDs?

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#52]
The SU2 mesh format states that the elements must have IDs "The final value is the element index given to each interior element in the mesh.". However, these values are completely ignored by SU2 (see geometry_structure.cpp in the code section starting with '/*--- Read the information about inner elements ---*/' around line 2981). Given that SU2 doesn't use them, we may as well remove them from the specification. They just make mesh files larger.

**Comment by hlkline** [comment]
It looks like this is another parallel vs serial behavior thing, as with https://github.com/su2code/SU2/issues/47, please reopen if you disagree.

**Comment by btracey** [comment]
I don't think it's resolved, but it will be resolved when #47 is resolved, so closing this is appropriate.
