### ISSUE TITLE
In parallel, SU2 is not working

### ISSUE THREAD

**Issue by LEESHQI** [su2code/SU2#521]
Hi, all !
There are some problems in the parallel computing of SU2, as shown in the following figure：
![su2_run](https://user-images.githubusercontent.com/37644741/38185974-37e443e8-3683-11e8-9a0e-b3b645159b76.jpg)

**Comment by vdweide** [comment]
From the picture it looks like you use the python script, but that is about all I could see. Could you therefore give some more details? What operating system do you use? How did you compile the code? What version of MPI do you use?

**Comment by juanjosealonso** [comment]
It looks like the SU2_RUN environment variable was not set as described here<https://su2code.github.io/docs/Build-from-Source/>.  Scroll to near the bottom for more details.

Best,

Juan

On Apr 2, 2018, at 12:00 AM, Edwin van der Weide <notifications@github.com<mailto:notifications@github.com>> wrote:


From the picture it looks like you use the python script, but that is about all I could see. Could you therefore give some more details? What operating system do you use? How did you compile the code? What version of MPI do you use?

**Comment by LEESHQI** [comment]
Thanks for Edwin van der Weide, I am using a Windows 7 system and compile SU2 with cygwin. The MPI version is 9.0.1247497.11. I am a newcomer to SU2 and following the tutorial now , but there is a problem with ONERAM6 parallel computing.
The following figure shows the contents of the tutorial：
The following figure shows the errors in the calculation：
Serial computing can run normally。
Thanks again, I hope you can help me !





At 2018-04-02 15:00:05, "Edwin van der Weide" <notifications@github.com> wrote:


From the picture it looks like you use the python script, but that is about all I could see. Could you therefore give some more details? What operating system do you use? How did you compile the code? What version of MPI do you use?

**Comment by chamsolli** [comment]
Seems like your figures are not attached. Please upload them again.

Also, please double check whether your "SU2_RUN" environment variable is set correctly as Juan mentioned. If serial computation worked fine only with "$ SU2_CFD inv_ONERAM6.cfg" command, I guess you set it correctly. However, from your error message, python script says it can't find a path to "SU2_RUN"

**Comment by vdweide** [comment]
I am not entirely sure, but as far as I know SU2 has not been tested on cygwin. So if the setting of the SU2_RUN environment variable does not solve the problem, could you test it without python? You do this using the following command

mpirun -np <# of ranks> <path to SU2 bin directory>/SU2_CFD.exe inv_ONERAM6.cfg.

It could be that instead of mpirun you must use mpiexec. That depends on your MPI implementation.

**Comment by EduardoMolina** [comment]
Using Cygwin's OpenMPI you can compile SU2 using the following command:

$SU2_HOME/configure --prefix=$SU2_EXEC --enable-mpi --with-cc=/usr/bin/mpicc --with-cxx=/usr/bin/mpicxx --enable-metis   --with-metis-cppflags="-D_FILE_OFFSET_BITS=64 -DNDEBUG -DNDEBUG2 -DHAVE_GETLINE -DMETIS_USE_LONGINDEX=1" --enable-parmetis --with-parmetis-cppflags="-DMETIS_USE_LONGINDEX=1" --enable-cgns

Ok, you will not have the same performance as a linux distribution but you will be able to run SU2.

I hope it can help.

Best,
Eduardo
