### ISSUE TITLE
3d case in SU2

### ISSUE THREAD

**Issue by subhanjan21** [su2code/SU2#523]
Hey.
I have been performing simulations and validating results using SU2. I have successfully carried out 2D cases. However, I am having a hard time while doing 3D cases. 
Can anyone share an example of a 3D case config file dealing with Euler and Navier-Stokes equation?
Thank you.

**Comment by chamsolli** [comment]
Hi,
There are some examples for 3D simulations in tutorials.
https://su2code.github.io/tutorials/Inviscid_ONERAM6/
https://su2code.github.io/tutorials/Turbulent_ONERAM6/

**Comment by subhanjan21** [comment]
Yes I know about the ONERAM examples. But the mesh files and config files do not match as their boundary conditions are different. Could you share your config file and meshed file to me regarding ONERAM ? 
Thank you.

**Comment by chamsolli** [comment]
I just pulled the master branch of SU2 and it worked fine with configuration file and mesh file. Which files did you use for your 3D simulation? You may download files from following links.

Inviscid : https://github.com/su2code/su2code.github.io/tree/master/Inviscid_ONERAM6
Turbulent : https://github.com/su2code/su2code.github.io/tree/master/Turbulent_ONERAM6

**Comment by subhanjan21** [comment]
@chamsolli 
I am trying to configure my own 3D Euler case for this mesh.
![capture](https://user-images.githubusercontent.com/31462793/38834251-7f1740ca-418d-11e8-962c-8e778331955e.JPG)

**Comment by chamsolli** [comment]
Please do run tutorial cases for 3D Euler and NS(Inviscid and Turbulent ONERAM6) first before running your own implementation. Tutorial pages are self-explanatory so I expect that you can easily grab which boundary markers to use in your implementation. 
As I said in previous comment, boundary conditions in config file and mesh file do match at least inviscid case.

**Comment by subhanjan21** [comment]
Thank you @chamsolli 
However, it says that some of the options like coefficients and binary restart are not analogous to the config file of SU2.
![screenshot from 2018-04-16 16-03-29](https://user-images.githubusercontent.com/31462793/38835288-c18a81e4-4190-11e8-8aae-d28eabbbc0d1.png)

**Comment by chamsolli** [comment]
Seems like you're using older version of SU2 master branch. We didn't have several config options such as "WRT_BINARY_RESTART" in older version. That's the reason why your SU2_CFD executable throws error message regarding it.
Please clean your SU2 directory, pull fresh copy of master branch of SU2, compile it and then run it.

**Comment by chamsolli** [comment]
No problem. I recommend you to open an issue here when you have some difficulties. Most of developers will look into issues so you'll have more chance to get some help.
