### ISSUE TITLE
Oversubscribe / hwthreads with parallel_computation.py and OpenMPI 3.0.1

### ISSUE THREAD

**Issue by timjim333** [su2code/SU2#526]
Hello,

I have a hyperthreaded 6-core machine (12 processors available) but I have the following issue when I try to specify `parallel_computation.py -n 12`. 
```
tjim@t3500:/opt/su2/SU2/TestCases/rans/oneram6$ parallel_computation.py -n 12 -f turb_ONERAM6.cfg 
Traceback (most recent call last):
  File "/opt/su2/SU2v6.0.0/bin/parallel_computation.py", line 116, in <module>
    main()
  File "/opt/su2/SU2v6.0.0/bin/parallel_computation.py", line 67, in main
    options.compute      )
  File "/opt/su2/SU2v6.0.0/bin/parallel_computation.py", line 94, in parallel_computation
    info = SU2.run.CFD(config) 
  File "/opt/su2/SU2v6.0.0/bin/SU2/run/interface.py", line 122, in CFD
    run_command( the_Command )
  File "/opt/su2/SU2v6.0.0/bin/SU2/run/interface.py", line 302, in run_command
    raise exception(message)
SU2.EvaluationFailure: Path = /opt/su2/SU2/TestCases/rans/oneram6/,
Command = mpirun -n 12 /opt/su2/SU2v6.0.0/bin/SU2_CFD config_CFD.cfg
SU2 process returned error '1'
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 12 slots
that were requested by the application:
  /opt/su2/SU2v6.0.0/bin/SU2_CFD

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```
It works if `-n 6` is used instead but then only half of the availalbe processes are being used.

I'm not sure if this is a bug with parallel_computation.py (or just a "feature" which has not yet been implemented) but using SU2 6.0.0, not all my processing threads can be used when using OpenMPI 3.0.0. I think this is due to the fact that it's not possible to pass `--use-hwthread-cpus` to `mpirun` as is mentioned on the StackOverflow page, [here](https://stackoverflow.com/questions/48835603/unable-to-use-all-cores-with-mpirun).

As a workaround, have tried
`tjim@t3500:/opt/su2/SU2/TestCases/rans/oneram6$ mpirun --use-hwthread-cpus -np 12 SU2_CFD turb_ONERAM6.cfg`
which seems to work ok. Is there any way to incorporate this into parallel_computation.py?

**Comment by TobiKattmann** [comment]
Hi @timjim333 ,

you can try to set an environmental variable 'SU2_MPI_COMMAND' which contains your specific mpirun command. Take a look at /SU2_PY/SU2/run/interface.py (line 66) in the source code, that might help. There the command which is called by parallel_computation.py is build.

For your case it should be:
export SU2_MPI_COMMAND="mpirun --use-hwthread-cpus -np %i %s"

I hope that helps :) Regards,
Tobi

**Comment by timjim333** [comment]
Hi @TobiKattmann ,

Thanks for your comment, sorry for the slow reply! I'm not 100% sure I understand the usage -  do you mean that I should first `export SU2_MPI_COMMAND="mpirun --use-hwthread-cpus -np %i %s"` then run `parallel_computation.py -n 12 -f  turb_ONERAM6.cfg `?

I suppose that %i is that number of core but what about %s?

Many thanks! =)
Tim

**Comment by TobiKattmann** [comment]
Hi @timjim333 ,

Exactly (concerning your first question). 

For the %s : In your initial post you stated that `mpirun --use-hwthread-cpus -np 12 SU2_CFD turb_ONERAM6.cfg`  worked for you. So %s is simply the place-holder for the SU2 module together with the configure script. Which in your case would be `SU2_CFD turb_ONERAM6.cfg` . But `parallel_computation.py` will also call `SU2_SOL turb_ONERAM6.cfg` for you after the solver routine to create output files for visualization. 
If you take a look into the `interface.py` (as in my previous post) and the `parallel_computation.py` you'll find exactly how its done.

Cheers, Tobi

**Comment by timjim333** [comment]
Hi @TobiKattmann ,

Apologies for the huge gap in communication - I had to attend to other matters before I could try this out. I just wanted to follow up and thank you for your suggestions. Doing `export SU2_MPI_COMMAND="mpirun --use-hwthread-cpus -n %i %s"` before calling 'parallel_computation.py' did the job!

Is it safe for me to edit line 70 in  interface.py from  `mpi_Command = 'mpirun -n %i %s'` to  `mpi_Command = 'mpirun --use-hwthread-cpus -n %i %s'` so that it is set permanently? Or is it better to put `export SU2_MPI_COMMAND="mpirun --use-hwthread-cpus -n %i %s"` in my .bashrc?

Many thanks and kidn regards,
Tim

**Comment by TobiKattmann** [comment]
Hey @timjim333  that's nice to hear,

I would put it in the .bashrc if you consistently call SU2 with your command, like that you can always switch the SU2-build and still have your clear settings already in place. Image having the master, develop and feature_whatever installed, you don't need to apply your patch to all of these versions if you put it in the bashrc.
But editing interface.py has the same effect, so its up to you what you prefer.

Tobi

**Comment by timjim333** [comment]
Just realised that I never closed this issue. Your fix works fine!

Thanks and regards,
Tim
