### ISSUE TITLE
Overflowing index in python_wrapper_structure.cpp

### ISSUE THREAD

**Issue by aa-g** [su2code/SU2#529]
This issue concerns the index `iVertex` that appears in the `CDriver` classes, defined in *SU2\_CFD/src/python_wrapper_structure.cpp* (rather, what was formerly *SU2\_CFD/src/driver_structure.cpp* in 5.0.0). Due to `iVertex` being declared as an `unsigned short`, one runs into overflow errors when more than 65535 surface nodes are "owned" by a single process (not uncommon for larger models). 

Declarations of `iVertex` as `unsigned short` may perhaps be more appropriate as `unsigned long` ?

**Comment by economon** [comment]
This one should be a quick fix and looks to be important.. let's keep it open.

**Comment by pcarruscag** [comment]
It shall be fixed in #807
