### ISSUE TITLE
NACA 0012 Mesh doesn't specify element node numbers 

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#53]
The SU2 mesh file format states that elements must have node numbers ("The final value is the element index given to each interior element in the mesh"). The NACA 0012 mesh does not have them, and thus doesn't follow the specification. See issue 52 for possible alternative resolution.

**Comment by hlkline** [comment]
Could you please specify which naca 0012 mesh did not have node numbers? I believe many of these meshes have been updated in the last few months.

**Comment by btracey** [comment]
Yep, this has been fixed. Thanks.
