### ISSUE TITLE
python wrapper and AD tool

### ISSUE THREAD

**Issue by najianaslreza** [su2code/SU2#539]
Dear all,

I am trying to use the python wrapper with AD tool support. For example I want to use CDiscAdjFluidDriver(options.filename, 1, 3, comm) but it fail and returns there is no AD support for python wrapper. 

Do you know how I can solve it ?!

@talbring @tobadavid 

Cheers,

reza

**Comment by talbring** [comment]
Dear Reza,

like the error message already implies, currently the python wrapper does not support the AD features. It is on our list, but I cannot give an estimate when it will be available.

Tim

Am 04.06.2018 13:46 schrieb najianaslreza <notifications@github.com>:

Dear all,

I am trying to use the python wrapper with AD tool support. For example I want to use CDiscAdjFluidDriver(options.filename, 1, 3, comm) but it fail and returns there is no AD support for python wrapper.

Do you know how I can solve it ?!

Cheers,

reza
