### ISSUE TITLE
Unable to find "configure" file 

### ISSUE THREAD

**Issue by ReenaAcharya** [su2code/SU2#549]
Hi,

I downloaded su2-***.tgz file for ubuntu server. I uncompressed it. 
When I am using following command:-
 ./configure --prefix=/root/downloads/su2-6.1.0
I get following error:-
-su: ./configure: No such file or directory

Need suggestion here. 

Thanks,
Reena

**Comment by ReenaAcharya** [comment]
Hi,

Any update on this. Need suggestion urgently.

Thanks.

**Comment by rsanfer** [comment]
This issue has already been dealt with in the forum, 
https://www.cfd-online.com/Forums/su2/203777-unable-find-configure-file.html
