### ISSUE TITLE
Unable to compile Python wrapper (invalid static_cast in parallel, undefined symbols in serial)

### ISSUE THREAD

**Issue by mprogram** [su2code/SU2#551]
Branch: `master` or `develop` (in this exampe)
`swig`: either 3.0.12 or 4.0.0 (more warnings, master branch, in this example)
`mpicxx`, a wrapper to `g++` (Ubuntu 8.1.0-9ubuntu1) 8.1.0
`mpi4py`: either 2.0.0 or 3.0.1a0 (master branch)

Steps to reproduce (compile SU2 in `$SU2_HOME` first):

`cd $SU2_HOME/SU2_PY/pySU2`

`swig -Wall -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -outdir ./ -o SU2_APIPYTHON_wrap.cxx -c++ -python pySU2.i`

`../../Common/include/mpi_structure.hpp:417: Warning 202: Could not evaluate expression 'defined(__GNUC__) || (defined(__ICC) && (__ICC >= 600))'`
`../../Common/include/mpi_structure.hpp:417: Warning 202: Error: 'Can't mix strings and integers in expression'`
`../../Common/include/mpi_structure.hpp:423: Warning 202: Could not evaluate expression 'defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901)'`
`../../Common/include/mpi_structure.hpp:423: Warning 202: Error: 'Can't mix strings and integers in expression'`
`../../Common/include/mpi_structure.hpp:425: Warning 202: Could not evaluate expression 'defined(__cplusplus) && (__cplusplus >= 201103)'`
`../../Common/include/mpi_structure.hpp:425: Warning 202: Error: 'Can't mix strings and integers in expression'`
`../../Common/include/mpi_structure.hpp:317: Warning 325: Nested struct not currently supported (Status ignored)`

`mpicxx -DHAVE_HDF5 -I/usr/include/hdf5/openmpi -DHAVE_SZIP -I/usr/include -DHAVE_ZLIB -I/usr/include -DHAVE_MPI -DHAVE_MUTATIONPP -I/usr/include/mutation++ -DHAVE_JSONCPP -I/usr/include/jsoncpp -I/usr/include/python2.7 -D_FORTIFY_SOURCE=2 -fPIC -O3 -I../../externals/metis/include -I../../externals/parmetis/include -I../../externals/tecio/include -I../../externals/cgns -I../../externals/cgns/adf -I../../Common/include -I../../SU2_CFD/include -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7 -c SU2_APIPYTHON_wrap.cxx -o SU2_APIPYTHON_wrap.o # $CXX $pySU2_CC_FLAGS $PY_INCLUDE -c $SWIG_WRAP_REAL.cxx -o $SWIG_WRAP_REAL.o`

`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:6704:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CGeneralDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:9766:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CFluidDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:10047:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CTurbomachineryDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:10597:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CDiscAdjFluidDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:10822:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CDiscAdjTurbomachineryDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:11053:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CHBDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:11268:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CFSIDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:11524:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CDiscAdjFSIDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:12095:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`
`SU2_APIPYTHON_wrap.cxx: In function ‘PyObject* _wrap_new_CMultiphysicsZonalDriver(PyObject*, PyObject*)’:`
`SU2_APIPYTHON_wrap.cxx:13250:38: error: invalid static_cast from type ‘int’ to type ‘SU2_Comm’ {aka ‘ompi_communicator_t*’}`
`...arg5 = static_cast< SU2_Comm >(val5);`
`......................................^`

`mpicxx -fPIC -shared -Wl,--no-as-needed -o _pysu2.so SU2_APIPYTHON_wrap.o ../../SU2_CFD/obj/libSU2Core.a ../../Common/lib/libSU2.a ../../externals/tecio/libtecio.a ../../externals/parmetis/libparmetis.a ../../externals/metis/libmetis.a ../../externals/cgns/libcgns.a  -L/usr/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu # $CXX $SO_LINK_FLAGS -o $SWIG_SO_REAL $SWIG_WRAP_REAL.o $pySU2_LD_FLAGS`

**(the latter step could not be reached through with** `mpicxx` **in parallel due to the previous errors; if substituted with** `g++` **produces undefined symbols** `nm -u _pysu2.so`, **which is why it could not be imported also with** `python -c 'import pysu2'`**)**

**Comment by clarkpede** [comment]
If I understand, you're calling `swig` manually? The typical way to set up the python wrapper is to use the typical build process (i.e. configure, make, make install) but to include the flag `--enable-PY_WRAPPER` during the configure step.

The build process will automatically call `swig` for you, with the correct arguments.

See the docs for more information: https://su2code.github.io/docs/Python-Wrapper-Build/

**Comment by mprogram** [comment]
No, your assumption of calling `swig` manually is not the cause why I've opened this issue (though, admittedly, "compile SU2 in `$SU2_HOME` first" – for getting the required libraries done – might sound confusing). Trying to be utterly relevant, I only replicated that part of the compilation process (yes, would-be with `--enable-PY_WRAPPER`) where one can explicitly debug the issue (please, have a look at the environment variables substituted by the `configure` script after `#` or post your `objdump -p _pysu2.so`, and/or `nm -u _pysu2.so` as also from the `config.log` your `CXX`, `pySU2_CC_FLAGS`, `PY_INCLUDE`, `SO_LINK_FLAGS`, `SWIG_SO_REAL`, `SWIG_WRAP_REAL`, and `pySU2_LD_FLAGS` to compare the correct arguments). The docs had been definitely read before opening the issue.

**Comment by clarkpede** [comment]
Ok.  I can duplicate your error on my system.  The error seems to be specific to gcc 8.1.  If I switch to gcc 7.2 while keeping everything else the same, the errors disappear and the build completes succesfully.

Unfortunately, I'm not one of the developers who helped write the wrapper.  So I'm out of my depth here.

**Comment by mprogram** [comment]
Following your suggestion I've tried to prepend the compiler with `OMPI_MPICXX=g++-7` to force `mpicxx` using – in the present particular case – `g++-7 (Ubuntu 7.3.0-16ubuntu3) 7.3.0`. Unfortunately. there was no change in the output comparing to that of `gcc-8`. Moreover, neither `clang++ version 7.0.0 (trunk)` resolved the issue, though adding/playing with `-std=gnu++11`, `-std=gnu++14`, `-std=gnu++17`, and `-std=gnu++2a` standards gave more warnings as well as same errors. Anyway, I appreciated your hint at possible `gcc` incompatibilities.

It appears the python wrapper has been broken already for some time – without, actually, anybody truly reporting it. It need some love for sure, so, there is a call for it. Meanwhile if you could share your `_pysu2.so` somewhere it would be greatly appreciated.

**Comment by mprogram** [comment]
I've managed to compile the `_pysu2.so`, indeed, with the typical build process. Fiddling further with manual `swig` a bit, I narrowed where it produces the wrong output: in generating `SU2_APIPYTHON_wrap.cxx`. So, I preserved one made during the build, and then even got the Python 3 wrapper version by running `swig` with the `-py3` key. Both imports are going fine, so, I'm closing the issue.
