### ISSUE TITLE
Error message is ony printed for Rank == 0.

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#564]
Error messages are only printed for Rank == 0, see the function CBaseMPIWrapper::Error

inline void CBaseMPIWrapper::Error(std::string ErrorMsg, std::string FunctionName){
  if (Rank == 0){
    std::cout << std::endl << std::endl;
    std::cout << "Error in \"" << FunctionName << "\": " << std::endl;
    std::cout <<  "-------------------------------------------------------------------------" << std::endl;
    std::cout << ErrorMsg << std::endl;
    std::cout <<  "------------------------------ Error Exit -------------------------------" << std::endl;
    std::cout << std::endl << std::endl;
  }
  Abort(currentComm, 0);
}

This makes sense when the error handler is called collectively, as this avoids a messy output. However, there are quite a few situations where the error handler is not called collectively and therefore the error message is not printed when Rank != 0. Would it therefore be possible to add an additional argument (possibly default argument) to the error handler to inform whether or the call is collective or not?

**Comment by talbring** [comment]
@vdweide I agree, there might be cases where is is useful. I am totally fine with adding an additional argument to the error handler.

**Comment by clarkpede** [comment]
This isn't just a hypothetical problem.

In "CSolver::LoadInletProfile", a specified inlet profile is compared against the loaded grid.  Since each MPI task "owns" a different section of the grid, you can get errors on one task but not another.

Here's the current workaround. The code currently does an `MPI_Allreduce` to check if there were any errors globally, then calls `SU2_MPI::Error` collectively if there were any errors.  The code works fine how it is, but it would be nice if there was a standardized way to approach problems like this.

**Comment by vdweide** [comment]
What about the following?

- Find out the lowest rank that calls the error handler.
- Only this rank writes the error  message.

The tricky part of course is how to find out this lowest rank. A possible solution would be (although I am open for alternatives here)

- The ranks in the error handler send out messages with a very specific tag to all other ranks.
- The ranks in the error handler attempt to receive messages for a certain amount of time or until all messages have been received. Typically MPI_Iprobe would be used for this purpose.
- Keep track of the lowest rank from which an actual message was received.

This may not be very efficient, but you don't care here. Furthermore, not all messages will be received if not all ranks call the error handler. Again, you don't care, because the computation is killed afterwards.

**Comment by vdweide** [comment]
Is it OK if I modify the error handler as described above?

**Comment by economon** [comment]
I am open to any option, but it might be worth taking a look at the newer MPI-3 options for one-sided communication or atomic-type operations. I am not that familiar with the latest, but maybe there are one or two quick calls that would let one rank alone enter the section (like an OpenMP critical section)?

**Comment by talbring** [comment]
For me either option would be fine. Although of course a cleaner option would be to use some of the built-in features of MPI, we might run into compatibility issues with older MPI implementations in that case.

**Comment by economon** [comment]
It was just a thought, in case someone knew of something quick/clean that could handle it with recent features. Otherwise, I think a quick and dirty fix, like you proposed already, Edwin, would work just fine too.

**Comment by vdweide** [comment]
I think it is possible to do this with one-sided communication. However, the window for handling the one-sided communication must be active during the entire simulation. If that is a problem then my earlier solution looks the only way of handling this.
