### ISSUE TITLE
Listing active branches in the main repo

### ISSUE THREAD

**Issue by rsanfer** [su2code/SU2#582]
Hi all, 

I will be opening a number of issues that were raised during the Developers Meeting for discussion, to get things started. One interesting open question is **how many of the branches available in the repo are still active.**

My suggestion is that we all work together in having a list of branches with a short description in order to have an idea of where we stand. I would propose that all of you go through your feature branches and collect the following information about them:

- Branch name
- A two line description on the goal of the branch
- Status of the branch:
  - Under active development (we are adding a new feature here)
  - Complete feature, (not necessarily up-to-date with develop)
    - In such case, latest compatible release
  - Mature feature (not necessarily complete)
  - Test feature, still under consideration
  - Test feature, discontinued
  - Old feature / unknown status
- Can the branch be deleted?

This information would be very valuable, as maybe some people would be interested in continuing old developments, some repetitive work would also be avoided, and collaboration between complementary branches would be enhanced.

I'm happy to help in collecting this information and later cleaning up the repository. Please let me know of your thoughts, but I think we should get this started asap.

**Comment by rsanfer** [comment]
Some additional ideas on this topic:

#### Using Github projects
- For compilation of branches, I have created a github project: https://github.com/su2code/SU2/projects/7
- In there, you can list your active/old branches by adding a note to the relevant column. Please be so kind to mark the name of the branch in bold using Markdown's format (`** my branch name **`).

#### Where do I find my branches?
- We have all worked on branches that we no longer remember, but Github has a really nice feature for this.
- Log-in to your Github user account and go to: https://github.com/su2code/SU2/branches/yours
- All the branches in which you have added at least one commit will be listed there.

#### Old branches
- We have found a lot of branches that are older than the latest release and have no commits ahead of master (you can see this in your branch list).
- This would mean that normally all of their commits have already gone into a released version of SU2 and they are no longer required.
- I am planning to do some cleaning of very old branches to have a more compact structure, however it would be helpful if all the developers could indicate explicitly which branches can be safely removed to avoid any future issue.

**Comment by economon** [comment]
Thanks for getting this started, @rsanfer . I think we all agree this is going to be helpful.

At the end of the meeting, @Kevin-Singh had a very nice suggestion to keep the overhead low on managing the branch information: we can create a small markdown file in the root of the repo (SU2/branch_info.md, for example), and put inside of it a very short template that each developer/owner of a branch should fill out (basically the info you list above). This keeps with our strategy of distributing things, keeping the overhead low, and it will then even show up in PRs or even just in the repo when folks are working on branches offline.

What do you think?

**Comment by rsanfer** [comment]
It may be indeed a good idea for future management; however we also need to solve the issue of the current (large) amount of branches that we have. 

I have just checked the Github project I opened yesterday, and there has been already some branch information added by @jayantmukho, @WallyMaier, @koodlyakshay and @talbring, so it seems it's working well. Have you had a look into that already? I think the overhead is also minimal.

**Comment by talbring** [comment]
Also we still strongly suggest to open Draft Pull Request as soon as possible in the development process even if it still far from being ready. This way discussions can start earlier, potential conflicts can be solved together, regression tests run and you are reminded to frequently merge with develop!
