### ISSUE TITLE
Autoconf/automake options

### ISSUE THREAD

**Issue by rsanfer** [su2code/SU2#584]
In link to a comment from @jayantmukho in  #573, I would like to raise the issue of the current versions of autotools which we maintain in SU2. In particular, in my local machine I can not longer run ./bootstrap, as the compilation of automake fails at:

  GEN      doc/automake-1.12.1
help2man: can't get `--help' info from automake-1.12
Try `--no-discard-stderr' if option outputs to stderr

Searching around the web, this appears to be a known issue when the local machine runs a newer version of Perl (in my case 5.26), see e.g.
http://gnu-automake.7480.n7.nabble.com/bug-29178-Failure-to-build-automake-gt-11-td22684.html 
so I foresee that as we move on this kind of problems will start appearing more often. 

We are still working with automake 1.12 from 2012...

**Comment by vdweide** [comment]
I'm running into problems as well on some machines. So I think it is a good idea to update the autotools to a more recent version. Don't know how much work this is though.

**Comment by economon** [comment]
Resolved in #586
