### ISSUE TITLE
Fixed-lift mode often fails for viscous flows. Needs more testing/verification.

### ISSUE THREAD

**Issue by economon** [su2code/SU2#59]

**Comment by pramsatriapalar** [comment]
I just tried the fixed-lift mode for viscous flow with SU2 v3, and it was not working. Is this issue already resolved in Su2 V.4?

**Comment by economon** [comment]
No changes were made to the fixed-lift mode with the v4.0 release. However, you might try playing with the damping, convergence parameters for the cauchy criteria, or even modifying the lift curve slope that is currently hard-coded (this could be changed). See CEulerSolver::SetFarfield_AoA()in solver_direct_mean.cpp.


On Jul 19, 2015, at 8:57 PM, pramsatriapalar <notifications@github.com<mailto:notifications@github.com>> wrote:


I just tried the fixed-lift mode for viscous flow with SU2 v3, and it was not working. Is this issue already resolved in Su2 V.4?

**Comment by economon** [comment]
Improved version available in v5.
