### ISSUE TITLE
Old PR's

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#593]
There are a couple of old PR's, some of them dating back to 2015. I have the feeling nobody does anything with these anymore and furthermore the corresponding branches are most likely running behind. Should we simply close these old PR's?

**Comment by economon** [comment]
I think it is ok if we send a few polite messages to say that we will close them but that they should feel very welcome to update their branches and resubmit the PRs. For a couple of them, it is partly our fault that they didn't get enough attention, as it was quite some time ago before we had really established our process.

**Comment by vdweide** [comment]
OK. Who will send the messages?

**Comment by economon** [comment]
No problem at all. I'll take care of it soon.
