### ISSUE TITLE
4th Annual SU2 Developers Meeting - May 8-10, 2019

### ISSUE THREAD

**Issue by economon** [su2code/SU2#632]
I am pleased to announce the first details for the 4th annual SU2 meeting. Please save the dates:

4th Annual SU2 Developers Meeting
May 8-10, 2019
Villa Monastero, Varenna, Italy

We plan to keep the general hackathon / presentation / developers roundtable meeting format. More information as we have it.

Please mark your calendars and consider joining us! If you already intend to participate and are interested in presenting your work at the meeting, please contact me.

**Comment by talbring** [comment]
Registration is now open! Just head over to https://su2code.github.io.

**Comment by WallyMaier** [comment]
Yay! All the docs are up!
