### ISSUE TITLE
input file for time variable pitching movement

### ISSUE THREAD

**Issue by Neumy94** [su2code/SU2#644]
Is there a possibility to implement an inputfile for realising a time variable pitching amplitude and frequency in the dynamic mesh definition?

**Comment by economon** [comment]
I think there are two options, but both will require checking the code. 

1) Go into grid_movement_structure.cpp and hack the Rigid_Pitching() routine to use your own function in time. Not elegant, but should just be a couple of lines to change.

2) A more general feature was implemented in the past to specify movement of surfaces in time by position of all surface nodes, but should be checked to make sure it is still working as expected. To use it, select 'EXTERNAL' as the grid movement type and provide a file with the surface node positions for each time step. Check in CSurfaceMovement::SetExternal_Deformation() for more info.

If you are interested in developing a better solution as a contribution, we are always open!
