### ISSUE TITLE
Cmake capabilities

### ISSUE THREAD

**Issue by BBArrosDias** [su2code/SU2#646]
Hello,
Is it there any plan to add Cmake capabilities to SU2?

**Comment by economon** [comment]
@BBArrosDias : thanks for the question. At the moment, there are no plans for Cmake. If this is a major pain point for the community (or if someone in the community has already added it and would like to contribute it), we are happy to consider it. Overall, folks seem fairly pleased with how autotools is performing on many different platforms.

**Comment by clarkpede** [comment]
There's some related discussion in Issue #685.
