### ISSUE TITLE
Segfault in ROE solver

### ISSUE THREAD

**Issue by WallyMaier** [su2code/SU2#651]
A segfault occurs when running Roe convective flux explicitly if jump variables are too high.
Line 3278 of numerics_direct_mean.cpp

Occurred when running high mach number (M=24) flow.

**Comment by EduardoMolina** [comment]
Wally,
Could please share the config file and point to the grid that you used?
Eduardo

**Comment by WallyMaier** [comment]
Sorry!
Here are the files!

[ramc61km_flow.cfg.txt](https://github.com/su2code/SU2/files/2881529/ramc61km_flow.cfg.txt)
[RAM-C_II_nondegen10deg.su2.txt](https://github.com/su2code/SU2/files/2881531/RAM-C_II_nondegen10deg.su2.txt)

**Comment by WallyMaier** [comment]
PR #654
