### ISSUE TITLE
How does one do electrodynamics simulations in SU2?

### ISSUE THREAD

**Issue by Geremia** [su2code/SU2#655]
The [description of SU2][1] says

>The primary applications are computational fluid dynamics and aerodynamic shape optimization, but has been extended to treat more general equations such as electrodynamics and chemically reacting flows.

Are there any examples of how [SU2][2] "has been extended to treat more general equations such as electrodynamics"?

  [1]: https://github.com/su2code/SU2#su2-introduction
  [2]: https://github.com/su2code/SU2

**Comment by WallyMaier** [comment]
The branch "feature-AdjTNE2" includes chemically reacting flows (SU2v3, I believe). There was a plasma functionality but was removed; you can probably find it in SU2v2 or v3.  Good luck!
