### ISSUE TITLE
AD Build fail with OpenMPI

### ISSUE THREAD

**Issue by amirkb91** [su2code/SU2#659]
Hi All,

It seems that the AD build fails with OpenMPI 4.0.0. I don't really know where the source of error is, but I suspect it's with CGNS and how it's handled by OpenMPI?

The error is as follows:

In file included from ../../../Common/lib/../src/../include/./mpi_structure.hpp:42:0,
                 from ../../../Common/lib/../src/../include/geometry_structure.hpp:41,
                 from ../../../Common/lib/../src/fem_cgns_elements.cpp:34:
/usr/local/include/mpi.h:2633:20: note: declared here
 OMPI_DECLSPEC  int MPI_Keyval_free(int *keyval)
                    ^~~~~~~~~~~~~~~
Makefile:1504: recipe for target '../src/libSU2_AD_a-fem_cgns_elements.o' failed
make[2]: *** [../src/libSU2_AD_a-fem_cgns_elements.o] Error 1
make[2]: Leaving directory '/home/akb1r19/CFD_Solvers/SU2/SU2-6.2.0/SU2_AD/Common/lib'
Makefile:441: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/akb1r19/CFD_Solvers/SU2/SU2-6.2.0/SU2_AD'
Makefile:13: recipe for target 'install-SU2_AD' failed
make: *** [install-SU2_AD] Error 2

My pregonfigure command is:

`export CXXFLAGS="-O3" && sudo ./preconfigure.py --enable-autodiff --prefix=/home/akb1r19/CFD_Solvers/SU2/Instldir --enable-mpi --with-cc=/usr/local/bin/mpicc --with-cxx=/usr/local/bin/mpicxx &>preconfig.out`

Attaching the whole make output, and the preconfigure log files here too.
I have successfully been able to compile with AD on a cluster with Intel MPI (2017.4.239). I run the exact same commands and it compiles without issue. I haven't tried mpich yet to see if the error persists. Any thoughts?

Thanks,
Amir

[config.log.ad.txt](https://github.com/su2code/SU2/files/2926538/config.log.ad.txt)
[config.log.base.txt](https://github.com/su2code/SU2/files/2926539/config.log.base.txt)
[conf_SU2_AD.log.txt](https://github.com/su2code/SU2/files/2926540/conf_SU2_AD.log.txt)
[conf_SU2_BASE.log.txt](https://github.com/su2code/SU2/files/2926541/conf_SU2_BASE.log.txt)
[make.out.txt](https://github.com/su2code/SU2/files/2926542/make.out.txt)

**Comment by amirkb91** [comment]
It has occurred to me that perhaps I need to compile hdf5 on my system for the parallel integration of CGNS with OpenMPI? I think this might be why make is throwing that error. I'll report back after trying it.

Amir

**Comment by economon** [comment]
I do not think that it is related to CGNS in particular (and no need to build hdf5 anyway, we aren't using it), but rather, there are some MPI issues there. Looks like MPI_Keyval_free() is causing a problem? I think this was deprecated, so perhaps the MPI wrapper is having trouble with something in OpenMPI 4 (or maybe this function was completely removed in the new version).

Thanks for reporting this. In the meantime, can you try with an earlier version of OpenMPI? v3 is working fine for me.

**Comment by talbring** [comment]
I just noticed the same problem. It is related to the current medi version we use. I have to update it to the newest version I guess. Gonna look into it ...

**Comment by amirkb91** [comment]
Hi,

Thanks so much for the replies. I can confirm that the problem indeed lied with OpenMPI 4.0.0. I tried with OpenMPI 3.0.3 and the AD build was successful. Thanks again.

**Comment by asawaswapnil** [comment]
add sudo in front of make install
