### ISSUE TITLE
SU2 mesh deformation for steady state simulation

### ISSUE THREAD

**Issue by hamid1attar** [su2code/SU2#661]
Hello,

I am running a wing problem, in which I have deformed coordinates of a wing surface that I am supplying externally. I have the original .su2 mesh file which is undeformed, and I wish to supply the new deformed coordinates of the wing surface to be used to deform the mesh, and then run a steady state simulation using SU2_CFD on the deformed wing. I have the .cfg file, undeformed .su2, and the coordinates of the new deformed wing surface called “surface_positions_00000.dat”

When I run the solver, I get the following error which I know is something to do with the memory but I am not familiar with C++ so I cannot identify it in the source code. 

Attached is my .cfg, .su2 and surface_positions_00000.dat files. 

Can someone please help?

![image](https://user-images.githubusercontent.com/48598583/54446557-21609400-473f-11e9-8550-a37d7c170dc3.png)

[Goland_wing_case.zip](https://github.com/su2code/SU2/files/2972006/Goland_wing_case.zip)

**Comment by economon** [comment]
Hi: please use the SU2_DEF module (with DV_KIND= SURFACE_FILE) to create the new mesh first before running SU2_CFD. Try the attached config file and rename your new coordinates file to 'surface_positions.dat' 
[inv_goland.txt](https://github.com/su2code/SU2/files/2979714/inv_goland.txt)
