### ISSUE TITLE
How to add a dynamic library into makefile?

### ISSUE THREAD

**Issue by ayuxjh** [su2code/SU2#662]
Hello, 
     Now I only want to compile the SU2_CFD module, so I type the "make" instruction under SU2-6.2.0/SU2_CFD/obj,  and it works very well.  Now I want to link a dynamic library when compiling, （I don't have a deep knowledge of automake tools.... sad..-.-\\\）, but I know they are made to produce the makefile only, so I guess maybe modify few lines of makefile that link the dynamic lib successfully. 
The lines I want to add like    `-lxxx -L \Path\To\The\Lib -Wl, -rpath=\Path\To\The\Lib`  and I append it after the Number 926 line of the makefile (__bin_SU2_CFD_LDADD), and it works!!!  But this way is illegal，here  I want to know how to link the library standardly?
Can someone help me?  very thanks!!!

**Comment by ayuxjh** [comment]
>  Hello, 
>  Now I only want to compile the SU2_CFD module, so I type the "make" instruction under SU2-6.2.0/SU2_CFD/obj,  and it works very well.  Now I want to link a dynamic library when compiling, （I don't have a deep knowledge of automate tools.... sad..-.-\\\）, but I know they are made to produce the makefile only, so I guess maybe modify few lines of makefile that link the dynamic lib successfully. 
> Can someone help me?  very thanks!!!

**Comment by pcarruscag** [comment]
Hello,
You need to use the appropriate environment variables, here is for example how I build one of my branches:
export CXXFLAGS="-Wno-deprecated-declarations -O3 -march=corei7-avx -I/rds/general/user/me/home/pastix/install -I/rds/general/user/me/home/Eigen335"
export CPPFLAGS="-DHAVE_PASTIX -DHAVE_LAPACK -DEIGEN_NO_DEBUG -DEIGEN_DONT_PARALLELIZE"
export LDFLAGS="-L/rds/general/user/me/home/pastix/install -L/rds/general/user/me/home/scotch/lib -L/apps/intel/2017.6/mkl/lib/intel64/"
export LIBS="-lpastix -lscotch -lptscotch -lptscotcherr -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
Regards,
Pedro
