### ISSUE TITLE
Get gradients using AD

### ISSUE THREAD

**Issue by amirkb91** [su2code/SU2#679]
Hi all,

I am trying to use the AD module in the discrete adjoint solver to calculate the sensitivity of the lift coefficient with respect to the closure coefficients of the SA turbulence model.

I've created new variable names in the CConfig class for the SA closure coefficients and have modified the code so that it reads the values for the coefficients from the config file, instead of the given hard coded values. (I would need to change the values later on).

Now I'm trying to get the sensitivity of my objective function (in this case Cl as specified in the config file) with respect to these closure coefficients. 

I've modified the CDiscAdjSolver class in solver_structure.hpp and solver_structure.inl by adding new variables for the sensitivities I want to calculate, defining inline Get functions which return the sensitivity values, and defining virtual functions onto the CSolver class.

I've modified solver_adjoint_discrete.cpp by adding new variables which read in the values of the closure coefficients from the config class and passing these variables onto AD::RegisterInput() _(these are done in the RegisterVariables routine)_, and then passing them onto SU2_TYPE::GetDerivative() to calculate the derivatives _(this is done in the ExtractAdjoint_Variables routine)_. I store the derivative values as new variables called Total_Sens_SA, similar to what's already done for Total_Sens_AoA, for example.

The problem I have is that when I pass the variables onto SU2_TYPE::GetDerivative(), the output is returned as 0. As far as I see, I've followed the same steps that are done to get the other sensitivity values such as Total_Sens_AoA or Total_Sens_Mach, but I don't understand why the derivative is being returned as 0. Is there something I'm missing here? I assumed as long as I register the variables whose derivatives I want onto AD::RegisterInput() the rest should be taken care of inside the AD and codi modules and the derivatives should be calculated correctly?

Curiously, in output_structure.cpp where values such as Total_Sens_AoA are called again to be printed to screen, these values differ from those calculated inside solver_adjoint_discrete.cpp. This to me suggests that the sensitivity values are altered elsewhere, but I cannot seem to find where this occurs.

Any help would be appreciated.

Kind regards,
Amir

**Comment by pcarruscag** [comment]
Hi @amirkb91,
It sounds like you have done things the right way, so if the variables are not being reset after they are registered my next guess is that they are not being considered for pre-accumulation. Try running the code without pre-accumulation (there is a config option, no need to recompile) and see if that makes a difference.
Cheers,
Pedro

**Comment by amirkb91** [comment]
Hi Pedro,

Thanks for your reply.

I tried without the pre-accumulation (PREACC= NO in config file) and still the returned derivative is 0.
In the existing code, when design variables such as Temp and Pressure are registered as AD inputs, their values are re-set using appropriate Set__() functions from the config and solver classes. I have also done the same thing with the SA coefficients, by passing the values onto functions defined inside the config class which set them to the same values that are read before they are registered as AD inputs. 

Still unfortunately the output gradient is zero. Anything else that might be worth trying?

Thanks again,
Amir

**Comment by pcarruscag** [comment]
The solver with the closest functionality to what you are trying to do is the elasticity solver, it may be worth having a look there. But in a nutshell there the variables we want to differentiate are held by (members of) the discrete adjoint solver, they are reset before being registered as inputs to clear the derivative information, and it is important that they are left alone during the recording phase.
You will see that the adjoint iteration class for this solver then needs to update the numerics classes (in SetDependencies), at least for the source term the SA coefficients are set in the constructor of the corresponding numerics so maybe this step is missing?
The key point is that whenever a coefficient is used you need to be able to trace its value back to the original variable you registered.
Also the derivatives should be extracted in the same order they were registered, and you cannot access them multiple times by calling "GetDerivative" on them repeatedly (not 100% sure if this restriction still exists after the update of CoDi).
If none of this makes sense point me to branch you are working on.

**Comment by amirkb91** [comment]
Hi Pedro,

Thanks a lot for your help. I will take a look into the elasticity solver. Reflecting on your comments, I am not sure whether the SA coefficients are left alone during the recording phase as it currently stands. Will look into this but this may very well be the reason why the gradient is returned as 0.
Here's the link to the branch I'm working on. If there's anything sticking out which is drastically wrong I'd be very grateful if you could please point it out for me.
[https://github.com/amirkb91/SU2/commit/12282c0e8a4bd0abc07c2ad3cbea0e2f746ab99d](url)

**Comment by pcarruscag** [comment]
Hi Amir,
I just had a look and that is not going to work I'm afraid.
The numerics classes are not getting the value of the coefficients from the variable that you register as input, this happens because config returns cb1 by value, meaning that what you register as input is not CConfig::cb1_usrdef (seen by numerics) but CSolver::cb1_adj.
You can try registering CConfig::cb1_usrdef as input, making it a public variable would be the easiest thing. This is a hack and personally I don't like the idea of differentiating variables that belong to CConfig. I would add a cb1 member variable to numerics and a method to set it, this method would then be called after you register CSolver::cb1_adj as input to set CNumerics::cb1 = CSolver::cb1_adj and the numerics would no longer get values from the config by themselves in ComputeResidual.
I hope this makes sense but do have a look at the elasticity solver and try to mimic the strategy used there.
Cheers,
Pedro

**Comment by amirkb91** [comment]
Hi Pedro,

Thanks, that makes a lot of sense actually. Out of curiosity I tried the hack you suggested. I set cb1_usrdef to a public variable in CConfig, and registered config->cb1_usrdef as the AD input (config is assigned as a pointer to CConfig already). In the numerics classes I also assigned cb1=config->cb1_usrdef, to ensure it's the same variable as the one registered as input in AD. This still yielded a gradient of zero.
I'm going to try your other solution. I agree it's a much better way of going about it. I'll let you know how it goes.
Thanks again,
Amir

**Comment by amirkb91** [comment]
Hi Pedro,

I tried the other solution you suggested. I declared a new private variable inside the solver class, which I assigned as config->cb1_usrdef. I registered this as the AD input. I then set a method inside the solver class which returns this value when called.
In the Numerics class, instead of reading cb1 from Config as I used to, I read it from the Solver class, using the method mentioned above.
Now I couldn't create a Solver object inside numerics_structure.inl, since according to the compilation order the solver class is dependant on the numerics class (Solver_structure.hpp includes numerics_structure.hpp). So the compiler doesn't know about the solver class while inside the numerics.
To work around the compiler error, instead I included the solver header file inside the numerics src files (cpp). I then created the solver objects in the relevant numerics functions and called the method which returns the AD-registered cb1 variable.
This all compiles now, but the AD gradient is still returned as 0. Adding print statements to the functions inside the numerics src files revealed that they are getting a cb1 value of 0, which I assume it's because solver_adjoint_discrete.cpp is called after the numerics src files have read the value of cb1, which at that point would be 0.
Would you agree that it's probably best to update the numerics classes inside the adjoint iteration class for CDiscAdjSolver, similar to what's done inside CDiscAdjFEAIteration? Is this what you meant when you referred to the elasticity solver?

Thanks for your help,
Amir

**Comment by pcarruscag** [comment]
Hi Amir,
If you create a solver object inside numerics how will this new solver know about the solver that is actually using numerics? The way the code is written does not make the relations between classes very clear as the solver and numerics containers get passed around quite freely... But the solvers are clients of the numerics (I think there are good diagrams of this in some of the papers), i.e. the solvers call methods of the numerics and not the other way around.
It is the numerics that needs a method whereby the solver can set the value of cb1, this is more or less what is done in the elasticity solver, so yes, try to follow that "recipe" as close as possible and it should work.
Cheers,
Pedro

**Comment by amirkb91** [comment]
Hi Pedro,

After much deliberation, I think I have managed to follow the elasticity solver fairly closely. I'm having what feels like a very small problem but I can't manage to fix it. I've added a new method inside the solver class called "GetSA_cb1_solver" which spits out the value of cb1 (which there is registered in AD), and I've added a new method inside the numerics class called "SetSA_num_cb1" which takes a value as input, and sets cb1 to that value.
Now in the fluid SetDependencies method inside the iteration class, I've added a line which is supposed to join the two methods above together: it takes the cb1 value from solver and passes it onto numerics.
My problem now is that the correct value of cb1 is not returned from the solver (it returns 0), even though, as far as I can see, the solver class should still be in the scope as it's being instantiated as an input to this method?
I was wondering if you could please have a quick look at my code and tell me if I'm on the right track? I think I'm getting fairly close so any help, even if little, will probably go a long way. Thanks very much for bearing with me.
https://github.com/amirkb91/SU2/commit/dc72eba2f2b86fc418cfa0d9bacf59d8a5b6e1fe

Cheers,
Amir

**Comment by pcarruscag** [comment]
Hi Amir,
I think you need to declare su2double CSolver::GetSA_cb1_solver(void) as virtual, i.e.:
virtual su2double CSolver::GetSA_cb1_solver(void);
I guess the message you added also does not get printed?
"AKB: inside GetSA_cb1_solver returning cb1_adj as: "
Cheers,
Pedro

**Comment by amirkb91** [comment]
Hi Pedro,
Thanks. I already have done that, it's already declared as virtual inside the CSolver class.
The message does get printed. What's strange is that it prints cb1_adj=0., even though inside solver_adjoint_discrete.cpp, cb1_adj is assigned as cb1_adj = config->GetSA_cb1(); before being registered as an AD variable, and therefore is not 0.
Thanks
Amir

**Comment by pcarruscag** [comment]
Ah yes sorry, I miss saw that. Well you seem to have the right "probes" in place, are you sure the "registervariables" method is being called on the disc adjoint turb solver? somewhere in CDiscAdjFluidIteration::RegisterInput

**Comment by amirkb91** [comment]
Yup, it is being called as far as I can tell. I've also put a print statement inside the registervariables method inside solver right after cb1_adj is registered with AD, and sure enough the screen outputs my statement along with the correct value of cb1_adj as read in from the config class.
Seems that only when we are inside the Iteration class and calling the solver method to return cb1_adj from solver it returns it as 0. Could it be an issue with the scope of cb1_adj? (I also tried making it a public variable inside the class but didn't make a difference).
Or perhaps instead of trying to get the _value_ of cb1_adj from solver, I need to get a pointer pointing to the memory address of cb1_adj, and pass _that_ onto numerics?

**Comment by pcarruscag** [comment]
Yes but it is being called on which solver? Don't forget there is one instance of DiscAdjSolver for the bulk flow and another for the turbulence, you are currently trying to get the value from solver_container[iZone][iInst][MESH_0][ADJTURB_SOL] so make sure RegisterVariables is called for this solver, you may be calling it for ADJFLOW_SOL instead, and that will still give you the right value of cb1 because it comes directly from the config.

**Comment by amirkb91** [comment]
Hey,

Yeah you're right, RegisterVariables was being called for ADJFLOW_SOL. Changing it so that it calls for ADJTURB_SOL throws a seg error (haven't investigated why yet).

However, if I keep the RegisterVariables as is (for ADJFLOW_SOL) and instead I change the solver instance inside CDiscAdjFluidIteration::SetDependencies to solver_container[iZone][iInst][MESH_0][ADJFLOW_SOL], and try to get the value for cb1 from there, it does return the correct value. Also, the final sensitivity values become non-zero so AD is definitely doing something now.

I assumed I had to use the solver_container with ADJTURB_SOL in SetDependencies since the disc_adj_turb flag inside driver_structure is set to true, and so the solver_container with ADJTURB_SOL is instantiated as a new CDiscAdjSolver during the numerics preprocessing. I guess it's a matter of consistency with the rest of the code though, so maybe my assumption was wrong.

I'll test to see if the sensitivity values I'm getting are correct, will let you know.
Thanks so much for your help, hopefully this has been solved for good :)
Cheers

**Comment by amirkb91** [comment]
Hi Pedro,

I can confirm that everything is now working correctly. I have tested the sensitivities against gradients from finite difference runs and the results match very closely.
I owe you a big thank you for your help with this, not only has my problem been solved but you also helped me learn a great deal about how the code works. Really appreciate it.
If we ever meet one day then drinks are on me :)
Cheers,
Amir

**Comment by pcarruscag** [comment]
Hi Amir,
Very glad to hear that, that it works and that drinks are on you (let me know if you ever come to Imperial).
Cheers,
Pedro

**Comment by economon** [comment]
Just a note to say that I really appreciate this type of helpful, professional exchange. Nice job @pcarruscag!
