### ISSUE TITLE
double parameters in  SU2/config_template.cfg 

### ISSUE THREAD

**Issue by marcovanderbijl** [su2code/SU2#682]
Double parameters in SU2/config_template.cfg
lines 25 to 29 and
lines 61 to 65 both specify
    % Specify Hybrid RANS/LES model (SA_DES, SA_DDES, SA_ZDES, SA_EDDES)
    HYBRID_RANSLES= SA_DDES
    %
    % DES Constant (0.65)
    DES_CONST= 0.65

Also double is LOW_MEMORY_OUTPUT= NO
on lines 1311 and 1339 in SU2/config_template.cfg

Also I noticed line 184 in SU2/config_template.cfg
    % Reference area for non-dimensional force coefficients (0 implies automatic
    % calculation) (m^2 or in^2)
    REF_AREA= 1.0
As 0 does an automatic calculation, it is probably better to have
    REF_AREA= 0.0
as the default?

Also I noticed that SUAVE BWB tutorial makes mention of
    REF_SHARP_EDGES = 3.0
    SENS_REMOVE_SHARP = YES
these options are not in the SU2/config_template.cfg
should not all possible options be mentioned (with an apropriate default setting)?

Also line 15 and line 1094
in SU2/config_template.cfg
should be commented out

**Comment by marcovanderbijl** [comment]
great! I just added a new issue that also involves config_template will check source if that one is also solved

**Comment by WallyMaier** [comment]
This issue was addressed in pull #686
