### ISSUE TITLE
Stuck in Geometry Preprocessing: Checking the numerical grid orientation.

### ISSUE THREAD

**Issue by timjim333** [su2code/SU2#683]
**Describe the bug**
Certain meshes seem to get stuck at Geometry Preprocessing: Checking the numerical grid orientation. It will remain stuck indefinitely (I've only left it for up to 20 hours, however).

This has only happened to prism meshes that I've generated with Pointwise's T-Rex function. However, it only seems to affect some of them.

I should mention that the geometry has a very sharp and flat wingtip - sometimes the final few cells on the wingtip become 2D flat plates rather than 3D cells. Will SU2 handle these? I notice that not all meshes with 2D tips get stuck, but all the meshes that are stuck are meshes with 2D tips. (i.e. some meshes seem to run fine.)

I'm not sure if this is a bug or user error but I've also attached some images to demonstrate what I mean. I hope this helps.
![Screenshot from 2019-05-17 17-20-26](https://user-images.githubusercontent.com/16842258/57913834-66807e00-78c8-11e9-9899-c96b10d14c7e.png)
![Screenshot from 2019-05-17 17-20-44](https://user-images.githubusercontent.com/16842258/57913836-66807e00-78c8-11e9-8bbe-c643994a62d4.png)
![Screenshot from 2019-05-17 17-21-11](https://user-images.githubusercontent.com/16842258/57913837-67191480-78c8-11e9-9c16-296cef99df9f.png)

**To Reproduce**
This is a case which got stuck for me. I had used `mpirun -n 40 SU2_CFD inv_69deg-delta.cfg`
N.B. Added .txt to the configuration file for upload.
[inv_69deg-delta.cfg.txt](https://github.com/su2code/SU2/files/3190339/inv_69deg-delta.cfg.txt)
[mesh.zip](https://www.dropbox.com/s/s3f3er9n0wv4bbf/mesh.zip?dl=0)

**Desktop (please complete the following information):**
 - OS: Linux (Red Hat Enterprise Linux Server release 7.3 (Maipo))
 - C++ compiler and version: g++ (GCC) 4.8.5 20150623
 - MPI implementation and version: Intel(R) MPI Library for Linux* OS, Version 2018 Update 2
 - SU2 Version: v6.2.0

**Comment by talbring** [comment]
Thanks @timjim333. 

I just tried the case using the newest develop version. I get 

```
Error in "virtual void CPhysicalGeometry::SetBoundVolume()": 
-------------------------------------------------------------------------
The surface element (0, 74472) doesn't have an associated volume element
------------------------------ Error Exit -------------------------------
```

So there seems to be an issue with the connectivity in the mesh file. Can anyone else try to run this case to see if we get some consistent information ?

Tim

**Comment by vdweide** [comment]
I'll give it a try.

**Comment by vdweide** [comment]
I tried on 1, 4 and 24 cores and I get the same error message as @talbring. This indeed indicates that something is wrong with your grid. The fact that your computation is stuck is most likely caused by your MPI implementation.

**Comment by timjim333** [comment]
Thanks for trying this out. @talbring I don't get the same - I guess it's because I'm using a release version as opposed to the develop. Is the develop stable enough for general use?

@vdweide you mentioned it could be an issue with MPI? As far as I can tell, everyone on the HPC is also referencing the same MPI - do you have any tips on how I might debug this?

Thanks again.
Tim

**Comment by vdweide** [comment]
@timjim333, create a sequential executable and run it on one core. It may take a couple of minutes, but it is not too bad. Then MPI is not used and you should definitely get the error message. I don't think there will be much of a difference in the release version and develop version for this problem.

As far as the MPI is concerned, a one-sided communication is used for the error message. Sometimes the error message is not shown, depending on the MPI distribution and number of cores. Maybe this is something we have to look into. In any case, what MPI distribution are you using?

**Comment by timjim333** [comment]
@vdweide I'm using the Intel MPI Library for Linux* OS (Version 2018 Update 2 Build 20180125) - it's the one that is available on our supercomputer system at the moment. I was running on 40 cores.

I also have a version of SU2 compiled with OpenMPI 3.0.0 on my personal workstation but I don't have the required RAM to get to the point where I get the error, however.

It seems strange that it happens for this mesh only as I have run many other similar meshes successfully on the same HPC system - would that not trip the same issue if it were the MPI installation?
Thanks for your thoughts!

**Comment by vdweide** [comment]
I am using Intel MPI as well, but on Ubuntu 18.04 and I get a clear error message. The likely reason why it hangs for you for this grid and not for the others is that this grid has an issue and the others do not. 

Can you run it on one core of your supercomputer?

**Comment by timjim333** [comment]
I'll give it a go and get back to you. Thanks @vdweide

**Comment by timjim333** [comment]
On running with a single core, I also get a similar error (attached below). In this case, I'm guessing that it doesn't like the 2D element? This seems strange as it managed to handle a few cases where flat cells were also present, do you have any thoughts on this?

Also, is it possible to identify the location of the cell based on the error message?
Many thanks,
Tim
```
------------------------ Geometry Preprocessing ------------------------
Setting point connectivity.
Renumbering points (Reverse Cuthill McKee Ordering).
Recomputing point connectivity.
Setting element connectivity.


Error in "virtual void CPhysicalGeometry::SetBoundVolume()": 
-------------------------------------------------------------------------
The surface element (0, 133348) doesn't have an associated volume element
------------------------------ Error Exit -------------------------------


application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
SU2_CFD failed with retcode 1
```

**Comment by vdweide** [comment]
As the error message indicates, a surface element is not part of a volume element. At least, the solver is not able to find one. From the error message this happens for surface element 133348 of marker 0.

**Comment by vdweide** [comment]
Actually, the part that worries me a bit, is the fact that the error handling does not seem to terminate the MPI job appropriately. @talbring, could this be caused by the one-sided communication that is used for this purpose?

**Comment by timjim333** [comment]
@vdweide How does SU2 organise the surface elements? As I have created the SU2 input mesh as a direct export from Pointwise, I don't think that the numbering system matches up.

**Comment by vdweide** [comment]
Indeed, the export from Pointwise should work just fine. It could be that this is a degenerated case. Is it possible for you to visualize the troubled region in Pointwise?

**Comment by timjim333** [comment]
Sorry @vdweide - what I mean is that I'm not sure how to locate the troubled region. Does SU2 run a table or dictionary relating the surface element number to a physical (x, y, z) coordinate? As far as I can tell, the run just fails without any outputs. Do I need debugging mode turned on or something similar? Thanks.

**Comment by vdweide** [comment]
You have to look for the connectivity of surface element 133348 of marker 0 in the grid file. Then you can look up the coordinates of the corresponding points in that same grid file.

**Comment by EduardoMolina** [comment]
Hi,

You can also use the mesh quality tools of Pointwise. It will be easier to find where the bad element is located.

Eduardo

**Comment by aeroamit** [comment]
All above,

Can any one share the experience of the mesh quality matrix acceptable by SU2.

In Pointwise, one can follow maximum included angle, centroid skewness or equiangle skew as guiding parameters. I have observed that some of the commercial Solvers can  accepts and run a very high max included angle (179.99 or so) also without trouble but some others have issues with the same. 

Many times due to complex geometry, one ends up with these high numbers. 

Any guidelines for SU2 on mesh quality is appreciated.

Regards 
Amit

**Comment by vdweide** [comment]
@timjim333, I checked your grid with just connectivity info and I get the following error messages

Boundary marker  BODY, surface element 77477: No corresponding volume element found.
Coordinates of the points
0.1815790.04981870.0020471
0.181850.04994770.00205104
0.1816670.04971090.00204381

Boundary marker  BODY, surface element 133348: No corresponding volume element found.
Coordinates of the points
0.1814850.04947420.00203657
0.1813090.04968980.00204316
0.181230.04944470.00204356

Boundary marker  BODY, surface element 134774: No corresponding volume element found.
Coordinates of the points
0.181230.04944470.00204356
0.1813020.04923740.00202934
0.1814850.04947420.00203657

Boundary marker  BODY, surface element 135217: No corresponding volume element found.
Coordinates of the points
0.1816670.04971090.00204381
0.181850.04994770.00205104
0.1815790.04981870.0020471

So clearly the grid is invalid.

**Comment by vdweide** [comment]
Oeps, there should have been spaces between the (x,y,z) coordinates, but I guess you can figure out that yourselves.

**Comment by timjim333** [comment]
@aeroamit I don't have a definitive source but just based on random Pointwise tutorials and videos I've come across, I've collated some general pointers for the tetrahedral portions of the mesh (perhaps other users can chime in if they have better values):
• Equiangle
	- Max ratio of the cell's included angle to the angle of the equilateral element
	- Between 0 and 1
	- Keep below 0.8
• Equivolume / equiarea skewness
	- The ratio of area or volume to optimum 
	- Varies between 0 and 1
	- Keep below 0.8 if possible. Closer to 0 is better. Some solvers up to 0.9
• Centroid skewness
	- 1 - max dot product between cell face normal and vector connecting cell centroid and face centroid
	- 0 (no skew) to 1 (collapsed cell)
	- Block cells
• Min included angle
	- Closer to 60 better?

**Comment by timjim333** [comment]
@vdweide Thanks for the update. How does one bring up this information? Is this referring to a 2D cell where a 3D one is expected?

**Comment by vdweide** [comment]
I simple wrote a program to test the grid, which searches for the boundary elements in the single faces, i.e. faces that are only part of one volume element, of the volume grid. What the error message means is that for 4 triangular surface elements of boundary marker BODY there is no corresponding face of the volume elements that is only part of one volume element. 

When I include the faces that are shared by two volume elements, only two boundary elements are not found. So in short, you have two boundary elements in boundary marker BODY that are no part of any volume element and two boundary elements that are shared by two volume elements.

**Comment by aeroamit** [comment]
@timjim333,

Yah, those are the general guidelines you mentioned but they do not always work in practical cases.
We will probably know more details when people will share their experiences and issues faced.

I have tried meshes with max include angle 175 or below, they go well. Even upto 179 also go through.
But I had trouble recently while just giving a trial for 179.8 or more case.
One thing to note is, SU2 constructs dual mesh from the primal mesh we supply but anyway properties of the primal mesh will carry forward.

Regards
Amit

**Comment by timjim333** [comment]
@vdweide thank you very much for checking out the mesh. Do you know if this is something that I might be able to tweak in Pointwise? (Not sure if you are also a PW user), or is this likely a bug in the mesh export procedure?

@aeroamit I thought that might be the case - apologies, I only had general ones to hand.

**Comment by vdweide** [comment]
I cannot say what is happening. However, Pointwise has a good support department and they may be able to help you.

**Comment by timjim333** [comment]
@vdweide @talbring Ok, thanks you for all your thoughts and help troubleshooting this so far - I guess it might be the SU2 export plugin introducing this as I can't seem to identify the mesh issue within Pointwise itself. I'll contact support and leave a message here if any workarounds are found.

**Comment by aeroamit** [comment]
@timjim333

The guidelines you mentioned are perfect but geometry complexity at times push it beyond those numbers. Infact most of the Solvers (especially commercial) are robust enough to take (as I mentioned) the mesh crossing these specific guidelines. I think SU2 also handles it reasonably well.

Latest version of Pointwise has direct export to SU2 (I think 17.3 onwards or so). Did you try CGNS format? 

Best
Amit
