### ISSUE TITLE
discrepancy between  config_template.cfg and option_structure.hpp

### ISSUE THREAD

**Issue by marcovanderbijl** [su2code/SU2#687]
option_structure.hpp:
FFD_TWIST = 15,	 /*!< \brief Free form deformation for 3D design (change the twist angle of a section).
FFD_CONTROL_POINT_2D = 19, /*!< \brief Free form deformation for 2D design (change a control point).

  config_template.cfg:
%    FFD_CONTROL_POINT_2D (  15, Scale | Mark. List | FFD_BoxTag, i_Ind, j_Ind, x_Mov, y_Mov )
%    FFD_TWIST    	     (  19, Scale | Mark. List | FFD_BoxTag, j_Ind, x_Orig, y_Orig, z_Orig, x_End, y_End, z_End )

identification number 15/19 mixed up

**Comment by economon** [comment]
@marcovanderbijl : I think this fix can also be consolidated with #686. Please just add more commits there or open a new PR as @talbring mentions. We are happy to help.
