### ISSUE TITLE
config_structure.cpp bad comment

### ISSUE THREAD

**Issue by marcovanderbijl** [su2code/SU2#688]
in SU2/Common/src/config_structure.cpp:

  addStringListOption("DV_MARKER", nMarker_DV, Marker_DV);
	/* DESCRIPTION: Parameters of the shape deformation
   - FFD_TWIST_ANGLE ( FFDBox ID, x_Orig, y_Orig, z_Orig, x_End, y_End, z_End ) */

I think FFD_TWIST_ANGLE is superseded (needs confirmation) by FFD_TWIST_2D and FFD_TWIST but the comment has not been updated to reflect this.

If FFD_TWIST_ANGLE is not in use anymore, then SU2/SU2_PY/SU2/io/config_options.py needs updating as it references FFD_TWIST_ANGLE also

**Comment by talbring** [comment]
@marcovanderbijl you can go ahead and open a pull request if you want (or push changes to #686) :+1:

**Comment by marcovanderbijl** [comment]
atm that still sounds like magic to me,... I really should learn this github stuff. But I was more hoping some experienced coder would pick this up instead of my messing up the code.

**Comment by talbring** [comment]
I know it can be a little bit intimidating at the beginning but don't worry about messing up the code. There is nothing you can do wrong :) You can find more information on how the development works here: https://su2code.github.io/docs/Gitting-Started/ 

Let me know if you have more questions.

**Comment by marcovanderbijl** [comment]
probably #689 is also old code? sorry, i'm only just starting with SU2 and don't know it's history
