### ISSUE TITLE
what happened to FFD_DIHEDRAL_ANGLE

### ISSUE THREAD

**Issue by marcovanderbijl** [su2code/SU2#689]
SU2/Common/include/option_structure.hpp
Ln1637)
Enumerates FFD_DIHEDRAL_ANGLE = 17,	 /*!< \brief Free form deformation for 3D design (change the dihedral angle). */

but it seems to be missing from the list 
Ln2739)
switch (this->design_variable[iDV]) {
        case NO_DEFORMATION:       nParamDV = 0; break;
        etc.

**Comment by WallyMaier** [comment]
FFD_DIHEDRAL_ANGLE was removed at some point.  I removed the hooks in option_structure.hpp
