### ISSUE TITLE
Question about time varying inlet BC

### ISSUE THREAD

**Issue by dean0927** [su2code/SU2#690]
Hi,

I want to use SU2 to do adjoint optimization on a geometry that is accelerating. I haven't been able to find anything about implementing time varying inlet BC's, and I was wondering if this is a feature in SU2/what would be the best way for me to implement this.

Thanks!
Dean

**Comment by economon** [comment]
@dean0927 : you might be in luck. In the open PR #672, we have some hooks for user-defined solutions, including BCs, that can be functions of both space and time (using BC_Custom() inside the solver classes). It may serve your purpose - give it a look.

**Comment by dean0927** [comment]
Sorry for the late response, and thanks for getting back to me! That definitely looks like what I'm looking for. I've taken a look through the code and I'm not entirely sure about what the syntax for including such a bc in the config file would be. Is there an example?

**Comment by dean0927** [comment]
@economon Hi, I've been looking at the code and I can't figure out how to use the custom BCs. Is there an example, preferably with a time dependent custom BC you could point me to? Thanks!

**Comment by economon** [comment]
@dean0927 : this is a very new feature, unfortunately, which is not quite released to the public yet and we do not yet have examples. However, you can take a look at the MMS cases at the following link and their configs to see how the options work. You will need to set KIND_VERIFICATION_SOLUTION= USER_DEFINED_SOLUTION, implement the solution/BC inside of the CUserDefinedSolution class, and then call BC_Custom() on the boundaries where you want it applied (MARKER_CUSTOM in the config)/

https://github.com/su2code/VandV/tree/master/mms/fvm_incomp_euler
