### ISSUE TITLE
Linear solver / Jacobian improvements for robust convergence

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#711]
Just to keep track of things, this is what is currently being done in #700, #691, and #705.
If anyone wants to join efforts (there are possibly similar efforts going on in personal branches) either by coding / testing / benchmarking / providing suggestions / etc. please do.

**Comment by pcarruscag** [comment]
#691 introduced Jacobian improvements to some schemes, sadly I could not do anything for the bread and butter of upwind schemes (Roe).
Further improvements to linear solvers and preconditioners will come as part of #789.

**Comment by economon** [comment]
One last Q on this: is there any reason not to make the adjustment to the centered scheme Jacobians the default behavior?

**Comment by pcarruscag** [comment]
No not really, it is a fairly safe thing to change but it only makes sense to do it if the CFL is also increased. I did not make it default at the time because many cases would change over 2 lines of code...
Maybe it can be done now as part of #790? I can help you with the testcase updates.
