### ISSUE TITLE
Issue building develop branch

### ISSUE THREAD

**Issue by dean0927** [su2code/SU2#712]
Hi,

I have no issues building the master branch, but when I tried to build the develop branch, I got the error 
../../../Common/lib/../src/../include/././datatypes/codi_reverse_structure.hpp:40:10: fatal error: codi/tools/dataStore.hpp: No such file or directory
 #include "codi/tools/dataStore.hpp"

I am running on a VirtualBox VM with Ubuntu 18.04.2 LTS
GCC version 7.4.0
SU2 Version v6.2.0

**Comment by talbring** [comment]
Hi @dean0927,

can you try a `git submodule update` ? It seems like the submodules are not up-to-date in your case.

**Comment by dean0927** [comment]
That worked, thanks! I was trying to install by downloading the zip file directly and not through git, which works for the master but not the develop branch.
