### ISSUE TITLE
Bug on multi-zone file output

### ISSUE THREAD

**Issue by rsanfer** [su2code/SU2#713]
**Describe the bug**
When running a multi-zone case, SU2 at the current develop throws a Segmentation fault after writing out the Paraview ASCII for the second zone. Debugging with cgdb points to an error in free() when the following deallocation is called:
```
COutput::SetResult_Files_Parallel()
  COutput::DeallocateConnectivity_Parallel()
    if (Conn_Tria_Par != NULL) delete [] Conn_Tria_Par;
```
Running under valgrind, the code goes past the error point, but points to the same instruction
```
==29692== Invalid free() / delete / delete[] / realloc()
==29692==    at 0x483958B: operator delete[](void*) (vg_replace_malloc.c:641)
==29692==    by 0x991A10: COutput::DeallocateConnectivity_Parallel(CConfig*, CGeometry*, bool) (output_structure.cpp:18466)
==29692==    by 0x9CCFF6: COutput::SetResult_Files_Parallel(CSolver*****, CGeometry****, CConfig**, unsigned long, unsigned short) (output_structure.cpp:12608)
==29692==    by 0x905C0C: CMultizoneDriver::Output(unsigned long) (driver_direct_multizone.cpp:595)
==29692==    by 0x905E23: CMultizoneDriver::StartSolver() (driver_direct_multizone.cpp:188)
==29692==    by 0x364A19: main (SU2_CFD.cpp:174)
==29692==  Address 0x9b1e500 is 0 bytes inside a block of size 48,192 free'd
==29692==    at 0x483958B: operator delete[](void*) (vg_replace_malloc.c:641)
==29692==    by 0x991A10: COutput::DeallocateConnectivity_Parallel(CConfig*, CGeometry*, bool) (output_structure.cpp:18466)
==29692==    by 0x9CCFF6: COutput::SetResult_Files_Parallel(CSolver*****, CGeometry****, CConfig**, unsigned long, unsigned short) (output_structure.cpp:12608)
==29692==    by 0x905C0C: CMultizoneDriver::Output(unsigned long) (driver_direct_multizone.cpp:595)
==29692==    by 0x905E23: CMultizoneDriver::StartSolver() (driver_direct_multizone.cpp:188)
==29692==    by 0x364A19: main (SU2_CFD.cpp:174)
==29692==  Block was alloc'd at
==29692==    at 0x483850F: operator new[](unsigned long) (vg_replace_malloc.c:423)
==29692==    by 0x99F3EA: COutput::SortVolumetricConnectivity(CConfig*, CGeometry*, unsigned short, bool) (output_structure.cpp:15318)
==29692==    by 0x9A14EC: COutput::SortConnectivity(CConfig*, CGeometry*, unsigned short, bool) (output_structure.cpp:14736)
==29692==    by 0x9CCD39: COutput::SetResult_Files_Parallel(CSolver*****, CGeometry****, CConfig**, unsigned long, unsigned short) (output_structure.cpp:12485)
==29692==    by 0x905C0C: CMultizoneDriver::Output(unsigned long) (driver_direct_multizone.cpp:595)
==29692==    by 0x905E23: CMultizoneDriver::StartSolver() (driver_direct_multizone.cpp:188)
==29692==    by 0x364A19: main (SU2_CFD.cpp:174)
```

If I run it in parallel and request output from PARAVIEW (so volume files are not written out) the error disappears, but it happens again when PARAVIEW_BINARY output is requested, so it's definitely on the volume writing structure. 

There have been some changes to output_structure.cpp since the last released version 6.2.0, I wonder if those are the reason. When running it with the released version the seg fault is not there. I haven't tried yet with the new output currently being finalized by @talbring. 

**To Reproduce**
To reproduce, run the case below using ```SU2_CFD config.cfg```
[square_beam.zip](https://github.com/su2code/SU2/files/3289851/square_beam.zip)

**Desktop (please complete the following information):**
 - OS: Antergos Linux x86-64 kernel 5.0.5-arch1-1-ARCH
 - C++ compiler and version: GCC 8.2.1
 - MPI implementation and version: OpenMPI 4.0.1
 - SU2 Version: current develop vs v6.2.0

**Comment by pcarruscag** [comment]
This problem appears to be solved, tested with current develop branch (hacked configs below).
[configs.zip](https://github.com/su2code/SU2/files/3724204/config.zip)
