### ISSUE TITLE
Optimize data structures for performance without losing readability/flexibility.

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#716]
Having spent some time on implementation details of linear algebra topics, and a bit of time on small algorithmic improvements to a few numerics classes, I would now like to focus on another performance bottleneck we have. One that always seemed quite daunting to tackle (to me) due to the amount of changes it would require, but recently I had a silly idea to reduce the invasiveness of the "procedure".

Discontiguous data structures are absolute performance killers for low order FVM.
*(skip this paragraph if this is obvious)*
What data structures? All the small ones the solver needs to "visit" to compute residuals.
Why? Mostly because they destroy locality. The useful data stored by consecutive nodes is very far apart. Modern CPU's try to hide the latency of accessing main memory (RAM) by caching frequently used areas of that memory, this effort is very easily undermined by accessing memory at random or predictably but at very large strides.
Let me give you some numbers, for CNSVariable in 2D the average distance between the primitives at consecutive nodes is 200 doubles or 1600 bytes. "What?! is the compiler dumb?" No, virtual methods take up quite a bit of space `sizeof(CNSVariable)` is 424 bytes, before it allocates any data.
And that can only get worse as more functionality is added to the code.

This is one of those "well known" things at least in a qualitative way, but let us try and quantify the cost using an approximation of our typical use case scenario.
*Spoiler alert:* It is up to one order of magnitude, if this does not surprise you feel free to go straight to "Proposed solution".

We will have a variable class that stores some data with some overhead (the 200 doubles):
```
class VariableBase
{
  protected:
    double* primary;
  public:
    VariableBase(int nVar, int overhead);
    virtual ~VariableBase();
    inline double* GetPrimary() {return primary;}
    inline virtual double* GetSecondary() {return nullptr;}
};

VariableBase::VariableBase(int nVar, int overhead)
{
    primary = new double [nVar+overhead];
    for(int i=0; i<nVar; ++i) primary[i] = 1.0;
}
```
All this does is give access to some primary variables held by the base class and allow derived classes to store their own secondary variables, e.g.:
```
class VariableDerived : public VariableBase
{
  private:
    double* secondary;
  public:
    VariableDerived(int nVar, int overhead);
    ~VariableDerived();
    inline double* GetSecondary() {return secondary;}
};
```
Then lets say we have dummy numerics classes.
```
class NumericsBase
{
  public:
    virtual ~NumericsBase();
    inline virtual double ComputeResidual(const double* a, const double* b) {return 0.0;}
};

class NumericsDerived : public NumericsBase
{
  private:
    int n;
  public:
    NumericsDerived(int nVar);
    double ComputeResidual(const double* a, const double* b);
};
```
`NumericsDerived` simply computes the dot product of `a` and `b`.
The use case is to loop over edges that connect nodes `a` and `b` passing the data of those nodes to `ComputeResidual` and using the result to update an array.
```
VariableBase** node = new VariableBase* [nNode];
for(int i=0; i<nNode; ++i)
    node[i] = new VariableDerived(nVar,overhead);
...
for(int i=0; i<nEdge; ++i)
{
    int p0 = connectivity[i].first;
    int p1 = connectivity[i].second;

    double r = numerics->ComputeResidual(node[p0]->GetPrimary(), node[p1]->GetPrimary());

    residual[p0] += r;
    residual[p1] -= r;
}
```
I hope that looks familiar.
`connectivity` is a `vector<pair<int,int> >` so nicely contiguous (in SU2 this information comes from an array of CEdge*). Note that we are never talking about sequential access here, this level of indirection will always be present.
To create a somewhat realistic access pattern we create 2 edges per node connecting it to nodes +- some distance away, this distance is small for end nodes and largest for the middle node (I assumed the maximum distance to be `sqrt(nNode)`). This should vaguely resemble an RCM ordered 2D connectivity.
We will measure the cost of this edge loop relative to using a row-major storage of our variables.
```
double* solution = new double [nNode*nVar];
for(int i=0; i<nNode*nVar; ++i) solution[i] = 1.0;
...
    double r = numerics->ComputeResidual(&solution[p0*nVar], &solution[p1*nVar]);
...
```
OK, so we run this for 1000000 nodes with 4 variables per node and a overhead (or "space between variables") of 200 and we see that CVariable is **8.4** times slower.
But we can actually confuse the CPU further by accessing the variables through the virtual method, i.e.
```
...
    double r = numerics->ComputeResidual(node[p0]->GetSecondary(), node[p1]->GetSecondary());
...
```
and now we measure our loop to be **10** times slower.
If we remove all overhead the loop is only **1.5** and **1.9** times slower respectively, it is really the enormous distance that kills performance.

**Proposed solution**
Now, I would like to get better performance, but I do not want to re-write the entire code, and I recognize the usefulness of polymorphism and that encapsulating data keeps the code more manageable and readable.
To that end I propose that CVariable should allocate data for all nodes, so CSolver would have one CVariable and not one per node e.g.
```
class DenseVariableBase
{
  protected:
    double* primary;
    int n, i;
  public:
    DenseVariableBase(int nVar, int nNode)
    {
        primary = new double [nVar*nNode];
        ...
    }
    virtual ~DenseVariableBase() {delete [] primary;}
    inline DenseVariableBase* operator[] (int iNode)
    {
        i = iNode;
        return this;
    }
    inline double* GetPrimary() {return &primary[i*n];}
    inline virtual double* GetSecondary() {return nullptr;}
};
```
To keep the same semantics of accessing variables `node[iNode]->Get()` (and thus avoid changing the entire code) the class now keeps track of what node we are accessing (member variable `i`) and all its methods have this in consideration see for example `GetPrimary` above.
We tell the class what node we want via `operator []` which returns a pointer to the object itself so we can call other methods on top of `[]`.
This does not exactly recover the same interface and it can create some bugs because one would be able to call methods without knowing what index they are on (it is also not thread safe but that is not a problem now).
So the final piece to recover the interface and shield direct calls to methods without specifying the index is a lightweight wrapper.
```
class DenseWrapper
{
  private:
    DenseVariableBase* nodes;
  public:
    DenseWrapper(int nVar, int nNodes);
    ~DenseWrapper();
    inline DenseVariableBase* operator[] (int iNode)
    {
        return (*nodes)[iNode];
    }
};
```
With this there is no way of getting to the variables without going through `[]` first.
If we run this code we see that it is only **1.08** and **1.57** times slower for the non-virtual and virtual accessors respectively.
This could be an intermediate solution while the CVariable methods would be migrated to allow passing the index as argument e.g. `field->Get(iNode)` and the code is updated gradually.

However, I think the wrapper could provide a way of dealing with the loss of versatility that contiguous storage creates...
There are no free lunches and this performance improvement would come at the cost of losing the ability to have different types of variables in different parts of the domain. I think currently only the elasticity solver uses this to keep "boundary" and "internal" variables.
If this versatility is really required the wrapper can keep special variables separately, that it would know to be special via a boolean vector and know how to access via a hash table (for example).

**Alternatives**
We could make the storage continuous by using a memory pool i.e. allocate outside the class and give the class a pointer to its memory location. This is still not truly contiguous as the pointers the class holds are variables themselves and so they would still be separated (albeit by a smaller huge distance), thus the amount of overhead would still influence performance.

Right, that is enough writing... please let me know what you think.

**Comment by talbring** [comment]
thanks @pcarruscag for this explanation and suggestions. I think most of us are aware that the virtual functions cause an overhead in runtime. Still, never thought it would be that drastic. However, I would be interested to see on how much faster it is in practice, since most of the work is currently done in the Compute_Residual of the numerics classes and the solution of the linear system.

But I like your proposed solution as it really keeps the code readable. So I don't really see a problem in adopting that in the code.

**Comment by pcarruscag** [comment]
Yes, I did not make that clear, the linear solver fraction of the time cannot be accelerated by this. But everything else can, from gradient/limiter computations to the Compute_Residual functions, as all those need to wait for data, it is however not very easy to measure how long that wait is compared to the rest of the computations.
In the 2015 joint work between Stanford and Intel they reported a 1.5x speed-up from this type of change for a case where the linear solver used 24% of the time. I do not know how heavy the CVariable infrastructure is now compared to then... We will see :)

**Comment by rsanfer** [comment]
Hi @pcarruscag,
thank you very much for the insight and the well thought proposed solution. I wasn't aware that there was such a loss in performance, it seems clear that something needs to be done.

The only question I have is regarding the following comment 

> There are no free lunches and this performance improvement would come at the cost of losing the ability to have different types of variables in different parts of the domain.

I'm using this feature more and more, I was planning to extend it in the structural solver to remove the `if fsi` statements, and I also used it in the rework of the mesh solver, as defining variables at the interface only reduces greatly the memory footprint (sort of like the node-vertex structures in geometry). You mention there are options to keep this versatility, how difficult do you think would be to implement them?

**Comment by pcarruscag** [comment]
Hi @rsanfer,
I was afraid you were going to say that...
On the subject of memory savings, and taking the specific case of CFEAVariable, the class is 304 bytes before it allocates data, once data is allocated for a plain nonlinear 3D problem the effective size is 704 bytes, looking at the constructors, for such a problem we allocate 22 doubles or 176 bytes. So effectively 75% of the memory (equivalent to 66 doubles) is wasted.
It is important to note that this "efficiency" figure does not get much better even when this class allocates all it members (for which one needs fsi + adjoint + unsteady). This happens because operator `new []` needs to store the size of the allocation together with the data for when `delete []` is called so you get "pointer + size + data" rounded to a multiple of 16B because of the default alignment.
Therefore my opinion is that we can "over allocate" and still save memory, unless you need massive amounts of data for the boundary points(?)... But looking at CFEABoundVariable I don't think that is the case.
If we want to be optimum in terms of performance and memory usage, we would need to mimic the CGeometry strategy in CSolver.
If we do not want to mimic that structure we need to either be able to rely on some ordering of the special cases, e.g. boundary variables stored first, so that at runtime:
```
double* Get(int iNode) {
    if (iNode < nBoundary)
        return &special[iNode];
    else
        return &normal[iNode-nBoundary];
}
```
If we cannot rely on some order we would need to tag nodes "special" or "normal" and then use some form of map for special cases... All this would cost a lot of indirection.

**Comment by rsanfer** [comment]
Hi @pcarruscag, thanks for the quick response. 

There are still several possible memory reductions on the FEA solver by moving stuff to the vertices. Even though over-allocating would probably be fine for the structural solver as problems remain relatively small,  I am replicating this structure for the mesh solver on the fluid side, and in there we should be careful not to add tons of doubles that are only necessary at the boundaries to the whole variable structure. I might also need a similar thing in the flow solver, e.g., to store boundary loads for the adjoint solver.

I believe that relying on some ordering would be quite complex and require a lot of reworking of the code, everything in the solvers links directly to the point index, which gets renumbered at the beginning. So forcing the vertex nodes to go on to the initial positions doesn't seem like an easy one. And, as you say, maybe if we flag the nodes (as boundary or interior) we end up pretty much at the starting point.

Possibly, the best alternative would be to replicate the structure in CGeometry in CSolver, therefore adding some CVertexVariable parent class and child for the different solvers. There are other boundary magnitudes that could be interesting to store as well. It would require some work, but given that there is a direct correspondence iMarker+iVertex -> iPoint, I would expect that to be the least invasive approach.

**Comment by pcarruscag** [comment]
Ok, so maybe we can start with over-allocating, and then move to a CVertexVariable approach?
If the extra allocations are for a few tractions/displacements we will save memory anyway.

**Comment by pcarruscag** [comment]
On the subject of virtual functions I would like to put another idea forward.
After moving things around in #725 I noticed that we have tons of `inline virtual` methods.
The keyword `inline` has two meanings to the compiler:
- "Dear merciful compiler please copy paste the body of this function and then do all your wonderful optimizations, if that pleases your excellency."
- "Dear forgiving compiler, you will find this method defined in multiple units, please don't be mad" (i.e. ignore the one-definition-rule).
`virtual` means determine what version of the method to call at runtime. This is not compatible with the first (and often the intended one) meaning of inline, therefore the compiler will in general not inline those methods.

They will only be inlined if they are being called on a pointer to the derived class that does not declare the method to be virtual anymore. CSolver knows what variables it creates and so in hot areas of the code it could do a static downcast to allow inlining (e.g. `static_cast<CEulerVariable*>(node[iNode])->DoStuff()`).
Where is this important? For example when computing gradients, where simple additions and subtractions are hidden behind virtual functions.
If you are worried about maintenance each solver can typedef its most safe downcast level or better yet (or just more modern), methods that could benefit from this can be templated for the type of downcast.
Those in favour say Yea those against say Nay.

**Comment by economon** [comment]
Aok on inlines.

Looking forward to the memory layout concept.. have you also thought about how we might combine this with vectorization (SIMD) across the edges in the residual / gradient / limiter routines? There's probably another 2x speedup available for those kernels.

Lastly, I don't think we should throw out the possibility of removing the CVariable class entirely in favor of allocating memory directly in the solver classes. We have thought about this in the past, and it is not used deliberately in the DG solver, for example. Food for thought.

**Comment by pcarruscag** [comment]
I've been doing some recreational reading on strategies that people have used for vectorization of fluxes but so far I have not thought of a way to reconcile them with the nice encapsulation we have of the numerics. For gradients (at least GG) and limiters on the other hand I do have ideas. By the way is there a branch on the repo for the work you, Francisco, Intel, and others did on this kind of stuff?

Yeah making solution variables members of the solver would avoid a lot of virtual calls but it would make it harder to eventually reach the solution for post processing, or in other areas like Integration/Iteration where the solution is manipulated directly by non-solver classes, we will see...

**Comment by vdweide** [comment]
My experience is that nice looking code and performance are two conflicting items, unfortunately. Apart from being contiguous in memory, you only obtain good performance when the vector length is a multiple of 8 or 16. This typically leads to padding the array, which does not improve readability. Furthermore, the best optimization is obtained when the vector length is known at compile time, typically leading to even uglier looking constructions,

**Comment by economon** [comment]
I can share that version of the code.. but beware, just as Edwin mentions, it is nasty looking and hard to compile (there are intrinsics and all sorts of architecture-specific changes). But, interesting to look at, of course. There you will see that we basically moved up all of the CVariable data (reordered contiguously) and methods to the solver to eliminate the extra layer of indirection, while still keeping access for outside classes, i.e. something like solver[FLOW_SOL]->node[iPoint]->GetPressure() becomes solver[FLOW_SOL]->GetPressure(iPoint).

Since you mentioned it, another target is the CNumerics classes. The flexibility is nice, but does it really need an entire set of classes with getters/setters/virtual functions? I think that most of the ComputeResidual() functions could be moved up as methods in the solver classes as well to make more efficient residual kernel loops.

In the early days, we thought completely removing CVariable and CNumerics would be very intrusive to change and would hurt flexibility. While the former is still true (although certainly doable), the latter does not seem to me as high of a priority any longer. Over the years, I don't think that folks have really modified the CNumerics classes all that often (once you have implemented the Roe method, it is more or less done). In addition, the CVariable and CNumerics child classes all live almost entirely within their own solvers, so we aren't taking much advantage of code reuse to justify having them as separate classes. For instance, if we just copied the relevant ComputeResidual() routines up into their solvers from numerics, we would have very little code duplication in the end, which is an indicator that we may not really need the extra baggage.

**Comment by clarkpede** [comment]
> In the early days, we thought completely removing CVariable and CNumerics would be very intrusive to change and would hurt flexibility... Over the years, I don't think that folks have really modified the CNumerics classes all that often (once you have implemented the Roe method, it is more or less done).

As someone who has worked with the CNumerics classes a lot, I can say that we really don't gain much by keeping them as separate classes.  On the surface, it seems like a good use of the [strategy pattern](https://sourcemaking.com/design_patterns/strategy).  But from a pragmatic approach, it's not as flexible as OO purists would like you to believe. First off, if you need a new variable in the CNumerics class, you need to change both the solver class and the numerics class, since the solver class calls Setters to set the numerics variables.  If you don't call the right Setters, you get a silent failure (unless you're using valgrind).  The passing of variables between solver and numerics also leads to a lot of code duplication. And for many solvers (e.g. the viscous NS numerics or the source terms in the SST model) you only end up with one numerics class anyways.

I also imagine there's a strong performance hit from all the Setters and copying of variables.  But I haven't taken the time to check for myself.

In my opinion, you could keep 80% of the current flexibility by using different functions instead of different classes.  But I also think we would have to work carefully, or else we'll make the code harder to maintain.

**Comment by pcarruscag** [comment]
I always thought of CSolver, CIteration, etc. as "strategies" and CNumerics as "visitors", but just because the numerics "visit" the edges. I like the separation between solver and numerics, but I think the implementation could be better to avoid the problems @clarkpede mentioned.
We will need the contiguous storage for vectorization, once we have that we should benchmark again to evaluate the overhead of the current numerics structure and the potential gains from vectorization and weight that against whatever loss of readibility we would need to incur.

**Comment by economon** [comment]
Thanks for sharing the progress on the container in #753 

You may already be going in this direction, but another idea to consider is making CVariable a pure data structure (basically a c-style struct with your new containers) with no methods. This could be interesting for 2 reasons: 1) we remove a level of indirection without the Getters/Setters and operate directly on the data, and 2) this breaks the current cycle we are stuck in where we need to add a new virtual function to the base class every time one of the child CVariable classes adds new data that it must access with Get()/Set(). 

Adding new data to the child classes for each solver becomes trivial if it is just a data structure. A pure data structure and an object with polymorphism will always be at odds - we should choose the best for each situation.

**Comment by pcarruscag** [comment]
@economon for prototyping, the changes proposed in #753 allow a container to be added to CVariable as a public member and thus directly accessible everywhere (one can even allocate only in some derived constructors, with no risk of leaking memory). For release-quality code I think encapsulation is desirable, that being said I'm not above declaring the client solver a friend of the specific CVariable it uses (also with the changes introduced, there would be a way to access member variables directly without moving them to base CVariable).
I like encapsulation not because of OOP principles but because of `GetVelocity(iDim)` instead of `GetPrimitive(iDim+1)`. As for overhead I think it is 0 as long as methods are inline: [example](https://gcc.godbolt.org/z/QXoExF)
But in all honesty I also chose to change the CVariable interface as less as possible to make my live easier.

**Comment by pcarruscag** [comment]
Ok time to share some results after #753.
I deviated a bit from the original plan in that I skipped the contrived strategy of using a wrapper container with a special [] operator (as it had a slight whiff of hackery), and went straight to adding "iNode" to the methods of CVariable instead (me and a few lines of python...).

The first rule of performance is **"measure it before changing code"**, I broke that rule because as my first post illustrated non contiguous storage at the scale we had is a real killer. With that out of the way, to some extent at least (the layout may not be optimum still) measuring is essential to decide what to do next.

This is the case I am using:
![case](https://user-images.githubusercontent.com/38071223/63288257-27d9d580-c2b4-11e9-9899-8b44b230b8bb.png)
It is a bad wing design (NACA0012) with some sweep and taper and a home-brew mesh whose quality rivals that of the design (it converges and the flow does not separate...).
The mesh is just over 500k vertices (so it "fits" comfortably in my pc) the y+ is not great (obvs) but the aspect ratios are 200 and 2000 in the chordwise and spanwise directions respectively, so not exactly linear solver friendly either. Some settings which are kinda optimal:
- Mach 0.6, AoA 2 degrees;
- SST (1st order);
- CFL 20 (higher and residuals would limit-cycle (regardless of linear solver settings)
- Roe;
- MUSCL - Green-Gauss and Venkat-Wang;
- FGMRES + LU_SGS to 0.05 residual (about 3 iters on avg.);
- 2 levels of MG (1,1,2 iterations, all zeros for other stuff and 0.7 damping both ways);

The case is light on the linear solver and therefore stands to benefit the most from better data layout. Conversely, applications that can take higher CFL / or use central schemes will not benefit as much.

**Running this from scratch to residual of 10^-8 on a couple of Xeon E5-2650v4 (24c total) shows a speedup of 1.4 and just over 10% lower memory usage.**
Those numbers will be better for an equivalent 2D case since the ratio of useful data to pointers and vtables is lower.

After a celebratory dance I attempted to profile the code using [Perf](https://en.wikipedia.org/wiki/Perf_(Linux)) which I "learned how to use" from [a YouTube video](https://www.youtube.com/watch?v=nXaxk27zwlk&t=2052s).
In a nutshell compile the code as usual but with the `-fno-omit-frame-pointer` cxx flag (so perf can figure out the name of the functions, debug symbols are not required).
Run `perf record -g [command]` where command can be your usual `mpirun...` (I did not recompile my mpi with the aforementioned flag), for 2-3 minutes for hundreds of MB of record (hence the 500k mesh...).
Run `perf report -g "fractal,0.5,caller"`, this will show % of time spent in a function relative to its caller and you can expand each function to see what are its children, grandchildren, etc. Like so:
![image](https://user-images.githubusercontent.com/38071223/63290949-725e5080-c2ba-11e9-90aa-ffc834e726db.png)
How cool is that!! Pro-tip hit "a" to look at some assembly, honestly sliced bread has nothing on perf.

NOTE: By and large Perf is not an intrusive tool, as such the accuracy of the measurements is limited i.e. it is probably not a good idea to draw conclusion about <1% variations.

Moving on, I took the top level percentages only, normalized by that of CFluidIteration::Iterate (to exclude pre-processing time) and multiplied the results from the total "iteration time" from the history file. Doing that for before and after results allowed computing individual speedup factors for each important routine (in terms of time, otherwise they are all special and important in their own way) e.g. gradients, limiters, upwind/viscous residuals, etc.
![image](https://user-images.githubusercontent.com/38071223/63292708-30cfa480-c2be-11e9-8d4a-5feb3dc61abf.png)

As predicted the linear solvers stay the same and routines that are light see more speedup than their arithmetic-intensive friends.
What is surprising to me is how intensive the convective residuals appear to be with only a 7% improvement, so surprising in fact, I do not think the above paints the full picture. Maybe the outlet bandwidth bottleneck (into the Jacobian matrix) is more important.
To but that do the test I switched to Euler-explicit time marching and repeat the measurements:
![image](https://user-images.githubusercontent.com/38071223/63293351-d8010b80-c2bf-11e9-8135-2502eac1128e.png)
Better, but not by much, which means upwind and viscous residuals computations might gain a lot from vectorization (SIMD). And like @economon mentioned even more if they are somehow fused together.
It also means the writes to CSysMatrix are relatively expensive, I think there are two-three reasons for it.
- We do a linear search on each Add/SubtractBlock - This could be replaced by a map.
- The Jacobian contributions are first written into a temporary block - Interleaving the writes with the computation could help mask latency.
- That temporary is not stored contiguously - Which makes it hard to vectorize the writes to CSysMatrix.

**So what do I think should be tackled next?**
Hybrid parallelism (wait what?!) from messing about with this case (and more refined versions) it is clear the MG puts some limits on how many cores can be used before it stops being able to produce coarse grids, both in number and quality. Going to an MPI+Threads strategy would move that limit by one order of magnitude.
I think I'll break it off here and keep my thoughts about SIMD and hybrid parallel for a later occasion (I have to do some "real" PhD work for a while) but please, if anyone has ideias, comments, corrections, suggestions, similar ongoing developments (specially)... I am all ears/eyes.

Cheers,
Pedro

**Comment by vdweide** [comment]
Thanks Pedro,

If you want I can run this test case also with the Intel performance tools. These usually give some more info what can be improved to obtain better performance.

Cheers,

Edwin.

**Comment by pcarruscag** [comment]
If it is not too much trouble that would be great Edwin, thank you. Here are all the [files required](https://www.dropbox.com/sh/sovf5osj1d947ii/AADYMPTvP3uq-FSqARdQA_Nva?dl=0).

**Comment by vdweide** [comment]
Pedro,

I did a single core analysis on a Xeon Gold @2.30 GHz for the implicit solver, see below
![SU2_Profile](https://user-images.githubusercontent.com/15017924/63409877-5067e980-c3f2-11e9-8957-0fc3ba26d69d.png)
I can give more details, if needed.

This is not shown in the picture, but the good news is that your feature_contiguous_cvariable_PR branch is a factor 1.25 to 1.3 faster per iteration than the current develop version.

The bad news is that the far majority is still spent in scalar loops and the performance of the vectorized loops is rather poor. However, that was to be expected with the current data structures.

My experience is that if you can vectorize the loops appropriately you can gain a factor of 3 to 4 compared to scalar loops (theoretically 8, but you never get that). However, that means a complete redesign of the current data structures and most likely a loss in generality and readability. If people want, we can start a discussion on this.

And indeed, the inviscid flux computations are very time consuming. In the DG code I created a more hard coded version of the Roe solver and that was significantly faster (factor of 3). So also that is something to think about.

Cheers,

Edwin

**Comment by pcarruscag** [comment]
Thanks Edwin, the vectorized loops in the code are probably very simple array copies, hence the low efficiency? I would put money on not a single vector instruction being generated for the important stuff.

I was surprised by the 1.25 to 1.3 factor you are seeing, for the exact same case I measured 1.39 (to be more precise).

Initially I thought it had something to do with running single core, thus leaving vast amounts of L3 for only that core to use, so on the same 24c platform I ran 2 processes (30MB of cache for each) (very uncivilised) and the factor went down to 1.37, so cache was not the reason.
So then I thought maybe the Intel compilers are very good at optimizing polymorphism away, but the development branch compiled with icc 17 runs at exactly the same speed as when compiled with gcc 5.4.

Then I compiled feature_contiguous_cvariable with icc 17 and it runs 9% slower than the gcc binaries, and so with icc 17 the speedup for this case was 1.27 errrrr... Anyone got a buddy at Intel?

**Comment by pcarruscag** [comment]
No need for Intel buddies, I know what's up.

Take [this code:](https://gcc.godbolt.org/z/siQamn)
```
class Base {
  public:
    inline virtual double get() const {return 0.0;}
};

class Derived : public Base {
    double val;
public:
    Derived(double a) : val(a) {}

    inline double get() const final {return val;}
};


double fun1(Base* obj) {
    return obj->get();
}

double fun2(Base* obj) {
    return static_cast<Derived*>(obj)->get();
}
```

`get` of derived has been marked `final` so in `fun2` polymorphism should be optimized away.

Here is the assembly for gcc 5.4:

```
fun1(Base*):
        mov     rax, QWORD PTR [rdi]
        jmp     [QWORD PTR [rax]]
fun2(Base*):
        movsd   xmm0, QWORD PTR [rdi+8]
        ret
```
`fun1` needs a jump, `fun2` knows what to return right away.

Here is the assembly for icc 17:
```
fun1(Base*):
        mov       rax, QWORD PTR [rdi]                          #16.12
        mov       rdx, QWORD PTR [rax]                          #16.12
        jmp       rdx                                           #16.12
fun2(Base*):
        mov       rax, QWORD PTR [rdi]                          #20.34
        mov       rdx, QWORD PTR [rax]                          #20.34
        jmp       rdx                                           #20.34
```

@vdweide please tell me you did not use icc 19, because it performs this optimization just fine on this simple example.

By the way @talbring (since you asked in #753), take away the `final` keyword and nothing gets optimized by the `static_cast`.

**Comment by vdweide** [comment]
@pcarruscag, my icpc version is 19.0.0.117 20180804....
The speed up is most likely also processor dependent. I ran this case on a Xeon(R) Gold 6140 CPU @ 2.30GHz with 24 Mb cache.

Anyway, this is probably as fast as you can get the code to run with the current data structures. Maybe you can squeeze another 10 percent out of it, but that's most likely it. If we really want to speed things up, we need to change the data structures significantly (structure of arrays, a single array per variable, aligned memory allocation, padding arrays to a multiple of 8, no small loops over the number of dimensions, etc.) . As said before, I think we can get at least a factor of 4 in speed compared to the current version if we can use a significant number of SIMD loops, i.e. vectorization. However, I don't know how much support there is for a pretty much complete rewrite of the computational kernel.

My two cents,

Edwin

**Comment by pcarruscag** [comment]
Interesting. Well I managed to get icpc 19.04 to work last night (cluster IT problems...) and sure enough I got my 9% back. I think that is too large a difference in relative performance of a code that does not have any architecture specific tuning to attribute to 1 CPU generation.

I have some ideas for vectorization + threads without complete re-writes and without readability concerns, I'll prototype them when I have time.

**Comment by vdweide** [comment]
@pcarruscag, what compiler flags do you use? I used the following
-O2 -qoverride-limits -qopt-zmm-usage=high -xCOMMON-AVX512 -mkl=sequential -DHAVE_MKL

**Comment by pcarruscag** [comment]
@vdweide, of relevance to performance I used -O3 -march=native -DNDEBUG. That last one disables the assertions the container class performs to detect out of bounds accesses.

**Comment by vdweide** [comment]
@pcarruscag, your compiler flags perform a lot better. Compared to what I used, it speeds up another 15 percent. Compared to the develop version I get a speed up of 1.5 now on my machine.

As far as your earlier question about vectorization is concerned, yes these are all small loops. None of the bigger loops is vectorized.

**Comment by pcarruscag** [comment]
Awesome, close to 1.5 was what I saw on the skylake architecture too (albeit the consumer version).
Thanks for testing again, without the DNDEBUG flag every access to CVariable is an if statement basically. That flag is now set by default when building with meson.

**Comment by pcarruscag** [comment]
I'm closing this as #753 is coming to an end and from the investigation in #789 it does not seem like the data layout will have to change much even if we want vectorization.
