### ISSUE TITLE
Giles boundary condition implemetation as non reflecting BC 

### ISSUE THREAD

**Issue by monika1387** [su2code/SU2#717]
I am running Nozzle jet flow to understand shear flow for aeroacoustics data. And I see pressure reflections at the outlet and wall boundaries. I tried to use NRBC BC which SU2 had it earlier but looks like latest does not have it. now it has GILES BC, so I am just trying to understand this GILES BC is only for turbomachinery cases? Can we use it for regular nozzle cases? Because I am trying hard to get this BC to be implemented by changing marker names for Boundaries to match Turbomachinery case. 
Please can someone help on this GILES BC implementation? I have attached my GILES BC which I am trying to use to trick this turbomachinery case
[GilesBC.zip](https://github.com/su2code/SU2/files/3315986/GilesBC.zip)

**Comment by stephansmit** [comment]
Maybe I'm missing something here, but if it just a nozzle, why not make it into a turbomachinery case?

You just need the following markers, specifying the inlet and the outlet of your domain.
MARKER_TURBOMACHINERY= (inflow, OutletTwo)
TURBOMACHINERY_KIND= AXIAL
GRID_MOVEMENT= NO

Now you can use the GILES_BC:
MARKER_GILES= (inlet, TOTAL_CONDITIONS_PT, 3.468206185120008e+05, 592.295, 1.0, 0.0, 0.0, 1.0, 1.0, OutletTwo, STATIC_PRESSURE, 94475.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0)

**Comment by monika1387** [comment]
Thank @stephansmit  I agree since its a nozzle so I tried using the turbomachinery case. I tried the same earlier but it did not work out. Still tried exactly the same way you suggested. Below is the segmentation error I received. Attached updated .cfg and .su2 file for reference. Can you help me with this error? This restart and .su2 file was running perfectly fine so far with other Reimann and other BCs.. 

[GILES_BC.zip](https://github.com/su2code/SU2/files/3411841/GILES_BC.zip)

---------------------- Turbomachinery Preprocessing ---------------------

Initialize Turbo Vertex Structure.
Number of span-wise sections in Zone 0: 1.
[nrlogin1:mpi_rank_0][error_sighandler] Caught error: Segmentation fault (signal 11)
Segmentation fault
