### ISSUE TITLE
Improvements to existing CGNS reader

### ISSUE THREAD

**Issue by economon** [su2code/SU2#727]
The current CGNS mesh reader (serial, ADF format) fails when reading large grids in parallel (>100 mio cells) due to memory exhaustion issues.

Updates to the underlying CGNS library are needed (to v3.4.0), and some additional improvements to the CGNS reader in SU2 are being added. 

This is joint work with @MicK7 and a PR will be opened before long.

**Comment by WallyMaier** [comment]
I believe this has been completed with #728
