### ISSUE TITLE
Both polynomial Cp and k for ideal gas

### ISSUE THREAD

**Issue by metuaee** [su2code/SU2#731]
Sometimes rather than solving lots of species equations, I prefer to treat gas as mixture of all species and define material properties such as Cp and k as polynomial of temperature only for mixture. As a solver Fluent can do that. I know Fluent is primitive solver, so it treats temperature as solution variable. Then it is easy to find Cv, Cp, k others secondaries for him. In SU2 as I understand (I am not sure), gamma is always constant in ideal gas model. This is not appropriate for high temperature flows such as in rocket nozzle etc. Is there a way to overcome this problem? Which classes I have to touch and re-write? I will be very appreciated if someone enlighten me.

Best regards.

**Comment by economon** [comment]
Hi @metuaee, thanks for the request. This approach was added for the incompressible ideal gas solver in #624. Please look there for the details on the implementation and the specific files that need to be modified. I expect that a lot of the incompressible implementation could be reused.

**Comment by MarcoFossati** [comment]
Hi @metuaee<https://github.com/metuaee>, further to @economon, I can add that we are presents working on a branch called NEMO (NonEquilibrium MOdels) that will deal with this type of aspects natively through a proper link with the library Mutation++.

We plan to make it available soon through GitHub after some verification and validation steps are finalized.

**Comment by metuaee** [comment]
Hi all,

I guess the difficulty is about calling Config->GetGamma() function in everywhere in code (solver, numerics etc.). I have to change Gamma according to temperature in every routine and be sure ideal gas equation is consistent between Temperature and Pressure.

I get stuck in this point.
