### ISSUE TITLE
Question about SU2_CFD/obj/Makefile.am in the develop branch

### ISSUE THREAD

**Issue by koodlyakshay** [su2code/SU2#737]
Hi all,

Shouldn't the lines 82-99 in SU2_CFD/obj/Makefile.am say

    ../include/variables/*.hpp

instead of 

    ../src/variable/*.hpp

Regards,
Akshay

**Comment by talbring** [comment]
Yep you are right. Apparently automake doesn't care about header files. I removed them from the .am files in #736.
