### ISSUE TITLE
Electromagnetic MHD Module

### ISSUE THREAD

**Issue by WenyinWei** [su2code/SU2#741]
**Is your feature request related to a problem? Please describe.**

Hello guys,

Have you ever heard about MHD(magnetohydrodynamics) simulation? That's used in plasma physics with the hypothesis that most of the particles in a control volume have the same velocity. However, the atoms' first electrons are stripped and, hence, magnetic field confinement to the plasma is possible due to ions and electrons' net charge. Moreover, due to the huge mass difference between ion and electron, they are normally treated as two-fluid interacting with each other.

The most successful MHD code is produced by [PPPL](https://w3.pppl.gov/~nferraro/m3dc1.html), but not open source. I want to base on SU2 to make a flexible one. Do you think a feature_* or develop branch is better?

feature_ExMHD(extended MHD) may be a good branch name?

**Describe alternatives you've considered**
If there already exists the relevant module concerning the electromagnetic content, please let me know. Importantly, if there exists a chemical diffusion problem solver, it would reduce my coding time significantly by imitating the code. 

If anyone can give some guidance on how to change the governing equations quickly and safely, please inform me.

**Comment by WenyinWei** [comment]
Surprisingly I have found the existing content related to plasma simulation in SU2. Really amazing. Could anyone give me any clues of the correspondent .cfg files? Or help me find the governing equations change which makes the plasma equations different from the neutral gas. 
 
![image](https://user-images.githubusercontent.com/33152225/61871269-5fef3200-af1b-11e9-82c5-cd8418a6f83c.png)

It already seems good enough at considering *E* field, but *B* is omitted. I can strive to supplement the equation. Could anyone give some guidance to me, a newcomer of SU2?

[Stanford University Unstructured An open-source integrated computational environment for multi-physics simula.pdf](https://github.com/su2code/SU2/files/3431264/Stanford.University.Unstructured.An.open-source.integrated.computational.environment.for.multi-physics.simula.pdf)

**Comment by clarkpede** [comment]
You may find the comments on issue #655 helpful. Do the comments there answer your question?

In case you were not aware, many questions can be answered by searching past issues and pull requests on Github.  To search past issues, go to the "Issues" tab on github, then type your query in the search bar.  To search both open and closed issues, you'll want to remove the "is:open" filter that's included by default.  For example, searching for "is:issue plasma" gives me two results, this issue and issue #655. Searching for "is:issue CMake" gives me issue #685 as the top result.

To search pull requests, you can do the same from the "Pull Requests" page.  The same "is:open" and "is:closed" filters apply there as well.  To search open, closed, and merged pull requests, you'll want to remove the "is:closed" filter.

You can also search for both pull requests and issues from either search bar. You just need to remove the "is:pr" or "is:issue" tags.

**Comment by WenyinWei** [comment]
Thanks for your kindly reply, Clark. It is a good habit to have a search before asking, and I should keep it. 

"feature-AdjTNE2" seems to be a good example to learn from how to edit the kernel of governing equations. I would try to deepen the utilities of electromagnetic computation.

**Comment by WenyinWei** [comment]
I found SU2-NEMO branch is executing a multi-species work and have an MHD potential, I should join them.
Hello @economon, it seems that NEMO relies heavily on Mutation to control species transform. Would you mind introducing to me how to let them incorporate well manually? Or I can contribute to embed the Mutation in the make streamline of SU2.

**Comment by WenyinWei** [comment]
For the confinement of plasma, an external EM module to probably is necessary for simulation work, helping with ensuring the EM background that plasma feels. Here are some EM module candidates, I will supplement more in a few days.

| Library  |      Language      |  MPI support | Comments |
|----------|-------------|------|---|
| [openEMS](http://openems.de/start/index.php) |   --| -- |--|
| [EMTL](http://fdtd.kintechlab.com/en/start) |   -- |   -- |--|
| [gprMAX](http://www.gprmax.com/) |  --| --    |--|
| [Elmer FEM](http://www.elmerfem.org/blog/) | -- | --    |--|

**Comment by economon** [comment]
Hi @WenyinWei : if they have some time, I think that @WallyMaier and @MarcoFossati could fill you in on their approach with the TNE2 branch and NEMO (the idea is for those branches to be merged). @MarcoFossati and one of his students have been coupling Mutation++ to SU2 and have been making nice progress.

For the work you cite some time ago in our group at Stanford, Maxwell's equations were solved directly in SU2 (well perhaps just a subset, Gauss's law, if I remember correctly). That work should still be in the git history back in v1.0 or v2.0, I think. Should be able to find it with some searching.

**Comment by MarcoFossati** [comment]
Dear @WenyinWei: presently Mutation is already fully linked to SU2 and is not only something that will allow to deal nicely with chemical reactions, but it presently also used to get all the species/mixture thermochemical properties (including ions and free electrons) and to address thermal non equilibrium (i.e. multiple-temperatures) by incorporating characteristic vibrational and electronic temperatures for various species.

We still have not pushed the latest developments in NEMO-TNE2 since we are finalizing some verification and validation test cases and producing appropriate documentation to be added on the SU2 webpage. @srcopela already created a nice substrate for all these features now we are trying to put this up to speed with the latest SU2 versions and capabilities and go beyond that with additional capabilities.

Introducing MHD is definitely something on our roadmap, but something that will come after we have completed our merging of TNE2+NEMO and we have one solid feature with thermochemical nonequilibrium. More than happy to discuss further, if you feel that you can take up this and provide a complete MHD functionality in SU2.

**Comment by WenyinWei** [comment]
Thank all for your kindly reply. I might first try to expand the Gauss equation in SU2 to complete Maxwell equations. After we finish our parts respectively, I can combine EM equations with your plasma equations together. 

Let me dive into SU2 code, need more time to understand its framework.

**Comment by WenyinWei** [comment]
Hello guys, maybe I know why only the Gauss equation is achieved in SU2. That is due to the lack of a kind of appropriate numerical scheme of vorticity, right? I have not found the vorticity scheme in CNumerics and doc.

**Comment by WallyMaier** [comment]
Hiya!  I am not completely sure why at the moment.  But If that's the case, it is doable to implement the correct scheme required, I would think!

**Comment by WenyinWei** [comment]
In progress, I will finish the job in 2 or 3 months.

**Comment by Gcubed333** [comment]
@WenyinWei, did you end up finishing that MHD module? I see that SU2-NEMO is in the current version of SU2, but it doesn't look like Maxwell's equations are mentioned in SU2's theory documents.

Please let me know if you finished it and would be willing to send it my way.

Thanks!
