### ISSUE TITLE
Adaptive Mesh Refinement

### ISSUE THREAD

**Issue by WenyinWei** [su2code/SU2#743]
**Is your feature request related to a problem? Please describe.**
For the problems in which parameters located in only a limited region vary much faster than others, the mesh is able to self-adjust to reduce the requirement to computational resources. One mature framework of the technique is [Chombo](https://commons.lbl.gov/display/chombo?atl_token=81243520c3e3754ade36ac0a45eb4e156dac45e0), which can surprisingly reduce the time required to finish the computation job for the aforementioned problem such as moving shock-wave.

**Describe  the solution you'd like**
AMR frame option added. 
Maybe it will be very difficult to merge Chombo and SU2, and not necessary. We can also develop our own AMR algorithm based on current research.

**Describe alternatives you've considered**
The aim of AMR is just for reducing run time. Or just increase the Grid number 

**Additional context**
[Adaptive Mesh Refinement.pdf](https://github.com/su2code/SU2/files/3426255/Adaptive.Mesh.Refinement.pdf)
[An introduction to AMR.pdf](https://github.com/su2code/SU2/files/3426257/An.introduction.to.AMR.pdf)

**Comment by MarcoFossati** [comment]
Dear WenyinWei,
presently SU2 is interfaced with the INRIA AMG library for mesh adaptation. You can find all the necessary details and examples at https://pyamg.saclay.inria.fr

There are efforts going on in Stanford to connect it to goal-oriented adaptation.

**Comment by WenyinWei** [comment]
Dear Marco,
That’s really an awesome website to show the power of SU2. Definitely make SU2 great. I have no problem now. If I have more relevant questions about AMR, I will reopen the issue. Thanks for your information, Macro!
