### ISSUE TITLE
Develop branch: No output in history files turbomachinery cases

### ISSUE THREAD

**Issue by stephansmit** [su2code/SU2#746]
During the change to the multizone config, the values in the history files for the turbomachinery cases are not being written anymore for the develop branch. The files are created as well as the header, but no values are written during every WRT_CON_FREQ iteration. Is there a marker that I need to add? I checked it with the APU_turbocharger testcase, nothing is written there as well..

 - SU2 Version: [current develop branch @ commit 27f3875 ]

**Comment by talbring** [comment]
Hi @stephansmit , 

thats indeed a bug ... I will fix it in one of the currently open PRs. Until then you can solve it by removing the following line:

https://github.com/su2code/SU2/blob/develop/SU2_CFD/src/output_structure.cpp#L4603

**Comment by stephansmit** [comment]
@talbring Thank you that indeed solved the issue.
