### ISSUE TITLE
Travis builds without Draft PR

### ISSUE THREAD

**Issue by TobiKattmann** [su2code/SU2#748]
Hey, 
I recall that @talbring disabled the automatic travis triggering of feature branches (if specified in .travis.yml) together with enabling the Draft PR's. Unfortunately i can't find the issue or PR where this was mentioned anymore.  

Is it wanted to open Draft PR's if one wants travis testing? If yes, then there should be a lot more Draft PR's right

My problem currently is that I can click `Restart build` in travis on my feature branch but it actually does a checkout on the old commit sha1 sum [Link to travis job](https://travis-ci.org/su2code/SU2/builds/556792412). Is there a way to trigger the builds automatically with the freshest commit like before without a Draft PR?

Thanks for clarification, Tobi

**Comment by talbring** [comment]
You have to use the 'Trigger Build' feature to trigger a build for a branch manually. You find this option in Travis under "More options" on the top right. 

I was mentioning that change here:
https://github.com/orgs/su2code/teams/developers/discussions/3

**Comment by TobiKattmann** [comment]
Hey @talbring, currently the 'Trigger build' function for non-PR branches seems to not work. @cvencro and I get the error message  `Oh no! You tried to trigger a build for su2code/SU2 but the request was rejected. ` . Do you know more about it? Thanks

**Comment by talbring** [comment]
You have to add that particular branch to the .travis.yml file.
See https://travis-ci.org/su2code/SU2/requests (Branch "feature_STLwriter" not included per configuration.)

**Comment by TobiKattmann** [comment]
Yep can confirm! ✅
