### ISSUE TITLE
exe is so large when build SU2 on windows using cygwin

### ISSUE THREAD

**Issue by hjxy2012** [su2code/SU2#754]
I build SU2 on windows using cygwin following this instruction.
https://su2code.github.io/docs/Cygwin-Build-for-Windows/
The SU2_CFD.exe generated is more than 600MB. And it can only be executed in the cygwin command line. The binaries provided by SU2 official is less than 18MB. Maybe it's because the static linking. I am not sure. Can anyone help me? Thank you.

**Comment by pcarruscag** [comment]
I am not familiar with cygwin but maybe you compiling with debug options (-g) ? What optimization level are you using?

**Comment by chiefenne** [comment]
Hi,
I made the Cygwin build installation instruction example. I just checked my SU2_CFD.exe and it is 625MB as well. Nevertheless, I have no clue why this is the case and how to solve that.

For reference I attach my config.log file.

[config.log](https://github.com/su2code/SU2/files/3483335/config.log)

**Comment by pcarruscag** [comment]
You are compiling with -g -O2, get rid of -g

**Comment by hjxy2012** [comment]
> miliar with cygwin but maybe you compiling with debug options (-g) ? What optimization level are you using?

I don't use any build optimization particularly at all. I'll check it and try to add some optimizations as your instruction. Thank you.

**Comment by hjxy2012** [comment]
> Hi,
> I made the Cygwin build installation instruction example. I just checked my SU2_CFD.exe and it is 625MB as well. Nevertheless, I have no clue why this is the case and how to solve that.
> 
> For reference I attach my config.log file.
> 
> [config.log](https://github.com/su2code/SU2/files/3483335/config.log)

The fllowing link may help us
https://stackoverflow.com/questions/1042773/gcc-c-hello-world-program-exe-is-500kb-big-when-compiled-on-windows-how

**Comment by hjxy2012** [comment]
> 2, g

I follow your instruction and try to rebuil it. The size of SU2_CFD.exe reduces to 596MB. Maybe I need more optimization options.

**Comment by hjxy2012** [comment]
> Hi,
> I made the Cygwin build installation instruction example. I just checked my SU2_CFD.exe and it is 625MB as well. Nevertheless, I have no clue why this is the case and how to solve that.
> 
> For reference I attach my config.log file.
> 
> [config.log](https://github.com/su2code/SU2/files/3483335/config.log)

According to the configure file(line 2726), try 'make install-strip' after 'make'. 
The exe will be smaller than before after adding the strip option.
The following link may help. Just have a look at faq 6.3.
https://www.cygwin.com/faq.html
Good luck.

**Comment by chiefenne** [comment]
**make install-strip** did the job.
I'll add that to the documentation.
