### ISSUE TITLE
Discrete Adjoint Iterations not controlled by EXT_ITER

### ISSUE THREAD

**Issue by jayantmukho** [su2code/SU2#755]
This is using the develop branch. 

I noticed that regardless of what I set EXT_ITER to, the discrete adjoint only ran for 1000 iterations. After some digging, I realized that the number of iterations for the discrete adjoint is controlled by the ITER option, not EXT_ITER. The CFD simulations iterations is still controlled by the EXT_ITER option. 

This is different behavior from before and I wasn't sure if this was intentional or not.

**Comment by pcarruscag** [comment]
See @talbring's reply in #752 it is part of their effort to standardise those options for time domain, multi physics, etc.
