### ISSUE TITLE
Forces Breakdown Manual Page

### ISSUE THREAD

**Issue by carlos-pereyra** [su2code/SU2#758]
Thank you very much for creating SU2,

I would like to know more about the drag coefficient calculation used to produce the results in Forces_breakdown.dat.

May someone add a page on the SU2 website to include further details on this?

Thanks a bunch.

**In general it would be great if there was a manual page for configuration options used in both compressible and incompressible flow simulations.**

**Comment by WallyMaier** [comment]
#788
