### ISSUE TITLE
SU2 configurer

### ISSUE THREAD

**Issue by WenyinWei** [su2code/SU2#759]
**Is your feature request related to a problem? Please describe.**
Hello guys, I developed a [primitive tool](https://github.com/WenyinWei/SU2Configurer) to help with editing the configure file. Anyone can add or delete lines freely in the tool to configure your input to SU2. After the editing, the menu can save the .cfg file as a standard SU2 configure file. 

![Profile_Screenshot_2019_08_16](https://user-images.githubusercontent.com/33152225/63140409-6cdfdc80-c014-11e9-9e09-fe8b970d84ff.png)

**Describe the solution you'd like**
1. I am not familiar with the software release pipeline so the tool now just works in my PC with Linux version. Anyone interested in joining to make it more complete?
It is based on Qt so there should be no problem for its usage on cross-platform.   

2. I am not so familiar with the option reliance relationship in SU2 cause there are too many options in the configure template. Complicated reliance and number of options obstrcut the further intelligent implementation of automatical completion. 

Any developer willing to tell me your module's option relationship will be appreciated.

**Comment by WenyinWei** [comment]
Any response or comments? Is this worthwhile work? :eyes:

**Comment by economon** [comment]
@WenyinWei : thanks for the proposal.. this idea has come up several times over the years and there have been a couple of implementations. You might want to see the old PR here, which proposed something similar (it is a pity that we were unable to merge that work). My comments there still apply: 

https://github.com/su2code/SU2/pull/172

If it is to go into the main repo, the key is that it is easy to keep updated. It should automatically parse the currently available options in the C++, like the old python-based script did.

**Comment by WenyinWei** [comment]
Hello Economon, here are some of my suggestions for the future convention of comments of the option structure:

1. __Index__. To illustrate the relationship among so many options, we need to set some reliance relationship manually in the comment lines. Do you think using names of options as index is reliable? I think it will be helpful for code writers, but might not for code readers.
2. __Relationship__. Here are some kinds of relationship between options. They are needed in comment for auto parsing.
  - _Reliance_. Some options may rely on the precedent ones, otherwise they will not be triggered to be used. Furthermore, descendent options may be optional or compulsory. For the optional ones, users don’t have to set the values they need, while for the compulsory ones, users will automatically see the tips of what kinds of options are needed.
  - _Mutual Exclusive_. Some options can not coexist together, or their precedent can not coexist together. Maybe option a has precedent A, option b has precedent B. If A and B can not coexist, a and b can’t , too.

I wish that there is already such C++ package for our need, even when it just covers the functionality of structuring the relationship net. Do you have any idea of such code that can handle the option relationships easily?

Any supplement?
