### ISSUE TITLE
Test case about AUSMPLUSUP or AUSMPLUSUP2

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#761]
> Hello. Can you add a test case about AUSMPLUSUP or AUSMPLUSUP2? I installed SU2 6.2.0 and used it to simulate two-dimensional lid-driven cavity flow. When I set 'CONV_NUM_METHOD_FOLW' to be 'AUSMPLUSUP' or 'AUSMPLUSUP2', it shows 'Error in ''void CSoLver::SetResidual_RMS(CGeometry*, CConfig*):' and 'MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD'. But when I set it to be other schemes like AUSM, ROE or so, it runs. Maybe if there is a test case, I can find where is my mistake. Thank you.

_Originally posted by @cjz667 in https://github.com/su2code/SU2/pull/628#issuecomment-522633022_

@cjz667, there are a couple of examples in PR #691, specifically here: https://github.com/su2code/SU2/pull/691#issuecomment-502193463
Which may not run with v6.2 but should work with the current develop version.
In any case can you please upload your config?

**Comment by cjz667** [comment]
Hello, @pcarruscag 

Thank you for help. I try the examples and they run well. By the way, SU2 v6.2.0 doesn't have the option 'USE_ACCURATE_FLUX_JACOBIANS'. I'm not practised enough to know what it is for.

Here is my config.
[cavity.zip](https://github.com/su2code/SU2/files/3525060/cavity.zip)
It still diverges on lid-driven cavity flow case, at even a rather low CFL number, like 0.01. However, when I simulate laminar boundary layer case with 0.1 incoming mach number, it is OK, converging very slowly.

Regards
Cao J. Z.

**Comment by pcarruscag** [comment]
Hi @cjz667,
I know, that is why I suggested using the current development version. You can read about what that option does in #691.

AUSM+up and similar schemes need a reference Mach number, which comes from MACH_NUMBER, apparently if that is 0 they do not do so well.
These settings should get you started: [cavity.txt](https://github.com/su2code/SU2/files/3526060/cavity.txt)

I will put a check in the code for v7 to avoid mysterious "divergence on the first iteration" problems, I'll leave this issue open to remind me.

Cheers,
Pedro

**Comment by aeroamit** [comment]
Hi @pcarruscag,

Indeed Meng liou has limited this reference Mach  parameter to  0.3 for some of the cases in his paper. But for low speed flows, this cutoff parameter has to go proptional to the Mach number for appropriate numerical dissipation scaling. With constant Ref. Mach 0.3 or so, you won't get that accuracy for successively lower Mach numbers (I have tried earlier) . On the other hand SLAU is free from such reference parameter. But it can be seen from the results that ausmup/up2 does slightly better job in low Mach limit(where reference Mach can be correctly specified (especially external flow applications).

**Comment by pcarruscag** [comment]
Error message for Minf = 0 has been included in #753

**Comment by cjz667** [comment]
Hello. What is the difference between AUSMPLUSUP and AUSMPLUSUP2?

**Comment by pcarruscag** [comment]
> Hello. What is the difference between AUSMPLUSUP and AUSMPLUSUP2?

Mostly the way the pressure flux is defined: https://www.sciencedirect.com/science/article/pii/S0021999113001769
