### ISSUE TITLE
config_template.cfg not up to date

### ISSUE THREAD

**Issue by vdweide** [su2code/SU2#772]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it is is not a bug either. The config_template.cfg in develop is not up to date.

**Describe the solution you'd like**
The keyword PHYSICAL_PROBLEM is still present in the template file. This should be replaced by SOLVER. However, there may be more, so it is a good idea that more people have a look at config_template.cfg.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by talbring** [comment]
Thanks for mentioning this. I will deal with this definitely before the release. Maybe I am gonna add a small test case which just reads the config_template.cfg to check whether it is up-to-date.

**Comment by WenyinWei** [comment]
One more thing to be added, please let the option authors also signature their email in comments in case of that nobody knows why the option exists and the community lost contact with the author.

**Comment by pcarruscag** [comment]
> One more thing to be added, please let the option authors also signature their email in comments in case of that nobody knows why the option exists and the community lost contact with the author.

I don't think anyone wants to have their email that publicly available. When features go out of support they are taken out of the code.

**Comment by WallyMaier** [comment]
I think this will be addressed with 7.0.   But the SU2_CFD -d  option seems to address this as well

**Comment by talbring** [comment]
Solved with release of v7.
