### ISSUE TITLE
HEAT_EQUATION_FVM lacks example .cfg and has bugs & Unsteady case diverges

### ISSUE THREAD

**Issue by WenyinWei** [su2code/SU2#783]
**Describe the bug**
1. Please update config template.

Now the physical problem choices in config template file still indicate that users have (EULER, NAVIER_STOKES, FEM_EULER, FEM_NAVIER_STOKES, FEM_RANS, FEM_LES,
                              **WAVE_EQUATION**, **HEAT_EQUATION**, FEM_ELASTICITY,
                              **POISSON_EQUATION**) to choose, where Wave and Poisson have expired, while Heat_Equation needs to be typed in as **HEAT_EQUATION_FVM**.

2. HEAT_EQUATION_FVM hard to run standalone
There is no example demonstrating how to use HEAT_EQUATION_FVM as the physical kernel. Users don't know how to configure. And there seem to be bugs while using HEAT_EQUATION_FVM physical kernel.

![2019-09-01 22-26-35 的屏幕截图](https://user-images.githubusercontent.com/33152225/64077943-c4b25f00-cd07-11e9-92cb-36fb96d97c69.png)

**Reproduce**

Here are configuration files for developers to debug.

[heat_wedge_HLLC.zip](https://github.com/su2code/SU2/files/3563624/heat_wedge_HLLC.zip)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 19.04)
 - C++ compiler and version:  g++ (GCC) 8.3.0
 - MPI implementation and version: no MPI
 - SU2 Version: v6.2.0

**Comment by WallyMaier** [comment]
I believe the config_template.cfg will be updated for the 7.0 release as per #772.  
I think this would be a great opportunity to create proper documentation/tutorials for the solvers.

**Comment by WenyinWei** [comment]
Hello Wally, do you know anyone has a TestCase config of HEAT_EQUATION_FVM? I have not found such one in the TestCases folder.

**Comment by TobiKattmann** [comment]
Hi @WenyinWei, 
using (on Linux) `grep -r HEAT_EQUATION_FVM .` in the `<SU2_root>/Testcases` folder will point you to `./coupled_cht/incompressible/configSolid.cfg:15:SOLVER= HEAT_EQUATION_FVM`. It is a CHT Testcase (i.e. coupled fluid and solid) but by changing `MARKER_CHT_INTERFACE ` in configSolid.cfg to `MARKER_ISOTHERMAL=(PINSD, 350)` for example you should be able to run the configSolid.cfg alone. 
Hope that helps, Tobi

**Comment by WenyinWei** [comment]
Thanks a lot, Tobi! I did find the file which is the only one has SOLVER=HEAT_EQUATION_FVM before and got an error output in the boundary condition. Your answer told me how to settle the BC error. I will have a try and test it later.

**Comment by WenyinWei** [comment]
Hey Tobi, I have tried and succeeded in testing the HEAT_EQUATION_FVM example. One more thing to mention, to run the configSolide.cfg alone, another line needs to be edited. 

```
%EXTRA_HEAT_ZONE_OUTPUT = 2-->
EXTRA_HEAT_ZONE_OUTPUT = 1
```

And one can directly delete all things concerning iZone=1 and rename iZone=2 to be iZone=1.

![2019-09-04 15-56-09 的屏幕截图](https://user-images.githubusercontent.com/33152225/64236361-d163cc80-cf2c-11e9-9971-2d4e2c01955c.png)


Except for that, is anyone familiar with the error: SU2 diverge? Every time when I want to add unsteady options to make an animation, the error tells me the solution diverges.

```
------------------------------ Begin Solver -----------------------------


Error in "void CSysSolve::ModGramSchmidt(int, std::vector<std::vector<double> >&, std::vector<CSysVector>&)": 
-------------------------------------------------------------------------
SU2 has diverged.
------------------------------ Error Exit -------------------------------
```

**Comment by pcarruscag** [comment]
I am very familiar. In your case it means the linear solver diverged, probably because something went wrong when assembling the Jacobian matrix...

**Comment by WenyinWei** [comment]
I have tried many times to figure out why the HEAT_EQUATION_FVM does not support unsteady simulation, but failed. It seems that when one set the UNSTEADY_SIMULATION= NO, he can see the flow.dat rewritten as long as a new iteration stage passes just like time goes by. However, when the option is set to be TIME_STEPPING, outputs are in flow_000*.dat Tecplot data file but the data keeps the same without change no matter how much time passes by. 

Dual time method seems to be totally unavailable in HEAT_EQUATION_FVM, because they cause the diverging problem.

**Comment by oleburghardt** [comment]
Hi there,
let's wait for the new release before proceeding with this issue. Many bugs had been removed along the road implementing a CHT capability and they will be merged in by then.

I'll also add a tutorial to make `HEAT_EQUATION_FVM` and CHT an official feature. There is no link to `HEAT_EQUATION` (a FEM implementation). I think `HEAT_EQUATION` is just not supported anymore.
