### ISSUE TITLE
Define Monitored Shape Area

### ISSUE THREAD

**Issue by carlos-pereyra** [su2code/SU2#788]
For simulations with **two or more bodies** defined within a mesh, it is difficult to define their corresponding areas. For instance:

`REF_AREA= 0`

Automatically determines the 'wetted' area of the two shapes 'shell1' and 'shell2' to be plotted or monitored, when we define: 

```
% Marker(s) of the surface to be plotted or designed
MARKER_PLOTTING= ( shell1, shell2 )
%
% Marker(s) of the surface where the functional (Cd, Cl, etc.) will be evaluated
MARKER_MONITORING= ( shell1, shell2 )
```

**The problem I am having is, how do I manually define the cross-sectional area for both of these shapes, shell1, and shell2.** At the moment I am solely relying on `REF_AREA=0` to determine the area. 

For my case this is especially relevant for determining proper drag coefficients.
Thanks.

**Comment by pcarruscag** [comment]
The forces_breakdown file gives you the \*cough\* breakdown per surface, the monitored value is just an indication of convergence.

**Comment by carlos-pereyra** [comment]
I understand the forces_breakdown.dat file contains information per surface, but drag coefficients CL, CD, CSF, etc are a function of the shape-entities cross-sectional area. 

So if you have multiple shapes, how do you assign the cross-sectional area per surface?

Thanks.

**Comment by WallyMaier** [comment]
Hi @carlos-pereyra , 
Have you found a solution for this problem?  Or are you still getting a singular force compared to multiple forces?

**Comment by carlos-pereyra** [comment]
@WallyMaier 

I am able to get two forces since I have defined
`% Marker(s) of the surface where the functional (Cd, Cl, etc.) will be evaluated
MARKER_MONITORING= ( shell1, shell2 )`

For instance I see 

`Surface name: shell1

Total CL...
...

Surface name: shell2

Total CL...
...

`

But these coefficients are dependent on shape attributes like `REF_AREA= 0` and `REF_LENGTH= 0.5` (diameter of sphere being 1 unit). I was just curious if there's a way for the user to define `REF_LENGTH` or `REF_AREA` for two objects that are being monitored? At the moment these shapes are the same dimension but I was curious about what to do in the case they are not identical.

**Comment by WallyMaier** [comment]
@carlos-pereyra 

I do not think its possible to define multiple ref_area and ref_length.  One suggestion would be to set them both at one and use the output non-dim forces to calculate the forces/transform forces offline.
