### ISSUE TITLE
Looking for a native piecewise linear interpolation function in SU2

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#791]
Hello everyone,

I am starting to work on adding inlet file interpolation capabilities in SU2. I currently have a spanwise PT and TT distribution (r vs PT or TT) for an inlet boundary for a Stator (periodic, turbomachinery case). I want to carry out a spanwise interpolation at the inlet vertices.

I can write a program to read an inlet file for a new format (r vs PT or TT). Then I want to 1D interpolate this data against the radii of all the vertices on the inlet face. The best way is to generate a **piecewise 1D interpolation function** that can return the value of the interpolated data at that radius. I have done this before in python using 'interp1D'. I have found the following library for C++ that does have this capability:

http://people.math.sc.edu/Burkardt/cpp_src/pwl_interp_1d/pwl_interp_1d.html

which will require _'The PWL_INTERP_1D test code needs the R8LIB and TEST_INTERP libraries._'

I hope these libraries will be integrated with SU2 without any issue. However, it would be better if I can use some of the built-in interpolation capabilities in SU2 like what I found in 'interpolation_structure.cpp'. I also look forward to extending this capability for 2D interpolation(that is, in r and theta).

It would be very helpful if someone who has worked with interpolation before can point to a function that is capable of generating a piecewise interpolation function that could work for my case or can pitch in any idea related to this.

Thanks!

@vdweide  @clarkpede @economon @juanjosealonso @sravya91 @bmunguia @jayantmukho

**Comment by clarkpede** [comment]
I've always interpolated my points externally, using Python.  I'll take my data, take the inlet vertices, and write a python script to interpolate between the two. I would also like to have more robust interpolation within SU2 itself, but it's not a high enough priority for me to work on it personally.

**Comment by auzbaig** [comment]
@clarkpede Thanks for your response! My work in focused on Turbomachinery and very frequently we need to have inlet profiles. I hope my work will give a neater, cleaner way of making this possible, though I also used python scripts in the past.

**Comment by juanjosealonso** [comment]
If you are interested, @vdweide spent considerable time between 2003 and 2008 writing a multiblock-structured turbo machinery code called SUmb, as part of the DoE ASCI program.  SUmb, although written in Fortran90/95, had all of the interpolation capabilities that you need for turbo machinery computations when radial inlet / outflow profiles (Tt, Pt, flow angles, static pressure, etc.) are given as inputs on a radial grid whose spacing does not match that of the actual computational grid.

You may consider creating some interpolation functions (with all the safeguards and error codes) in C++ based on the SUmb code (which was structured in a C++-like way) or at least take inspiration from that approach to identify interpolation utilities / libraries in C++ that could be used for the same purpose.

Both @vdweide and I can provide you with access to the appropriate routines / functions in SUmb.

On Sep 20, 2019, at 3:30 PM, Aman uz zaman Baig <notifications@github.com<mailto:notifications@github.com>> wrote:


@clarkpede<https://github.com/clarkpede> Thanks for your response! My work in focused on Turbomachinery and very frequently we need to have inlet profiles. I hope my work will give a neater, cleaner way of making this possible, though I also used python scripts in the past.

**Comment by auzbaig** [comment]
@juanjosealonso Thanks for your response. I would definitely want to have a look at SUmb. If there is some documentation with the code and any published work that shows its capability will also help.

> Both @vdweide and I can provide you with access to the appropriate routines / functions in SUmb.
Please do provide me the access.
