### ISSUE TITLE
Bug in CDriver.cpp

### ISSUE THREAD

**Issue by koodlyakshay** [su2code/SU2#792]
Hello,

There is a stray allocation in the Integration_Postprocessing routine in line 1804 in the develop branch.

Currently reads:

    if (template_solver) integration[val_iInst][TEMPLATE_SOL] = new CSingleGridIntegration(config);

instead of delete. Is this resolved in a more recent PR?

Cheers,
Akshay

**Comment by talbring** [comment]
@koodlyakshay Thanks for mentioning. That's indeed a bug. Will remove it in one of my PRs.

**Comment by koodlyakshay** [comment]
Hi @talbring ,

Also I noticed there is no breakdown file being written for incompressible problems. I suspect this is because the flow boolean in the SpecialOutput_ForcesBreakdown routine only checks for EULER, NS and RANS but not the INC versions of those.  

Cheers,
Akshay

**Comment by talbring** [comment]
@koodlyakshay Thats already fixed in #724 !
