### ISSUE TITLE
variable properties (transport and thermodynamic) for compressible flows with any eos

### ISSUE THREAD

**Issue by FlorianDm** [su2code/SU2#794]
Hello,

I'd like to model compressible flow  but I have also strongly varying cp (900-2000), gamma (1.2-1.8), mu (1.1-1.6e-5), k (0.012-0.024) and thus Pr (0.8-1.2) in my domain (MachNo 0.1-2, T 270-360K). 

Is there any plan to make polynomial properties available with the implicit compressible solver? Or perhaps completely table based eos and properties?  Does it matter then if it is an ideal gas or a Peng-Robinson eos? 

I consider implementing something myself. According to https://github.com/su2code/SU2/pull/624 it seems to be just a question of "activating" the options.

Any guidance would be appreciated. 

Best regards
Florian

**Comment by stephansmit** [comment]
"Or perhaps completely table based eos and properties"

In the branch "feature_unst_lut" there is a fluid model with a look up table. You need to supply a unstructured table for the fluid properties and a structured table for the transport properties.

**Comment by banuti** [comment]
Hi,

is that branch still active? It seems the last commit was more than two years ago.

Best,
Daniel

**Comment by matteopini** [comment]
Hi Daniel,

You can find the implementation of variable properties with cubic EoS in the master/develop version. If you need to compute the properties with more accurate thermo-physical models, e.g. multi-parameter, there are 2 main ways:


  *   By using the external library FluidProp (feature_fluidprop_final, yet outdated)
  *   By means of look-up tables (feature_adjoint_lut)

We are about to improve the look-up table method and will work on having this feature in the develop soon. Just let me know if you are interested and I will give you more details.

Best,

Matteo





——————————————————
Dr. ir. Matteo Pini, PhD
Assistant Professor
Propulsion & Power<http://www.pp.lr.tudelft.nl/>
Aerospace Engineering Faculty
Delft University of Technology

Kluyverweg 1
2629 HS Delft
The Netherlands

Phone :  +31 15 27 84794
Skype  :  matteo_pini1
