### ISSUE TITLE
Turbulence convective numerical scheme poor default

### ISSUE THREAD

**Issue by WallyMaier** [su2code/SU2#796]
When running a turbulence model, one must select CONV_NUM_SCHEME= SCALAR_UPWIND.
To my knowledge, this is the only option to run RANS.

In my opinion, this should should be defaulted to the option that would allow this to run. 

I think this brings up a bigger issue, that I have mentioned before, it seems that options and defaults are mismatched, poor or not properly documented.

**Comment by pcarruscag** [comment]
Are there defaults for convective schemes? Looking at the code that does not seem to be the case.

**Comment by WallyMaier** [comment]
You are correct. However this leads to weird behavior when running.

**Comment by talbring** [comment]
As much as bug reports and enhancements are also appreciated, we are not following the strict *see something, say something* policy :) we need more application of the *see something, do something* policy :D

**Comment by pcarruscag** [comment]
Addressed in #824, error message thrown (it is not easy to implement a good default due to shared code with other CONV_NUM_METHOD_??? options).
