### ISSUE TITLE
Pressure field near wall using SST 

### ISSUE THREAD

**Issue by emoralest6** [su2code/SU2#797]
While doing some simulations with the version 6.2.0, I found a strange behaviour on the pressure field.
The test case is a naca0012 at AoA=0°, M=0.7, Re=9e6.
When running with SST turbulence model, the pressure field in the "boundary layer region" is not constant. Using SA turbulence model, this behaviour is not shown. It looks like the tubulent kinetic energy field affect the computation of pressure field, leading to a non zero gradient pressure at wall, as shown in the attached figures:

In the figures it can be seen a comparison between the in-house solver of the Italian Aerospace Research Center (CIRA), where SST model is implemented, and SU2 using both available turbulence models, SST and SA. The isolines represent the pressure field and the contour is the TKE field obtained with SU2 with SST. In particular, solid red line is CIRA solver, the solid black line is SU2-SST, and dashed black line is SU2-SA.

Near the LE where TKE is 0, the isolines are similar and 0 pressure gradient at the wall is obtained with both turbulence models. When TKE starts to grow, the pressure computed with SU2-SST shows a non constant behaviour and at the wall has non 0 gradient. Furthermore,  in the wake region the defect is more evident.

Leading edge detail:
![cp_tke_detail_Le](https://user-images.githubusercontent.com/36844965/66407922-53448b00-e9ee-11e9-877d-88ace3a222fb.png)

Detail at 30% of the chord length:
![cp_tke_detail_1](https://user-images.githubusercontent.com/36844965/66407921-53448b00-e9ee-11e9-8a22-87106066984b.png)

Wake region detail:
![cp_tke_detail_wake](https://user-images.githubusercontent.com/36844965/66407920-53448b00-e9ee-11e9-92ad-b770e0ac5743.png)

Has anyone found previously this behaviour? Could it depend on the set up  that I have used? 

I attach the grid and configurations files.
[grid_and_conf_files.zip](https://github.com/su2code/SU2/files/3703135/grid_and_conf_files.zip)

Thanks in advance.

**Comment by economon** [comment]
Thanks for reporting this, @emoralest6. My first suggestion is that we go through the mean flow solver and double-check our inclusion of the -2/3*rho*k term from the stress tensor (and TKE correction for energy) to make sure we do not have a bug there (see https://turbmodels.larc.nasa.gov/sst.html). This is one of the primary differences between the SA and SST implementations and would affect pressure. Could be a good place to start.

**Comment by emoralest6** [comment]
Thanks for the quick answer @economon. I will wait for further updates. In the meanwhile, can you tell me which are the files in the source code where the SST and the mean flow are implemented in order to start looking at it?

**Comment by koodlyakshay** [comment]
Hello,

I ran an incompressible case with NACA 0012 (AoA=0, TMR case) and I see a similar difference between SA and SST on the grid level 3 (https://turbmodels.larc.nasa.gov/naca0012_grids.html, 257 points on the airfoil surface). I also tried the SST_SUST model and have attached the plots for mid section and wake here (white lines - SA, red - SST, green - SST_SUST). The SUST model gives the same difference at mid chord and LE but not in the wake. The SST_SUST under predicts the drag value though (also I had some convergence issues with SUST).
![pressure_line_cmp_mid](https://user-images.githubusercontent.com/28007882/66496216-dd5a2580-eaba-11e9-869e-097cce8e52b4.png)
![pressure_line_cmp_wake](https://user-images.githubusercontent.com/28007882/66496217-dd5a2580-eaba-11e9-9c72-1980625dd550.png)



@economon , the SetStressTensor routine includes the -2/3 * rho * TKE term, so I suppose the TKE is accounted for in the viscous residual of the mean flow equations. 

@emoralest6 if you wanted to check the source code, the mean flow solver is in SU2_CFD/src/solver_direct_mean.cpp and the corresponding numerics in the SU2_CFD/src/numerics_direct_mean.cpp file

Cheers.

**Comment by vdweide** [comment]
Akshay, regarding the convergence problems with SST_SUST, what free-stream values did you use? This model is more sensitive to free-stream values than SST, because for latter the turbulent variables dissipate. For SST_SUST I typically use

% Ratio of the turbulent and laminar viscosity in the free-stream (10.0)
FREESTREAM_TURB2LAMVISCRATIO= 0.882
%
% Free stream turbulence intensitity, sqrt(2 k_inf/3)/U_inf (0.0005)
FREESTREAM_TURBULENCEINTENSITY= 0.0007

Especially FREESTREAM_TURB2LAMVISCRATIO is much lower than the default version.

**Comment by koodlyakshay** [comment]
Hi Edwin,

Looks like I used the default values for the SST_SUST as well. I will re-run it with your values and check what happens soon.

**Comment by economon** [comment]
I have gone through the SST model in detail and made a few changes. I removed the term involving the TKE from the viscous stress tensor in the mean flow equations, as this is often ignored in codes (and omitting it gives better results, including the pressure field). I also fixed a bug in the definition of the eddy viscosity, where strain magnitude was being used when it should be the vorticity magnitude.

Below, you will find the results for the 2D bump-in-channel case with the SST model from the NASA TMR page (https://turbmodels.larc.nasa.gov/bump_sst.html). The comparisons with CFL3D and FUN3D are excellent for all quantities. These results will go onto a new V&V page we are prepping.

Thanks again for posting, @emoralest6, let's close this for now. The changes are implemented in the feature_nlctrl branch which is an open PR #790 and will be merged soon. If you'd like to try it out right away, please use that branch and follow the new options described in #790. 

![bump_cd_gridconv](https://user-images.githubusercontent.com/4896083/67539227-58fcca80-f696-11e9-81a3-92940a0520aa.png)
![bump_cf_0p63_gridconv](https://user-images.githubusercontent.com/4896083/67539228-59956100-f696-11e9-8c88-65fe5e479d42.png)
![bump_cf_0p75_gridconv](https://user-images.githubusercontent.com/4896083/67539230-5a2df780-f696-11e9-9e40-b78272892dac.png)
![bump_cf_0p87_gridconv](https://user-images.githubusercontent.com/4896083/67539231-5a2df780-f696-11e9-942b-ca534659a49a.png)
![bump_cf_profile](https://user-images.githubusercontent.com/4896083/67539232-5a2df780-f696-11e9-9479-cc3c368fa0cf.png)
![bump_cl_gridconv](https://user-images.githubusercontent.com/4896083/67539235-5b5f2480-f696-11e9-9c6e-0d00237096bc.png)
![bump_cp_profile](https://user-images.githubusercontent.com/4896083/67539236-5b5f2480-f696-11e9-98f2-b0d8ce9bc3a1.png)
![bump_eddy_profile](https://user-images.githubusercontent.com/4896083/67539237-5bf7bb00-f696-11e9-94b8-9e213165aac3.png)
![bump_k_profile](https://user-images.githubusercontent.com/4896083/67539238-5bf7bb00-f696-11e9-8dc9-5540f0a4e45e.png)
![bump_omega_profile](https://user-images.githubusercontent.com/4896083/67539239-5c905180-f696-11e9-8b8a-c467b30a3d72.png)
![bump_vel_profile](https://user-images.githubusercontent.com/4896083/67539241-5d28e800-f696-11e9-9ca9-5b866d078c56.png)
![residual_convergence](https://user-images.githubusercontent.com/4896083/67539242-5d28e800-f696-11e9-90aa-6094ed0e6ba6.png)

**Comment by clarkpede** [comment]
The verification you show is for a low-Mach test case.  The omitted term in the stress tensor (the isotropic contribution from the turbulent stress) is mostly applicable for flows with strong velocity dilatation.  Have you tried the new SST model for a flow with a shock wave? For example, how do the results change for the RAE2822 case?

**Comment by economon** [comment]
Attaching some results for the RAE2822 of the pressure field zoomed in right near the shock on the upper surface. The results do change (lift and drag by a couple percent) mostly due to a change in shock position it seems. The pressure field also shows the same behavior referenced above when the term is included. Unfortunately, we do not have much data to compare with here, since this case is not on the TMR. The integrated quantities above for the bump problem do not appear to be too sensitive to it either way, but the pressure field does indeed show the same discrepancies.

In general, I have not been able to find any strong arguments for or against including the term in literature/codes. Although it is prescribed by the theory, some folks mention it is sometimes dropped (TMR also says it is sometimes ignored unless supersonic), or it gets dropped without mention at all. It is certainly affecting the pressure distribution, so we should take that into consideration. It is possible that there is some other bug that gets exposed by its inclusion, but I did not come across anything yet. As we know the SA model does not exhibit this behavior, I lean toward removing it. I'm all ears if you have any other insight.

<img width="1313" alt="Screen Shot 2019-10-25 at 2 47 16 PM" src="https://user-images.githubusercontent.com/4896083/67607461-615a1180-f739-11e9-9d68-9c5d15fb0acc.png">
<img width="1312" alt="Screen Shot 2019-10-25 at 2 47 06 PM" src="https://user-images.githubusercontent.com/4896083/67607471-68811f80-f739-11e9-82bd-ac1c23b4caad.png">

**Comment by clarkpede** [comment]
It definitely seems to me like the SST model is inadequate somewhere.  The results you show do indicate that the model seems to handle the near-wall region much better without the divergence term.  Since the divergence term is theoretically justified, that indicates to me that either the SST model itself has poor near-wall behavior or the SU2 implementation of the model is poor.  Removing the divergence term seems to cover up those flaws.

I don't have any suggestions, but I do think it's important to keep these difficulties in mind.

**Comment by economon** [comment]
Thanks, @clarkpede, I agree that the outcome is not very satisfying. I have some confidence in the SST implementation in SU2 given how closely we match with CFL3D and FUN3D, especially the profiles for k and omega near the wall.

I think the best thing we could do is pursue a manufactured solution to verify the model. For example, there is some good information here about RANS manufactured solutions, and we could look into it for the SA and BSL k-omega models once we have some time: https://turbmodels.larc.nasa.gov/eca1.html

**Comment by clarkpede** [comment]
This may be relevant, and it may not be.  Is there a reason that the molecular and turbulent diffusion of turbulent kinetic energy is not included in the total energy terms? I'm talking about terms like:

 ![molecular and turbulent diffusion of tke](https://latex.codecogs.com/gif.latex?\left(&space;\mu&space;&plus;&space;\frac{\mu_t}{\sigma_k}\right)\frac{\partial&space;k}{\partial&space;x_j})

This term is listed both in Wilcox's "Turbulence Modeling for CFD" book and the [NASA TMR website](https://turbmodels.larc.nasa.gov/implementrans.html).  NASA's page basically just copies what Wilcox states, and then says "This expression in the energy equation is also sometimes neglected."

Rumsey clarified his position in a [2009 report](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20090015399.pdf), saying that "when considering high Mach number compressible boundary layer flows using k-omega models, the conservation of total energy should be configured to include the contribution of the turbulent kinetic energy k... It is sometimes common practice to ignore these effects, which is certainly justified when k is signficantly smaller than the square of the mean velocity."  But he also states: "Note that in CFL3D, the turbulence models are decoupled from the mean flow equations, k is *not* included in the definition of the total energy, and the diffusion of k does not appear in the mean flow energy equation for its models tested here." He also omitted the 2/3 \rho k term in both the production and the turbulent stress tensor, and found that it made little difference even for M=10 wall-bounded flows.

SU2's version of SST is in a weird spot right now, where it's using the turbulent kinetic energy in some places but not others.  It's using it here:

+ Total energy definition
+ Production of turbulent kinetic energy
+ RANS evolution equations
+ Eddy viscosity definition

But not here:

+ Molecular and turbulent diffusion of turbulent kinetic energy in the total energy conservation equation
+ Deviatoric part of the turbulent stress tensor

Is there any rationale behind this split, aside from simply stating that "this seems to work?"

**Comment by economon** [comment]
Thanks for digging around on this @clarkpede. I don't expect the original author will be able to chime in, but I would say we can investigate the differences w.r.t. how the tke is included. 

I have tested removing it from the total energy definition for some low speed cases while I was debugging, and it had almost no impact. As stated above, we know that including in the mean flow stress tensor does noticeably impact the solution. I have not tried including it in the energy equation. I will reopen this issue, and we can continue the discussion here.

**Comment by clarkpede** [comment]
I can test out some aspects as well. This directly impacts my research, so it's a medium-level priority for me.

**Comment by clarkpede** [comment]
So I tried adding the molecular and turbulent diffusion of turbulent kinetic energy in the total energy equation.  It did not appear to fix this issue. At this point though, it's unclear exactly what the problem really is.  I don't know have "correct" pressure, turbulent kinetic energy, or total energy fields for the NACA 0012 or RAE 2822 test cases. By "correct," I mean DNS or experimental data. The lack of "correct" data it hard to tell where the problems may actually be occurring.  Is it coming from total energy? Resolved kinetic energy? Turbulent kinetic energy?  All we're doing right now is comparing SST to SA, and one code's SST to another code's SST.  That makes it hard to figure out what the correct answer really should be.

Unless we have a problem that both 1) exhibits this problem, and 2) has high-quality pressure, temperature, total energy, or turbulent kinetic energy fields, then I agree that manufactured solutions is might be the best way to check "correctness."

**Comment by economon** [comment]
WIP related to #905

**Comment by clarkpede** [comment]
Just an update: There is now WRLES data for the axisymmetric transonic bump case on the NASA Turbulence Modeling Resource.  The data includes pressure, turbulent kinetic energy, and density.  While the WRLES is not "ground truth," it is a reliable data source for comparison. Sometime over the next few weeks, I'll compare the WRLES data with the SU2 results, including some of the possible changes.  This will give us a better idea of how these model changes impact the predictive accuracy.
