### ISSUE TITLE
Energy balance

### ISSUE THREAD

**Issue by chiefenne** [su2code/SU2#800]
I do not know if it exists already and /or if it is planned at all. In the case it does not exist it would be good to have output information on global energy balances at hand. This specifically applies to CHT multizone computations, but not only.

**Describe the solution you'd like**
The energy balance should take care about delta enthalpy between inlet(s) and outlet(s). That can be compared to the heat transferred across the wall(s). So in a steady simulation with one inlet, one outlet and a wall the balance global balance should be zero. When working e.g. on a heat exchanger designs could also be compared with respect to their performance (e.g. NTU numbers or similar). This could be specifically interesting for multizone examples. Further that should work for steady, unsteady, open/closed domains and also consider technical work (as in the case of turbomachinery). 
Essentially it is an output request that should reflect the first law of thermodynamics (including open, transient systems and technical work).
It would help in engineering assessment, convergence control and be a check when new features are implemented.

**Example**

Integrated Inlet Power [W] =  3.0050E+05
Integrated Outlet Power [W] =  2.5441E+05
Integrated Wall Heat Loss [W] =  5.4138E+03
Global Energy Balance [W] =  4.0676E+04 (could be internal energy or error)
Mean Temperature Based HTC [W/m2K] =  8.5339E+02
Near-Wall Temperature Based HTC [W/m2K] =  7.7598E+02
Number of Transfer Units-NTU [-] =  1.8859E+01
Thermal Residence Time [s] =  8.0691E-03
Thermal Relaxation Time [s] =  4.2786E-04

**and/or**

	LHS = dQtot + dHtot + Ptot;
	RHS = dU/dt + dE/dt;
	err_energy = LHS - RHS;
	xcol("", "dHtot", "W", dHtot);
	xcol("", "dQtot", "W", dQtot);
	xcol("", "dWtot", "W", Ptot);
	xcol("", "LHS", "W", LHS);
	xcol("", "RHS", "W", RHS);
	xcol("", "E-imbalance", "W", err_energy);
	xcol("", "E-imbalance-relative", "%", 100.0 * err_energy / energy_ref);
	xwrite("energy_balance.txt");

**Comment by oleburghardt** [comment]
Hi @chiefenne Thanks for bringing it up. I think it could additionally serve as a _quality measure_ for the solvers. 
(For instance, one concern sometimes was - don't know whether it still is - mass conservation in the incompressible solver. That would also be reflected in an energy balance if there really was a problem, or one could check in a very easy way if all boundaries that act as a heat sink/source do what they should. Altogether, one would have some global numbers to confirm that the result is reliable..)
I think @economon could also be interested in such a feature.

I'll have to do some maintenance for heat-related stuff soon, especially to push some fixes for instationary computations. I can then at least check how such a feature could be set up.

**Comment by chiefenne** [comment]
Thank you.

**Comment by economon** [comment]
@chiefenne @oleburghardt : I like this idea a lot. This type of reporting is tremendously useful for assessing a simulation.

You might want to take a look at the MARKER_ANALYZE capability, which will at least give you basic quantities averaged at any markers you specify (area- or mass-averaged). It likely needs some extension to better handle heat transfer/energy. However, it may be a good place to start when thinking about a more general framework.
