### ISSUE TITLE
airfoil_fsi_rbf failing travis

### ISSUE THREAD

**Issue by WallyMaier** [su2code/SU2#801]
Hi All,

It seems that one of the new pull requests has somehow caused airfoil_fsi_rbf on travis. 

The error is:
ERROR: The code was not able to get to the "Begin solver" section.
ERROR: The iteration number 0 could not be found.

I am not sure if this was done intentionally as the fix is coming in one proposed PRs. If this is the case, i will close this issue.  However, I think this would be urgent as most of PRs are currently failing to pass because of this.

**Comment by pcarruscag** [comment]
That is my fault.
The case was broken, I fixed it in #753 and updated the testcase repo thinking #753 would be merged shortly but merging with #774 is proving more difficult than I thought... If I can't find a solution soon I'll fix it.
