### ISSUE TITLE
Momentum force calculation

### ISSUE THREAD

**Issue by metuaee** [su2code/SU2#802]
Hello community,

In the solver_direct_mean.cpp file there is a small but important bug about the calculation of momentum forces.

I aware the situation while solving RANS nozzle flow and calculating corresponding thrust value from exit via momentum forces input only. The resulting values are completely unmatched with the experiments. It seems the problem about uninitialized values in Momentum_Forces method. When the following code segment (coppied from pressure forces method) applied problem is solved.

  /*-- Variables initialization ---*/
  
  AllBound_CD_Mnt = 0.0;        AllBound_CL_Mnt = 0.0; AllBound_CSF_Mnt = 0.0;
  AllBound_CMx_Mnt = 0.0;          AllBound_CMy_Mnt = 0.0;   AllBound_CMz_Mnt = 0.0;
  AllBound_CoPx_Mnt = 0.0;          AllBound_CoPy_Mnt = 0.0;   AllBound_CoPz_Mnt = 0.0;
  AllBound_CFx_Mnt = 0.0;          AllBound_CFy_Mnt = 0.0;   AllBound_CFz_Mnt = 0.0;
  AllBound_CT_Mnt = 0.0;           AllBound_CQ_Mnt = 0.0;    AllBound_CMerit_Mnt = 0.0;
  AllBound_CEff_Mnt = 0.0;

 - Linux (Ubuntu 16.4)
 - g++ (GCC) 5.4
 - Serial, AD support
 - SU2 Version v6.2.0

**Comment by pcarruscag** [comment]
Thank you for reporting this. It appears to be fixed in the develop branch.
