### ISSUE TITLE
Discrete adjoint results do not match finite differencing

### ISSUE THREAD

**Issue by Jethro-Moses** [su2code/SU2#804]
Hi,

I'm trying to compare the gradient from Discrete Adjoints to Finite differences using SU2v6.2 for a RAE2822 airfoil (2D) with a sharp trailing edge. I'm using the Spalart Allmaras turbulence model. The flow is transonic. I've used FFD to parameterize the airfoil. However, I cannot get my discrete adjoint values to match my finite difference values. The directions of the gradients match, however, the magnitudes differ significantly. 

I've posted my full question here

https://www.cfd-online.com/Forums/su2/198057-gradients-calculated-through-discrete-adjoint-near-zero.html

**Comment by pcarruscag** [comment]
Hi @Jethro-Moses,
I'm closing this here and replying via CFD online as most of our issues here are development related.
