### ISSUE TITLE
How to output heatflux?

### ISSUE THREAD

**Issue by cjz667** [su2code/SU2#805]
Hello. There are some problems when I want to output heatflux as result. There are some corresponding codes in function 'void COutput::MergeSolution' from file 'output_structure.cpp'. But why they don't seem to work? I'm clueless about it. Here are my configure file, mesh file and results. Thank you.

[configure and mesh.zip](https://github.com/su2code/SU2/files/3762201/configure.and.mesh.zip)
[result.zip](https://github.com/su2code/SU2/files/3762206/result.zip)

**Comment by pcarruscag** [comment]
If you are referring to surface heat flux it is one of the default surface outputs.
Maybe there is a bug in v6.2 but in current develop it seems to work fine, you can try using this config: [v7.cfg.zip](https://github.com/su2code/SU2/files/3762621/v7.cfg.zip)
Some options changed name since v6.2, you can read about it here: https://su2code.github.io/docs/Guide-to-v7/
I replaced the relevant time domain options but commented out all the output options.

On another note I think you should revise your settings, you had a time step of 0 on an unsteady simulation for example. If you have setup questions have a look at the user forum https://www.cfd-online.com/Forums/su2/ and start a topic if there is no related one already.

If you have issues with heatflux output with the develop version / v7 we can re-open this issue.

**Comment by cjz667** [comment]
> 如果您指的是表面热通量，则它是默认的表面输出之一。
> v6.2中可能存在一个错误，但是在当前的开发中它似乎可以正常工作，您可以尝试使用以下配置：[v7.cfg.zip](https://github.com/su2code/SU2/files/3762621/v7.cfg.zip)
> v6.2之后更改了一些选项的名称，您可以在此处阅读：[https：// /su2code.github.io/docs/Guide-to-v7/](https://su2code.github.io/docs/Guide-to-v7/)
> 我替换了相关的时域选项，但注释了所有输出选项。
> 
> 另一方面，我认为您应该修改设置，例如对于不稳定的模拟，您将时间步长设置为0。如果您有设置方面的问题，请访问用户论坛[https://www.cfd-online.com/Forums/su2/，](https://www.cfd-online.com/Forums/su2/)并在没有相关主题的情况下启动主题。
> 
> 如果开发版本/ v7的heatflux输出存在问题，我们可以重新打开此问题。

Thank you. It helps a lot.

**Comment by cjz667** [comment]
> If you are referring to surface heat flux it is one of the default surface outputs.
> Maybe there is a bug in v6.2 but in current develop it seems to work fine, you can try using this config: [v7.cfg.zip](https://github.com/su2code/SU2/files/3762621/v7.cfg.zip)
> Some options changed name since v6.2, you can read about it here: https://su2code.github.io/docs/Guide-to-v7/
> I replaced the relevant time domain options but commented out all the output options.
> 
> On another note I think you should revise your settings, you had a time step of 0 on an unsteady simulation for example. If you have setup questions have a look at the user forum https://www.cfd-online.com/Forums/su2/ and start a topic if there is no related one already.
> 
> If you have issues with heatflux output with the develop version / v7 we can re-open this issue.

I tried but heatflux equals to 0.000. What is wrong?

> If you are referring to surface heat flux it is one of the default surface outputs.
> Maybe there is a bug in v6.2 but in current develop it seems to work fine, you can try using this config: [v7.cfg.zip](https://github.com/su2code/SU2/files/3762621/v7.cfg.zip)
> Some options changed name since v6.2, you can read about it here: https://su2code.github.io/docs/Guide-to-v7/
> I replaced the relevant time domain options but commented out all the output options.
> 
> On another note I think you should revise your settings, you had a time step of 0 on an unsteady simulation for example. If you have setup questions have a look at the user forum https://www.cfd-online.com/Forums/su2/ and start a topic if there is no related one already.
> 
> If you have issues with heatflux output with the develop version / v7 we can re-open this issue.

I tried but heatflux equals to 0.000. What is wrong?

**Comment by pcarruscag** [comment]
Please describe what you tried.

**Comment by cjz667** [comment]
> If you are referring to surface heat flux it is one of the default surface outputs.
> Maybe there is a bug in v6.2 but in current develop it seems to work fine, you can try using this config: [v7.cfg.zip](https://github.com/su2code/SU2/files/3762621/v7.cfg.zip)
> Some options changed name since v6.2, you can read about it here: https://su2code.github.io/docs/Guide-to-v7/
> I replaced the relevant time domain options but commented out all the output options.
> 
> On another note I think you should revise your settings, you had a time step of 0 on an unsteady simulation for example. If you have setup questions have a look at the user forum https://www.cfd-online.com/Forums/su2/ and start a topic if there is no related one already.
> 
> If you have issues with heatflux output with the develop version / v7 we can re-open this issue.

I wonder that if I use TIME_STEPPING without dual time, is timestep a must?

**Comment by cjz667** [comment]
> Use the develop branch of the code and the config file I uploaded before. Heatflux is being outputted.
> Please understand that we do not have resources to fix bugs in previous versions of the code.

Hello. 

I read the code. In the file 'solver_direct_mean.cpp', there is a function, 'CNSSolver::Friction_Forces', in which a line of code is wrong. The last parameter of the code, 'HeatFlux[iMarker][iVertex] = -thermal_conductivity*GradTemperature*RefHeatFlux;' is for normalization, but we only declare it before. In another word, 'RefHeatFlux' is forgotten. If I delete 'RefHeatFlux' in this line of code, it works. Certainly, at this moment, heatflux I get is not normalized any more.

My version is 6.2.0.

**Comment by economon** [comment]
Hi @cjz667 : you are correct, the re-dimensionalization of the heat flux was missing in previous versions of the code (prior to v6.2.0, the non-dimensional heat flux was output). We have fixed this for the upcoming v7 release, as @pcarruscag mentioned, which contains the missing reference value. You can already try this version of the code for yourself by checking out the develop branch with the following command:

$ git clone -b develop https://github.com/su2code/SU2.git

Please give that a try, and if it still is not working, we can reopen the issue.
