### ISSUE TITLE
Rename CNumerics to CSpatialScheme

### ISSUE THREAD

**Issue by aniketaranake** [su2code/SU2#81]
The word "numerics" applies to most of what SU2 does including time integration. For this reason, a class called CNumerics that only relates to spatial discretization is confusing. 

Considering the routines which inherit from this parent class (CUpwRoe_Flow, CAvgGradCorrected_Flow, etc.), I suggest as a new name CSpatialSchemes

**Comment by WallyMaier** [comment]
@economon is this still something we should pursue?  If so, I can work on it.

**Comment by economon** [comment]
This is related to #691. Perhaps we can bring any renaming there for discussion, including the potential division of files.
