### ISSUE TITLE
Python wrapper fails to generate with MPI and AD

### ISSUE THREAD

**Issue by dkavolis** [su2code/SU2#819]
**Describe the bug**
SWIG fails with
```Nothing known about namespace 'medi'``` from
https://github.com/su2code/SU2/blob/9446c8bc207574bde8fe0bfac285070d467bab4f/Common/include/mpi_structure.hpp#L57
See https://github.com/swig/swig/issues/1068. Using `-includeall` is not an option since the wrapper takes far too long to generate, I cancelled it after waiting for 15 minutes.

**To Reproduce**
Build SU2 with python wrapper, MPI and autodiff.

**Desktop (please complete the following information):**
 - OS: any
 - C++ compiler and version: any
 - MPI implementation and version: any
 - SU2 Version: any with python AD wrapper enabled

**Comment by talbring** [comment]
Hm with Linux/Mac it definitely works with g++ and OpenMPI. So **any** for OS, Compiler, MPI is definitely not correct.

**Comment by dkavolis** [comment]
I've tried compiling it with MinGW and had CODI_REVERSE_TYPE flag defined for generation (not meson). Removing it for generation works.
