### ISSUE TITLE
A question between primitive value and conserved value

### ISSUE THREAD

**Issue by cjz667** [su2code/SU2#820]
Hello.

I use SU2_6.2.0. I wonder why we use the gradient of the primitive variables, but not conserved one? When simulating compressible fluid, is conserved value better?

Thank you.

Cao J. Z.

**Comment by talbring** [comment]
@cjz667 Thanks for your interest in SU2, but please use the [forum](https://www.cfd-online.com/Forums/su2/) to ask general questions. Issues should only be opened if you want to report a bug, request a feature, suggest an improvement (with information on why you think it is better this way)  and so on.
