### ISSUE TITLE
What does the label 'no_changelog' mean?

### ISSUE THREAD

**Issue by TobiKattmann** [su2code/SU2#822]
Hi all,

Recently the `no_changelog` label was added to nearly all PR's (and now to this issue) and I am wondering has to be done to achieve 'there_is_a_changelog'. 

I found this [template / proposal](https://keepachangelog.com/en/1.0.0/) on how to set up and maintain a changelog ... but we have no such file or similar in our repo (to my knowledge).

Please enlighten me :) Cheers Tobi

**Comment by talbring** [comment]
See #813. Maybe the explanation is not detailed enough though.

**Comment by TobiKattmann** [comment]
> The change log entries are categorized depending on the labels feature, fix, chore for new features, bug fixes and maintenance. If you don't want your PR listed, add the label no_changelog.
So remember to always add a label to your PR (maybe we will automate that soon)!

That describes it pretty well in my opinion. 

I'll close this issue in a day or so... maybe someone had the same question and didn't read the PR description yet as well.
