### ISSUE TITLE
Hardcoded paths in build scripts

### ISSUE THREAD

**Issue by dkavolis** [su2code/SU2#823]
**Describe the bug**
* https://github.com/su2code/SU2/blob/15f0258a7607245be601b72fa2c158f79f01c922/SU2_PY/pySU2/meson.build#L5-L15
You should not assume that mpi4py is installed in python system directory, instead use `import mpi4py; print(mpi4py.get_include())` to get the required path directly.

* https://github.com/su2code/SU2/blob/15f0258a7607245be601b72fa2c158f79f01c922/meson.build#L114-L118
You should not assume that MKL is installed in a single master directory even though it might be true in most cases. For example, installing MKL from Ubuntu PPA will not work with SU2 since headers are installed in `/usr/bin/include/mkl` and libraries - `/usr/lib/x86_64-linux-gnu` though it does provide `pkgconfig` files.

**Desktop (please complete the following information):**
 - OS: any
 - C++ compiler and version: any
 - MPI implementation and version: any
 - SU2 Version: develop

**Comment by pcarruscag** [comment]
Hi @dkavolis,
It seems like you know your stuff about build systems and associated best practices, it would be great if you could open a PR with the fixes for this, I'd be happy to test the MKL stuff on the systems I have access to.
Cheers,
Pedro
