### ISSUE TITLE
SU2 v7 NOT writing a restart file for Turbomachinery cases

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#831]
**Describe the bug**
I expect a restart file to be generated by running SU2. If I include Turbomachinery markers it is not generating a restart file. I am using the transonic_stator 2D case in the Testcases directory.

**To Reproduce**
The config and mesh files can be found at: 
https://mailuc-my.sharepoint.com/:f:/g/personal/baigan_mail_uc_edu/EumoIwGRZqRChSZ8NvdQpyoBPgBXZpnS_xVrPDuzZYHkxA?e=SXJov7

One config file has Turbo markers and the other has Turbo markers commented. You just have to run the two config files and see the difference.

**Desktop (please complete the following information):**
 - OS: [ OpenSuse 15.1]
 - C++ compiler and version: [g++ > 7]
 - MPI implementation and version: [N/A]
 - SU2 Version: [v7.0]

**Comment by auzbaig** [comment]
@salvovitale any update?

**Comment by pcarruscag** [comment]
@auzbaig I put a fix for this in #824, please test it with your cases, if you use harmonic balance test that too as the fix should affect it as well.

**Comment by pcarruscag** [comment]
I think this is fixed, for Hb cases all time instances are outputted. Please reopen the issue if #824 does not fix the issue.

**Comment by auzbaig** [comment]
@pcarruscag yes this fix works for the case.
