### ISSUE TITLE
Multizone CHT with compressible flows

### ISSUE THREAD

**Issue by jrdntrt** [su2code/SU2#838]
**Describe the bug**
Multizone CHT coupling does not appear to work properly for compressible flows. Specifically there does not seem to be heat transfer between linked markers

**To Reproduce**
See the config files / explanation in this post: https://www.cfd-online.com/Forums/su2/222835-su2-compressible-cht.html

**Desktop (please complete the following information):**
 - OS: Linux
 - C++ compiler and version: GCC 5.4.0
 - MPI implementation and version: Open MPI 1.10.2
 - SU2 Version: 7.0.0

**Comment by oleburghardt** [comment]
Hi,

thanks for bringing it up here. It seems to be some top-level (merge?) error that occured when putting together v7. 
The interface data exchange apparently is just not called. I'll push a fix for this, open up a draft PR and then we can check if everything is alright again for compressible flows as well.

Ole

**Comment by oleburghardt** [comment]
Please check with branch `fix_compressible_CHT`.

(You can either select it in the drop down menu before downloading or in case you have a repository clone on your machine, you can check it out via
`git fetch`
`git checkout fix_compressible_CHT`)

**Comment by jrdntrt** [comment]
Hi Ole,

Thanks for pushing the fix. It seems that the CHT still may not be working as intended. I changed to the fix_compressible_CHT branch and recompiled SU2 and then ran the same config files as before. These are the resulting volume vtk outputs attached:
[vtk_out.zip](https://github.com/su2code/SU2/files/3956891/vtk_out.zip)
It seems to me that the heat fluxes are getting sent from the fluid zone to the solid zone correctly, reducing the temperature of the solid, but the updated plate surface temperature may not be getting set back into the fluid zone. Please let me know if you think the results indicate something else.

Jordan

**Comment by oleburghardt** [comment]
From looking at your vtk files I've exactly the same impression. Must be something "easy" (nothing physical or numerics ..) so hopefully I can push the fix soon.

Thanks for your help!

**Comment by oleburghardt** [comment]
Please re-check with latest commit (very small correction for a copy-and-paste-error from yesterday, not sure whether it has had some impact).

I've run your test case again and I had a closer look at the interface which in fact looks alright (it's maybe just that thermal conductivities are so different that zones appear to be separated..?)

![temp_profile](https://user-images.githubusercontent.com/22639394/70803014-5889d180-1db3-11ea-8e6b-ef7f95a9466a.png)

By the way: You can easily increase the CFL number to 1000 in both zones. You get a fully converged solution after a few hundred iterations.

**Comment by jrdntrt** [comment]
Hi Ole, the temperatures appear to be matching now, I think this fix solved the issue. Thanks for the help!
