### ISSUE TITLE
Error message for missing required inputs in .cfg file

### ISSUE THREAD

**Issue by themrdjj** [su2code/SU2#842]
I just managed to run my first SU2 CFD simulation, however it took me a few days to get it to work. "SU2_CFD.exe" was always crashing right after "Begin solver". It took me quite a while to figure out that I was missing some required inputs in the ".cfg" file (for example CONV_NUM_METHOD_FLOW), especially because this isn't mentioned clearly on the website.

I would suggest the following solutions:

- An error message telling which required input is missing in the .cfg to help beginners with debugging.
- A simple list with all the required inputs, i.e. those which don't have a default value, for instance on the website.
- An example of a minimal working .cfg file, basically the opposite of [this one](https://github.com/su2code/SU2/blob/master/config_template.cfg).

(This is my first time opening a feature request on Github, I hope I did everything right)

**Comment by pcarruscag** [comment]
Hi @themrdjj,
Thank you for the feedback, there was already a similar report in #796 (which incidentally went stale and was closed), I will try to do something about it, or if you would like to contribute code to the project I can point you to right place to add an error message.

Meanwhile my best advice is to not start a config from scratch until you know SU2 very well (and even then...) look for a test case that uses similar features and go from there.
The minimal config is the one in Quickstart, the template if more of a catalog :) I don't think we'll ever have a unified minimal config, SU2 does many things, some mutually exclusive.
Convective options are reasonably well documented here: https://su2code.github.io/docs_v7/Convective-Schemes/
The output messages before "Begin Solver" can be helpful (although in this particular case you would need to know what to expect).

Cheers,
Pedro

**Comment by themrdjj** [comment]
Thanks for your reply! Could you please point me to the right place in the code? I will have a look and see if I can do something about it.

**Comment by pcarruscag** [comment]
In CDriver::Numerics_Preprocessing(...), around line 2030, begins a (large) switch `switch (config->GetKind_ConvNumScheme_Flow()) {` which is where the numerics classes get instantiated, there is a check there for `NO_CONVECTIVE` which should trigger an error (´SU2_MPI::Error(...)´).
But it appears that the error is not triggered, I would start by checking what value CConfig::GetKind_ConvNumScheme_Flow returns when the option is not present in the config, possibly the default value (set somewhere in CConfig) is not `NO_CONVECTIVE`.
If you look for `CONV_NUM_METHOD_FLOW` in config_structure.cpp you will find the line that tries to read that option.

**Comment by themrdjj** [comment]
Well I've taken a look at this but it's probably beyong my current programming skills. I only have experience with Python. Perhaps someone else could look at this? I still think it's a very helpful error message for new users and it sounds like it wouldn't be too much work to fix it.

**Comment by koodlyakshay** [comment]
It looks like the default option for KindConvNumScheme is set to SPACE_CENTERED instead of NO_CONVECTIVE. If I understand it correctly, I think this is set in the SetDefault() of COptionConvect class in option_structure.hpp (line 2658).

**Comment by pcarruscag** [comment]
> Well I've taken a look at this but it's probably beyong my current programming skills. I only have experience with Python. Perhaps someone else could look at this? I still think it's a very helpful error message for new users and it sounds like it wouldn't be too much work to fix it.

Thank you for having a look at the code, I am sure your skills are fine, this area of the code is just horribly complex. It is fixed in #824, it should have been a separate PR but I had changes to the NumericsPreprocessing in that PR already.
