### ISSUE TITLE
SU2 7.0 iteration number for restart run

### ISSUE THREAD

**Issue by kohyun** [su2code/SU2#844]
When I restart the calculation, I cannot figures out the total iteration number.
In 6.2 I definitely knew the iteration number when I try restart from the saved data.

I want to know about the iteration number summing with previous run like 6.2 version. 

Thanks in advance.

**Comment by TobiKattmann** [comment]
Hi @kohyun ,

please see here https://www.cfd-online.com/Forums/su2/222715-su2-7-0-restart-run.html for an explanation.

Cheers, Tobi

**Comment by TobiKattmann** [comment]
And for your notice, I will tackle this metadata stuff as I need it in a different context. During that I might bring back the iteration number "pick-up" as I also found it quite convenient. If I am quick enough that could come back with the new master.
Therefore I close this issue.
