### ISSUE TITLE
Issue with "Physical Case Definition" screen output

### ISSUE THREAD

**Issue by scolonia** [su2code/SU2#846]
Hi,

first of all thanks for your continuing effort in developing a very powerful CFD software.

I noticed a mistake in the implementation of a part of the screen output in "confing_structure.cpp" in SU2-7.0.0.

In the "Physical Case Definition" there are no cases for"Kind_Solver" as "INC_EULER", "INC_NAVIER_STOKES" or "INC_RANS" and therefore there is no screen output stating which equations are going to be used in the computation.

This leaves uncertainty on whether or not the set of equations chosen in the config file is actually implemented. For example in my case I would like to use SA_DDES with INC_RANS but I don't know if this combination is not implemented or just not visible in the screen output due to the mistake I mentioned before (looking at the source code it seems like it is implemented but I may missing something and fixing the screen output would help non expert users).

Thanks for your time.
With Best Regards.

**Comment by pcarruscag** [comment]
You are right, this used to be covered by the `Kind_Regime` logic but it is broken now...
(One more example where #770 would help)
