### ISSUE TITLE
Request: Using restart flow as an initial guess for the flow field

### ISSUE THREAD

**Issue by DGIorio** [su2code/SU2#852]
It would be really useful to be able to use a restart flow as an initial guess for a similar simulation. Usually in shape design there is a small variation in the geometry, so being able to use a previous solution as an initial guess would accelerate the simulation process.

Since the new mesh points does not necessarily will match the previous mesh points, it will be necessary to do some interpolation in the near points, or, for a first try, just an average would be good.

At the momment, I am considering writing a Python script based on Eduardo Molina's one ([issue #787](https://github.com/su2code/SU2/issues/787#issuecomment-528461173)) that read the restart_flow.dat, and for each point of the new mesh: do the average of the points data near it and then write on a new restart_flow.dat.

Thanks in advance!

**Comment by pcarruscag** [comment]
Are you talking about shape optimization with re-meshing?
If yes, people are already working on restart with interpolation (@jayantmukho @bmunguia )
Otherwise, SU2 already restarts when doing shape optimization.

**Comment by DGIorio** [comment]
> Are you talking about shape optimization with re-meshing?
> If yes, people are already working on restart with interpolation (jayantmukho bmunguia )
> Otherwise, SU2 already restarts when doing shape optimization.

Yes, but also for other cases where some small modification on the geometry were made, it wouldn't be necessary to simulate from scratch, since the flow should have almost the same behavior.

I modificated the @EduardoMolina's script in order to add interpolation and some other modifications. It resulted in a much faster convergence in a simulation of a 2D nozzle, with a reduction of about 1000 iterations. However, the script wrote in Python is very slow, probably rewriting it on c/c++ would give a much better performance.

Pastebin of the script: [https://pastebin.com/LyWSp85U](https://pastebin.com/LyWSp85U)
[SU2_initial_guess.zip](https://github.com/su2code/SU2/files/4113038/SU2_initial_guess.zip)

**Comment by pcarruscag** [comment]
You can restart after a small (or large) geometric change so long as the mesh topology is the same (the minimum requirement is probably that the number of points in the file be the same).
This is what happens when you use SU2_DEF to parameterize / deform the mesh.

Yes one does need to be careful with the interpolation methods used for this, e.g. use the connectivity information of both meshes when looking for nearest neighbors to keep the runtime O(N).

**Comment by timjim333** [comment]
> Are you talking about shape optimization with re-meshing?
> If yes, people are already working on restart with interpolation (@jayantmukho @bmunguia )
> Otherwise, SU2 already restarts when doing shape optimization.

Is restart with interpolation already in the latest repo? It would be very useful for running remeshed but roughly similar cases! Thanks.
