### ISSUE TITLE
Install bits need atleast Python 3.5 (Please mention this in the documentation)

### ISSUE THREAD

**Issue by tgautham16** [su2code/SU2#855]
**Describe the bug**
*A clear and concise description of what the bug is and what you expect the behavior to be instead. If applicable, add screenshots to help explain your problem.*

**To Reproduce**
*Please provide a config file and mesh for a minimal example that recreates the problem.*

**Desktop (please complete the following information):**
 - OS: [e.g., Linux (Redhat 6.6)]
 - C++ compiler and version: [e.g., g++ (GCC) 4.8.5]
 - MPI implementation and version: [e.g., OpenMPI 3.0.0]
 - SU2 Version: [e.g., v6.2.0]

**Comment by talbring** [comment]
Thanks for opening the issue. Can you give a little bit more details on what you mean exactly ?

**Comment by tgautham16** [comment]
Sure
If you want to install Su2 version 7.0.0 from scratch, you need python 3.5
atleast
The installation guide says just python 3
One of the functions used in meson.py is only available in python 3.5
