### ISSUE TITLE
Bug when using rotating frame simulations in 2-D

### ISSUE THREAD

**Issue by koodlyakshay** [su2code/SU2#860]
**Describe the bug**
The rotating frame grid velocities are not set properly if used in  2-D. This is due to the error in SetRotationalVelocity routine in CGeomtery class (Cgeometry.cpp line 3881). The loop counter to find the Omega only goes upto nDim and in 2-D any rotation about the Z-axis is not considered. 

**To Reproduce**
https://github.com/su2code/SU2/tree/master/TestCases/turbomachinery/centrifugal_blade is an example of a test case using rotating frame simulations in 2-D. Some of the turbomachinery options did not work for me, so I changed the turbomachinery markers to simple inlet and outlet just to get something running in this [config file.](https://github.com/su2code/SU2/files/4158761/centrifugal_blade.txt)

The fix is fairly straightforward to change the loop counter to 3 in line 3891, but I wasn't sure if it is appropriate to make a PR for just this. Is it possible to add it into one of the existing ones?

Regards,
Akshay

**Comment by cvencro** [comment]
Hi Akshay,

Yes this is a simple fix and it could go in quickly on it's own or as part of another PR. I have this fix already modified in the draft PR #833 which is just pending the addition of a test case. I can add that and move to a PR soon if you are happy to wait?

Best wishes,
Charanya

**Comment by koodlyakshay** [comment]
Hello Charanya,

No worries, I can wait. I hadn't noticed it in the PRs. 
Thanks for the fix.

Regards,
Akshay

**Comment by economon** [comment]
Thanks for reporting, @koodlyakshay, and good idea @cvencro! 

We'll close this one since it's pending..
