### ISSUE TITLE
Building with (static) OpenMPI fails because of incomplete libs list

### ISSUE THREAD

**Issue by cesss** [su2code/SU2#867]
**Describe the bug**
I'm trying to build SU2 with OpenMPI 4.0.2, which I installed as static only. The SU2 build fails when it tries to link an executable, because it links with libmpi.a, but it doesn't link with `-lopen-pal -lopen-rte -lz` which are required by OpenMPI (as correctly stated in the pkgconfig files that were created when compiling OpenMPI, but that are ignored by the SU2 build system).

If I go to the build directory and try to link the executable manually, adding `-lopen-pal -lopen-rte -lz` at the end of the link line, it works, but then when running ninja again, it wants to relink it again (I hate it when build tools don't let you to do tricks :wink: ) so I get stuck and I cannot proceed beyond this point.

**To Reproduce**
Just try to build with `./meson.py builddir --prefix=myinstalldir -Denable-autodiff=true -Denable-directdiff=true -Denable-pywrapper=true -Denable-cgns=true -Denable-openblas=true` provided that you previously installed OpenMPI as static only.

**Desktop (please complete the following information):**
 - MacOS Sierra
 - LLVM 7.0.0 (custom build)
 - OpenMPI 4.0.2
 - SU2 7.0.1

**Comment by cesss** [comment]
BTW, can I add any parameter (or environment variable) to the `meson.py` line (or to the `ninja` invocation) in order to force linking with `-lopen-pal -lopen-rte -lz`, as a temporary workaround to this problem? Note that I cannot use LDFLAGS because its contents would be put **before** libmpi.a so the link would fail anyway... Is there any other environment variable I can set for adding libraries **at the end** of the link line?

**Comment by cesss** [comment]
I attach my pkgconfig file for ompi-cxx.pc . Note the Libs.private line, which correctly states dependencies, but it seems to be ignored by the SU2 build system:

```
# Copyright (c) 2010 Cisco Systems, Inc.  All rights reserved.
# Copyright (c) 2016      IBM Corporation.  All rights reserved.
#
Name: Open MPI
Description: Portable high-performance MPI implementation
Version: 4.0.2
URL: http://www.open-mpi.org/
#
prefix=/Users/cesss/OpenMPI/4.0.2
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib
pkgincludedir=${includedir}/openmpi
#
# Note that -lopen-pal and all the EXTRA_LIBS are only necessary when
# static linking (they're pulled in by libopen-rte.so's implicit
# dependencies), so only list these in Libs.private.
#
Libs: -L${libdir}     -lmpi
Libs.private: -lopen-rte -lopen-pal -lm -lz 
#
Cflags: -I${includedir}
```

**Comment by talbring** [comment]
Hi @cesss ,

you can use the option '-Dcustom-mpi=true'. This will tell meson do not look for MPI (but still set all preprocessor flags) so that you can provide all necessary linker/compiler flags manually using environment variables. Let me know if it works for you.

**Comment by cesss** [comment]
Thanks a lot @talbring !!

What would be the environment variable that Meson would honor for libraries? (LDFLAGS is for linker flags rather than libraries, and if the linker line puts the LDFLAGS before the object files, you'd get the libs before the objects, so a linker error). Maybe something like LIBS? However, looking at [the variables that the Meson docs say it supports](https://github.com/mesonbuild/meson/blob/8c1221b437b2930fa64d78517337293e8a0e079f/docs/markdown/Reference-tables.md#compiler-and-linker-flag-environment-variables), I don't see any LIBS-like variable...

**Comment by talbring** [comment]
@cesss I have a little bit of a confusion here, why is it necessary to link with `-lopen-rte -lopen-pal -lm -lz ` ? Its in Libs.private because it should only be needed in case you want to link SU2 statically. Can you give the error that you get when compiling ?

**Comment by talbring** [comment]
So just putting setting `LDFLAGS` doesnt work ? I did this with MPICH a while ago and it worked.

**Comment by talbring** [comment]
alternatively you can use a hostfile. Below is an example that is used to statically link SU2 and include a statically linked MPICH library. 

You can set the hostfile with `--hostfile=<path_to_hostfile>` in the meson call. `-Dcustom-mpi=true` must be also set in that case.

I never ran into problems with the order and I think that `LDFLAGS` and the hostfile approach are equivalent in your case, but anyway, its worth a try.

```
[binaries]
c = 'x86_64-linux-gnu-gcc'
cpp = 'x86_64-linux-gnu-g++'
ar = 'x86_64-linux-gnu-ar'
strip = 'x86_64-linux-gnu-strip'
pkgconfig = 'x86_64-linux-gnu-pkg-config'

[host_machine]
system ='linux'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
cpp_link_args = ['-static', '-static-libstdc++', '-static-libgcc', '-L/mpich-x86_64-linux-gnu/lib', '-lmpi', '-lxml2', '-lbacktrace', '-lz', '-lpthread', '-lrt']
c_link_args   = ['-static', '-static-libstdc++', '-static-libgcc', '-L/mpich-x86_64-linux-gnu/lib', '-lmpi', '-lxml2', '-lbacktrace', '-lz', '-lpthread', '-lrt']
cpp_args      = ['-Wno-inconsistent-missing-override', '-I/mpich-x86_64-linux-gnu/include']
c_args        = ['-I/mpich-x86_64-linux-gnu/include']
```

**Comment by cesss** [comment]
Thanks a lot @talbring !!  Yes, with LDFLAGS it worked, although I believe it's not failsafe because the order of elements in the link line usually has an effect. BTW, I got another error later in the build, this time due to libpython3.8.a not being added to the link line (I don't know why --in fact Meson says it found python 3.8 when configuring SU2). I'm rebuilding again, this time adding -lpython3.8 to LDFLAGS.

I'm closing the issue because I believe it's solved 👍
