### ISSUE TITLE
Document whether OpenBLAS should be built serial or parallel

### ISSUE THREAD

**Issue by cesss** [su2code/SU2#869]
**Is your feature request related to a problem? Please describe.**
I'm going to build SU2 with PaStiX, which requires BLAS built in serial mode (not parallel). So, I must build OpenBLAS as sequential for PaStiX.

However, SU2 also makes use of BLAS... but... what kind of build for OpenBLAS, sequential or parallel?

It's not a subtle thing, because things can go wrong (or lose a lot of performance) if it's built in a way different to what SU2 expects.

**Describe the solution you'd like**
Just mention it in the build instructions where you mention that OpenBLAS can be used by SU2.

**Comment by pcarruscag** [comment]
I build mine for parallel with OpenMP and then use the environment variable
OMP_NUM_THREADS

**Comment by cesss** [comment]
@pcarruscag But what value do you set in OMP_NUM_THREADS? I mean, do we want BLAS functions to be parallelized, or do we want them to be sequential because they'll be called from already parallel threads/processes?

**Comment by pcarruscag** [comment]
For PaStiX serial (1 thread), but you need the parallel build anyway if you
use the threaded version of PaStiX.
For DG solver serial (I believe).
For RBF interpolation parallel (but serial also fine...).
Those are the only places we use blas I think.

**Comment by pcarruscag** [comment]
Documentation updated.

**Comment by cesss** [comment]
Thanks a lot, @pcarruscag !!
