### ISSUE TITLE
Improve the console output

### ISSUE THREAD

**Issue by ghost** [su2code/SU2#88]
e.g. the sentence 

"Surface(s) where the force coefficients are evaluated and their reference origin for moment computation: aircraft (167.583, 0, 18.2292), nearfield_inner (167.583, 0, 18.2292)."

We should split this sentence, something like this would be OK:

"Surface(s) where the force coefficients are evaluated and their 
reference origin for moment computation: 
- aircraft (167.583, 0, 18.2292), 
- nearfield_inner (167.583, 0, 18.2292)."

**Comment by economon** [comment]
Complete.
