### ISSUE TITLE
Why are you told to set $SU2_HOME after building the source?

### ISSUE THREAD

**Issue by cesss** [su2code/SU2#886]
When you finish building SU2, you are told to set both $SU2_RUN (pointing to the install path) and $SU2_HOME (pointing to the source path).

However, if you install a precompiled binary, there's no source in it, and [you are told](https://su2code.github.io/docs_v7/SU2-Linux-MacOS/) to set $SU2_RUN only.

Do I really need to set $SU2_HOME for using SU2 if I built it from source? What if I prefer to keep the source packed in a tarball rather than extracted? What's the use of $SU2_HOME?

**Comment by pcarruscag** [comment]
Based on `grep -r "SU2_HOME" .`, no, you don't need to set it, maybe it's legacy, maybe it's future proofing :)

**Comment by cesss** [comment]
Thanks a lot, @pcarruscag !
