### ISSUE TITLE
Why there's no velocity outlet?

### ISSUE THREAD

**Issue by cesss** [su2code/SU2#892]
Is it not possible to constrain the velocity at an outlet? Or should I just create a velocity inlet with the direction vector pointing outside of the domain? (Note: I have two windows in a cavity: one of them pushes air into the domain at constant speed, and the other one extracts air at the same constant speed)

**Comment by koodlyakshay** [comment]
Hi,

There is the option to use MASSFLOW_OUTLET with the incompressible solver. Is that something that would work for your case?

Cheers,
Akshay.

**Comment by cesss** [comment]
I'm not sure, @koodlyakshay ...what I want to simulate is a room closed in all sides except for a window open to exterior air, and with wind blowing parallel to the window. So, my idea is to create a wind stream parallel to the window by using a velocity inlet, and, ideally, a velocity outlet (which doesn't exist). The inlet and the outlet would create the wind stream...

**Comment by pcarruscag** [comment]
The short answer, because it is not very physical (unless that boundary is a moving wall...)
Regarding how to setup particular simulations you will probably find people that are familiar with particular applications in the general sections of CFD Online.

**Comment by cesss** [comment]
Thanks a lot, @pcarruscag !
