### ISSUE TITLE
Solving Euler equations using Roe's scheme

### ISSUE THREAD

**Issue by Simone1593** [su2code/SU2#896]
Hi everyone, I'm trying to calculate the coefficient of pressure on a wing using Roe's upwind scheme. The solver is Euler.
I have got two different grids, a finer and a coarser one.

Here are the results on the coarser grid:
![meshA](https://user-images.githubusercontent.com/61738722/75774333-0f14a700-5d50-11ea-9432-613684af1b89.JPG)

Here are the results on the finer grid (with a zoomed view near the leading edge):
![meshD](https://user-images.githubusercontent.com/61738722/75774382-32d7ed00-5d50-11ea-94af-31292dc2dfda.JPG)
![meshDzoom](https://user-images.githubusercontent.com/61738722/75774388-353a4700-5d50-11ea-837a-bc526648e4b3.JPG)

The problem is that spike near the leading edge, which is not present in the solution computed with Ansys (I made a comparison between Ansys' solution and SU2's solution). Is this problem due to a bug in the code?

Here are my cfg files (A is the coarser grid, D is the finer grid):

[wingA.txt](https://github.com/su2code/SU2/files/4281175/wingA.txt)
[wingD.txt](https://github.com/su2code/SU2/files/4281177/wingD.txt)

**Desktop :**
 - OS: Windows 10
 - SU2 Version: 7

**Comment by WallyMaier** [comment]
Hi @Simone1593 ,
Are the meshes the same between Ansys and SU2?  Also, are you reaching the same levels or convergence? How do these results compare to the actual pressure distribution?

**Comment by Simone1593** [comment]
Hi @WallyMaier, the meshes and the levels of convergence are the same between Ansys and SU2. I didn't understand your third question
