### ISSUE TITLE
SU2_SOL doesn't complain if the number of doubles in a row does not match the number of columns

### ISSUE THREAD

**Issue by btracey** [su2code/SU2#9]
Currently if you have more column headings than data values in the row SU2_SOL will print garbage into the remaining spots. There should be some check on this.

**Comment by WallyMaier** [comment]
This is still an issue.

**Comment by WallyMaier** [comment]
This may not be an issue with the new output structure. However this issue occurs if someone (like me) incorrectly sets the output fields -> The SU2_SOL works fine, but the resulting solution file wont be readable by Tecplot/Paraview
