### ISSUE TITLE
Meson Build on Linux with Python Wrapper: python3 not found

### ISSUE THREAD

**Issue by aaronyicongfu** [su2code/SU2#903]
Hey guys, I am running into a seemingly super simple problem. I am trying to build SU2(v7.0.2) with python wrapper option, and I got an error "Run-time dependency python3 found: NO", but clearly python3 is installed, as shown below:

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/42105225/76112937-2e5e3f00-5fb1-11ea-817f-178f4ffd811f.png">

other info:
 - OS: Ubuntu 18.04
 - C++ compiler and version: [e.g., g++ (GCC) 7.4.0]
 - MPI implementation and version: [e.g., OpenMPI 2.1.1]
 - SU2 Version: [e.g., v7.0.2]

Could anyone help on this? Thanks!

Best,

Aaron

**Comment by jayantmukho** [comment]
You might be able to fix this problem by running your command as: 

`python3 ./meson.py build -Denable-pywrapper=true --prefix=\home\aaronfu\bin\SU2`

Running it as `./meson.py` runs it using your system default python, which might be some flavor of 2.7. You can check you default python by running 

`python --version`

**Comment by aaronyicongfu** [comment]
Thanks @jayantmukho for the reply! I tried what you said but it seems I got the same thing..

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/42105225/76119301-26a49780-5fbd-11ea-9b69-8f6321e7ed7e.png">

Also, I tried to alias python to python3, but it didn't help as well.

**Comment by jayantmukho** [comment]
Do you have pkg-config installed? It uses pkg-config to look for the dependencies it required. You can check if you have pkg-config with `which pkg-config`

If you don't have it, you can install on your ubuntu through

`sudo apt-get install pkg-config`

If it still doesn't work, or if you already have pkg-config installed, the python3.pc needs to be found by the pkg-config. Usually done by setting a `PKG_CONFIG_PATH` environment variable that points to the relevant python3.pc file.

**Comment by aaronyicongfu** [comment]
@jayantmukho Uh no I didn't have pkg-config before. Problem solved after I install it. Thank you so much!

**Comment by jayantmukho** [comment]
No problem!
