### ISSUE TITLE
Issue: Unable to open SU2 restart file

### ISSUE THREAD

**Issue by DGIorio** [su2code/SU2#906]
**Description:**
I am running some nozzle simulations and once in a while I got the following error when the software is writing the restart file:

```
Error in "virtual void CSU2BinaryFileWriter::Write_Data()":
-------------------------------------------------------------------------
Unable to open SU2 restart file restart_flow.dat
```

**To Reproduce**
I am attaching a config file and mesh that recreates the problem.
[Config_and_mesh.zip](https://github.com/su2code/SU2/files/4304107/Config_and_mesh.zip)

Command used: `mpiexec -n 4 SU2_CFD config.cfg`

I run this simulation four times, two of them worked properly and the other two had the error (one of them in iteration 1000 and the other 3000).

**Desktop:**
 - OS: Windows 10 x64
 - MPI implementation and version: Microsoft MPI v10.1.12498.18
 - SU2 Version: v7.0.2 (win64-mpi) and v7.0.0 (win64-mpi).

**Comment by leminhman0312** [comment]
I ran your test case 4 times and could not reproduce the problem.  The code rewrites the restart_flow.dat fine and there were no warnings.  I even tried to run modify the `config.cfg` so we run with different number iterations; therer are still no errors.  

I have SU2 v7.0.2 running on Manjaro x64 and mpiexec 4.0.2

**Comment by Yhnhex** [comment]
I am running the Mach3-cylinder-master and I keep getting the same problem you have, did you solve it?
