### ISSUE TITLE
Stuck at Python Interface Preprocessing

### ISSUE THREAD

**Issue by timjim333** [su2code/SU2#907]
Hi, 

I've got an issue where on starting an SU2 6.2.0 Falcon case, the preprocessing steps run but then the output gets stuck at:

```
---------------------- Python Interface Preprocessing ---------------------
Setting customized boundary conditions for zone 0
```

- and remains frozen there until I kill the job. 

It seems to have happened for only 3 out of nearly 400 successful cases. They are all similar, running Euler at Mach 1.7, on 40 cores. They all have similar simple body, farfield, and and symmetry conditions.

I'm not sure of the best way to diagnose this, so any guidance would be appreciated.

Many thanks and kind regards, 
Tim

**Comment by pcarruscag** [comment]
Try v7.0.2

**Comment by timjim333** [comment]
Hi, is this a known bug with v6.2? I saw that some people seemed to be having issues with results reproducibility after going up a version - was this fixed? I did plan to update but since I'm halfway through a case study, I originally wanted to complete my outstanding cases using the same solver. If v7.0.2 will produce the same results, then I guess I will try to update.
Thanks and regards,
Tim

**Comment by pcarruscag** [comment]
The symmetry boundary condition was changed so you will probably not get the same results.
