### ISSUE TITLE
shape_optimization restart for unsteady cases

### ISSUE THREAD

**Issue by Eduardo-Carvalho** [su2code/SU2#909]
Dear SU2 Team Members,

I've been trying to optimize bluff bodies geometries with the shape_optimization script, but I wasn't able to restart any optimization with restart files from previous simulations. This causes too much computational time to be expended to reach a periodic condition of the flow (starting from freestream).

Is it possible to implement this kind of restart for unsteady flow optimization? I've looked for answers at the forúm, doing test simulations and at the tutorial's commentary section, but this feature seems to not exist.

During my tests, I found out that the script doesn't recognize restart files with dual-time step indexes. When the script doesn't find a restart file, it starts from freestream condition, setting the config file inside the first direct simulation folder with the command "RESTART_SOL=NO". This problem can be bypassed by making a copy of one restart file and renaming it without its index. Then the script runs until it reaches other index problems with the output files. This also can be solved by renaming files while the script goes, but it still crashes at the end of the first design cycle.

**Comment by economon** [comment]
Thanks for the issue @Eduardo-Carvalho.

If anyone working in an area related to unsteady optimization has a moment to take a look at this (maybe @TobiKattmann or @ScSteffen?), I'd appreciate it.

**Comment by ScSteffen** [comment]
I'll have a look, but it may take a while until I find some time to work on it :) .

**Comment by ScSteffen** [comment]
Hi @Eduardo-Carvalho ,

your request is now merged into the develop branch and you can test/use it if you like. 
Handling is intuitive: Just set your restart iteration in the config file as you would do normally and activate the restart solution option. Furthermore, place your restart file (two in the case of 2nd order time integration) in the same directory as the config file of your test case.

Then you are set up and can run the scripts as normal. 
For more details, I refer to pull request #964. 

Best
Steffen
