### ISSUE TITLE
Meson and ninja in a disconnected system

### ISSUE THREAD

**Issue by erangit** [su2code/SU2#910]
Hi
Might be a specific problem: Meson and Ninja work well when your system
is connected to the web network. 
However, importing the software to a disconnected network, that also lacks python3, 
make them unavailable.

Would you think that it can be possible to conserve the previously configure procedure as an additional installation script? less efficient but always working...
Trying to use the configure from older versions works, but then Make aborts missing
some modules, like CHeatSolverFVM.cpp

Thanks,
Eran

**Comment by pcarruscag** [comment]
Hi Eran, please see #898, a few of us still keep the old build system up to date, but because it is not under testing it is often broken. If this is critical to you I recommend checking which PR's introduce changes to meson.build files and if so request corresponding changes to the MakeFiles.

**Comment by erangit** [comment]
Thanks for this PR
I think it is critical since our main working clusters are disconnected from the web. 
Meson/ninja work like a charm but only on my web-connected laptop.
I believe that this is not a singular case. 
 However, the PR  that you have mentioned was already merged into develop branch, but from a fresh clone of develop  I had 2 problems (at least):
1. the configure script was missing (I have copied it from a previous version)
2. The make failed due to missing reference to CHeatSolverFVP.cpp which actually
doesn't exist.

So some work is still needed here. I shall try to see also what I can find out

**Comment by pcarruscag** [comment]
Try preconfigure.py.

**Comment by erangit** [comment]
Naturally, I was using preconfig.py
However, while running it complained that it can't find configure: here is the printout
----------------------
 export CXXFLAGS="-O3 -Wall  -std=c++11 " && ./preconfigure.py --enable-autodiff --enable-mpi --with-cc=mpicc --with-cxx=mpicxx  --prefix=/home/eran/applications/SU2/SU2test 
-------------------------------------------------------------------------
|    ___ _   _ ___                                                      | 
|   / __| | | |_  )   Release 6.2.0 'Falcon'                            | 
|   \__ \ |_| |/ /                                                      | 
|   |___/\___//___|   Pre-configuration Script                          | 
|                                                                       | 
-........ (I removed the header print here) ...

Checking the status of submodules
=====================================================================
Initialize submodule externals/codi using git ... 
Submodule 'externals/codi' (https://github.com/scicompkl/CoDiPack) registered for path 'externals/codi'
Cloning into '/home/eran/applications/SU2/git_noMeson/SU2/externals/codi'...
Submodule path 'externals/codi': checked out '501dcf0305df147481630f20ce37c2e624fb351f'
Found correct version of CoDiPack in externals/codi.
Initialize submodule externals/medi using git ... 
Submodule 'externals/medi' (https://github.com/SciCompKL/MeDiPack) registered for path 'externals/medi'
Cloning into '/home/eran/applications/SU2/git_noMeson/SU2/externals/medi'...
Submodule path 'externals/medi': checked out 'edde14f9ac4026b72b1e130f61c0a78e8652afa5'
Found correct version of MeDiPack in externals/medi.

Preparing build environment
=====================================================================
Command: ./bootstrap
Logfile written to bootstrap.log

Running configure in folder SU2_AD using CODI
=====================================================================
Command: ../configure --with-cc=mpicc --with-cxx=mpicxx --prefix=/home/eran/applications/SU2/SU2test --enable-mpi --enable-codi-reverse

There was an error while running command '../configure --with-cc=mpicc --with-cxx=mpicxx --prefix=/home/eran/applications/SU2/SU2test --enable-mpi --enable-codi-reverse'.
=== Error Log ===
/bin/sh: 1: ../configure: not found

---------------------------------------------
When I copied configure.py from older installations it kept running but then aborted on
missing modules

**Comment by erangit** [comment]
It appears that cut and pastes from terminal to this window change the format of the text.
Sorry

**Comment by pcarruscag** [comment]
That looks a bit strange, you still get Release 6.2.0 but in the aforementioned PR @jayantmukho clearly updated the version to 7.0.2, I use the old build system in an old computer and it is currently working...

**Comment by erangit** [comment]
Strange indeed. It was a fresh cloning of the develop branch.
Look at the begining of preconfigure.py:

#!/usr/bin/env python

## \file configure.py
#  \brief An extended configuration script.
#  \author T. Albring
#  \version 7.0.2 "Blackbird"
#
# SU2 Project Website: https://su2code.github.io
# 
# The SU2 Project is maintained by the SU2 Foundation 
# (http://su2foundation.org)
#
# Copyright 2012-2020, SU2 Contributors (cf. AUTHORS.md)
#
Clearly 7.02. So there is somewhere a mixup with the 6 version. But the problem that not
just the headers numbers are mixed up

**Comment by erangit** [comment]
I think I have zoomed on the problem:
First I had to renstall m4 (a local problem)
Then, In the AD part, there is a refernce to CHeatSolverFVM instead of CHeatSolver.
So, a patch, is to copy routines:
 in SU2_CFD/src/solvers :  cp CHeatSolver.cpp  CHeatSolverFVM.cpp
 in SU2_CFD/src/variables :  cp CHeatVariable.cpp CHeatFVMVariable.cpp
After that make and make install work

This is a patch. The repair requires a match of the names of the CHeat routines to the actual files names. I didn't track where the list exists.

Last but not important: configure.ac prints a header with  Release 6.2.0 Falcon
instead of 7.02 Blackbird. This explaines the header that I have printed in previous message

**Comment by pcarruscag** [comment]
Have you tried manually deleting the SU2_BASE/AD/DIRECTDIFF folders before running preconfigure.py?

**Comment by erangit** [comment]
Sorry but I don't follow your suggestion:
The .deps folders in SU2_BASE (where the linkage to the CHeaterFVM routines exist) are
created during the preconfigure.py step, related to the codi part. There you can find 
pointers with DIRECTDIFF (like libSU2Core_DIRECTDIFF_a-CHeatFVMVariable.Po).
Can you clarify?

**Comment by pcarruscag** [comment]
rm -r SU2_BASE
rm -r SU2_AD
rm -r SU2_DIRECTDIFF
Followed by the normal:
export CXXFLAGS="-O3 -Wall -std=c++11 " && ./preconfigure.py --enable-autodiff --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=/home/eran/applications/SU2/SU2test

On another note you should add -DNDEBUG to the flags.

**Comment by erangit** [comment]
I'm doing my tests on a fresh clone from the git.
None of the folders that you menthoned exist after cloning. They are created during
the preconfigure run.  The wrong naming does not originate from layers of history in 
the git folder.
And yes, adding no debug flag makes sense.

**Comment by pcarruscag** [comment]
If you type "git log", is this the first message you see?
```
commit 3f9402f499dfba9b5a7f633fda1e452e48722e40
Merge: c0867da 4f9bc2f
Author: Jessie Lauzon <jtlau@users.noreply.github.com>
Date:   Fri Mar 6 13:52:14 2020 -0800
```

**Comment by erangit** [comment]
Ok, now you have tracked it.
I was making my tests with master branch (I used the develop with meson, but I thought to be conservatiev here). That way my most recent activity in the git log was from Tim by the end of February.
Switching to develop, then the git log message match your comment above.
Further, preconfig, make and make install work without any patches.
Cool
another note: -DNDEBUG note recognized by preconfigure (nor --DNDEBUG).
I suggest to update the master branch, since it is supposed to be a stable distribution

**Comment by pcarruscag** [comment]
We have releases every month and the official build system is meson.
If this (or any other) feature is fundamental to you, I kindly suggest that you follow the pull requests, and/or test the develop branch prior to each release to make sure it still works.
-DNDEBUG should be added to the compiler flags (CXXFLAGS) not to the preconfigure options.
