### ISSUE TITLE
ninja gets built even when it's already installed

### ISSUE THREAD

**Issue by simonvanderveldt** [su2code/SU2#911]
Ninja gets built even when it's already installed, this should not happen, meson should use the already available (in this case system installed) ninja

```
~/s/t/SU2:master ◼ ❯ ninja --version
1.8.2
~/s/t/SU2:master ◼ ❯ which ninja
/usr/bin/ninja
~/s/t/SU2:master ❯ ./meson.py build
Initialize submodule /home/simon/src/tmp/SU2/externals/codi using git ... 
Submodule 'externals/codi' (https://github.com/scicompkl/CoDiPack) registered for path 'externals/codi'
Cloning into '/home/simon/src/tmp/SU2/externals/codi'...
Submodule path 'externals/codi': checked out '501dcf0305df147481630f20ce37c2e624fb351f'
Initialize submodule /home/simon/src/tmp/SU2/externals/medi using git ... 
Submodule 'externals/medi' (https://github.com/SciCompKL/MeDiPack) registered for path 'externals/medi'
Cloning into '/home/simon/src/tmp/SU2/externals/medi'...
Submodule path 'externals/medi': checked out 'edde14f9ac4026b72b1e130f61c0a78e8652afa5'
Initialize submodule /home/simon/src/tmp/SU2/externals/meson using git ... 
Submodule 'externals/meson' (https://github.com/mesonbuild/meson) registered for path 'externals/meson'
Cloning into '/home/simon/src/tmp/SU2/externals/meson'...
Submodule path 'externals/meson': checked out '0435691e83fb7172e2a9635d2eb32d5521089916'
Initialize submodule /home/simon/src/tmp/SU2/externals/ninja using git ... 
Submodule 'externals/ninja' (https://github.com/ninja-build/ninja) registered for path 'externals/ninja'
Cloning into '/home/simon/src/tmp/SU2/externals/ninja'...
Submodule path 'externals/ninja': checked out '2d15b04e411229cb902332957281622119025e77'
ninja executable not found. Building ...
bootstrapping ninja...
wrote build.ninja.
bootstrap complete.  rebuilding...
[31/31] LINK ninja
```

**Desktop (please complete the following information):**
 - OS: Linux (gentoo)

**Comment by simonvanderveldt** [comment]
Also, this might be more of a question I guess, why does this `meson.py` script exist/why isn't the normal way of using meson (simply running `meson <builddir>`) used?

**Comment by talbring** [comment]
Hi @simonvanderveldt. Thanks for the questions. The custom meson.py script shipped with su2 also initializes the git submodules. You can of course also use an installed version of meson/ninja for building (should be also noted in the documentation on the website) by simply replacing '`./meson.py` with `meson`.

**Comment by simonvanderveldt** [comment]
@talbring Thanks for the quick and helpful answer! I'm looking at creating an ebuild/package for gentoo, compilation is a lot simpler than OpenFoam :P which is a big plus :)

Anyway, I was looking at the old docs (the main docs still point to 6.0, I missed the red text that mentioned that somehow :P), not sure why, but you're right it's indeed mentioned in the 7.0 docs here https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/#configuration-and-compilation

The "Automatically installed dependencies" section left me a bit confused because it sounded like the things listed there, which includes meson and ninja, would always get installed.
Maybe merging that section into the configuration and compilation section might help to make it more clear?

If you don't mind I have some additional questions:
- I didn't initialize the git submodule at all and configuration, compilation and running worked fine. Does this mean the CoDiPack and MeDiPack dependencies are optional? Or does this mean I could have a crash at runtime somewhere?
- Would it be possible to add a source package to the GitHub releases (in addition to the binary ones) that includes the (CoDiPack and MeDiPack) submodules? Unfortunately the GitHub provided source downloads don't include submodules.
- Are MKL and OpenBLAS build-time and exclusive options or can they both be compiled in and chosen at runtime?

**Comment by pcarruscag** [comment]
Answer to the third point here: https://www.cfd-online.com/Forums/su2/224652-building-source-code-mkl-openblas.html

**Comment by simonvanderveldt** [comment]
stale :gun:

**Comment by simonvanderveldt** [comment]
This stale bot plague really needs to stop
