### ISSUE TITLE
Multipoint optimization for INC_RANS

### ISSUE THREAD

**Issue by jatrin** [su2code/SU2#912]
We would love the option to use multipoint optimization in combination with our existing INC_RANS primal and discrete adjoint config file.

We would love to see config options for incompressible settings available in the config file. (MULTIPOINT_INC_VELOCITY_INIT in particular.)

We have tried hardcoding values (INC_VELOCITY_INIT in particular) in functions.py and gradients.py. This was an effort to essentially create a multipoint optimization using INC_RANS. However this method led SU2_DEF to ouptut a defective mesh. We have not yet found a workaround for this issue. 

INC_RANS has proved robust and quick to converge for our application. We would love to be able to use it for multipoint!`

**Comment by economon** [comment]
Hi @jatrin - glad to hear that the incompressible RANS solver is working well for you! 

Thanks for the feature request. We have worked on this a little in the past, although there is no general method to expose any desired option for multipoint yet. However, in the past, we implemented the same concept for mass flow outlets with the incompressible solver. You might check the commit here to see the changes, and perhaps you can apply them to your own situation: 

https://github.com/su2code/SU2/commit/541cae41c2ed5dc47ff1ce8a5ee5f7aff9c5fbf1#diff-e344798f2c0e495f61cf1e9a773e4257

**Comment by jatrin** [comment]
Great! Thanks @economon for the link.

I have 2 main questions after reading through those changes:

1. Would the custom objective function below need to modified for a velocity init/pressure outlet instead of a mass flow outlet?

`Total_Custom_ObjFunc = pow((config->GetSurface_MassFlow(0)/config->GetSurface_MassFlow(1) - 0.046),2.0)`

2. This question needs a bit of context. A summary of the issues I see in the deformed mesh:

a. ~1.04M (out of ~4.2M) elements are missing:
<img width="713" alt="Screen Shot 2020-03-18 at 10 39 32 AM" src="https://user-images.githubusercontent.com/62301101/77670983-ed749d00-6f54-11ea-86ee-6a49c0003f84.png">
b. Sequences of elements interleaved at irregular intervals:
<img width="714" alt="Screen Shot 2020-03-18 at 10 40 10 AM" src="https://user-images.githubusercontent.com/62301101/77671352-7ee40f00-6f55-11ea-91b8-ed13178139db.png">
c. The NPOIN= declaration is missing, and points also interleaved at irregular intervals:
<img width="884" alt="Screen Shot 2020-03-18 at 10 37 14 AM" src="https://user-images.githubusercontent.com/62301101/77671853-29f4c880-6f56-11ea-9061-046d690ab42f.png">

To me it almost seems as if different processes are trying to write to the file at the same time and overwriting each other. Could this be caused by my using the DRAG objective function with my hardcoded initial velocity values? If so, could a custom objective function solve this problem?

**Comment by talbring** [comment]
Regarding the second problem, which version are you using?

**Comment by jatrin** [comment]
@talbring I'm using v7.0.2.

**Comment by economon** [comment]
Concerning your first question.. that was an old example of using the custom objective option for running shape optimization (it was hard-coded for a particular problem - I do not recommend doing it that way). This is only necessary if you would like to include what is happening at the boundaries as part of the objective function or as a constraint. 

If your sweep over the inlet velocity is not part of the objective/constrain definition, then you do not need to do this. For example, if you are minimizing drag by changing the shape of a solid boundary given multiple inlet conditions, you can use the normal drag objective.

**Comment by jatrin** [comment]
That's good to know, thanks. I'll keep using the drag objective.

Regarding the mesh file, I was informed by my cluster's sysadmin that our cluster does not have a parallel file system. I was using multiple nodes, but the cluster has a traditional, UNIX file system. Could this explain my issue with the mesh file?

**Comment by jatrin** [comment]
Ok, I think the mesh file issue may have been due to the file system. The mesh file issue happened when I ran the simulation across three nodes on the cluster I was using. I tested on a single high memory node instead and the issue went away. It looks like problem solved! The drag objective also seems to be working.

Thanks for the responses!

**Comment by economon** [comment]
Great, glad to hear it! We'll close this one for now, but feel free to open a new issue in the future if you run into more issues.
