### ISSUE TITLE
Moving wall cases diverge when restarted

### ISSUE THREAD

**Issue by pcarruscag** [su2code/SU2#915]
This comes in the sequence of https://www.cfd-online.com/Forums/su2/225090-restart-causes-fgmres-orthogonalization-failed.html

**Describe the bug**
Something goes wrong when restarting a rotating wall case and SU2 diverges. Even when the rotation rate is 0.
The residuals close to the rotating wall shoot up when restarting, it does not seem to be a "first iteration proble" I tried setting the initial CFL very low and the solver is not able to recover.

Does anyone have any clue why this might happen?

**To Reproduce**
Run TestCases/moving_wall/spinning_cylinder, then restart.
This also happens in 3D.

**Comment by economon** [comment]
My first guess would be that we are not correctly initializing the grid velocities in the solver upon reading them from the restart file, or the grid velocities are corrupt or not in the restart file at all.

**Comment by talbring** [comment]
I guess the reason is that the grid velocities are not automatically written to the restart file .. I will change that.

**Comment by pcarruscag** [comment]
Hmm but why would they need to? Dynamic FSI cases restart just fine...
I have not looked into this further (been fixing other bugs). But since the case does not recover after the first iteration it seems that the grid velocities are not computed at all.

**Comment by pcarruscag** [comment]
You are right @talbring, if one asks for the grid velocities in the output file the restart works.
However, for these cases using option RESTART_STEADY_STATE= YES should also work without grid velocities (which are recomputed in CDriver::StaticMesh_Preprocessing) but currently it does not.
I'll fix the issues and make the output of grid velocities default when there is grid movement.

**Comment by economon** [comment]
👍 thanks @pcarruscag
