### ISSUE TITLE
False flow rate output for axisymmetric cases in SetAnalyzeSurface(...) 

### ISSUE THREAD

**Issue by FlorianDm** [su2code/SU2#926]
The flow rate output for axisymmetric cases from SetAnalyzeSurface(...) is wrong due to the "else" on line 196 in CFlowOutput.cpp.

When y[i] = 0 (the node lies on the axis) AxiFactor is just set to 1.0 instead of y[i] * 2 * pi (y-coordinate of the vertex of the primal grid) which may cause a significant error

For me I fixed it simply by setting " else AxiFactor = 0.5 * y[i-1] * 2 * pi " as the loop always ends on the axis. This works for my inlet and outlet (left to right) but this will fail if the loop starts at y=0 instead of ending there. Perhaps that could happen in a right to left domain. 

There is certainly a safer more general way I imagine by accessing the y-coordinate of the vertex of the dual grid 

AxiFactor = PI_NUMBER*geometry->node[geometry->vertex[iMarker][iVertex-1]->GetNode()]->GetCoord(1);

**Comment by economon** [comment]
Another idea is to use the y-coordinate of the nearest normal neighbor to the point that falls on the axis with something like:

```
Point_Normal = geometry->vertex[val_marker][iVertex]->GetNormal_Neighbor();
AxiFactor = PI_NUMBER*geometry->node[Point_Normal]->GetCoord(1);
```

Note that this only works for the node that lies on the marker, all others should be computed as before.

If you have some time, could you please submit a pull request with your proposed changes for us to consider? Thanks!

**Comment by FlorianDm** [comment]
Hi, thanks for the fast response. 

GetNormal_Neighbor() didn't return the index needed so I did it the other way. Perhaps someone can improve on that easily.
