### ISSUE TITLE
PT and KE Loss: Objective functions or constraints?

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#934]
Hi all,

If I give TOTAL_PRESSURE_LOSS or KINETIC_ENERGY_LOSS as an objective function for my adjoint sensitivities, it doesn't make sense to specify only one MARKER_MONITORING as the loss is calculated across two markers. However, the discrete_adjoint.py script solves happily if I give one marker for those objective functions and gives me the required sensitivities.

How are the two objective functions calculated? Are they supposed to be used as constraints?
I was not able to find a definition for them in the solver classes.

**Comment by economon** [comment]
Hi @auzbaig - please see inside the file output_structure_legacy.cpp and output_physics.cpp to see how some of those quantities are computed (search for TotalPressureLoss, for instance).

COutputLegacy::ComputeTurboPerformance() computes many of the quantities that you are interested by using data from inflow and outflow.

**Comment by economon** [comment]
Will close this for now, but don't hesitate to reopen / add a new issue for other topics.
