### ISSUE TITLE
Compiling SU2 on a linux computer cluster and it asks for root access

### ISSUE THREAD

**Issue by nelson1423** [su2code/SU2#936]
**Describe the bug**
I am trying to compile SU2 on a Linux cluster. I have an mpi module loaded and I run the command ./mseon.py build and that works. Then I run ./ninja -C build install. It will try to compile SU2 but while compiling it asks for root access. 
This is the output I get:
Installing SU2_CFD/src/SU2_CFD to /usr/local/bin
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ===
Authentication is needed to run `/usr/bin/python3' as the super user
Authenticating as: root

Is there a way to compile SU2 without root access?

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.7.1908 (Core) 
- C++ compiler and version:  gcc.x86_64       4.8.5-39.el7 
 - MPI implementation and version: openmpi-3.1.5-gcc-9.2.0-r3pnpzw
 - SU2 Version: ver. 7.0.3 "Blackbird"

**Comment by pcarruscag** [comment]
You need to specify an installation direction for which you have permissions via meson option `--prefix`
Further information here: https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/
In the SU2 section of CFD Online (https://www.cfd-online.com/Forums/su2/) you can find a lot of useful info about compiling / installing / running SU2 on clusters.
