### ISSUE TITLE
Problem with running the parallel code

### ISSUE THREAD

**Issue by mottiadar** [su2code/SU2#938]
Hi Everyone.

I'm new to SU2.
Installed on my mac (Catalina) the parallel version 7.0.2.
Also installed MPICH.

I am not using bash but rather tcsh (maybe there is a problem there...)
Added the following lines to .tcshrc:
setenv SU2_RUN /Applications/SU2/bin
setenv PYTHONPATH $SU2_RUN

I have tried to run the onera3D tutorial case in parallel and got the following message:
% parallel_computation.py -f inv_ONERAM6.cfg -n 2
Traceback (most recent call last):
  File "/Applications/SU2/bin//parallel_computation.py", line 110, in <module>
    main()
  File "/Applications/SU2/bin//parallel_computation.py", line 57, in main
    options.compute      )
  File "/Applications/SU2/bin//parallel_computation.py", line 88, in parallel_computation
    info = SU2.run.CFD(config) 
  File "/Applications/SU2/bin/SU2/run/interface.py", line 111, in CFD
    the_Command = build_command( the_Command, processes )
  File "/Applications/SU2/bin/SU2/run/interface.py", line 266, in build_command
    raise RuntimeError('could not find an mpi interface')
RuntimeError: could not find an mpi interface

Ideas to what can I do?

**Comment by erangit** [comment]
Motti
Welcome to the community 🙂
Did you install with mpi?
Best
Eran

**Comment by mottiadar** [comment]
Hi Eran,
Thank you.
I am not sure I understand your question.
I have downloaded the parallel version. What do you mean exactly by "installing with mpi"?

**Comment by erangit** [comment]
Did you install by meson/ninja or by preconfigure/make/make install?
Meson looks for a mpi in your system and should give you a message like:
"Run-time dependency MPI for c found: YES 2.1.1
Run-time dependency MPI for cpp found: YES 2.1.1
"
among other messages.

In preconfigure you should tell the installation to use MPI:
-enable-mpi --with-cc=mpicc --with-cxx=mpicxx as parameters

Cheers,
Eran

**Comment by mottiadar** [comment]
I didn't compile it.
I downloaded the complied version for mac.

**Comment by economon** [comment]
Hi @mottiadar : can you please check that you can find mpirun (or mpiexec) in your path with

```
$ which mpirun
```

if that returns empty, then check your MPI installation. If that returns the expected mpich version of mpirun, try running SU2 without python, e.g.,

```
cd SU2/QuickStart/
$ mpirun -n 2 SU2_CFD inv_naca0012.cfg
```

**Comment by mottiadar** [comment]
Hi @economon 

So I get command not found for which mpirun
But /opt/local/bin is in my path
For example I can find mpirun-mpich-mp in my path

These is how my /opt/local/bin looks like:
lrwxr-xr-x  1 root  wheel       40 Apr 15 15:17 port-tclsh -> /opt/local/libexec/macports/bin/tclsh8.5
lrwxr-xr-x  1 root  admin       22 Apr 15 15:57 mpirun-mpich-mp -> mpiexec.hydra-mpich-mp
-rwxr-xr-x  1 root  admin   629984 Apr 15 15:57 mpiexec.hydra-mpich-mp
lrwxr-xr-x  1 root  admin       22 Apr 15 15:57 mpiexec-mpich-mp -> mpiexec.hydra-mpich-mp
-rwxr-xr-x  1 root  admin   536952 Apr 15 15:57 hydra_pmi_proxy-mpich-mp
-rwxr-xr-x  1 root  admin   461524 Apr 15 15:57 hydra_persist-mpich-mp
-rwxr-xr-x  1 root  admin   462020 Apr 15 15:57 hydra_nameserver-mpich-mp
-rwxr-xr-x  1 root  admin     3430 Apr 15 15:57 parkill-mpich-mp
-rwxr-xr-x  1 root  admin    59240 Apr 15 15:57 mpivars-mpich-mp
-rwxr-xr-x  1 root  admin    13856 Apr 15 15:57 mpifort-mpich-mp
lrwxr-xr-x  1 root  admin       16 Apr 15 15:57 mpif90-mpich-mp -> mpifort-mpich-mp
lrwxr-xr-x  1 root  admin       16 Apr 15 15:57 mpif77-mpich-mp -> mpifort-mpich-mp
-rwxr-xr-x  1 root  admin    10144 Apr 15 15:57 mpicxx-mpich-mp
-rwxr-xr-x  1 root  admin    48376 Apr 15 15:57 mpichversion-mpich-mp
-rwxr-xr-x  1 root  admin    10584 Apr 15 15:57 mpicc-mpich-mp
lrwxr-xr-x  1 root  admin       15 Apr 15 15:57 mpic++-mpich-mp -> mpicxx-mpich-mp

I'm not sure how to fix it.

**Comment by economon** [comment]
You could try making a soft link (ln -s) in that directory for mpirun that points to the mpirun-mpich-mp (does it work if you call that directly btw?)

Otherwise, you could try a different MPI installation, e.g., openmpi

**Comment by economon** [comment]
Actually, if you are still having issues, I recommend also trying to build up the parallel version from source (as @erangit was mentioning). The vanilla build is just a couple of commands. See here: https://su2code.github.io/docs_v7/Build-SU2-Linux-MacOS/
