### ISSUE TITLE
Missing Vorticity Output in 2D RANS test cases

### ISSUE THREAD

**Issue by ScSteffen** [su2code/SU2#939]
**The Bug**
In 2D test cases, (I tested an unsteady RANS flow), setting the option VOLUME_OUTPUT = VORTEX_IDENTIFICATION has no effect. This means, the output field "vorticity" is not written to the .vtk (or other output) file.

Checking the source code, i thing that this is caused by the following lines of code in `src/output/CFlowCompOutput.cpp.`, Line  404 : 

` if (nDim == 3) {      
`
`AddVolumeOutput("VORTICITY_X", "Vorticity_x", "VORTEX_IDENTIFICATION", "x-component of the vorticity vector"); ` 
`AddVolumeOutput("VORTICITY_Y", "Vorticity_y", "VORTEX_IDENTIFICATION", "y-component of the vorticity vector");`
 `AddVolumeOutput("Q_CRITERION", "Q_Criterion", "VORTEX_IDENTIFICATION", "Value of the Q-Criterion");
    }`

Then, in 2D,  we have only `VORTICITY_Z` written to the VolumeOutput. I believe, that somewhere else, the executable must fail by writing `VORTICITY_Z` due to missing `VORTICITY_X`.

**To Reproduce**
Execute `direct_differentiation.py -f 0_naca0012.cfg -n 4` to repoduce the issue.
Files are attached below.
[reproducible_vorticity_issue.zip](https://github.com/su2code/SU2/files/4493025/reproducible_vorticity_issue.zip)

**Desktop:**
 - OS: Manjaro 19.0.2 
 - C++ compiler and version: gcc 9.3.0
 - MPI implementation and version: mpirun (Open MPI) 4.0.3
 - SU2 Version: 9.0.2

**Comment by pcarruscag** [comment]
Should be just a matter of taking the Q-criterion part out of the nDim==3 statement, can you check if the definition in CFlowOutput::GetQ_Criterion(...) is ok for 2D? (it should, but always worth checking)

**Comment by ScSteffen** [comment]
> Should be just a matter of taking the Q-criterion part out of the nDim==3 statement

Taking the Q-criterion part out of the if clause does not fix this. 
Deleting the if clause (taking all three lines out of the clause) causes SU2 to produce a vorticity output. However, it is zero everywhere.

> , can you check if the definition in CFlowOutput::GetQ_Criterion(...) is ok for 2D? (it should, but always worth checking)

I think its definition is the reason why we get zeros as vorticity. 
In there, the curl of the velocity field (or its gradient, i dont know tbh) is computed. (`CFlowOutput.cpp Line 916 `)
However, the curl computation assumes the field to be 3D. In a 2D case, the 3rd dimension values are zero, thus we get a curl equal to zero.
