### ISSUE TITLE
Changed behaviour of URANS flow solver

### ISSUE THREAD

**Issue by ScSteffen** [su2code/SU2#940]
**Is your feature request related to a problem? Please describe.**

I've noticed, that the flow solutions of SU2 have changed shortly before launch of version 7.0.0. In detail, I've computed an unsteady flow field around an airfoil with high angle of attack and its design sensitivities. Whereas the sensitivities computed with the old version exhibited periodic behaviour, the sensitivities computed with the new version explode and show somehow chaotic behaviour. 
Above sensitivities where computed using the `direct_differentiation.py` script. 
Naturally an adjoint sensitivity computation with the newer version fails to converge. In the older version, adjoint and direct sensitivities match. 

By older version, I mean before commit https://github.com/su2code/SU2/commit/56ee75 ,
and by newer version, I mean after commit https://github.com/su2code/SU2/commit/714d7e9 .

Somewhere between these two commits, the unit tests for (unsteady) flows have been adjusted, so I think this is where the change happened. 

**Describe the solution you'd like**

Is it possible to provide an option to switch to the old behavior of SU2 in the sense of this flow computation?
What was the reason for this change, so to say?

I think @BeckettZhou  and @talbring  might be interested in this. 

** Files to reproduce the issue**

I've attached two .zip files. One contains the an example of the older code and one contains the  example of the newer code. You can see that both .cfg files are identical. To emphasize the issue, compare the time dependent DRAG and D_DRAG of both history.csv files, that are provided.

[01_older.zip](https://github.com/su2code/SU2/files/4493235/01_older.zip)
[02_newer.zip](https://github.com/su2code/SU2/files/4493236/02_newer.zip)

Kind regards,
Steffen

**Comment by economon** [comment]
@ScSteffen : you might try to revert the Jacobian fix factor to the previous value since you are using JST (and perhaps it is not converging with the new setting). Try adding this option to the config (the default is currently 4.0):

CENTRAL_JACOBIAN_FIX_FACTOR= 1.0

**Comment by cvencro** [comment]
Hi @ScSteffen, did the CENTRAL_JACOBIAN_FIX_FACTOR solve the difference in results or is it still there in the latest code?

**Comment by ScSteffen** [comment]
Hello @cvencro, 
sorry for the late reply. 
Unfortunatley, CENTRAL_JACOBIAN_FIX_FACTOR= 1.0 does not resolve the issue. The residuals have not changed significantly and the gradients still explode. 

Best
Steffen
