### ISSUE TITLE
TOTAL_HEATFLUX keyword not working as objective function with python optimization

### ISSUE THREAD

**Issue by MiGaff** [su2code/SU2#946]
The shape_optimization.py script fails when setting `OPT_OBJECTIVE= TOTAL_HEATFLUX `.
The name of the variables have apparently been changed, but this change is not reflected in files  _SU2_CFD/src/output/CFlowCompOutput.cpp_ and _SU2_CFD/src/output/CFlowIncOutput.cpp_

In those files, replacing all instances of `"HEATFLUX"` with `"TOTAL_HEATFLUX"` solves the problem. 
For reference, I also run the script SU2/SU2_PY/updateHistoryMap.py after recompiling, but I am not sure if this is needed.

**Desktop (please complete the following information):**
 - OS: Linux (Red Hat 7.6)
 - C++ compiler and version: g++ 8.3.0
 - MPI: mvapich 2.3.1
 - SU2 Version: v7.0.3

**Comment by economon** [comment]
Thanks for posting @MiGaff! This issue is similar to #889, and it sounds like you have the fix, including the python update.

If you have a moment, could you please submit your changes via PR to the develop branch? It would be great to have your contribution.

**Comment by MiGaff** [comment]
Thanks for your reply @economon,
I created a pull request. It's the first time I use git (other than for cloning / pulling) so I hope what I did is correct.
