### ISSUE TITLE
CoDiPack downloads even why bypassed

### ISSUE THREAD

**Issue by SumanVajjala** [su2code/SU2#953]
Hi,

I am trying to install SU v7.0.3 and I find a peculiar problem. I have set -Denable-autodiff = false & -Denable-directdiff = false during configuration creation using meson.py. However, the configuration still downloads CoDiPack and MediPack. Shouldn't the downloading be bypassed or is there something wrong with my understanding?

Thanks and regards
Suman

**Comment by talbring** [comment]
Nope, there is nothing wrong. All submodules are downloaded, even if you don't need them. Feel free to reopen the issue in case this doesn't answer your question.
