### ISSUE TITLE
Installation: Error during building configuration

### ISSUE THREAD

**Issue by SumanVajjala** [su2code/SU2#954]
Hi,

I am trying to installSU2 in my machine. I am using python3 as suggested. When I am building the configuration using ./meson.py build I get the following error:

Traceback (most recent call last):
  File "./meson.py", line 74, in <module>
    build_ninja()
  File "./meson.py", line 60, in build_ninja
    subprocess.run([sys.path[0] + os.path.sep + 'ninja', '--version'], stdout=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'

What does this error indicate? Do I require a later version of python (>3.5)?

Regards
Suman

**Comment by talbring** [comment]
Meson (and therefore also SU2) requires at least python 3.5

**Comment by SumanVajjala** [comment]
Thank you for the clarification.

Regards
Suman
