### ISSUE TITLE
Failure Linking SU2 Without MPI

### ISSUE THREAD

**Issue by GomerOfDoom** [su2code/SU2#956]
**Describe the bug**
Error at link time when compiling SU2 without mpi ("-Dwith-mpi=disabled") with debug flags ("--buildtype=debug"). This problem does not seem to occur when compiling with release ("--buildtype=release").

Error message:
```
/usr/bin/ld: Common/src/libSU2Common.a(interface_interpolation_CMirror.cpp.o): in function `CMirror::SetTransferCoeff(CConfig const* const*)':
/local/SU2/build/../Common/src/interface_interpolation/CMirror.cpp:173: undefined reference to `MPI_STATUS_IGNORE'
/usr/bin/ld: /local/SU2/build/../Common/src/interface_interpolation/CMirror.cpp:174: undefined reference to `MPI_STATUS_IGNORE'
/usr/bin/ld: /local/SU2/build/../Common/src/interface_interpolation/CMirror.cpp:175: undefined reference to `MPI_STATUS_IGNORE'
```
I noticed that this method does not use any MPI preprocessor flags (i.e. this function does not make use of #ifdef HAVE_MPI); however, it's not obvious to me why switching the build type to release would solve the problem. 

**To Reproduce**
Configure with meson:
"./meson.py build --reconfigure --buildtype=debug -Dwith-mpi=disabled"
Build with ninja:
./ninja -C build install

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.6.3-arch1-1
 - C++ compiler and version: gcc (Arch Linux 9.3.0-1) 9.3.0
 - MPI implementation and version: Open MPI 4.0.3
 - SU2 Version: SU2 v. 7.0.3, branch: develop, commit: c093a62a2b

**Comment by pcarruscag** [comment]
Probably because with optimizations turned on the compiler optimizes away the unused argument.
The linker probably fails because the base MPI wrapper defines MPI_STATUS as extern, should be a quick fix.

**Comment by talbring** [comment]
I will put a fix in a small PR for bug fixes that I want to open for the next release anyway.

**Comment by pcarruscag** [comment]
Already fixed

**Comment by GomerOfDoom** [comment]
Pedro and Tim, thank you for your quick responses! Any idea when this fix will make it into the code?

**Comment by talbring** [comment]
We are gonna start merging PRs that are ready this week, so that we can have 7.0.4 out at latest on Friday.

**Comment by GomerOfDoom** [comment]
Sounds good. I applied Pedro's fix to my code (temporarily), and it seems to have cleared up the problem. Thanks guys! Do you want me to close this now, or wait until the PRs are applied to develop?
