### ISSUE TITLE
Problem with mpi and run SU2_CFD in parallel

### ISSUE THREAD

**Issue by hcogollo** [su2code/SU2#968]
Hi, I'm trying to run SU2 in parallel but an error with the mpi always keeps showing.

[hcogollo@localhost QuickStart]$ SU2_CFD inv_NACA0012.cfg 
SU2_CFD: error while loading shared libraries: libmpi.so.40: cannot open shared object file: No such file or directory

Does anyone know how to fix it? thanks a lot.

**Comment by pcarruscag** [comment]
Hello,
Probably you downloaded the pre-compiled binaries and you don't have MPI installed on your machine (run "which mpirun" if it is empty you don't have it). 
Please use CFD online for this kind of question, as this is not really a code issue.
Regards,
Pedro
