### ISSUE TITLE
The inlet.dat file does not get copied during a shape optimization

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#970]
The inlet profile file does not get copied/linked to the directories DIRECT and ADJOINT_* during a shape optimization.  Which python scripts need to be changed to resolve this?

**Comment by clarkpede** [comment]
I can submit a PR later this week addressing this issue.  I've done shape optimization with inlets before.

**Comment by auzbaig** [comment]
That will be great.  Although I have been restarting my optimizations to work around this, I feel this fix is important.

**Comment by auzbaig** [comment]
@clarkpede it would be great if you could push that change. Will save me some unnecessary efforts. We can then close this bug. Thanks!

**Comment by pcarruscag** [comment]
What happens if you use a relative path?

**Comment by auzbaig** [comment]
What do you mean by a relative path? I currently have a bash script copying the inlet file to the folders being created in the DESIGNS/DSN_*/* directories.

**Comment by pcarruscag** [comment]
`../../the_file` with however many `../` you need.

**Comment by auzbaig** [comment]
you mean this:
`INLET_FILENAME=../../../../Interpolated_Data_inlet.dat`?

**Comment by auzbaig** [comment]
This works for a single case. I will try running a shape optimization with this and update this thread. It was a smart way of setting this. Thanks.

**Comment by auzbaig** [comment]
I am closing this since the relative path is working fine. However, it would be more appropriate in the future to include the inlet file with other solution files when they are linked in the design folders.

**Comment by clarkpede** [comment]
Check out the branch [fix_inlet_file_shape_opt](https://github.com/su2code/SU2/tree/fix_inlet_file_shape_opt).  There's just one commit that differs from develop (921e85b9d7d9c152c131874a84f3534caf5705c2). I tested it on a simple case, and it seemed to work.  But I don't have any more complex test cases to test it on.  All my "complex" test cases involve other features not merged with develop.

You can either merge that branch or (if your branch is not up to date with develop) cherry-pick the commit.

**Comment by auzbaig** [comment]
@clarkpede Thanks for the fix. It is working as expected. I don't think any 'complex' test is required to test this. It is reading the inlet file name and linking it to all the desired folders. That's all that's required. Maybe you can open a pull request into develop for this.

**Comment by clarkpede** [comment]
By complex, I meant more complex than my simple toy problem.  So if it's working for you, then that's what I was aiming for.

I'll open a PR shortly.
