### ISSUE TITLE
NELEM incorrect after mesh deformation during shape optimization

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#972]
The NELEM of the deformed mesh is incorrect. I have to pause the optimization, correct the file and then resume to run the primal solution on the new design.

My mesh file is pretty big. If it is needed I can find a way to upload it.

- OS: CentOS 7
- SU2 Version: branch: [turbo_output_opt](https://github.com/su2code/SU2/tree/turbo_output_opt)

the branch I am working on is branched out from [feature_turbomanchinery_output](https://github.com/su2code/SU2/tree/feature_turbomanchinery_output) by @arubino 

I have replaced the turbomachinery objective function TOTAL_PRESSURE_LOSS with PRESSURE_LOSS in the new single-zone output format. It is not updated with the latest develop as I ran into some conflicts when merging. It is, however, updated with SU2 7.0.1.

I cannot run this optimization with the latest SU2 version. Doesn't work with turbo markers right now.

If this problem has been fixed is it possible for someone to point me to the commit so I can make those changes in this branch.

Thanks.

**Comment by auzbaig** [comment]
The issue got resolved after I used a single core instead of 2 cores. Should I close the bug or wait for the appropriate mpi fix?

**Comment by talbring** [comment]
This bug should already be solved in 7.0.2 ... please update your branch.
