### ISSUE TITLE
Input profile for non-inlet boundary conditions? Is it implemented?

### ISSUE THREAD

**Issue by cesss** [su2code/SU2#973]
Hi!

I hope you can answer this question, because it's basically what I need for checking if I can use SU2 for my simulations or not, and I'd rather look for other CFD codes if this is not currently implemented in SU2:

I need to run a case (over time, unsteady, or steady for each timestep) for an incompressible natural convection lid-driven cavity in 3D, where the values of the BCs change for each timestep. 

This test has no inlets, but it has a speed BC for the lid at the top, and BCs for the walls as well.

The (time-dependent) unit vector and magnitude of the speed for the lid is tabulated, for each timestep, on a external file.

The (time-dependent) temperature at each point in each wall is also tabulated, for each point in the walls and for each timestep, on a external file.

So the question is: Can SU2 currently import data like this? I only saw this feature for inlets, but not for other types of BCs... is it implemented, or not?

Thanks a lot! As I said at the beginning, it will help me a lot to know if this is possible, so that I look elsewhere if it's not!

**Comment by pcarruscag** [comment]
Hi,
So far as I can tell from the code, no.
It would however be very simple to hack that kind of feature, I can point you to the right places if you want.

**Comment by cesss** [comment]
Thanks a lot @pcarruscag but for the moment I decided to use [NaSt3DGP](https://ins.uni-bonn.de/media/public/u/griebel/NaSt3DGP/index.html) instead. It is a very simple code that implements 3D incompressible NS with natural convection, and I can very easily understood because it's really a very minimal implementation (parallelized, though).

I'm closing this, although if you consider this feature would be of interest for SU2, don't hesitate to open this issue again, as a feature request.
