### ISSUE TITLE
FFD_DEGREE syntax issue

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#977]
The website states that the FFD Box is created as follows:

% FFD box degree: 3D case (x_degree, y_degree, z_degree)
%                 2D case (x_degree, y_degree, 0)
FFD_DEGREE= (10, 8, 1)

which can be cross-checked in the following image:

![image](https://user-images.githubusercontent.com/46273732/81594431-df58cf80-938e-11ea-9a30-dddfbe3d91b7.png)

However, in my experience it works like,

FFD_DEGREE=(z_degree, x_degree_ y_degree)

and you can that in the two FFD boxes created below for my blade geometry:

**FFD_DEGREE=(6, 3, 1):**

![image](https://user-images.githubusercontent.com/46273732/81594674-48404780-938f-11ea-9576-13b8812e462d.png)

**FFD_DEGREE=(11, 2, 5):**
![image](https://user-images.githubusercontent.com/46273732/81594725-5db57180-938f-11ea-8c83-5f79a33d3442.png)

I am visualizing the ffd_boxes.dat file.

Now, am I doing something wrong, is the visualization incorrect or did someone made a change in the code that affected this unintentionally?

**Comment by pcarruscag** [comment]
The degrees are specified by "logic" axis (i j k), i.e. the result depends in the order you specify the corners in FFD_DEFINITION, e.g. your geometry has the span aligned with X, whereas in the first image the span is aligned with Y.

**Comment by auzbaig** [comment]
Yes it definitely is confusing. Then we have to use set_ffd_design_var.py giving i,j,k which are not really 'units' in x,y,z. The website should be updated to show this.

I am wondering how does SU2_DEF will determine the "logic axis". Won't a simple x,y,z approach have been simpler?

**Comment by pcarruscag** [comment]
If the box is axis aligned the following mnemonic works:
"i" is the "fast" coordinate, if X is the coordinate that changes in FFD_DEFINITION between the first and second corner points then "i" : "X";
"k" is the "slow" coordinate, it maps to the direction between the first 4 and last 4 corner points.

Simpler yes, versatile not so much, what would you do if your geometry was not aligned?

**Comment by auzbaig** [comment]
Yes, for a geometry that's not aligned it makes sense. Essentially, we are making a local coordinate system for the ffd box creation, right?

**Comment by pcarruscag** [comment]
Yes.

**Comment by auzbaig** [comment]
@pcarruscag If I do this: 
DV_VALUE=0.001
DEFINITION_DV= ( 11, 1.0 | blade | FFD_BOX, 0, 0, 0, 1.0, 1.0, 1.0 )

Then am I perturbing 0.001 in x,y and z or i, j and k?
And is the perturbing 0.001 in every direction (or a vector)?

**Comment by pcarruscag** [comment]
You select the point in "i j k", then move it in "x y z", DV_VALUE is the magnitude in the direction defined by "x y z" components.
I do not know it the direction is normalized internally you'll have to check that yourself.
The typical use is to move either along x y or z, not all at the same time.

**Comment by jayantmukho** [comment]
Looking at `CSurfaceMovement::SetFFDCPChange` in `Common/src/grid_movement_structure.cpp`, it looks like it would move by 0.001 in all directions. The movement vector would be [0.001, 0.001, 0.001]. 

Like @pcarruscag said, we usually only move in one of the directions. If you want to move in all directions and let the optimizer control them independently, you could define multiple DVs for the same control point: 

DEFINITION_DV= ( 11, 1.0 | blade | FFD_BOX, 0, 0, 0, 1.0, 0.0, 0.0 ); ( 11, 1.0 | blade | FFD_BOX, 0, 0, 0, 0.0, 1.0, 0.0 ); ( 11, 1.0 | blade | FFD_BOX, 0, 0, 0, 0.0, 0.0, 1.0 )

But I would be careful when doing this. It can cause some wonky-looking deformations.

**Comment by auzbaig** [comment]
oh. I was doing `DEFINITION_DV= ( 11, 1.0 | blade | FFD_BOX, 0, 0, 0, 1.0, 1.0, 1.0 )` what is the difference?

**Comment by jayantmukho** [comment]
> `DEFINITION_DV= ( 11, 1.0 | blade | FFD_BOX, 0, 0, 0, 1.0, 1.0, 1.0 )`

This constrains the control point to move in a direction such that `dx = dy = dz` since the `DV_VALUE` would be applied to all directions equally. It will also project the adjoint gradients along that direction. 

If you specify it as 3 different DVs, they will have three different `DV_VALUE`s, one for each direction. The gradients would be projected in each direction individually, giving the optimizer more freedom to move the point.

**Comment by auzbaig** [comment]
Right. Also, is the DV_VALUE=0.001, calculated at every design iteration? In my case it appears to be the same across all designs.

**Comment by jayantmukho** [comment]
The `DV_VALUE` should be different across design iterations since this is determined by optimizer. 

Is this the case in the config_DEF.cfg in the DEFORM folder?

**Comment by auzbaig** [comment]
Oh yes you are right. I was looking in ADJOINT_/config_DOT_AD.cfg. That shows as 0.001 for all design variables.
