### ISSUE TITLE
MOMENTUM_DISTORTION definition

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#978]
Can anyone give an explanation or a reference of how the momentum distortion is defined in the CFlowOutput.cpp file?

It seems to be a ratio of the normal velocity over area-weighted normal velocity squared, however, looking at a mathematical equation will make it look more plausible.

The nomenclature in the file can be confusing sometimes.

Thanks.

**Comment by auzbaig** [comment]
My general suggestion is that in the future there could be a document to show how all of the output quantities are defined.

**Comment by economon** [comment]
The uniformity / distortion parameters are those defined by Banko et al. in Sec. 3.2 of https://www.sciencedirect.com/science/article/pii/S0142727X16301412

**Comment by auzbaig** [comment]
Thanks @economon. That exactly answers my question!

**Comment by economon** [comment]
👍 If you have a minute, perhaps it would help to embed the link to the paper in a comment near the definition for the future

**Comment by auzbaig** [comment]
You mean here?
https://github.com/su2code/SU2/blob/20888f488752e4e8aaa5230e56c5417923c7c344/SU2_CFD/src/output/CFlowOutput.cpp#L513

**Comment by auzbaig** [comment]
or this is actually better:
https://github.com/su2code/SU2/blob/20888f488752e4e8aaa5230e56c5417923c7c344/SU2_CFD/src/output/CFlowOutput.cpp#L453

**Comment by economon** [comment]
They are first mentioned here (some of the factors are first computed there): https://github.com/su2code/SU2/blob/20888f488752e4e8aaa5230e56c5417923c7c344/SU2_CFD/src/output/CFlowOutput.cpp#L273

You could put it in the comments above those two sections where they are computed if you like

**Comment by auzbaig** [comment]
Ok, I will try to do it.
