### ISSUE TITLE
Meson build SU2 requires root password on Linux

### ISSUE THREAD

**Issue by leminhman0312** [su2code/SU2#979]
* When installing SU2 from fresh or recompiling to update changes, the installation process always requires root permission to finish.  The reason is that the binaries are installed in `/usr/local/bin`, which needs root access.  The installation went well, it is just that I don't feel like entering root password everytime.  

* A way to go around this would be to have the binaries installed in the bin folder in the home folder, so on Linux that would be `/home/user/bin`.  Even better, we can have it creates a separate SU2bin folder, where only the binaries from SU2 will be stored.  Of course, doing this would change the environmental variables as well.  

* What do you all think? Is this too much hassle?

**Comment by pcarruscag** [comment]
You can use the --prefix option (most "build from source" software works
like that).
Do you know of a portable name to determine the user name?

**Comment by leminhman0312** [comment]
Hello @pcarruscag, what do you mean by portable name? Do you mean a variable on Linux to determine the user name? If so, then it is `$USER`.
