### ISSUE TITLE
Dryrun Fails

### ISSUE THREAD

**Issue by GomerOfDoom** [su2code/SU2#988]
**Describe the bug**
Attempting to run SU2 in dryrun mode (with "-d" flag) fails when compiled with debug flags:

```
SU2_CFD_SERIAL_DEBUG: ../Common/src/linear_algebra/../../include/geometry/dual_grid/../../toolboxes/graph_toolbox.hpp:268: const Index_t* CCompressedSparsePattern<Index_t>::outerPtr() const [with Index_t = long unsigned int]: Assertion `!empty() && "Sparse pattern has not been built."' failed.
Aborted (core dumped)
```
Seems to run ok with release build.

**To Reproduce**
Compile code with debug flags and run with dryrun option.

**Desktop (please complete the following information):**
 - OS: Arch Linux (kernel 5.6.10)
 - C++ compiler and version: gcc v. 9.3.0
 - MPI implementation and version: openmpi 4.0.3
 - SU2 Version: v. 7.0.4, branch: develop, commit: 31e55ed9f5f13762e939cd44650e34d6e4d5f0f7

**Comment by pcarruscag** [comment]
Looks like I got work to do. I'm starting to loathe this dry run mode.
