### ISSUE TITLE
running 7.0.4 using XCODE

### ISSUE THREAD

**Issue by kohyun** [su2code/SU2#994]
Hi all,

I have downloaded SU2 and am testing this using Xcode.

Because I am a newbie in Xcode, I can't run SU2 successfully.
When I build and run, I got the following message.
=============================================
configfile: File does not exist: inv_wedge_HLLC.cfg
Run with --help for more information.
Program ended with exit code: 105
=============================================

In my guess, I didn't designate correct path to cfg and mesh file.
But I don't know how to designate it.

Sorry for wrong question, but it will be helpful for me to have the answer for this question.

Thanks in advance.

**Comment by leminhman0312** [comment]
Hello @kohyun, to navigate to the mesh and config file you can just use the Terminal App and `cd` to your directory with mesh/config.

**Comment by economon** [comment]
In Xcode, go to the menu item Product -> Scheme -> Edit Scheme... Once the dialogue pops up, there are tabs for "Arguments" where you can add the config file name to the command line call, and also "Options" where you can set a custom working directory where the config/mesh are located.

**Comment by talbring** [comment]
Since we are already touching the Xcode topic here, has anyone tested the xcode backend in meson (with `--backend=xcode` in the meson call)? Maybe we can remove all this xcode stuff that we have currently in the repo.

**Comment by kohyun** [comment]
> In Xcode, go to the menu item Product -> Scheme -> Edit Scheme... Once the dialogue pops up, there are tabs for "Arguments" where you can add the config file name to the command line call, and also "Options" where you can set a custom working directory where the config/mesh are located.

Thank you very much @economon 
Your method works exactly.
