### ISSUE TITLE
Different zones for different MARKER_PLOTTING

### ISSUE THREAD

**Issue by auzbaig** [su2code/SU2#995]
When I do:
MARKER_PLOTTING=(inlet, outlet)
I get one file which has both as one zone (I use Tecplot). This makes it difficult to analyse inlet and outlet separately. This can be resolved by running SU2_SOL with only one marker but it would be desirable to have them (say 5 surface markers) as separate zones in the future.

**Comment by talbring** [comment]
I think the have to ask the tecplot guys if they can help with that (at least for the tecplot binary output).

You might be interested to hear that we have a similar feature already for paraview though (see #845). If you add  `PARAVIEW_MULTIBLOCK` to `OUTPUT_FILES` you get a `*.vtm` file that contains all markers and the volume solution. You can then individually interact with those objects within paraview.

**Comment by auzbaig** [comment]
It's good to hear Paraview has this capability. If SU2 has the structure for such an output maybe this can be extended to Tecplot as well. This will be a good capability.

Additionally, I was also thinking of finding a way to plot along gridlines but that is not possible in Tecplot. It's an unstructured mesh so no i, j, k. If the output structure can have some additional information (maybe assign "dummy" i, j, k?) that would be a good capability to have as well.

**Comment by pcarruscag** [comment]
If you want to implement that you can start by looking at `CSysMatrix::BuildLineletPreconditioner`, it finds lines normal to walls.

**Comment by auzbaig** [comment]
I think you did some spelling mistake, I cannot find that keyword in the code.

**Comment by auzbaig** [comment]
I will check that.
