### ISSUE TITLE
Caradonna_tung test case is not initialazing solution

### ISSUE THREAD

**Issue by javsu** [su2code/SU2#997]
Hello. I have been trying to work with test case "Caradonna_tung". I have obtained the latest config file and mesh file i believe. Hovewer, when i run the solver, it gives value "zero" for everything and seemingly converged after only 10 iterations. I believe i could not initialize the solver. Can anyone help me with it ? Thank you.

[caradonna_tung.zip](https://github.com/su2code/SU2/files/4664054/caradonna_tung.zip)

**Comment by pcarruscag** [comment]
Can you try
ITER= 99999
Instead of
OUTER_ITER= 99999

@talbring is OUTER_ITER supposed to be interchangeable with ITER for single zone steady state problems?

**Comment by javsu** [comment]
@pcarruscag Unfortunately, i tried to use ITER=99999 and it still gives zero result for every variable.

**Comment by talbring** [comment]
INNER_ITER and ITER are interchangeable. But it looks like there might be some other problem. Seems like the rotation is not applied correctly somehow. The grid velocity is definitely non-zero so it can be a problem with the rotating frame source term? But that would mean that other cases also fail, but the turbomachinery cases work ..

**Comment by javsu** [comment]
I tried to give a non-zero Mach Number in config file and it succeed. I obtained a rotary solution. However, giving a non-zero Mach Number would mean it is not hover anymore. Is there anyway to initialize this problem without given any forward speed ?

**Comment by pcarruscag** [comment]
The source term is being computed, but it is zero because the momentum is
zero.
If run a few iterations with MACH > 0 and then restart the simulation
putting it back to 0 are the results ok?

javsu <notifications@github.com> escreveu no dia sexta, 22/05/2020 à(s)
14:01:

**Comment by economon** [comment]
Even with the source term = 0 (Mach = 0), the grid velocity at the Euler BC should kick in and give non-zero residual. Perhaps this is also related to #828

**Comment by talbring** [comment]
Might be.. its a little bit strange that the residual is more or less exactly zero. The BC implementation definitely accounts for the grid velocity (at least it is set in the residual class).

**Comment by javsu** [comment]
@pcarruscag I tried to restart the solution with zero mach number for config. However, for some reason, convergence takes so much longer than simply solving mach=0.1 config. Indeed, i started my simulation when you post your suggestion and it still haven't converged yet. Residual getting smaller but it is so slow. Therefore it might not be an efficient solution. Thanks for advice anyway.

**Comment by economon** [comment]
So, I think the issue is in the Euler BC w.r.t. the grid velocity terms. They should be taken into account during the reflection of the velocity. Something like
```
if (dynamic_grid) {
  su2double ProjGridVel = 0.0;
  su2double* GridVel_i = geometry->nodes->GetGridVel(iPoint);
    for (iDim = 0; iDim < nDim; iDim++)
      ProjGridVel += 0.5*(GridVel_i[iDim]+GridVel_i[iDim])*UnitNormal[iDim];
    ProjVelocity_i -= ProjGridVel;
  }
```
should be added just before the velocity is reflected here: https://github.com/su2code/SU2/blob/20888f488752e4e8aaa5230e56c5417923c7c344/SU2_CFD/src/solvers/CEulerSolver.cpp#L6880

Seems to be converging now for me (solution seems to be ok), but I did not run it to completion. Please see is if this works for you. If so, I expect this also helps #828

**Comment by talbring** [comment]
@economon Thanks, I assumed already that something like that was missing. @TobiKattmann maybe you can also have a look at it. Let's hope that it solves the problems :)

**Comment by javsu** [comment]
@economon Thanks for your recommendation and care for the topic. I tried to implement it just before the line you specified. However, i get the following error;
"../SU2_CFD/src/solvers/CEulerSolver.cpp:6888:36: error: ‘class CGeometry’ has no member named ‘nodes’; did you mean ‘node’?
   su2double* GridVel_i = geometry->nodes->GetGridVel(iPoint);"

And i changed it to "node" instead of "nodes" just in case and tried it again. But then, i got the following error;
"../SU2_CFD/src/solvers/CEulerSolver.cpp:6888:42: error: request for member ‘GetGridVel’ in ‘* geometry->CGeometry::node’, which is of pointer type ‘CPoint*’ (maybe you meant to use ‘->’ ?)
   su2double* GridVel_i = geometry->node->GetGridVel(iPoint);"

My Su2 code was 7.0.3. Just to check if the problem caused from my current Su2 version. I am installing 7.0.4 to try it out. 

I am very much beginner in C++, so it might be better to post the current state of the code to be sure about i am doing something wrong ( even though i just copy pasted it)
"  ...
    for (iDim = 0; iDim < nDim; iDim++)
	
if (dynamic_grid) {
  su2double ProjGridVel = 0.0;
  su2double* GridVel_i = geometry->node->GetGridVel(iPoint);
    for (iDim = 0; iDim < nDim; iDim++)
      ProjGridVel += 0.5*(GridVel_i[iDim]+GridVel_i[iDim])*UnitNormal[iDim];
    ProjVelocity_i -= ProjGridVel;
  }
        V_reflected[iDim+1] = nodes->GetVelocity(iPoint,iDim) - 2.0 * ProjVelocity_i*UnitNormal[iDim];
...."
Thank you again all of you helping

**Comment by talbring** [comment]
@javsu The code snippet was for v7.0.4 . For older versions it has to look like the following:
```
if (dynamic_grid) {
  su2double ProjGridVel = 0.0;
  su2double* GridVel_i = geometry->node[iPoint]->GetGridVel();
    for (iDim = 0; iDim < nDim; iDim++)
      ProjGridVel += 0.5*(GridVel_i[iDim]+GridVel_i[iDim])*UnitNormal[iDim];
    ProjVelocity_i -= ProjGridVel;
  }
```

**Comment by javsu** [comment]
@talbring I tried with 7.0.4 but it gives the same errors again. However, i tried to implement your version to 7.0.4 and it compiled somehow. However, it diverged. Then, i implement your version to 7.0.3 and it diverged again.
Now i am trying to understand why i could not implement @economon 's version to 7.0.4. May it be related with my gcc version or something ?

**Comment by pcarruscag** [comment]
No it's just because we made changes to the code.

No other operations are required unless you add new files.

**Comment by javsu** [comment]
@pcarruscag I did not make any other changes in the code. 
Then, there is 2 problem i guess. 
1. @economon  proposal for change in CEulerSolver.cpp can not be compiled even if i use 7.0.4 or 7.0.3 versions.
2. @talbring proposal for change can be compiled. However, solution diverges.

Once again thanks all of you for helping me out.

**Comment by pcarruscag** [comment]
The changes we made are in the develop branch, they have not been released.
There is also the chance that the case diverges because the settings are not adequate for the magnitude of the source term.
You can try reducing the rotation rate for example to make it easier to converge.

**Comment by economon** [comment]
@javsu : can you try the change in the develop branch directly? It was working for me there with the config in the test cases repo (other than changing EXT_ITER -> ITER). You can also be more aggressive with the CFL in that config.

**Comment by javsu** [comment]
@economon I am able to compile the code with develop branch. However, it diverges no matter my cfl number or cfl config i tried. I changed rotational speed too. But even changing rotational speed to 1 rad/s does not lead to convergence. Thanks again for all recommendations  posted

**Comment by economon** [comment]
@javsu : please try the branch fix_gridvel where I have aded the change and updated the config file for that case. Shouldn't require any modifications (it converges ~10 orders in a little over 1k iters for me).

**Comment by javsu** [comment]
@economon Thank you so much sir. It is working without a problem now

**Comment by economon** [comment]
@javsu : you are very welcome.

@TobiKattmann @cvencro : if you have some time, can you check if you agree with this change and if it has an impact on #828?

**Comment by TobiKattmann** [comment]
Hey @economon, it has! And it seems to recover the results of the older Euler Wall implementation, at least it does for the pitching NACA64A010 which @cvencro analyzed in more detail :+1: 
I'll add an image over at 828
