### ISSUE TITLE
Nan value might appear in BCGSTAB solver.

### ISSUE THREAD

**Issue by herayning** [su2code/SU2#999]
**Describe the bug**

At line 602, file "SU2/Common/src/linear_algebra/CSysSolve.cpp",
```
omega = A_x.dot(r) / A_x.squaredNorm();
```

The value of omega will be Nan if the elements of A_x are all zeros. It may not happen in practical environment but it happens in VS2019 when I solve a small linear system of equations like
```
A*x=b
A=diag[2 3 2 3 2 3],
b=[1; 2; 2; 3; 3; 4]
```
I think the denominator should be limited like
```
omega = A_x.dot(r) / fmax(A_x.squaredNorm(), 1e-30);
```

**Comment by pcarruscag** [comment]
Thanks I'll put a check for this.
Both Octave and Eigen have some form of dealing with this so I guess it does happen.

**Comment by economon** [comment]
Btw, we have this definition of an eps in the linear solvers: https://github.com/su2code/SU2/blob/20888f488752e4e8aaa5230e56c5417923c7c344/Common/src/linear_algebra/CSysSolve.cpp#L40

We also have an EPS constant in option_structure.hpp.

Perhaps this is a chance to standardize on an EPS that can be used everywhere.

**Comment by pcarruscag** [comment]
Sure... if you move the math constants out of the option_structure.
